### ISSUE TITLE
Could `vim.g.have_nerd_font` be a local variable instead?

### ISSUE THREAD

**Issue by sol** [nvim-lua/kickstart.nvim#1000]
## Describe the bug

- `:help have_nerd_font` did not return any matches, so I assume that it is only used by kickstart itself? Or is this some convention to indirectly communicate with other plug-ins?
- I am by no means a Lua expert, but from what I understand a local variable should work just fine?

Is there an important reason that  `have_nerd_font` has to be a  global vim variable?  If not, then I think using a global vim variable is confusing at best.

## To Reproduce

NA

## Desktop
- OS:  NA
- Terminal:  NA

## Neovim Version

v0.10.0

**Comment by feoh** [comment]
It's a simple flag, and the name of the flag tell you exactly what the flag does.

What would help say?

"Do we have Nerd Fonts installed? (y/n)"

Sorry I guess I just don't understand the issue.

**Comment by sol** [comment]
> Sorry I guess I just don't understand the issue.

@feoh as per the issue title, my question is:  Could `vim.g.have_nerd_font` be a local variable instead?

**Comment by feoh** [comment]
Thank you. I understand the question, but I don't understand *why* :)

What advantages does this. change bring? What does it do for us? Why should we make it?

**Comment by sol** [comment]
@feoh thanks for your attempt to help.  However:

1. You didn't answer my question.
2. From you~r "weaseling around"~ not giving a straight answer, I assume that no, there's no important reason to use a global variable here.  Please correct me if I'm wrong.
3. If somebody uses a global variable then I assume that person has a good reason for doing so. You wouldn't just use global variables for no good reason, right? So when I try to understand what's going on here, there are two possibilities: (a) somebody used a global vim variable "by accident" or (b) there is some important reason that slipped my attention, or I'm missing the full picture somehow.

   If it's (b) I would not want to miss the chance to deepen my understanding.  If it's (a) however and you don't wanna fix this then that's up to you, I'm not willing to argue over this.  Just don't be surprised if people are utterly puzzled.

**Comment by feoh** [comment]
Hi. I don't know what your native language is, but in English, using the word 'weasel' has some rather negative connotations.

Perhaps you might choose differently.

I don't know the answer to your question. If you want to make PR to change this, please do so, but as stated this isn't an issue that's actionable so I'm closing for now.
