### ISSUE TITLE
rocks.nvim support instead of lazyVim in the future

### ISSUE THREAD

**Issue by gam-phon** [nvim-lua/kickstart.nvim#1008]
What do you think of using [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) instead of lazyVim, since it simplify things for user.
Here is a good article https://www.jonashietala.se/blog/2024/06/02/migrating_to_rocksnvim/ for more details

**Comment by DoktorMike** [comment]
> What do you think of using [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) instead of lazyVim, since it simplify things for user. Here is a good article https://www.jonashietala.se/blog/2024/06/02/migrating_to_rocksnvim/ for more details

I don't really have any experience with it but your question peeked my interest. So I also saw that the author of the blog post you linked wrote a follow up post where he broke up with rock.nvim again. Linking it here for those interested. 

https://www.jonashietala.se/blog/2024/06/25/back_to_lazynvim/

**Comment by feoh** [comment]
I appreciate the idea but I don't see this as a direction this project will take in the foreseeable future. Closing for now.
