### ISSUE TITLE
Autocomplete does not work as intended. 

### ISSUE THREAD

**Issue by CowGivesMilk** [nvim-lua/kickstart.nvim#1012]
## Bug description
Autocomplete suggestion is displayed properly but when we press enter we move to next line like a normal enter.  

## To Reproduce

1. Clone the repository and install required LSPs
2. Start working in a file. For example cpp file
3. Code suggestion appears, press Enter 

## Desktop

- OS: Arch Linux x86_64
- Terminal: konsole

## Neovim Version

NVIM v0.10.0
```
```

**Comment by AMacedoP** [comment]
You can see in https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L732 that the default keymap to confirm the selection is <C-y>, but it also says how to change it to <CR>.
