### ISSUE TITLE
New issues with which-key 3.x.0

### ISSUE THREAD

**Issue by grous0** [nvim-lua/kickstart.nvim#1024]
## Describe the bug
I think there is a not ciritcal problem in mappings with new update of folke/which-key.nvim (3.x.0)

## To Reproduce
1. Install kickstart.nvim
2. Launch
3. run command ":checkhealth which-key"

## Desktop
- OS: Fedora 40 (GNU/Linux 6.9.8-200.fc40.x86_64)
- Terminal: Kitty

## Neovim Version
NVIM v0.10.0

**Comment by grous0** [comment]
mention PR: #1022

**Comment by rivenirvana** [comment]
Associated PR merged, issue can be closed now.

**Comment by tjdevries** [comment]
Thanks for the issue and confirmation it's fixed
