### ISSUE TITLE
LSP settings not working with fresh install 

### ISSUE THREAD

**Issue by seancanobrien** [nvim-lua/kickstart.nvim#1026]
## Describe the bug
LSP settings are not being passed to LSPs. 
In particular, `Lua.completion.callSnippet` is still `"Disable"` (the default) rather than `"Replace"`, as specified. This is not specific to `lua_ls`, all LSPs cannot be changed from their default settings.

LSP install is working fine, I can add LSPs via `init.lua` and they are automatically installed. Just no settings are being passed to the LSPs.

## To Reproduce
1. Fresh install of nightly (or stable) nvim.
2. Clone kickstart.nvim.
3. Start nvim.
4. Inspect `lua_ls` `LSP server configuration schema`, using `:Mason`

## Desktop
- OS: Debian 12
- Terminal: Kitty

## Neovim Version
NVIM v0.11.0-dev-411+geab535e10                                                                                                                                                                        
Build type: RelWithDebInfo                                                                                                                                                                             
LuaJIT 2.1.1720049189

**Comment by VlaDexa** [comment]
It seems that Meson only shows the schema with defaults, not your actual config.

Did you check if the actual feature works? [Here's an example of how it should look like (expanding with parameter names).](https://luals.github.io/wiki/settings/#completioncallsnippet)

**Comment by seancanobrien** [comment]
My bad! An unfortunate mix of a specific issue with the LSP and not understanding the info from Mason.
For anyone in my same state of ignorance `:checkhealth lsp` is the correct way to debug such things. Not `:Mason`.
