### ISSUE TITLE
Neovim throws error when opening a file

### ISSUE THREAD

**Issue by 0x-r4bbit** [nvim-lua/kickstart.nvim#103]
**Describe the bug**
After installing this kickstart config successfully, I wanted to take a closer look at the kickstart file, however whenever I try to open a file, I get the following error:

```
Error detected while processing FileType Autocommands for "*":                                                                                                                                 
Error executing lua callback: .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: attempt to call field 'start' (a nil value)                                                      
stack traceback:                                                                                                                                                                               
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: in function 'attach'                                                                                                   
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'                                                                                           
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'                                                                                         
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:130> 
```

**To Reproduce**
1. Follow the installation guide as per readme
2. After plugins and everything is successfully installed, try opening a file with neovim

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.5 LTS
- Terminal: Ubuntu Terminal app

** Neovim Version **
 - Output of running `:version` from inside of neovim:

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org
Features: +acl +iconv +tui

```

**Comment by MaxVerevkin** [comment]
As readme mentions, only the latest stable (0.8) and latest nightly (0.9) versions are supported.

**Comment by 0x-r4bbit** [comment]
Ah, I installed it via https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable as per official installation guide, but it indeed says that one should check what versions are available there.

Will reinstall Neovim through other means and update here once I know more!

**Comment by 0x-r4bbit** [comment]
That did the trick. Thanks @MaxVerevkin !
