### ISSUE TITLE
Visual mode puts a wall of text on my screen

### ISSUE THREAD

**Issue by matthewelmer** [nvim-lua/kickstart.nvim#1034]
Visual mode puts a wall of text on my screen. How do I get rid of it? I couldn't find anything in `:Tutor`, and nothing comes up when I google this.

Sorry if this isn't the right place to ask! I just don't know where else to go.

Edit: This thing:
![image](https://github.com/user-attachments/assets/df10c446-12aa-4608-898b-731a55de2e65)

**Comment by matthewelmer** [comment]
Found the culprit:
![image](https://github.com/user-attachments/assets/fdeff6d5-68a2-4e27-ac9d-b9e06c1ad954)

**Comment by dam9000** [comment]
You can use this bit of config to disable which-key popup in visual mode enter, but still keep the pop-up for some of the leader key (space, g) combos in visual mode:
```
require('which-key').setup({
  triggers = {
    { '<auto>', mode = 'nisotc' },
    { '<leader>', mode = { 'v' } },
    { 'g', mode = { 'v' } },
  }
})
```
