### ISSUE TITLE
Unable to lauch

### ISSUE THREAD

**Issue by end3r-man** [nvim-lua/kickstart.nvim#1046]
## Describe the bug
after installing neovim on arch linux with kickstart im unable to start that got this error

## To Reproduce
1. install neovim
2. setup kickstart
3. lauch it

## Desktop
- OS: Arch Linux
- Terminal: Alacritty

## Neovim Version
:version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478

```
Failed to run `config` for which-key.nvim

/home/enderman/.config/nvim/init.lua:278: attempt to call field 'add' (a nil value)

# stacktrace:
  - .config/nvim/init.lua:278 _in_ **config**
```

**Comment by end3r-man** [comment]
while space and s+/

```
[telescope.live_grep]: 'ripgrep', or similar alternative, is a required dependency for the live_grep picker. Visit https://github.com/BurntSushi/ripgrep#instal
lation for installation instructions.
```

**Comment by VlaDexa** [comment]
Please run `:Lazy update` to get the latest version of which-key.nvim.

Regarding your 'ripgrep' error: Please follow Arch install steps from [README.md](https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#linux-install)

**Comment by feoh** [comment]
Seems like this one's resolved. Please reopen if that's incorrect.

**Comment by end3r-man** [comment]
> Seems like this one's resolved. Please reopen if that's incorrect.

forgot to close the issue
