### ISSUE TITLE
Error After cloning kickstart repo and launching nvim

### ISSUE THREAD

**Issue by Abhishek-Bohora** [nvim-lua/kickstart.nvim#1048]
## Describe the bug
When I launch nvim after cloning the repo it throws the error that I showed in the screenshot:
![issue](https://github.com/user-attachments/assets/2471aa9c-dbc6-493e-aa07-d9c2d056f081)

## To Reproduce
1. git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
2. nvim

## Desktop
- OS: Ubuntu 22.04.4 LTS
- Terminal: WSL Ubuntu 

## Neovim Version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

**Comment by dam9000** [comment]
Your Neovim is too old: `NVIM v0.6.1`, you need the latest release (0.10)

**Comment by Abhishek-Bohora** [comment]
Ok, Thank you
