### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by kumiawan** [nvim-lua/kickstart.nvim#1051]
## Describe the bug
after install kalilinux then start using kickstart.nvim im unable to start got this eror

## To Reproduce
1. install neovim
2. install kickstart
3. launch it

## Desktop

- OS:  kalilinux Linux 6.6.15-amd64
- Terminal: xfce4-terminal

## Neovim Version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1719379426

```
rror detected while processing /home/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/user/.config/nvim/init.lua:207: attempt to index field 'uv' (a nil value)
stack traceback:
        /home/user/.config/nvim/init.lua:207: in main chunk
```

**Comment by bdura** [comment]
You'll need a later version of neovim for it to work (didn't work with `v0.9.5`, works with `v0.10.1` in my case)

**Comment by IFoodstampZ** [comment]
If you can't get the newest version through your package manager (i.e. gentoo not having the updated neovim package) reinstall neovim through the tarball here [https://github.com/neovim/neovim-releases/releases/tag/v0.10.1](url). Don't forget to unmerge/uninstall beforehand so 2 versions are not present.

**Comment by n0omad** [comment]
It's possible to run this without lazydev.nvim just by changing uv to loop 
```
if not vim.loop.fs_stat(lazypath) then ...
```
Hopefully we'll find a way to get lazy.nvim without building from the source!
