### ISSUE TITLE
Issue with one of plugin cmp_nvim_lsp

### ISSUE THREAD

**Issue by itsmaheshkariya** [nvim-lua/kickstart.nvim#106]
**Describe the bug**
I guess there is issue with one of plugin **cmp_nvim_lsp**

**To Reproduce**
1. nvim 

**Desktop (please complete the following information):**
- OS:  MacOS
- Terminal: Warp

** Neovim Version **
 - Output of running `:version` from inside of neovim:

```
 Error detected while processing /Users/youtube/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/youtube/.config/nvim/init.lua:359: attempt to call field 'default_capabilities' (a nil va
lue)
stack traceback:
        /Users/youtube/.config/nvim/init.lua:360: in main chunk
```

**Comment by tjdevries** [comment]
Run PackerSync and see if the issue persists.
