### ISSUE TITLE
Unable to setup rustanalyzer

### ISSUE THREAD

**Issue by PxCommoner** [nvim-lua/kickstart.nvim#1063]
Hi, I am having difficulties in getting rustanalyzer to function properly using your script. I was able to get it to function properly in the past using one of your older scripts. I am unsure as to what has radically changed and render rustanalyzer unable to function properly for me.

File extension has been changed to .txt to allow for the file to be attached to this issue.

[init.txt](https://github.com/user-attachments/files/16409539/init.txt)
[init_old.txt](https://github.com/user-attachments/files/16409559/init_old.txt)

For whatever reason, my old config no longer functions ever since I used the newest version of kickstart.

**Comment by iton0** [comment]
The config you provided is not up to date with the master branch. After uninstall and then reinstall rustanalyzer. I would additionally check if your neovim is up to date as well. After see if that fixes the issue.

**Comment by PxCommoner** [comment]
I had recently updated the config today. What part of it is not up to date?

`rustup update` provides the following output:

```
warning: downloading with complete profile isn't recommended unless you are a developer of the rust language
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: latest update on 2024-07-25, rust version 1.80.0 (051478957 2024-07-21)
info: checking for self-update

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.80.0 (051478957 2024-07-21)

info: cleaning up downloads & tmp directories
```

`rustup component add rust-src` provides the following output:
`info: component 'rust-src' is up to date`


**_Per your instructions, I have downloaded and setup the kickstart init.lua file to support rust again._**
The uploaded file extension has been changed to .txt to allow for the file to be attached to this issue.
[init.txt](https://github.com/user-attachments/files/16415782/init.txt)

After doing so, rust_analyzer is still not working and behaving as expected.
**My neovim and neovide installations are up to date.**

One thing that I have noticed is that when I edit the init.lua config file, a small message of "loading the workspace" and "lua_ls" will appear in the lower right hand corner. After a few seconds, a green checkmark will appear and the messages will disappear.

When I attempt to edit a .rs file, the messages "Completed Fetching, Completed Indexing, rust_analyzer" will appear and disappear after a few seconds. However, a green checkmark does not appear. In the past, the green checkmark would be present and rust_analyzer would behave as expected.

**Comment by VlaDexa** [comment]
Can you please explain what exactly doesn't work with rust_analyzer? 

There are situations when rust_analyzer breaks because of rust version change, so please also try `cargo clean`.

**Comment by feoh** [comment]
Hi I'm sorry you're having trouble but rust-analyzer is working great for scads of people.

Please try a fresh check-out of stock kickstart.nvim.

**Comment by PxCommoner** [comment]
> Can you please explain what exactly doesn't work with rust_analyzer?
> 
> There are situations when rust_analyzer breaks because of rust version change, so please also try `cargo clean`.

I did some more testing and found that rust_analyzer does function as expected (code completion, warning / error messages for syntax errors or bad code, etc.) for my organized code that has a cargo file or was initially generated using `cargo new`

For raw code or files without a cargo file or was probably not initially generated using `cargo new`, rust_analyzer appears to startup but never displays a checkmark in the lower right hand corner.

Was this behavior always the case?
