### ISSUE TITLE
After Installation, whenever I go to insert mode, Error message :Failed to Source

### ISSUE THREAD

**Issue by Efe-Torunoglu** [nvim-lua/kickstart.nvim#1066]
## Describe the bug
After installing kickstart following the guide, I.e cloning into my . files (MAC) I got multiple errors telling me that there were issues with my lua caches. Not sure why this error is happening as I cleared everything before installing. 

<img width="1018" alt="Screenshot 2024-07-30 at 10 05 26 AM" src="https://github.com/user-attachments/assets/aee349bd-9fdb-4cfe-a6d0-0e57c57c75b4">

## To Reproduce

1. Install Kickstart
2. Open Nvim 

## Desktop

- OS: Mac
- Terminal: Iterm

## Neovim Version

:version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
```
```

**Comment by clayton-schneider** [comment]
Checkout issue #537. Removing the entirety of `~/.local/share/nvim/` and opening nvim backup allowed Lazy to install the proper versions.
