### ISSUE TITLE
Not finding packages installed in currently-active conda environment on Mac (works on linux)

### ISSUE THREAD

**Issue by IanQS** [nvim-lua/kickstart.nvim#1067]
## Describe the bug

With my freshly-cloned `kickstart.nvim` on my linux, `nvim` is able to automatically find the packages installed within my current anaconda environment. However, on my mac I get the error that it is unable to find the packages. Specifically, the LSP says `Import "X" could not be resolved`. 

## To Reproduce

0. Back up nvim config (if any)
1. Do a fresh clone of kickstart.nvim on mac following the instructions

`git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim`

2. run `conda activate x`, where `x` is the environment
3. Paste the following test script somewhere

```
import numpy as np

a = np.asarray([1,2,3])
a *= 2
print(a)
```

At this point you might see the error

<img width="581" alt="Screenshot 2024-07-30 at 6 48 13 PM" src="https://github.com/user-attachments/assets/669c7ce5-a612-4df7-9dc9-f1cff641cf20">

I ran `LspInfo` and got the following:

```
 Language client log: /Users/ianquah/.local/state/nvim/lsp.log
 Detected filetype:   python
 
 2 client(s) attached to this buffer: 
 
 Client: ruff_lsp (id: 1, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             /Users/ianquah/.local/share/nvim/mason/bin/ruff-lsp
 
 Client: pyright (id: 2, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             /Users/ianquah/.local/share/nvim/mason/bin/pyright-langserver --stdio
 
 Configured servers list: jsonls, taplo, texlab, pyright, yamlls, ruff_lsp, tsserver, zls, lua_ls, rust_analyzer
```

but admittedly I don't know what to do with it

## Desktop

- OS: Macos 14.5
- Terminal: `wezterm` (wezterm 20240203-110809-5046fc22) and `terminal`Version 2.14

## Neovim Version

```
:version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.10.1/share/nvim"

Run :checkhealth for more info
```

---

# Checkhealth

I ran `:checkhealth` just for additional debug info and I've stuck it on [pastebin](https://pastebin.com/MhfVzPf0)

The most relevant things I could see from the `checkhealth` were

```
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set. Searching for python3.10 in the environment.
- Executable: /opt/homebrew/anaconda3/envs/robustness/bin/python3.10
- Python version: 3.10.12
- pynvim version: 0.5.0
- OK Latest pynvim is installed.
```
and it looks like it's finding the environment just fine (the executable)

and it also looks like the `lsp`, `pyright` is looking in the right location for my code(?)

```
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /Users/ianquah/.local/state/nvim/lsp.log
- Log size: 56 KB

vim.lsp: Active Clients ~
- ruff_lsp (id: 1)
    Root directory: nil
    Command: /Users/ianquah/.local/share/nvim/mason/bin/ruff-lsp
    Settings: {}
    Attached buffers: 1
- pyright (id: 2)
    Root directory: ~/coding_projects/phd_research/robust
    Command: /Users/ianquah/.local/share/nvim/mason/bin/pyright-langserver --stdio
    Settings: {
      python = {
        analysis = {
          autoSearchPaths = true,
          diagnosticMode = "openFilesOnly",
          useLibraryCodeForTypes = true
        }
      }
    }
    Attached buffers: 1
```

Anyone know what's up? Sorry if this is the wrong location to open this issue, but I'm not sure where to look. The

**Comment by feoh** [comment]
Please report this bug to the pyright folks. We just provide a kickstart configuration to get you going.
