### ISSUE TITLE
vim.uv field is nil causing error in init.lua

### ISSUE THREAD

**Issue by CSRept1l1an** [nvim-lua/kickstart.nvim#1073]
## Describe the bug

When trying to initialize and use the `uv` module in Neovim, I encountered an error indicating that the `vim.uv` field is `nil`. This issue arises when using the `fs_stat` function to check if a path exists.

## To Reproduce

1. Use Neovim version `v0.9.5`.
2. Add the following code to `init.lua`:
   ```lua
   if not vim.uv.fs_stat(lazypath) then
     local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
     local out = vim.fn.system { 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath }
     if vim.v.shell_error ~= 0 then
       error('Error cloning lazy.nvim:\n' .. out)
     end
   end
   vim.opt.rtp:prepend(lazypath)
   ```
3. Start Neovim.

**Expected Behavior:**
The `uv` module should be initialized correctly, allowing the use of `fs_stat` to check if a path exists.

**Actual Behavior:**
Neovim throws the following error:
```
E5113: Error while calling lua chunk: /home/kali/.config/nvim/init.lua:210: attempt to index field 'uv' (a nil value)
stack traceback:
        /home/kali/.config/nvim/init.lua:210: in main chunk
Press ENTER or type command to continue
```

## Desktop

- OS: Kali Linux
- Terminal: GNOME Terminal

## Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1719379426

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Additional Information:**
Changing `vim.uv` to `vim.loop` resolves the issue:
```lua
local uv = vim.loop

if not uv.fs_stat(lazypath) then
  local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
  local out = vim.fn.system { 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath }
  if vim.v.shell_error ~= 0 then
    error('Error cloning lazy.nvim:\n' .. out)
  end
end

vim.opt.rtp:prepend(lazypath)
```

Please let me know if this is the intended usage or if there are any additional configurations required.

**Comment by VlaDexa** [comment]
`vim.uv` was added in 0.10 and is a rename of `vim.loop`, which made the latter depreciated, hence the switch to `vim.uv`. Kickstart supports only the latest neovim versions.
You can either update to the latest stable neovim release, use a version before `7513ec8` commit or modify kickstart to work with your neovim version.

**Comment by coryschwartz** [comment]
I encountered this issue as well when I was merging my fork, and it came as quite a surprise. I'm on nvim v0.9.4 which is the latest version provided by my package manager at this time.

Hmm, I wonder if it makes sense to tag releases so users know which kickstart works with which nvim? Like if you're on nvim 0.9.5, then you might try kickstart 0.9.5. You can try later tags if you wish, but that's not going to be tested or developed further.

By the way, I love this project. For somebody like me, I've used vim  (now, neovim) just about every day for 20 years, but I've never been a great vim customizer. Projects like this give you just the bump you need to setup language servers and other niceties that aren't obvious out of the box. If you had a donation link, I'd kick you a few bucks.
