### ISSUE TITLE
Init problem: Attempt to call field 'add' (a nil value)

### ISSUE THREAD

**Issue by djkero** [nvim-lua/kickstart.nvim#1079]
## Describe the bug
![kickstart_nvim](https://github.com/user-attachments/assets/d61b8f6b-71fd-46cc-adea-cc316e7098ec)

## To Reproduce
1. Have the master branch set to the commit of this PR: #1022. (or newer)
2. Open nvim.

## Desktop

- OS: Bazzite Stable (Kinoite base)
- Terminal: Ptyxis 46.5

## Neovim Version
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.10.1/share/nvim"

Run :checkhealth for more info
```

**Comment by djkero** [comment]
I've checked and this happens inside a Distrobox container too.
Going back one commit, to #925, makes the error go away. Don't know if it resolves the underlying issue or if it just avoids the error.

**Comment by asthetik** [comment]
> I've checked and this happens inside a Distrobox container too. Going back one commit, to #925, makes the error go away. Don't know if it resolves the underlying issue or if it just avoids the error.

Hello, I also found the same problem, and then I pulled the master branch again, but the problem was still not solved
<img width="600" alt="image" src="https://github.com/user-attachments/assets/0efe5a06-daac-43b5-a639-f259a8fb7fb6">

**Comment by djkero** [comment]
I somehow managed to find a workaround while messing around with both the Brew and the Distrobox packages, poking around by deleting and cloning the repo and using the `:Lazy` command.

I'm sorry I don't have any clue as to what actually fixed it, but you can try doing the same.

**Comment by asthetik** [comment]
> I somehow managed to find a workaround while messing around with both the Brew and the Distrobox packages, poking around by deleting and cloning the repo and using the `:Lazy` command.
> 
> Sorry I don't have any clue as to what actually fixed it, but you can try doing the same.

thank you! fixed this issue your way

**Comment by ModEraNoah** [comment]
I had the same issue and calling `:Lazy` fixed it as well.
The reason for it is that you have to update your dependency packages, which Lazy does. The commit #f5c919558 introduced v3 of the which-key package. Therefore, your local dependency package of the which-key must also be updated.
If just calling 
`:Lazy` does not help, try afterwards to call *Update* inside of the Lazy UI

@DJKero From my point of view the ticket can be closed as it is not a problem related to the kickstart project but an user-update-issue

**Comment by feoh** [comment]
Seems like we're good here now. Please reopen if I'm incorrect.
