### ISSUE TITLE
E5108: Error executing lua ....local/share/nvim/lazy/mini.nvim/lua/mini/statusline.lua:658: attempt to call field 'is_enabled' (a nil value)

### ISSUE THREAD

**Issue by llkkdb** [nvim-lua/kickstart.nvim#1085]
## Describe the bug
Hi, I followed the WSL installation to install neovim and kickstart.nvim. Below is the error I have experienced.
![image](https://github.com/user-attachments/assets/54121ef1-d279-475a-86e2-7c3980605dd2)

## To Reproduce
wsl --install
wsl
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt update
sudo apt install make gcc ripgrep unzip git xclip neovim
git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
nvim

## Desktop
- OS: OS: Ubuntu 20.04.6 LTS on Windows 10 x86_64
- Kernel: 5.10.102.1-microsoft-standard-WSL2
- Terminal: Windows Terminal

## Neovim Version
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

```
```

**Comment by P1llus** [comment]
I am getting this as well, reproduced with the same issue (also on WSL with the same nvim version). I worked past it for now by disabling statusline in init.lua.

**Comment by echasnovski** [comment]
It is most certainly due to using development version of Neovim 0.10. Updating to released 0.10 (or relatively late development build) will fix this.

**Comment by Jynxzzz** [comment]
> I am getting this as well, reproduced with the same issue (also on WSL with the same nvim version). I worked past it for now by disabling statusline in init.lua.

comment out lines that contains stautsline in init.lua file just work fine.

**Comment by echasnovski** [comment]
> comment out lines that contains stautsline in init.lua file just work fine.

Not using the code that produced issue will, of course, work. Same as not using severely outdated Neovim development version, which is arguably the better solution.

**Comment by Jynxzzz** [comment]
> > comment out lines that contains stautsline in init.lua file just work fine.
> 
> 
> 
> Not using the code that produced issue will, of course, work. Same as not using severely outdated Neovim development version, which is arguably the better solution.

Thx a lot. I followed your suggestion and worked out. It's a better suggestion, all the plugins working now. i just downloaded newer NEOVIM to fix it. 0.11

**Comment by feoh** [comment]
Is this still an issue? I can't repro on released 0.10 or 0.11

**Comment by echasnovski** [comment]
This is *only* an issue if using 0.10 development version not sufficiently late in its development cycle. This should not happen on released 0.10 and later.

**Comment by feoh** [comment]
Thank you. That's well outside our margin of support. Closing.
