### ISSUE TITLE
nvim/init.lua:210: attempt to index field 'uv' (a nil value)

### ISSUE THREAD

**Issue by astralchan** [nvim-lua/kickstart.nvim#1092]
## Describe the bug

Starting neovim causes an error.

## To Reproduce

```
rm -rf "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
nvim
```

output:
```
Error detected while processing /home/amber/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/amber/.config/nvim/init.lua:210: attempt to index field 'uv' (a nil value)
stack traceback:
        /home/amber/.config/nvim/init.lua:210: in main chunk
Press ENTER or type command to continue
```

## Desktop

- OS:
/etc/os-relase:
```
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Terminal: WSL cmd

## Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1719379426

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by echasnovski** [comment]
Code in 'kickstart.nvim' [targets latest 'stable' and latest 'nightly' Neovim versions](https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#installation). The latest minor release 0.10.0 had `vim.loop` table renamed to `vim.uv` (while still leaving `vim.loop` present). You have at least two options to fix this:
- Update Neovim version to at least 0.10.0.
- Replace all instances of `vim.uv` (there seems to be single one in code) with `vim.loop`.

**Comment by astralchan** [comment]
> Code in 'kickstart.nvim' [targets latest 'stable' and latest 'nightly' Neovim versions](https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#installation). The latest minor release 0.10.0 had `vim.loop` table renamed to `vim.uv` (while still leaving `vim.loop` present). You have at least two options to fix this:
> 
>     * Update Neovim version to at least 0.10.0.
> 
>     * Replace all instances of `vim.uv` (there seems to be single one in code) with `vim.loop`.

Thank you. This ended up fixing that.

Fix:

```
rm -rf "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
sed -i "s/vim\.uv/vim\.loop/" "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim/init.lua
nvim
```

Upon starting neovim, I get this:

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:24: Error executing lua: /usr/share/nvim/runtime/filetype.lua:25: BufReadPost Autocommands for "*"..FileType Autocommands for "lua": Vim(append):lazydev.nvim requires Neo
vim >= 0.10
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:25: in function </usr/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>
```

I'm using debian in wsl, and am already on codename "trixie", so I don't think that upgrading neovim to 0.10 is an option at the moment.

**Comment by echasnovski** [comment]
> I'm using debian in wsl, and am already on codename "trixie", so I don't think that upgrading neovim to 0.10 is an option at the moment.

You can [download appimage](https://github.com/neovim/neovim/releases/tag/v0.10.1) and use it as a standalone executable. Otherwise, stop using plugins which depend on 0.10 (by commenting out lines which load them) is another option.

**Comment by astralchan** [comment]
Commenting out this code fixed the lazydev issue:

```
  -- LSP Plugins
--  {
--    -- `lazydev` configures Lua LSP for your Neovim config, runtime and plugins
--    -- used for completion, annotations and signatures of Neovim apis
--    'folke/lazydev.nvim',
--    ft = 'lua',
--    opts = {
--      library = {
--        -- Load luvit types when the `vim.loop` word is found
--        { path = 'luvit-meta/library', words = { 'vim%.uv' } },
--      },
--    },
--  },
```

Currently trying to fix this:

```
Error detected while processing LspAttach Autocommands for "*":
Error executing lua callback: /home/amber/.config/nvim/init.lua:520: attempt to index field 'Methods' (a nil value)
stack traceback:
        /home/amber/.config/nvim/init.lua:520: in function </home/amber/.config/nvim/init.lua:467>
        [C]: in function 'nvim_exec_autocmds'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1530: in function '_on_attach'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1357: in function 'cb'
        vim/_editor.lua:263: in function <vim/_editor.lua:262>
```

I'll snoop around and see if I can't post a fix soon.

**Comment by astralchan** [comment]
It seems there is no backwards-compatible support and *only* targets new versions. Aw well, back to vscode...

**Comment by martinlevesque** [comment]
fixed it by installing latest neovim https://github.com/neovim/neovim/blob/master/INSTALL.md

It would be great somehow if the upgrade/notification would be smoother - it just broke after updating kickstart. (not an expert in nvim/kickstart so not sure where this could lie/if it makes sense).

**Comment by astralchan** [comment]
Debian isn't a rolling release distro there isn't an option to use latest neovim without using appimage / etc which I generally don't use. Currently updated to codename trixie which is latest. All one can do is wait, until kickstart breaks on 0.11
