### ISSUE TITLE
can't highlight StatusLine

### ISSUE THREAD

**Issue by kamomil** [nvim-lua/kickstart.nvim#1093]
I run in command mode:

> :lua vim.cmd.hi 'StatusLine guigb=red'

But statusline won't become red.
It does work if I remove the code that loads and configure echasnovski/mini.nvim

**Comment by iton0** [comment]
I believe you have a spelling error: it should be guibg not guigb

**Comment by dam9000** [comment]
Maybe consider using lualine, for which there are many themes available.

**Comment by nhld** [comment]
`:lua vim.cmd.hi 'MiniStatuslineFilename guibg=red'` is probably what you are looking for.
You can use `:Telescope highlights` to explore the highlights.

**Comment by feoh** [comment]
Thanks for the issue. Folks have given you some options here, I'm going to close this for now because it's not actually a bug :)
