### ISSUE TITLE
neard font issues

### ISSUE THREAD

**Issue by TobiasWallner** [nvim-lua/kickstart.nvim#1094]
## Describe the bug

As seen in the provided image some of the symbols do not appear. Which makes it difficult to navigate through some menues

![image](https://github.com/user-attachments/assets/ce007eef-faf0-4e65-8a1b-ea70e29b5df0)

exiting the terminal is especially challanging

![image](https://github.com/user-attachments/assets/8478f800-db32-4b3d-9331-dc47f835ddb9)

## To Reproduce

1. Windows 10
2. cmd / powershell / cmder
3. following the kickstart guide / "The Only Video You Need to Get Started with Neovim"
  3.1 installing neo vim from: https://github.com/neovim/neovim/blob/master/INSTALL.md
  3.2 cloning https://github.com/nvim-lua/kickstart.nvim
  3.3 opening nvim and MYVIMRC
5. Installing the following NeardFonts: Hacker, JetBrains, Bitstorm Wera (active font in the screenshots: Hacker)
6. regardless of the value of `vim.g.have_nerd_font` + restart of nvim

## Desktop

- OS: Windows 10 
- Terminal: cmd / powershell / cmder

## Neovim Version

* NVIM v0.10.1
* Build type: Release
* LuaJIT 2.1.1713484068
```
```

**Comment by iton0** [comment]
Can you double check that you have the Hacker font as the default font for your Powershell. If it is, see if JetBrains font produces the same problem as well.

**Comment by copypasteonly** [comment]
Hi, I had the same problem using my own NerdFont patched font, I just added a regular NerdFont as a fallback font in my terminal and it works now :)

**Comment by TobiasWallner** [comment]
@iton0 
> Can you double check that you have the Hacker font as the default font for your Powershell. If it is, see if JetBrains font produces the same problem as well.

I tried JetBrains Neard Font and some symbols are still lacking:
![image](https://github.com/user-attachments/assets/0ba0f016-8048-4f36-bf34-58fb75dfe3a5)

**Comment by TobiasWallner** [comment]
@copypasteonly 
> Hi, I had the same problem using my own NerdFont patched font, I just added a regular NerdFont as a fallback font in my terminal and it works now :)

I am new to using Nerd Fonts, I just downloaded some from here: https://www.nerdfonts.com/font-downloads and installed them. Are those not the regular NeadFonts? If not where do I find a regular NerdFont?

**Comment by feoh** [comment]
Seems like you're good here. Closing.
