### ISSUE TITLE
Command Line Disappearing

### ISSUE THREAD

**Issue by TobiasWallner** [nvim-lua/kickstart.nvim#1096]
## Describe the bug

After rescaling the window, depending on the width of the terminal the command line disappears or reappears.

## To Reproduce

1. Open nvim and rescale the window. At first everything is normal
![image](https://github.com/user-attachments/assets/4c9dbe8b-5798-4523-b655-76c1e1d49622)

2. Then after a certain threshhold the command line input disappears or gets pushed out of the screen. This seems to be only depending on the windows width and invariant to the windows height. In the following screenshot you can see the same terminal/window from the above screenshot, only that the window has been taken on the left edge and stretched ever so slightly to the left (basically increasing the width of the window)

![image](https://github.com/user-attachments/assets/5c727873-b3a4-45b2-bc1a-b51a1eaa2147)

Without changeing the height of the window, the command line input gets pushed out of the visible screen. Funnily I noticed that the buffer and window height of the terminal gets increased by 1 as well (only the width has been actively changed). Very strange.

Furthermore this only seems to occur when resizeing the window on the left edge or one of the bottom corners. I could not reproduce the issue when resizeing the window on the top corners. 

I tried using `:redraw!` but the command line input is still pushed out of the screen. 
Happens both on cmd and powershell.

## Desktop

- OS: Windows 10
- Terminal: cmd / powershell

## Neovim Version

```
NVIM v0.10.1 
Build type: Release
LuaJIT 2.1.1713484068
```

## Optional:
Could probably be a windows related issue.

**Comment by feoh** [comment]
Thank you for your contribution but this doesn't seem like an issue with kickstart.nvim and is instead maybe an issue with base Neovim. Please report this issue there or give clear evidence showing that the fault lies with our configuration.
