### ISSUE TITLE
Which-Key rendering nerd-font icons when option set to false

### ISSUE THREAD

**Issue by Joaco-1321** [nvim-lua/kickstart.nvim#1097]
## Describe the bug

Which-Key showing nerd fonts regardless of the value of `vim.g.have_nerd_font`

![image](https://github.com/user-attachments/assets/30d526f6-b657-4df1-bcf6-83193ee15931)

![image](https://github.com/user-attachments/assets/21a39ef7-4ad5-4f8b-b414-de62a3a649ae)

## To Reproduce

1. Install Neovim as shown in the Ubuntu install recipe
2. Install Kickstart
3. Press space

## Desktop

- OS: Windows 11 with Ubuntu WSL
- Terminal: Windows Terminal

## Neovim Version

```
NVIM v0.11.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by Joaco-1321** [comment]
It seems that it also happens in Ubuntu, this is a fresh neovim install with only Kickstart

![imagen](https://github.com/user-attachments/assets/bad5c411-3f09-4c25-9803-5bb0c17e519f)

**Comment by laajila** [comment]
what worked for me : 

1.) Download a [Nerd Font](http://nerdfonts.com/)

2.) Unzip and copy to ~/.fonts (create folder if it doesn't exist) 

3.) Run the command fc-cache -fv to manually rebuild the font cache

4) change this line in init.lua
```
vim.g.have_nerd_font = true
```

**Comment by Joaco-1321** [comment]
> what worked for me : 
> 
> 1.) Download a [Nerd Font](http://nerdfonts.com/)
> 
> 2.) Unzip and copy to ~/.fonts (create folder if it doesn't exist) 
> 
> 3.) Run the command fc-cache -fv to manually rebuild the font cache
> 
> 4) change this line in init.lua
> ```
> vim.g.have_nerd_font = true
> ```
> 

Sorry I should clarify, I'm not using a nerd font and dont want to use one, but still renders like I have one

**Comment by iton0** [comment]
I checked out the whichkey docs; try in your whichkey config `opts.icons.mappings = vim.g.have_nerd_font`. I will update #1068 to reference this issue.

**Comment by Joaco-1321** [comment]
thanks @iton0, that solved part of the problem, but there's still some characters that doesn't get rendered.

I'm using Windows Terminal with Cascadia Code as font.

![image](https://github.com/user-attachments/assets/d0463349-eb3d-472d-9df1-e4a63cb76c14)

**Comment by iton0** [comment]
Update the relevent key strings how you would like them to appear.
```
opts.icon.keys = {
      Up = " ",
      Down = " ",
      Left = " ",
      Right = " ",
      C = "󰘴 ",
      M = "󰘵 ",
      D = "󰘳 ",
      S = "󰘶 ",
      CR = "󰌑 ",
      Esc = "󱊷 ",
      ScrollWheelDown = "󱕐 ",
      ScrollWheelUp = "󱕑 ",
      NL = "󰌑 ",
      BS = "󰁮",
      Space = "󱁐 ",
      Tab = "󰌒 ",
      F1 = "󱊫",
      F2 = "󱊬",
      F3 = "󱊭",
      F4 = "󱊮",
      F5 = "󱊯",
      F6 = "󱊰",
      F7 = "󱊱",
      F8 = "󱊲",
      F9 = "󱊳",
      F10 = "󱊴",
      F11 = "󱊵",
      F12 = "󱊶",
    },
```

**Comment by Joaco-1321** [comment]
again, thanks a lot @iton0, I should've read the docs first. do you know why they changed it? I remember when space was just `<space>`. and also, do I have to manually set all of these or is there a way to disable it? I will look the docs just in case but please let me know if you have an answer.

should I close this issue?

**Comment by Joaco-1321** [comment]
also, keep up the good work man, I've seen you in various issues fixing things, your help it's very appreciated 😁

**Comment by iton0** [comment]
@Joaco-1321 thank you! Keep this issue open for now. From the docs it seems like you have to do this manually but if you find otherwise please put the solution in here. 

Additionally, I would ask in the which-key discussion for more info about the icons.

**Comment by Joaco-1321** [comment]
thanks, this is what I've come up with if anyone that sees this issue is interested.

boring but simple.

![image](https://github.com/user-attachments/assets/877d92c5-4423-4b19-88d3-f14320e5d3d8)

**Comment by iton0** [comment]
could you actually put that in a code block?

**Comment by Joaco-1321** [comment]
oh sure, here it is.

```lua
require('which-key').setup {
  icons = {
    mappings = vim.g.have_nerd_font,
    keys = {
      Up = '<Up> ',
      Down = '<Down> ',
      Left = '<Left> ',
      Right = '<Right> ',
      C = '<C-…> ',
      M = '<M-…> ',
      D = '<D-…> ',
      S = '<S-…> ',
      CR = '<CR> ',
      Esc = '<Esc> ',
      ScrollWheelDown = '<ScrollWheelDown> ',
      ScrollWheelUp = '<ScrollWheelUp> ',
      NL = '<NL> ',
      BS = '<BS> ',
      Space = '<Space> ',
      Tab = '<Tab> ',
      F1 = '<F1>',
      F2 = '<F2>',
      F3 = '<F3>',
      F4 = '<F4>',
      F5 = '<F5>',
      F6 = '<F6>',
      F7 = '<F7>',
      F8 = '<F8>',
      F9 = '<F9>',
      F10 = '<F10>',
      F11 = '<F11>',
      F12 = '<F12>',
    },
  },
}
```
