### ISSUE TITLE
Cursor position moves to the right after performing search through default <space>sh

### ISSUE THREAD

**Issue by dybucc** [nvim-lua/kickstart.nvim#1098]
## Describe the bug
After a fresh install of the config on a previously unconfigured Neovim, when using the default mapleader `<space>` and performing a help search through `<space>sh`, after closing the help pane and returning to the previous editor, the cursor has moved one column to the right. I believe it's related to the `<space>` key still being registered as the default Neovim keybind for moving the cursor one column to the right, instead of fully replacing such behaviour with the mapleader option.

## To Reproduce

1. Open any file or pane
2. Perform a search through `<space>sh` with `<space>` as mapleader and default keybindings, and follow through to the nvim help pane on any item
3. Close the nvim help pane and return to the one you initially opened
4. The cursor position will have moved one column to the right

## Desktop
- OS: Linux
- Terminal: Alacritty

## Neovim Version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123

**Comment by iton0** [comment]
vim.keymap.set({ 'n', 'v' }, '<Space>', '<Nop>')

**Comment by byrmsh** [comment]
Wow. That is so specific. It is reproducible in my setup too. It only works for `"[S]earch [H]elp"` and not for other Telescope searches I've tried. It also doesn't work if cancelled without choosing any help entry.

**Comment by dam9000** [comment]
I think this should be reported to the Telescope project not kickstart.

**Comment by feoh** [comment]
Yes please report this [at the telescope project](https://github.com/nvim-telescope/telescope.nvim).
