### ISSUE TITLE
Replace nvim-lsp-installer with mason.nvim

### ISSUE THREAD

**Issue by graves501** [nvim-lua/kickstart.nvim#11]
`nvim-lsp-installer` will not be maintained anymore, see the [official Github repo](https://github.com/williamboman/nvim-lsp-installer/#%E2%84%B9%EF%B8%8F-project-status). The project recommends to switch to `mason.nvim` instead.

**Comment by tjdevries** [comment]
Yeah, that's on my todo list -- I just needed to see what it would take and if we should make any other changes regarding the switch. Thanks for creating the issue!
