### ISSUE TITLE
Black background in lsp popup when using transparency option on some themes

### ISSUE THREAD

**Issue by Joaco-1321** [nvim-lua/kickstart.nvim#1100]
## Describe the bug

I don't know if this is intended behavior but when using themes that support transparency, setting the option to true results on a black background in the lsp popup, some examples:

catppuccin without the transparency
![image](https://github.com/user-attachments/assets/cbcf201a-6176-4da0-920c-58c119e4e204)

catppuccin with the transparency
![image](https://github.com/user-attachments/assets/714b2944-fdd6-4621-b811-a735a9c141b9)

gruvbox without the transparency
![image](https://github.com/user-attachments/assets/745155e8-9266-46ec-8981-8dba99f10157)

gruvbox with the transparency
![image](https://github.com/user-attachments/assets/150580c2-d230-4638-aeaa-7d610b85befb)

## To Reproduce

1. Install any theme that has the option to enable transparency (catppuccin, gruvbox, etc)
2. Enable the option
3. Restart neovim

## Desktop

- OS: Windows 11 with Ubuntu WSL
- Terminal: Windows Terminal

## Neovim Version

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123

```

**Comment by iton0** [comment]
try this in the fidget config 
```lua
  notification = {
    window = {
      winblend = 0,
    },
  },
```

**Comment by Joaco-1321** [comment]
I owe more than one dude, I should really get into the habit of look more into the problem before opening an issue, thanks so much. 🙌🏽

**Comment by Joaco-1321** [comment]
and also thanks for the mention in the other PR, even though it was just a Lua table.

**Comment by iton0** [comment]
No worries. Can you also close this issue when you get the chance?
