### ISSUE TITLE
Having trouble installing on Windows 11

### ISSUE THREAD

**Issue by bfnoling** [nvim-lua/kickstart.nvim#112]
I followed the instructions on the README as best I could for windows. I am running this on a Development VM where the user account is named "User"

1. Created 

**To Reproduce**
1. Installed the Windows prerequisites by installing the "Desktop development with C++" workload in Visual Studio
2. Created  "C:\Users\User\.config\nvim"
3. Pasted the contents of init.lua from the repo to C:\Users\User\.config\nvim\init.lua"
4. Updated the line about fuzzy finder with the Windows specific line in the repo
5. Launched nvim.exe and nothing has changed

I grabbed Neovim from Winget and am using v0.8.0-1210-gd367ed9b2

Windows Version 21H2

I am using neovim from Windows Terminal and every time I start nvim.exe, a line like the one below is added to C:\Users\User\AppData\Local\nvim-data\log

"ERR 2023-01-01T20:35:11.773 nvim.2828.0 terminfo_start:359: uv_tty_set_mode failed: invalid argument"

I really apologize if I missed something in the documentation. I got this running in Linux with no problem and appreciate your help.

**Comment by seantwie03** [comment]
Hello,

Let's start by correcting the location of your init.lua file. It should be in `~/AppData/Local/nvim/init.lua`

Fore more information please see [:h config](https://neovim.io/doc/user/starting.html#config)

**Comment by bfnoling** [comment]
That did the trick. Thank you!
