### ISSUE TITLE
Unable to install OXY2DEV/markview.nvim plugin

### ISSUE THREAD

**Issue by moshpirit** [nvim-lua/kickstart.nvim#1120]
## Describe the bug
Adding the plugin [OXY2DEV/markview.nvim](https://github.com/OXY2DEV/markview.nvim) to `~/.config/nvim/lua/custom/plugins/init.lua` or directly to `~/.config/nvim/init.lua` doesn't seem to work, meaning it doesn't seem to be able to load it with lazy (even if changing the option in the configuration), nor let us use the `:Markview toogle` command.

That said, I'm very new to kickstart, so this is probably my fault.

## To Reproduce
1.  install fresh kickstart
2. modify  `~/.config/nvim/lua/custom/plugins/init.lua`  to:
``` lua
-- You can add your own plugins here or in other files in this directory!
--  I promise not to create any merge conflicts in this directory :)
--
-- See the kickstart.nvim README for more information

-----------------  NOTE: Mis plugins -----------------

-- NOTE: Markview.nvim
return {
  'OXY2DEV/markview.nvim',
  lazy = false,
  dependencies = {
    'nvim-treesitter/nvim-treesitter',
    'nvim-tree/nvim-web-devicons',
  },
  config = function()
    require('markview').setup {
      -- Configuración opcional
      modes = { 'n', 'i', 'no', 'c' },
      hybrid_modes = { 'n' },
      callbacks = {
        on_enable = function(_, win)
          vim.wo[win].conceallevel = 2
          vim.wo[win].concealcursor = 'c'
        end,
      },
    }
    vim.cmd 'Markview enableAll'
  end,
}
```
or add this to the main file (`~/.config/nvim/init.lua`):

```lua
-- NOTE: Here is where you install your plugins.
require('lazy').setup({
[…] 

  {
    'OXY2DEV/markview.nvim',
    lazy = false, -- Recommended
    -- ft = "markdown" -- If you decide to lazy-load anyway

    dependencies = {
      -- You will not need this if you installed the
      -- parsers manually
      -- Or if the parsers are in your $RUNTIMEPATH
      'nvim-treesitter/nvim-treesitter',

      'nvim-tree/nvim-web-devicons',
    },
  },
})
```
3. Save and Sync+Install+Update Lazy 
4. open a markdown file in a new session (like a new terminal)
5. Open Lazy to check if it's loaded or try to use `:Markview`
6. Cry :cry: 

## Desktop

- OS: Arch Linux 
- Terminal: Kitty

## Neovim Version

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
```

**Comment by VlaDexa** [comment]
Have you enabled this line in init.lua?
https://github.com/nvim-lua/kickstart.nvim/blob/a22976111e406ec0e4903ae78bf66a1fc0125b8a/init.lua#L930-L932

**Comment by abeldekat** [comment]
I tested with the steps you provided. In all cases, the plugin installs. Restart `nvim`, open the `README`, and the plugin is activated. The `Markview` command works.
