### ISSUE TITLE
laravel blade syntax highlighting

### ISSUE THREAD

**Issue by AshokFK** [nvim-lua/kickstart.nvim#1127]
how to setup laravel blade syntax highlighting ?
is there any step by step to achieve this ?

**Comment by VlaDexa** [comment]
See this: https://github.com/EmranMR/tree-sitter-blade/discussions/19#discussion-5400675

**Comment by feoh** [comment]
This isn't an issue with kickstart. Please see @VlaDexa 's suggestion.
