### ISSUE TITLE
nvim-treesitter

### ISSUE THREAD

**Issue by rpolasek-sde** [nvim-lua/kickstart.nvim#113]
i have freshly installed `lua.vim` w/o changes on _ubuntu 22.04 lts_. when i open a `cpp` file i can see the error below:
```
                    Error detected while processing FileType Autocommands for "*":
Error executing lua callback: .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: attempt to call field 'start' (a nil value)
stack traceback:
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:130>
```

**Comment by abdullah2993** [comment]
Had the same issue on `ubuntu` looks like the ubuntu ppa has version `0.7` so I installed the latest version from source instead and the error is gone, hope it helps

**Comment by krassdanke** [comment]
> Had the same issue on `ubuntu` looks like the ubuntu ppa has version `0.7` so I installed the latest version from source instead and the error is gone, hope it helps

Thanks for your hint - did you install nvim from source or treesitter then? Which installation instructions did you follow?

**Comment by s-marios** [comment]
FWIW, I run into this, when using nvim 0.7.2 as provided by debian. The solution is indeed to update to a later version; see the releases page, pick a package/app image/source from there and proceed to install a newer version of nvim on your system.

**Comment by tjdevries** [comment]
Yeah -- this is outdated neovim problem. Shouldn't happen on the supported versions of neovim.
