### ISSUE TITLE
C++ Standard Library Errors

### ISSUE THREAD

**Issue by sins621** [nvim-lua/kickstart.nvim#1139]
## Describe the bug
"In included file: no type named 'pos_type in 'std:char_traits<char>'" error under `#include <iostream>` and "In template: no type named 'int_type' in 'std::char_traits<char>'" under the insertion operator in a simple hello world cpp file on a fresh windows install.

![Screenshot 2024-09-11 222856](https://github.com/user-attachments/assets/26aa1d7e-dbc8-4b09-9875-343654b0b456)

## To Reproduce
1. Fresh Windows Install
2. Kickstart Windows Choco Install Recipe
3. Clone kickstart.nvim in CMD.
4. Uncomment "-- clangd{}" in init.lua
5. Close nvim.
6. `nvim main.cpp` to make a new cpp file and create a simple hello world program

As a side note I have no issues with cpp under vscode using mingGW following their installation instructions. Here are my g++, gdb and gcc versions if that helps. 

![image](https://github.com/user-attachments/assets/d1534e36-0f63-42e9-8324-4d34cb9fc990)

I've tried installing Node.js, NPM and LLVM to see if that helps but unfortunately it does not. 

I'm fairly new to programming and very new to neovim so this could definitely be my doing but I've tried to troubleshoot it myself over the last two days to no avail.

## Desktop
- OS: Windows 11
- Terminal: Wezterm (CMD)

## Neovim Version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068

**Comment by sins621** [comment]
I seem to have the same problem with the lazy vim distro so this is a me problem I'll have to sort out.

**Comment by mbrdg** [comment]
Hi!

This is not a bug with kickstart, just a project's misconfiguration. When interpreting the source, clangd needs to locate the [system headers](https://clangd.llvm.org/guides/system-headers#what-are-system-headers-). Naturally, the solution is to tell clangd where it can locate such files.

The solution is described [here](https://clangd.llvm.org/guides/system-headers#how-clangd-finds-those-headers).

> Best way to ensure clangd can find your system includes is by putting the directories to be searched into your compile flags via -isystem. You can achieve this with [compile_flags.txt](https://clang.llvm.org/docs/JSONCompilationDatabase.html#alternatives), [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html) or a [clangd configuration file](http://clangd.llvm.org/config.html#compileflags).

The generation of these compilation databases depends on the project. Fortunately, tools such as [cmake](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) or [bear](https://github.com/rizsotto/Bear) can be used to generate them automatically.

**Comment by bradlycarpenter** [comment]
Hey @mbrdg appreciate the response. I really wish I was at the level to understand how to set my project up correctly as you have described but I still have a lot to learn. If you don't mind explaining to me like I'm 5 (lol) do you possibly know why I don't need to do this configuration under Linux? I'm using Pop Os on my other machine so I'm guessing something may have been pre-bundled? Also wondering why I didn't have to create any configuration files on my previous win11 installation, maybe I'd installed something there too.

Not a huge problem, I'll likely just use vsc*de on my windows machine until I've learnt some more but I'm interested to know nonetheless.

**Comment by bradlycarpenter** [comment]
I just noticed that after running :checkhealth on my linux machine cpp is present under Parser/Features:
![image](https://github.com/user-attachments/assets/f600421f-998b-45ef-a3b4-87cfc8dc3008)

cpp was not present on my windows machine, not sure if this has anything to do with it.

**Comment by sins621** [comment]
Hi @mbrdg appreciate the response, I had a read through the documentation you linked and surmised that there is a way to set clang to search the correct paths for Mingw globally without the need for configuration files, unfortunately I couldn't figure out how to do that but I solved this issue by installing Visual Studio 2019 and the C++ Desktop Development Modules which seems to set the path correctly automatically? Not entirely sure but now clang can locate the headers without me needing to create any configuration files.
