### ISSUE TITLE
LSP Folding or Folding in General

### ISSUE THREAD

**Issue by Maxuvious** [nvim-lua/kickstart.nvim#1143]
I'm interested in seeing if it's possible to add lsp based folding to neovim kickstart. I've been looking around for how to configure this properly and have not found a proper implementation for myself yet.

I've had odd problems like having the same buffer open in two windows will make everything collapse or expand to the last set z-M or z-R once I saved the file with :w and would also move my cursor all the way to the top of the buffer in the other window I wasn't using -- lots of frustrating behaviors that would make me move to doom emacs agan for the next hour or so. I was using UFO -- it's probably just the way I had it configured.

A few other flavors of neovim have decent implementations of folding behavior by default, but that not as fun as having kickstart.

**Comment by feoh** [comment]
Can you please give a specific example (like a link?) to what you're looking for?

**Comment by metalinspired** [comment]
Are you maybe using chrisgrieser/nvim-origami also?
I had the exact same issue until I removed this plugin.

**Comment by feoh** [comment]
@Maxuvious Please respond. If we don't hear from you in another week I'll close the issue, and thanks for the report!

**Comment by glmlm** [comment]
@Maxuvious
I recently made a PR which might be related to this issue.
Frankly, I think adding a plugin for this feature would be a matter of opinion. However, at least I believe it's necessary for someone, and it wouldn't be a bad idea to note it as a best practice to help those lost beginners.
If you agree with my PR, I would appreciate it if you would use #1198 and give me your feedback.
