### ISSUE TITLE
Structuring your plugins help isn't correct

### ISSUE THREAD

**Issue by Sephster** [nvim-lua/kickstart.nvim#1152]
## Describe the bug
In lua.init, there is a comment that states, _run `:help lazy.nvim-lazy.nvim-structuring-your-plugins` for more information on structuring your plugins_ or words to those effect. When run, neovim cannot find the help.

## To Reproduce

1. run `:help lazy.nvim-lazy.nvim-structuring-your-plugins`

## Desktop

- OS: Ubuntu 22.04
- Terminal: Kitty

## Neovim Version

```
v0.10.1
```

**Comment by feoh** [comment]
Thanks for the report but I have no hope of understanding what you want here.

Please provide additional details.

How are our plugins improperly structured? Please provide concrete examples.

**Comment by Sephster** [comment]
Sorry for any confusion caused. To be clear, in init.lua there is a comment saying you can run `:help lazy.nvim-lazy.nvim-structuring-your-plugins` to get help/guidance on how to structure your plugins.

However, if you run this command, it errors out. I hope this clears up things. The line in question is here:

https://github.com/nvim-lua/kickstart.nvim/blob/4120893b8a1f31a0957f2f891f7fbef73ddfb9b1/init.lua#L931

**Comment by samarth-na** [comment]
Yes it appears like that help tag can't be found, use `help lazy.nvim-🔌-plugin-spec` in mean while.
the `example` sub-section should be useful
