### ISSUE TITLE
Doesn't recognize onedark color scheme

### ISSUE THREAD

**Issue by 1103-Guyer-Josiah** [nvim-lua/kickstart.nvim#116]
**Describe the bug**

Error detected while processing :source (no file):
E5108: Error executing lua [string ":source (no file)"]:123: Vim(colorscheme):E185: Cannot find color scheme 'onedark'
stack traceback:
        [C]: in function 'cmd'
        [string ":source (no file)"]:123: in main chunk

**To Reproduce**
I deleted my last config and started from scratch to using this one.

**Desktop (please complete the following information):**
- OS: ubuntu 20.04
- Terminal: 

** Neovim Version **
 - Output of running `:version` from inside of neovim:
 -v 0.8.1

```
```

**Comment by shanujha** [comment]
Just checking:

When you say 
> I deleted my last config and started from scratch to using this one.

Do you mean you have removed all existing configuration? including running these two commands

    sudo rm -rf ~/.local/share/nvim
    sudo rm -rf ~/.config/nvim/plugin

Please confirm this for me. My conclusion for now is that some stuff may have not been deleted or even the new installation could be dirty.
Would you mind also showing me if all plugins were installed successfully?

**Comment by thomsebastin** [comment]
I had the exact issue and the workaround from @shanujha worked for me.

**Comment by 1103-Guyer-Josiah** [comment]
@shanujha thank you! It worked
