### ISSUE TITLE
[Question] How do you update Kickstart.nvim?

### ISSUE THREAD

**Issue by mubin-thinks** [nvim-lua/kickstart.nvim#1160]
As of now, if there's any update to Kickstart.nvim, you have the option to clone the repository and install it by yourself. But there's a downside to this. 

What do you do to save your old configurations? They maybe in different locations of the `~1003`LOC in `init.nvim`. And Copying and pasting my changes to the new config doesn't seem that good + you can forget some of your configurations.

Is there any better way to achieve this task?

**Comment by rivenirvana** [comment]
Fork the repository, clone the fork instead of this repo, commit your changes to the fork instead of this repo, and merge any new updates from this repo to your fork using git.

**Comment by ChillerDragon** [comment]
Yes git is the way to go. Do not copy paste code. If you plan to do frequent and long term merging into upstream I recommend some git conflict driven development. Try to avoid touching init.nvim as much as possible. And only in the places that are unlikely to change. You can use lua's [require](https://github.com/ChillerDragon/kickstart.nvim/blob/0f30c432a46ca49053b0e798dad5c77e5beaeb65/init.lua#L1017-L1020) keyword and put your changes in extra files.

kickstart is quite fork friendly it loads all the lua files in the [plugins directory](https://github.com/nvim-lua/kickstart.nvim/tree/4120893b8a1f31a0957f2f891f7fbef73ddfb9b1/lua/custom/plugins) by default.

**Comment by mubin-thinks** [comment]
Ok, closing as I got my solution.
