### ISSUE TITLE
Request to Use/Modify ASCII Art/Text for Emacs Kickstart

### ISSUE THREAD

**Issue by LionyxML** [nvim-lua/kickstart.nvim#1170]
Hey there!

First off, kickstart.nvim is awesome! I love how it makes setting up Neovim super easy. I’m working on creating (yet another) similar "kickstart" setup for Emacs and wanted to ask if it’s cool to copy/modify the initial ASCII art/text from kickstart.nvim for that project.

The idea is to bring the same "easy setup" vibe to Emacs (no editor wars here, just love for open-source tools). I think making both editors accessible is great for everyone.

Let me know what you think!

Thanks!

**Comment by ghost** [comment]
download

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme

you may need to install the c compiler

**Comment by LionyxML** [comment]
Btw, 

Besides the above bot response, 

After inquiring* both r/emacs and r/neovim about the interest in this project,  I ended up developing the idea into this: https://github.com/LionyxML/emacs-kick

Also, I explain a bit about it here: https://www.rahuljuliato.com/posts/emacs-kick

I'd love any feedback on it.

Thanks.

**Comment by feoh** [comment]
Thank you for your interest and your contribution but this is a Neovim project, not an emacs project :)

Closing.

**Comment by LionyxML** [comment]
Own, too bad our projects couldn't be friends.

Thanks for your answer. I'll remove the `kickstarter.nvim` inspired ascii from `emacs-kick` on next release.

Still thanks for all the work on this project, it inspires beyond the Neovim sphere :)

**Comment by ccjmne** [comment]
Oh, that's... not what I expected would happen.
Thanks @LionyxML for your positivity, and good luck with your projects!
And that's some very nice ASCII art you've got there as a replacement ;)

Hm... you know, I'm sorta considering giving Emacs a spin now, after quickly going through your README—that may be a nice way to spend some long and cold Winter nights.

See you around :)

**Comment by feoh** [comment]
Hi. I'm sorry I don't think I read this properly the first time around. I apologize for that.

The ASCII art is open source with a permissive license, use what you like, but as folks said the replacement looks lovely :)

**Comment by LionyxML** [comment]
Haha, we're cool, our projects can be friends again 😄 

@ccjmne thanks man! Let me known if you adventure through Emacs and if this config made your ride less painful.

@feoh I don't blame you, re-reading my writing also made me confuse now 😋, thanks to our 'confusion' here, we gave birth to the new art. I'm gonna keep it for now ;)

Take care! o/
