### ISSUE TITLE
Kickstart.nvim Not Recognizing Wget and Other Formulae

### ISSUE THREAD

**Issue by MrCherub** [nvim-lua/kickstart.nvim#1171]
Kickstart.nvim is not recognizing wget and several other formulae, even after reinstalling them and running checkhealth in Neovim. I would appreciate any assistance in resolving this issue.

Thank you.

Okay the issue appears to be resolved. I don't know what was done.

**Comment by iton0** [comment]
is this still an issue or can this be closed?
