### ISSUE TITLE
None of the cmp plugins will load within lazy.

### ISSUE THREAD

**Issue by MrCherub** [nvim-lua/kickstart.nvim#1174]
macOS Sequoia 15.0 Intel Mac
Nvim v0.10.1
Lua 5.4.7 installed

I believe I have all the required dependencies installed for this. However, below my other 19 plugins, it shows ‘Not Loaded (6),’ with four of them being cmp plugins. Even when I run lua require('cmp'), then sync and exit, it reverts the changes I made.

**Comment by rivenirvana** [comment]
They will load at their specified events (in their defaults or your configuration) or when their functionality is required by either user invocation (i.e. via a keymap), other plugins as a dependency, or some other mechanism.

For example, you may see some of those plugins you say are not loaded will have a label saying "InsertEnter". If you enter insert mode and go back to normal mode, checking `:Lazy` again will show that those plugins, and any dependencies they require that are not loaded yet, will have loaded.

You can read more about this on lazy's docs for [lazy loading](https://lazy.folke.io/spec/lazy_loading) or the [event property](https://lazy.folke.io/spec#spec-lazy-loading) of the plugin spec.

**Comment by MrCherub** [comment]
> They will load at their specified events (in their defaults or your configuration) or when their functionality is required by either user invocation (i.e. via a keymap), other plugins as a dependency, or some other mechanism.
> 
> 
> 
> For example, you may see some of those plugins you say are not loaded will have a label saying "InsertEnter". If you enter insert mode and go back to normal mode, checking `:Lazy` again will show that those plugins, and any dependencies they require that are not loaded yet, will have loaded.
> 
> 
> 
> You can read more about this on lazy's docs for [lazy loading](https://lazy.folke.io/spec/lazy_loading) or the [event property](https://lazy.folke.io/spec#spec-lazy-loading) of the plugin spec.

I just checked by doing that and it did load them but why is autocomplete not working at all? I am not seeing any auto-suggestions when editing a file or simply typing in a fresh file.

**Comment by rivenirvana** [comment]
May be one or several possible reasons:
- You do not have snippets or a plugin that loads snippets (kickstart's `init.lua` suggests a plugin config for this)
- You do not have an installed LSP for your filetype (see `:Mason`)
- You do have an installed LSP, but there is an issue (bug or misconfig) that prevents it from attaching to your file's buffer
- Other reasons

**Comment by samarth-na** [comment]
have you tried putting all cmp-plugins as dependencies in nvim-cmp

**Comment by MrCherub** [comment]
> May be one or several possible reasons:
> 
> - You do not have snippets or a plugin that loads snippets (kickstart's `init.lua` suggests a plugin config for this)
> 
> - You do not have an installed LSP for your filetype (see `:Mason`)
> 
> - You do have an installed LSP, but there is an issue (bug or misconfig) that prevents it from attaching to your file's buffer
> 
> - Other reasons

Auto completion is now ONLY working for lua files only because of the two lua LSP's that I have enabled but auto completion for text doesn't work at all; I added name = 'buffer' as well. I was also wondering how I could enable the pyright LSP within Mason. I also changed the key mapping for confirm to ['<"Right">'] (I didn't use the parenthesis inside I simply put those so you could see it but it is still using C-y instead of the new mapping despite me saving and syncing. 

Edit: I have pyright LSP enabled now. The autocomplete mapping now works somehow. However, the autocomplete is not working on .py files nor is the text suggestions even working on any buffer outside of lua...

Editv1: Okay I had to set filetype=Python on the file for pyright to work but the text suggestions outside of these files does not work at all...
