### ISSUE TITLE
Unreliable git cloning when opening nvim with kickstart-script for the first time. 

### ISSUE THREAD

**Issue by PietJanHein** [nvim-lua/kickstart.nvim#1176]
## Describe the bug
Every time kickstart refuses to clone every repository, there are 3 or 4 repositories which it can't download. Which ones differs a little bit but always the ones at the end of the list (and alphabet) which can't be a coincidence. I will attach the screenshots of 2 such attempts but I tried it more often and I have this problem every time with the current version of kickstart. I understand that servers are not always 100% reliable but every time this problem, that consistency points to some issue.

## To Reproduce

1. Install nvim and the required dependencies.
2. Do a git clone for this repository
3. Run nvim
4. The startscreen appears and then it turns out that very consistently 3 or 4 repositories can't get cloned. See the included screenshot for an example. 
5. Uninstall kickstart according to the instructions. 
6. git clone again, run nvim again: 3 or 4 repositories can't get cloned, not necessarily exactly the same ones. 

Alternatively for 5 and 6: try to run Update (shift+U) on the startingscreen and once again it fails to get all the data. 

My internet-connection is not a problem, I have a stable roughly 11 MBps (so times 8 to get Mbps) internet-connection (I never notice any problem while updating Arch, watching YouTube, downloading a big game or whatever) and when I manually git clone these repositories then it is fine. Concrete example of how I do that for one of the repositories which kickstart didn't get: git clone https://github.com/folke/which-key.nvim.git/ ~/.local/share/nvim/lazy/which-key.nvim after the kickstart-script failed to download it, the cloning never fails. So it seems that either there is an issue with this version of the script or there is an issue with GitHub when the user downloads this many repositories this fast. 

## Desktop

- OS: Arch Linux
- Terminal: Alacritty

## Neovim Version

VIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1725453128

![image](https://github.com/user-attachments/assets/2278423c-7ba0-4162-b62b-3af6ef541b6b)
![image](https://github.com/user-attachments/assets/25c89d0c-5ba0-423f-8d17-05de463e10ae)

**Comment by razein97** [comment]
This problem was happening to me when I used to connect from India -Jio network, but using a vpn and switching to canada solved it for me. No errors at all. All installation done at first try.

**Comment by feoh** [comment]
Hi sorry you're having network connectivity issues.

Unfortunately, these are beyond the scope of kickstart.nvim

Closing.
