### ISSUE TITLE
Feature in colorscheme no longer working

### ISSUE THREAD

**Issue by nnathan** [nvim-lua/kickstart.nvim#118]
Hi,

First of all apologies if this is not the place to ask these questions, but I don't know where else to ask.

I just switched to using kickstart.nvim but I made some customisations to use my own colorscheme [desertrocks](https://github.com/nnathan/desertrocks).

In init.lua I swapped out onedark to load `nnathan/desertrocks` instead.

Then I put the following config:

```
vim.g.desertrocks_show_whitespace = 1
vim.cmd [[colorscheme desertrocks]]                                                 
```

In particular the `vim.g.desertrocks_show_whitespace = 1` should enable [this feature](https://github.com/nnathan/desertrocks/blob/master/colors/desertrocks.vim#L376-L387):

```vim
if exists('g:desertrocks_show_whitespace')
    augroup desertrocks_show_whitespace
        autocmd!
        autocmd Syntax *
            \ syntax match Tab           /\v\t/         containedin=ALL |
            \ syntax match TrailingWS    /\v\s\ze\s*$/  containedin=ALL
    augroup END

    " missing guibg
    highlight Tab ctermbg=234
    highlight TrailingWS ctermbg=203
endif
```

Sure enough the codepath is being executed as I can see the highlight groups when I edit a syntax coloured file like go source code, but I'm not seeing trailing whitespaces being highlighted.

This was working fine before I switched to kickstart.nvim when I was using init.vim with vim-plug.

**Comment by seantwie03** [comment]
Kickstart sets `termguicolors = true` [here](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L122)

Reading `:h termguicolors` it says: ` Uses "gui" |:highlight| attributes instead of "cterm" attributes.`

In that code block you pasted there is a comment that says `" missing guibg`

So, you can probably solve this problem by adding a guibg to the highlight TrainlingWS or by removing the `set termguicolors = true` line.

**Comment by nnathan** [comment]
This is now sorted. The issue was with the Syntax event not being emitted. I rewrote the snippet in lua and changed the event to VimEnter and it works now.

For more info, see this issue I created at neovim: https://github.com/neovim/neovim/issues/21816
