### ISSUE TITLE
lsp_implementations won't work

### ISSUE THREAD

**Issue by kamomil** [nvim-lua/kickstart.nvim#1183]
## Describe the bug

I use the kernel code and clicking 'gI' for 'Goto Implementation' does not do anything.

## To Reproduce

1. clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
2. compile with `make KBUILD_OUTPUT=~/kbuild ARCH=x86_64`
3. generate the compile_command.json file with `./scripts/clang-tools/gen_compile_commands.py -d ~/kbuild/`
4. inside neovim, stand on a function call and run:
`:lua vim.print(require('telescope.builtin').lsp_implementations())`
this does nothing.

## Desktop

- OS:  ubuntu 22
- Terminal:  terminator

## Neovim Version

```
:version                                                                                                                                            
NVIM v0.10.0                                                                                                                                                 
Build type: Release                                                                                                                                          
LuaJIT 2.1.1713484068                                                                                                                                        
```

**Comment by kamomil** [comment]
lsp_definitions do work, the following command jumps to the definition of a function:

```
:lua vim.print(require('telescope.builtin').lsp_definitions())
```

**Comment by batyrmuhadov** [comment]
How to set up LSP with local servers that were not installed by Mason? I am trying to set a zig and specified the server
`      zls = {
        cmd = { '~/user/bin/Zig/zls' },
      },
`
but it keeps installing zls from Mason.

**Comment by feoh** [comment]
Hi. This is not an actual issue. Closing.
