### ISSUE TITLE
I installed debugpy, jdtls, ast-grep, java-debug-adapter, but none of these are functioning. I have the LSPs set in the init.lua file as well. 

### ISSUE THREAD

**Issue by MrCherub** [nvim-lua/kickstart.nvim#1184]
I have debugpy installed and it is loaded within Mason. I also have pyright installed and it works well but debugpy is not functioning correctly. Whenever I run F5 the debug lanes close and I get a pop up window. I am having trouble getting jdtls to work properly as well. When I open a java file it states, "Client jdtls quit with the exit code 1 and signal 0. Check log for errors: /Users/jj/.local/state/nvim/lsp.log" The java debugger doesn't work either After hitting F5 I get "No configuration found for 'java'. You need to add configs to 'dap.configurations.java' (See ':h dap-configuration')"
OS: macOs Sequoia 15.0.1 Intel mac
Terminal: iterm2
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1727621189
<img width="1920" alt="Screenshot 2024-10-06 at 11 45 59 PM" src="https://github.com/user-attachments/assets/67db9f22-eabd-4b06-877f-25d69fcd26f7">
return {

  'mfussenegger/nvim-dap',
  dependencies = {
 
    'rcarriga/nvim-dap-ui',

    'nvim-neotest/nvim-nio',

    'williamboman/mason.nvim',
    'jay-babu/mason-nvim-dap.nvim',

    'leoluz/nvim-dap-go',
  },
  keys = function(_, keys)
    local dap = require 'dap'
    local dapui = require 'dapui'
    return {
      -- Basic debugging keymaps, feel free to change to your liking!
      { '<F5>', dap.continue, desc = 'Debug: Start/Continue' },
      { '<F1>', dap.step_into, desc = 'Debug: Step Into' },
      { '<F2>', dap.step_over, desc = 'Debug: Step Over' },
      { '<F3>', dap.step_out, desc = 'Debug: Step Out' },
      { '<leader>b', dap.toggle_breakpoint, desc = 'Debug: Toggle Breakpoint' },
      {
        '<leader>B',
        function()
          dap.set_breakpoint(vim.fn.input 'Breakpoint condition: ')
        end,
        desc = 'Debug: Set Breakpoint',
      },
      -- Toggle to see last session result. Without this, you can't see session output in case of unhandled exception.
      { '<F7>', dapui.toggle, desc = 'Debug: See last session result.' },
      unpack(keys),
    }
  end,
  config = function()
    local dap = require 'dap'
    local dapui = require 'dapui'

    require('mason-nvim-dap').setup {
      -- Makes a best effort to setup the various debuggers with
      -- reasonable debug configurations
      automatic_installation = true,

      -- You can provide additional configuration to the handlers,
      -- see mason-nvim-dap README for more information
      handlers = {},

      -- You'll need to check that you have the required things installed
      -- online, please don't ask me how to install them :)
      ensure_installed = {
        -- Update this to ensure that you have the debuggers for the langs you want
        'delve',
        'debugpy', -- Ensure debugpy is included here
        'java-debug-adapter',
      },
    }

    -- Dap UI setup
    -- For more information, see |:help nvim-dap-ui|
    dapui.setup {
      -- Set icons to characters that are more likely to work in every terminal.
      --    Feel free to remove or use ones that you like more! :)
      --    Don't feel like these are good choices.
      icons = { expanded = '▾', collapsed = '▸', current_frame = '*' },
      controls = {
        icons = {
          pause = '⏸',
          play = '▶',
          step_into = '⏎',
          step_over = '⏭',
          step_out = '⏮',
          step_back = 'b',
          run_last = '▶▶',
          terminate = '⏹',
          disconnect = '⏏',
        },
      },
    }

    dap.listeners.after.event_initialized['dapui_config'] = dapui.open
    dap.listeners.before.event_terminated['dapui_config'] = dapui.close
    dap.listeners.before.event_exited['dapui_config'] = dapui.close

    -- Install golang specific config
    require('dap-go').setup {
      delve = {
        -- On Windows delve must be run attached or it crashes.
        -- See https://github.com/leoluz/nvim-dap-go/blob/main/README.md#configuring
        detached = vim.fn.has 'win32' == 0,
      },
    }
  end,
}

**Comment by iton0** [comment]
this is not a kickstart issue. https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation will give you info and help on how to configure. hope this helps

**Comment by feoh** [comment]
These are working for others. Please submit issues to the indiviual LSP repo if needed. CLosing.
