### ISSUE TITLE
Stuck at [mason-lspconfig.nvim] installing sumneko_lua

### ISSUE THREAD

**Issue by ysiivan** [nvim-lua/kickstart.nvim#119]
**Describe the bug**
nvim never gets past "[mason-lspconfig.nvim] installing sumneko_lua"
![image](https://user-images.githubusercontent.com/17600396/210436485-1b92ca4f-a2a4-404b-a5aa-9b848c0aa4bf.png)

**To Reproduce**
1. Start clean
2. Copy the repo's init.lua in ~/.config/nvim/
3. Start nvim
![image](https://user-images.githubusercontent.com/17600396/210436963-88ab98dd-7eb7-459b-98db-6ef769bd6056.png)
![image](https://user-images.githubusercontent.com/17600396/210437078-4cfb1a15-7cdb-4432-a717-362a3b790e14.png)
4. Exit nvim and start it again
This is the last status message displayed. 
![image](https://user-images.githubusercontent.com/17600396/210437437-476bd6d6-4e6d-4cb8-8dae-480023695da4.png)
5. Exit nvim and start it again.
Never gets past this
![image](https://user-images.githubusercontent.com/17600396/210437598-fd60b92a-7a94-4cfc-9ba2-05cfe8981733.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04 in WSL2 on Windows 11
- Terminal: Windows Terminal

** Neovim Version **
 ```
:version
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az190-151

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

**Comment by seantwie03** [comment]
I would check the `mason.log` file to see if there are any error messages. It should be located here: `$HOME/.cache/nvim/log`

**Comment by redonaghy** [comment]
Hey ysiivan

I experienced the same issue on my WSL install of Debian. After a bit of digging I realized that I needed a tool called `unzip` to install the lsp which I installed with

```bash
# sudo apt install unzip
```

After that it installed just fine.

 Hopefully this solves the issue for you!

**Comment by ysiivan** [comment]
@redonaghy 
Thank, but ```unzip``` is already installed

**Comment by ysiivan** [comment]
@seantwie03 
Indeed a ```Mason``` issue. By default it connects to a proxy repository, access to which is blocked by my corporate watchdog appliance.  Other users are reporting the same for their corporate networks.
The solution is to config ```Mason``` not to use its intermediate repo.
```lua
    -- The provider implementations to use for resolving package metadata (latest version, available versions, etc.).
    -- Accepts multiple entries, where later entries will be used as fallback should prior providers fail.
    -- Builtin providers are:
    --   - mason.providers.registry-api (default) - uses the https://api.mason-registry.dev API
    --   - mason.providers.client                 - uses only client-side tooling to resolve metadata
    providers = {
        "mason.providers.client",
    },
```
