### ISSUE TITLE
This { name = 'buffer' }, is not working at all. Most of my LSPs work except for jdtls but when it comes to autocomplete in buffers it doesn't work at all.

### ISSUE THREAD

**Issue by MrCherub** [nvim-lua/kickstart.nvim#1190]
{ name = 'buffer' },
Doesn't do anything at all. I have tested it many times in countless different buffers and it doesn't function. I haven't been able to get this to work. 

## Desktop

- OS: macOS Sequoia 15.0.1
- Terminal: iterm2

## Neovim Version

NVIM v0.10.2

**Comment by glaulher** [comment]
jdtls working for me . You can check my configuration in my repository here:
[GitHub - glaulher/kickstart.nvim.](https://github.com/glaulher/kickstart.nvim)
branch mykickstart
Maybe it will help you!

**Comment by MrCherub** [comment]
> jdtls working for me . You can check my configuration in my repository here:
> 
> [GitHub - glaulher/kickstart.nvim.](https://github.com/glaulher/kickstart.nvim)
> 
> branch mykickstart
> 
> Maybe it will help you!

Do you have autocomplete in an empty buffer or a clean file without an LSP?

**Comment by glaulher** [comment]
![image](https://github.com/user-attachments/assets/b5c9fcad-c46e-4519-a478-85c4050b47cf)
on an empty buffer with lsp

**Comment by glaulher** [comment]
nvim-java plugin wiki also has a configuration with kickstart:

https://github.com/nvim-java/nvim-java/wiki/Kickstart

**Comment by feoh** [comment]
In any case this isn't a kickstart issue. Closing.
