### ISSUE TITLE
Error detected while processing /home/cbdev/.config/nvim/init.lua: E5113: Error while calling lua chunk: /home/cbdev/.config/nvim/init.lua:165: attempt to index field 'keymap' (a nil value) stack traceback:         /home/cbdev/.config/nvim/init.lua:165: in main chunk Press ENTER or type command to continue

### ISSUE THREAD

**Issue by calloumi123** [nvim-lua/kickstart.nvim#1204]
## Describe the bug

Hi, I need help with a Neovim error. I recently cloned a Neovim configuration repository, and now I'm getting an error every time I open Neovim. I very new so this might be user error/skill issues .

Here's the error I'm seeing:
CopyError detected while processing /home/cbdev/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/cbdev/.config/nvim/init.lua:165: 
attempt to index field 'keymap' (a nil value) 
stack traceback: /home/cbdev/.config/nvim/init.lua:165: in main chunk
Can someone help me fix this? I'm new to Neovim configuration."

## To Reproduce

1. All i did was clone the repo delete the lazylock.json form repo. and I get error, it feels like im making skill isssues but iIreally dont know why its happenig

## Desktop

- OS: Windows but nvim is on WSL (ubuntu) 
- Terminal: powershell

## Neovim Version

0.6.1

```
```

**Comment by calloumi123** [comment]
Im silly i was missing dependencys sorry

**Comment by pavloo** [comment]
Getting the same error. What was the solution? Tried a nightly build of Neovim, didn't help. It seems I have all the system dependencies from the list.

**Comment by pavloo** [comment]
It turned out to be the old version of Neovim that I had installed in my system. 0.6.x vs the latest 0.10.x (as of time of writing)
