### ISSUE TITLE
Can not scroll through documentation window

### ISSUE THREAD

**Issue by YouRik** [nvim-lua/kickstart.nvim#1206]
## Describe the bug

Using `<C-f>` and `<C-b>` as defined in the init.lua to scroll through the documentation window does not work.
Instead, they scroll up and down the worked on buffer by one full page.
See:
https://github.com/nvim-lua/kickstart.nvim/blob/4120893b8a1f31a0957f2f891f7fbef73ddfb9b1/init.lua#L771-L773

## To Reproduce

1. Install kickstart.nvim
2. Install some LSP for a programming language (in my case Python and Pyright)
3. Open a file for that programming language
4. hit `<S-K>` to hover over a symbol that has documentation and observe the documentation window appear
5. Press `<C-f>` or `<C-b>` and observe that it's not scrolling the documentation

## Desktop

- OS: macOS 15
- Terminal: iterm2

## Neovim Version

```
:version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run ":verbose version" for more info
```

**Comment by YouRik** [comment]
I understood that this is probably not a bug.
The keys map to scrolling the  documentation window of `cmp` which is triggered by `<C-Space>`.
The window that pops up on hover is apparently unrelated to `cmp` and therefore not scrollable by the mapped key combination.

I will close the issue if someone can confirm this.

**Comment by samarth-na** [comment]
for me `C-space` just moves cursor forward and does not toggle cmp documentation

not an exact solution but you can `K` on the word and get same documentation

**Comment by feoh** [comment]
Yes I am not sure I understand what "Hit for hover" means.

Sorry if you can give me a real example and exact keystrokes maybe I can help?

**Comment by samarth-na** [comment]
okay here you go:-

- you should be in normal mode
- go over the word you want to get documentation of
- type `K` on the word 
![image](https://github.com/user-attachments/assets/083b8379-cc7a-4b73-ba63-b07adb61efbe)
some window like this should appear then if you hit K again your cursor will go into the window and you can scroll like any other buffer 

i hope this helped but if not feel free to ask again

**Comment by feoh** [comment]
OK so if I'm understanding correctly we're Working As Designed (TM).

Closing. Please feel free to reopen if there's actual work for the kickstart.nvim project here.
