### ISSUE TITLE
Help with LSP for Astro in Neovim

### ISSUE THREAD

**Issue by gianlucahe** [nvim-lua/kickstart.nvim#1209]
Hi there,

I'm fairly new to Neovim, so I apologize if this question seems basic. I'm trying to get the Language Server Protocol (LSP) running for Astro, but I'm encountering some issues. When I run :Mason, it indicates that I've installed the language servers. However, when I open .astro files, I don't get any autocompletion or error highlighting.

The only change I've made is adding this to my configuration (line 620):
```
local servers = {
    tsserver = {},
    html = { filetypes = { 'html', 'twig', 'hbs' } },
    astro = {},
}
```

I would greatly appreciate any help, as the attempts I've made so far haven't resolved the issue, and I'm unsure how to proceed. Thank you!

**Comment by iton0** [comment]
First replace tsserver with ts_ls; the reference to the lsp was updated recently. also check that the LSP is connected to the astro file buffer via running LspInfo in the command line. if the root directory says not found that usually indicates that the astro file needs to be in a git repo so make sure that it is. hope this helps

**Comment by gianlucahe** [comment]
Hi @iton0, 
first of all thanks for your tip. So I did all that and Astro is shown when I do LspInfo. Unfortunately now that I changed from tsserver to ts_ls I am getting this error "[lspconfig] Cannot access configuration for ts_ls. Ensure this server is listed in `server_configurations.md` or ad ded as a custom server. Press ENTER or type command to continue". 

Btw I did fix it because it first said that it doesn't know ts_ls with this [code](https://github.com/neovim/nvim-lspconfig/pull/3232#issuecomment-2331025714).
Really appreciate your help with that, thank you :)

**Comment by iton0** [comment]
see if running MasonUpdate resolves the error

**Comment by gianlucahe** [comment]
Unfortunately not. When I change it so that I simply change from tsserver to ts_ls and I do the MasonUpdate I get this: 
```
Error executing vim.schedule lua callback: ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:80: Cannot f
ind package "ts_ls".
stack traceback:
        [C]: in function 'error'
        ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:80: in function 'get_package'
        ...on-tool-installer.nvim/lua/mason-tool-installer/init.lua:166: in function 'callback'
        ...share/nvim/lazy/mason.nvim/lua/mason-core/async/init.lua:87: in function 'step'
        ...share/nvim/lazy/mason.nvim/lua/mason-core/async/init.lua:96: in function 'run'
        ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:202: in function 'refresh'
        ...on-tool-installer.nvim/lua/mason-tool-installer/init.lua:195: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by iton0** [comment]
1. make sure that the mason-lspconfig plugin is updated. 
2. comment out the ts_ls = {}, line, 
3. make sure that the ts_ls is not installed, 
4. run the MasonUpdate, 
5. uncomment the ts_ls line
6. and then reinstall and see if that works.

**Comment by gianlucahe** [comment]
I followed all those steps. In Lazy, I updated mason-lspconfig and tried removing tsserver from Mason, then reinstalled ts_ls. However, after all that, I couldn’t even find ts_ls in Mason manually—only tsserver was available. I really appreciate the help, but does this mean I have to use tsserver?

**Comment by iton0** [comment]
Yeah sorry bout all the step. If tsserver works for you use that. Just note in the future if u update mason-lspconfig and it can't find tsserver you will just need to change it to ts_ls. I would also suggest since your new to neovim to check out the video in the kickstart readme if you haven't already.

**Comment by gianlucahe** [comment]
No worries and thanks for the help! I will definitely try to check it out :) I know it was pretty long tho

**Comment by iton0** [comment]
If you no longer need further assistance, please close the issue
