### ISSUE TITLE
<leader>/ does neither theme selection to fuzzy buffer finding well

### ISSUE THREAD

**Issue by kubauk** [nvim-lua/kickstart.nvim#1218]
## Describe the bug
The configuration in init.lua is confused for <leader>/. 

The help messages and descriptions all indicate that the key map should be to fuzzy file the current buffer, but the lua configuration is trying to set up a theme selection window. As a consequence if you run the key map, the current buffer is displayed in a tiny window.

## To Reproduce
1. Open nvim
2. Type <leader>/ in normal mode

## Desktop

- OS: MacOS 15.0.1
- Terminal: iTerm2 and also neovide

## Neovim Version

```
:verbose version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.10.1/share/nvim"
```

**Comment by iton0** [comment]
that is the expected behavior

**Comment by drelephant** [comment]
I am super new to nvim but when I type `<leader>/` which is `space` then `/`, it pops up a fuzzy search for the current buffer for me.

**Comment by kubauk** [comment]
The confusion is on my side. I was thinking about how I can change neovim
themes where I see now that the example with <leader>/ is about telescopes
look and feel.

Please close this issue.

**Comment by iton0** [comment]
@kubauk close the issue yourself please
