### ISSUE TITLE
How to get mini.surround to work?

### ISSUE THREAD

**Issue by drelephant** [nvim-lua/kickstart.nvim#1221]
Warning! I am very new to neovim!

## Describe the bug
I can't get any of the surrounding commands to work.

## To Reproduce

1. `git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim`
2. I also enabled neo-tree by uncommenting `require 'kickstart.plugins.neo-tree',` on line 936
3. `nvim`
4. open any file

If I type `space sk` to show keymaps in telescope, it shows a lot of commands for surrounding text (I assume with brackets or quotes).

![image](https://github.com/user-attachments/assets/374ed38e-383c-48d8-ad80-9c043396444c)

eg I'm trying to use `sa` to add surrounding quotes...

In Normal mode, as soon as I press `s`, it deletes the character under the cursor and goes into Insert mode.

If I'm in Visual mode with a selection, as soon as I press `s`, it replaces all the selected text with nothing and goes into Insert mode.

How can I access those commands to surround text?

## Desktop

- OS: Ubuntu 20.04
- Terminal: Putty from Windows 10

## Neovim Version

```
NVIM v0.10.1
Build type: Debug
LuaJIT 2.1.1713484068
```
I'm sure I'm probably doing something dumb.

Thanks!

**Comment by iton0** [comment]
It may be the timeoutlen option is too short. Try increasing it to 500 and see if that works.

**Comment by drelephant** [comment]
Thanks, that fixed it!!

There's no way I would have ever found that.
