### ISSUE TITLE
cant use kickstart.nvim

### ISSUE THREAD

**Issue by Rxz777** [nvim-lua/kickstart.nvim#1224]
# Cant use kickstart.nvim its gives me this error 
Error detected while processing /home/sepehr/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/sepehr/.config/nvim/init.lua:165: attempt to index field 'keymap' (a nil value)
stack traceback:
        /home/sepehr/.config/nvim/init.lua:165: in main chunk
Press ENTER or type command to continue

**what do i do**

# The machine I'm using
Hardware model Sony Corporation VPCEA2KGX
# The os i'm using Pop!_OS 22.04 LTS

let me know if you want anymore info.

**Comment by cmdrrobin** [comment]
What version of Neovim are you using? And are you not accidentally using vim rather than (Neovim) nvim?

To see what version of neovim you can do `nvim --version`

**Comment by jeshtroy** [comment]
+1 Facing same error
Fresh install of neovim using `sudo apt install neovim`
```
$ neovim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by iton0** [comment]
You are running v0.6.1; latest stable version as of writing this is v0.10.2

Kickstart.nvim targets only the latest ['stable'](https://github.com/neovim/neovim/releases/tag/stable) and latest ['nightly'](https://github.com/neovim/neovim/releases/tag/nightly) of Neovim.

Update accordingly and it will no longer be an issue.

**Comment by skalixur** [comment]
Hello! Same issue here. Running v.0.10.2 on windows via chocolatey.

```
Error detected while processing C:\Users\<name>\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: C:\Users\<name>\AppData\Local\nvim\init.lua:230: module 'lazy' not found:
        no field package.preload['lazy']
        no file '.\lazy.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy.lua'
        no file 'C:\tools\neovim\nvim-win64\bin\lua\lazy\init.lua'
        no file '.\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\lazy.dll'
        no file 'C:\tools\neovim\nvim-win64\bin\loadall.dll'
stack traceback:
        [C]: in function 'require'
        C:\Users\<name>\AppData\Local\nvim\init.lua:230: in main chunk
Press ENTER or type command to continue
```

```
❯ nvim -v
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

Edit: Oh. Seems to be a different error?

**Comment by cmdrrobin** [comment]
@skalixur yeah, this is a different error. If still exists, could you please create a new issue?

**Comment by lfelipebmacedo** [comment]
Hi! I`m using neovim v0.10.2

```
E5113: Error while calling lua chunk: vim/loader.lua:0: attempt to call upvalue '' (a nil value)
stack traceback:
        vim/loader.lua: in function 'cache_file'
        vim/loader.lua: in function 'read'
        vim/loader.lua: in function 'loadfile'
        vim/loader.lua: in function <vim/loader.lua:0>
        [C]: in function 'require'
        ...elipe/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:77: in function 'setup'
        /home/felipe/.config/nvim/init.lua:230: in main chunk
```

**Comment by feoh** [comment]
The OP has gone radio silent and pretty clearly seems to be running an older version.

Closing. Please feel free to reopen if you can prove you're running a more current compatible version.

**Comment by jxu** [comment]
I had the same issue using Ubuntu 22.04 neovim from apt repos which is at 0.6. 
Is there a PPA? Edit: Nvm I found it at the recipes which is below the linux install instructions
