### ISSUE TITLE
indent-blankline.nvim not working correctly for some file types

### ISSUE THREAD

**Issue by christiaan-janssen** [nvim-lua/kickstart.nvim#1237]
## Describe the bug
When using `indent-blankline.nvim` the settings are not applied to all file types. If I use the same plugin in NVChad, I don't have these problems.

It is working for lua for instance:

![Screenshot 2024-11-19 at 10 09 51](https://github.com/user-attachments/assets/53dcce4c-9025-457d-b51d-fc73e715b81a)

but for go it is showing wierd results:

![Screenshot 2024-11-19 at 10 10 29](https://github.com/user-attachments/assets/a7133911-8cd2-4b58-b68c-69252cba9f36)

## To Reproduce
Use my [fork](https://github.com/christiaan-janssen/kickstart.nvim) of the repo

## Desktop
I have tried this on both my Macbook and my Linux laptop
- OS: OSX Ventura 13.6.9
- Terminal: kitty 0.36.2 & iTerm 3.5.5

- OS: Arch Linux 
- Terminal: kitty 0.37.0 & alacritty 0.14.0

## Neovim Version
OSX:
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
```

Linux:
```
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
```

**Comment by feoh** [comment]
Is it possible that vim-sleuth is getting things mixed up here? I've seen it make some questionable decisions with less common file types.

**Comment by christiaan-janssen** [comment]
I removed vim-sleuth, but that does not solve the issue unfortunately.

**Comment by kaezrr** [comment]
Do you have a formatter installed for those file types? and check if it is attaching properly to the buffer using `:ConformInfo`

**Comment by christiaan-janssen** [comment]
Yes, I have the formatter for go installed and it seems to connect. I do get some errors about stylelua and terraform_fmt, but I don't think this should have any impact, as I get the same error in file types that have no problem.

```
Log file: /Users/christiaan/.local/state/nvim/conform.log
          
          09:42:10[ERROR] Formatter 'stylua' error: error: could not format from stdin: failed to format from stdin: error parsing: error occurred while creating ast: unexpected token `init`. (starting from line 237, character 5 and ending on line 237, character 9)
          additional information: expected '}'
          
          2024-11-06 10:22:03[WARN] Formatter 'terraform_fmt' timeout
          2024-11-06 10:22:06[WARN] Formatter 'terraform_fmt' timeout
          2024-11-14 09:27:52[ERROR] Formatter 'stylua' error: error: could not format from stdin: failed to format from stdin: error parsing: error occurred while creating ast: unexpected token `local`. (starting from line 3, character 1 and ending on line 3, character 6)
          additional information: expected '}'
          
          2024-11-14 09:28:02[ERROR] Formatter 'stylua' error: error: could not format from stdin: failed to format from stdin: error parsing: error occurred while creating ast: unexpected token `map`. (starting from line 8, character 1 and ending on line 8, character 4)
          additional information: expected '}'

Formatters for this buffer:
LSP: gopls

Other formatters:
stylua ready (lua) /Users/christiaan/.local/share/nvim/mason/bin/stylua
```

**Comment by iton0** [comment]
comment out `vim.opt.listchars = { tab = '» ', trail = '·', nbsp = '␣' }`; based on this https://github.com/lukas-reineke/indent-blankline.nvim/discussions/897

**Comment by feoh** [comment]
Not blowing you off here but have you thought about asking on [their repo](https://github.com/lukas-reineke/indent-blankline.nvim) instead?

**Comment by christiaan-janssen** [comment]
> comment out `vim.opt.listchars = { tab = '» ', trail = '·', nbsp = '␣' }`; based on this [lukas-reineke/indent-blankline.nvim#897](https://github.com/lukas-reineke/indent-blankline.nvim/discussions/897)

Turning of `listchars` solves the problem, thank you!

> Not blowing you off here but have you thought about asking on [their repo](https://github.com/lukas-reineke/indent-blankline.nvim) instead?

Yes I did, I wasn't sure where to ask. But as the problem didn't show up in other nvim setups I have used, I thought to ask here.

**Comment by iton0** [comment]
@christiaan-janssen a good rule of thumb is if you are having issues with a particular plugin to check the plugin's github repo.
From there that's where can take the steps to:
- read the docs for that plugin
- check the issues/discussions (also where you should ask first)

Then if none of that works that is when you can come here.

Please close this issue.

**Comment by iton0** [comment]
@feoh it may be useful to update the bug report template to include a checklist similar to the steps I pointed out in the above comment.
