### ISSUE TITLE
Nerd font not working with LSP diagnostic errors

### ISSUE THREAD

**Issue by pkenway** [nvim-lua/kickstart.nvim#1240]
## Describe the bug
I'm not able to see the selected nerd font glyphs in inline diagnostic messages. I can verify that the glyphs are rendered correctly when they appear in a text file. (For this screenshot, I haven't saved the typo, so the init.lua was parsed correctly when nvim started)
<img width="707" alt="Screenshot 2024-11-21 at 11 06 15 AM" src="https://github.com/user-attachments/assets/7ea8f38e-de85-4cd4-aae2-e1e7c1237374">

## To Reproduce
1. `brew install --cask font-fira-code-nerd-font`
2. select the installed font in iTerm
3. set have_nerd_font = true in  `init.lua`
4. uncomment this code:
```  -- Change diagnostic symbols in the sign column (gutter)
     -- if vim.g.have_nerd_font then
      --   local signs = { ERROR = '', WARN = '', INFO = '', HINT = '' }
      --   local diagnostic_signs = {}
      --   for type, icon in pairs(signs) do
      --     diagnostic_signs[vim.diagnostic.severity[type]] = icon
      --   end
      --   vim.diagnostic.config { signs = { text = diagnostic_signs } }
      -- end
```
5. restart nvim

I also verified that the above code block is executing using a print() statement.

## Desktop

- OS: MacOS Sonoma
- Terminal: iTerm2

## Neovim Version
```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
```

**Comment by glmlm** [comment]
This feature is intended to change only the diagnostic signs displayed in the status column, and not those displayed inline.
If I understand your goal correctly, you might need to add something like:
```
vim.diagnostic.config {
  signs = { text = diagnostic_signs },
  virtual_text = {
    prefix = function(diagnostic)
      return signs[vim.diagnostic.severity[diagnostic.severity]]
    end,
  },
}
```
If you'd prefer not to use the same signs for the status column and inline, you might want to consider trying something like:
```
local signs_prefix = { ERROR = 'E', WARN = 'W', INFO = 'I', HINT = 'H' }
...
    prefix = function(diagnostic)
      return signs_prefix[vim.diagnostic.severity[diagnostic.severity]]
...
```

**Comment by feoh** [comment]
Please feel free to re-open if the provided workaround doesn't meet your needs. Closing.
