### ISSUE TITLE
Help files for dap not found

### ISSUE THREAD

**Issue by Daemo00** [nvim-lua/kickstart.nvim#1241]
## Describe the bug
Help for debug plugins is not found, for instance for `dap.txt`.
Help files are found after the first time the debugger is activated.

I have done some investigation and this has been caused by https://github.com/nvim-lua/kickstart.nvim/pull/1216.
Loading a plugin only when needed is great for optimizing resources, but help files should be always available, shouldn't they?
I opened this as a bug but maybe this is the expected behavior?
Maybe this is an issue of Lazy itself.

By the way, thanks for all the great work 🚀

## To Reproduce

1. Open Neovim
3. `:h dap.txt` (autocompletion does not work)

### Observed
> E149: Sorry, no help for dap.txt

### Expected
Help file https://github.com/mfussenegger/nvim-dap/blob/cc92b054720a96170eca6bd9bdedd43d2b0a7a8a/doc/dap.txt is shown

## Desktop

- OS: Ubuntu 24.10
- Terminal: zsh

## Neovim Version

```
NVIM v0.11.0-dev
Build type: RelWithDebInfo                                                                                                                                                                    
LuaJIT 2.1.1719379426
```

**Comment by glmlm** [comment]
> I opened this as a bug but maybe this is the expected behavior?
> Maybe this is an issue of Lazy itself

That's correct. the lazy-loaded plugin directory is not loaded until the activation condition is met, so of course the help files are not loaded either.
If you have any feedback regarding this specification, you can file an issue in the lazy.nvim repository.

If you haven't had much response from the lazy.nvim team on this, and you'd like to suggest changes to the lazy-loading event of debug.lua in this project, I must admit that my personal opinion is not entirely in favour. I believe that the advantage of enabling a plugin only when necessary by entering a specific key outweighs the benefit of having unloaded plugin help files available at all times. Moreover, the activation key for it can be found by which-key.nvim at any time.

**Comment by feoh** [comment]
Thanks @gloomy-lemon-debatable!

@Daemo00 I get where you're coming from here but as said above, please file the issue against the lazy.nvim repository.

Closing.

**Comment by Daemo00** [comment]
For whoever comes by, this has already been discussed in Lazy's repo in a few issues, the root issue is probably https://github.com/folke/lazy.nvim/issues/567.
