### ISSUE TITLE
Warning setting up kickstart in init.lua

### ISSUE THREAD

**Issue by forevpurity** [nvim-lua/kickstart.nvim#1257]
Hi, 

I'm new to nvim, after following the installation guide, when I opened `init.lua`, there're a lot of warnings, is this normal, or did I do something wrong, I'm using Ubuntu-24.04 on WSL:

![image](https://github.com/user-attachments/assets/13c91b9a-8029-460d-9ffd-32b3a5ab0858)
![image](https://github.com/user-attachments/assets/fbfa5ae6-d9fc-4a03-93f7-de9f6439199e)

Thanks a lot for help !!!

**Comment by r-keenan** [comment]
Yeah, I am having the same issue. I will let you know if I figure out the fix. I have not had an opportunity to troubleshoot it.

**Comment by iton0** [comment]
uncomment this line your code 
              `-- diagnostics = { disable = { 'missing-fields' } },`

**Comment by feoh** [comment]
Hi.

Missing field detection is a feature that, as @iton0 pointed out, can be disabled.

Working as designed. Closing.

**Comment by paatre** [comment]
Wanted to add a comment here to reiterate what @iton0 suggested here to use the `missing-fields` warning disabling. I noticed that @Ln86 reacted with a 👎🏻 emoji so maybe this helps: an issue has been created on the `mason-lspconfig` repository 3 weeks ago that also describes this exactly the same warning issue: https://github.com/williamboman/mason-lspconfig.nvim/issues/500.

The issue author notes the following in the comment section:

> Use `---@diagnostic disable [missing-fields]` or pass all the `MasonLspconfigSettings` fields to the setup call until this is addressed.

`mason-lspconfig` is only one Lua plugin with "missing required fields" that `lua_ls` warns about. It wouldn't be wise from Kickstart's point of view to start addressing _all_ the different plugin definition issues that rise up. It isn't Kickstart's job, it's for the plugin contributors to keep the type annotations as such that reflects the reality of how the configuration should and can be used. In this required fields case, the plugin contributors can make the fields optional which fixes these warning issues.

But, if a single Neovim (especially with a Kickstart variant on this context) user wants to address this issue without disabling the warning, you can provide some defaults by yourself.

Hopefully this helped!
