### ISSUE TITLE
新安装的kickstartnvim，代码补全按回车会直接换行

### ISSUE THREAD

**Issue by Aiontropy** [nvim-lua/kickstart.nvim#1260]
## Describe the bug

第一次使用 nvim 。新安装的 kickstartnvim ，代码补全按回车会直接换行，应该是默认的 lsp ，启动了 neo-tree 和 autopairs

## To Reproduce

1. 输入 a 
2. 会出现代码提示
3. 按回车就会换行

https://github.com/user-attachments/assets/9866b326-8e28-4375-8906-5a932d9d1e0c

## Desktop

- OS: Windows
- Terminal: cmd/powershell

## Neovim Version

```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

**Comment by FLchs** [comment]
If I understand well you are complaining about the default "accept autocompletion" keymap not being tab or enter ? (google translate is not that efficient here)

You can find and edit the nvim-cmp keymaps here : https://github.com/nvim-lua/kickstart.nvim/blob/8d1ef972bc32faa86fee21a57f9033b41f612ebb/init.lua#L775-L822

**Comment by Aiontropy** [comment]
> If I understand well you are complaining about the default "accept autocompletion" keymap not being tab or enter ? (google translate is not that efficient here)
> 
> You can find and edit the nvim-cmp keymaps here :
> 
> https://github.com/nvim-lua/kickstart.nvim/blob/8d1ef972bc32faa86fee21a57f9033b41f612ebb/init.lua#L775-L822

Sorry, my English is bad.
Thanks for your reply, I think Google Translate is right.

Your reply is solved my problem.
I hope I'm not disturbing you.
I'm noob, sorry, and very very very thank you!!!
