### ISSUE TITLE
cmp-nvim: backslash before trailing slash in paths

### ISSUE THREAD

**Issue by benabub** [nvim-lua/kickstart.nvim#1261]
## Describe the bug   

Not sure which this bug is: cmp-nvim or kickstart configuration.  

Will be appreciated for vector to search.

This problem was described by AllergicMushroom under cmp-path issue:  

---
(link)[https://github.com/hrsh7th/cmp-path/issues/79#issue-2662704911]

Everytime I press , the suggestion is accepted and a trailing slash is added, but a backslash is also added before this slash.

Is there an option to disable the addition of this backslash ?

Note: I have not changed cmp-path settings, and the readme specifies that the trailing slash option is disabled by default, so I am unsure if this completion comes from cmp-path. This plugin is loaded as a dependency of nvim-cmp though.

---

## To Reproduce

1. Start typing the path in quotes
2. Choose cmp option

Expected: `path/`

Actual: `path\/`

## Desktop

- OS: Linux Mint
- Terminal: zsh

## Neovim Version

```
NVIM v0.11.0-dev                                                                                                                
Build type: RelWithDebInfo                                                                                                      
LuaJIT 2.1.0-beta3  
```

**Comment by feoh** [comment]
Which kickstart settings do you think cause/effect this issue?

If you can't point to code in kickstart that does this, please file the bug in the cmp repo.

Thank you!
