### ISSUE TITLE
mini.surround uses s as keymap, just like substitute.

### ISSUE THREAD

**Issue by moshpirit** [nvim-lua/kickstart.nvim#1268]
## Describe the bug

We can select a piece of text and substitute it using `s`, which is a very basic command from vim, but mini.surround uses it too to surround that piece of text. Since kickstart is focused on novel Nvim users, shouldn't it be remapped to use `<leader>s` instead?

It's kind of confusing to have these functionalities:

- `Vs` makes mini.surround operate.
- `viws` makes substitute operate (same with selecting the sentence, etc.).
- `viw<leader><BS>s` makes mini.surround operate.
- `S` substitutes the whole line

## Desktop

- OS: Arch Linux
- Terminal: Kitty

## Neovim Version

```
NVIM v0.10.2                                                                                                                                                                              
Build type: RelWithDebInfo                                                                                                                                                                
LuaJIT 2.1.1731601260                                                                                                                                                                     
```

**Comment by omnster** [comment]
This seems to be the conventional behavior inherited from `tpope/vim-surround`.  Since in the visual mode `s` mostly coincides with `c`, I believe the remap by the surround plugins is justified.

**Comment by moshpirit** [comment]
> This seems to be the conventional behavior inherited from `tpope/vim-surround`. Since in the visual mode `s` mostly coincides with `c`, I believe the remap by the surround plugins is justified.

Hmm you're right! then, I think that `s`should be completely unmap before loading the plugin to avoid this misbehavior (for example: `vs` vs `viws`)

**Comment by feoh** [comment]
Yup. This is the way it should be IMO. Closing but thanks for the report!

**Comment by moshpirit** [comment]
> Yup. This is the way it should be IMO. Closing but thanks for the report!

Thanks for replying! Sorry to bring this up again. I'm still learning, do I need to do anything? If so, what do I need to do to make this happen?

**Comment by nicanordlc** [comment]
I have this currently to unmap the `s` key before loading `mini.surround` but it is not working:

```
-- Unmap the 's' key globally before loading mini.surround
vim.api.nvim_del_keymap('n', 's')
require('mini.surround').setup()
```

**Comment by n-prat** [comment]
I had this issue and it took a while to understand the origin(new Neovim user 🫣). I have done the fix [ linked by mini.surround](https://github.com/echasnovski/mini.surround/blob/aa5e245829dd12d8ff0c96ef11da28681d6049aa/doc/mini-surround.txt#L572
) and it works fine now.
