### ISSUE TITLE
Quickfix diagnostic keymap question

### ISSUE THREAD

**Issue by keymatch-clovis** [nvim-lua/kickstart.nvim#1271]
Hi! I hope everything is going well, and thank you for this amazing piece of software!

## Description

I have a quick question about some configuration with the diagnostics quickfix list keymap.

I was watching [this video](https://youtu.be/wOdL2T4hANk?si=KWW1KoM2JiZPEo0e&t=324) from TJ about diagnostics with quickfix, and I noticed that the keymap is a bit different, like:

https://github.com/nvim-lua/kickstart.nvim/blob/de44f491016126204824fac2b5a7d7e544a769be/init.lua#L168

If I leave it like this, I can't use other keymaps to traverse the quickfix list, like:

```lua
vim.keymap.set('n', '<M-h>', '<cmd>cnext<CR>')
vim.keymap.set('n', '<M-l>', '<cmd>cprev<CR>')
```

It tells me that there are no errors in the quickfix list.

If I change the keymap to the function TJ references in the video, from `vim.diagnostic.setloclist` to `vim.diagnostic.setqflist`, like:

```lua
vim.keymap.set('n', '<leader>q', vim.diagnostic.setqflist, { desc = 'Open diagnostic [Q]uickfix list' })
```

I can use the previous keymaps to traverse the quickfix list.

So, my question is, is this expected? The use of `vim.diagnostic.setloclist` doesn't affect other functionality, maybe?

Thank you!

**Comment by keymatch-clovis** [comment]
After doing a bit of research, I think I can answer my own question:

[This article](https://freshman.tech/vim-quickfix-and-location-list/) explains it very well:

> The location list behaves just like the quickfix list except that it is local to the current window instead of being global to the Vim session. So if you have five open windows, you can have up to five location lists, but only one quickfix list.

I imagine then that the behavior of a location list with `vim.diagnostic.setloclist` is expected; we would want to have different lists for different windows. I just have to change my keymaps with the counterparts from quickfix list to location list, something like:

```lua
vim.keymap.set('n', '<M-h>', '<cmd>lnext<CR>')
vim.keymap.set('n', '<M-l>', '<cmd>lprev<CR>')
```

And everything is working fine!

I will change the description, though. As I'm very new to this deeper dive to Neovim, I was a bit misled from that. I'll set it to something like:

```lua
vim.keymap.set('n', '<leader>l', vim.diagnostic.setloclist, { desc = 'Open diagnostic [L]ocation list' })
```

**Comment by ccjmne** [comment]
Excellent question and self-answer.
Have fun diving deeper into Neovim, I'm looking forward to seeing you around :)
