### ISSUE TITLE
Warnings in init.lua

### ISSUE THREAD

**Issue by Babahasko** [nvim-lua/kickstart.nvim#1283]
## Describe the bug
After installing in "init.lua" show`s warning message
line - 662 in init.lua

1. Missing required fields in type `MasonLspconfigSettings`: `ensure_installed`, `automatic_installation` [missing-fields]"

![image](https://github.com/user-attachments/assets/865be930-f7bf-435b-8e86-9e07d8a87721)

line - 946 in init.lua

1. Missing required fields in type `LazyConfig`: `root`, `defaults`, `spec`, `local_spec`, `lockfile`, `git`, `pkg`, `rocks`, `dev`, `install`, `headless`, `diff`, `checker`, `change_detection`, `performance`, `readme`, `state`, `profiling`, `debug` [missing-fields]
![image](https://github.com/user-attachments/assets/b82cdc17-3646-4384-9539-08cc51d2d367)

## To Reproduce
1. Install all dependencies
3. Fork the repo
4. git clone the repo
5. nvim init.lua

## Desktop

- OS: Windows 10
- Terminal: cmd

## Neovim Version
```
NVIM v0.10.2                                                                                                                         
Build type: Release
LuaJIT 2.1.1713484068
```

**Comment by iton0** [comment]
@Babahasko look at this #1257 and please close this issue after

**Comment by paatre** [comment]
I just wrote a comment to https://github.com/nvim-lua/kickstart.nvim/issues/1257#issuecomment-2571266302 and it regards to the same issue as this one so I'll link these two together with a comment here. Read this if you think disabling the warning is an issue for you.
