### ISSUE TITLE
Support multiple tab LSP?

### ISSUE THREAD

**Issue by Pxartist** [nvim-lua/kickstart.nvim#133]
The default configuration does not properly support multiple tab and window LSP.

If I enable the rust analyzer in init.lua, only the first rust file opened will have error detection and checks. Opening additional tabs and windows does not have such detections.

**Comment by cprn** [comment]
Is this issue with `init.lua` from this project or is it something specific to rust-analyzer in NeoVim in general?

**Comment by Pxartist** [comment]
@cprn I do not know. It appears that I am the first one who has been bothered that the rust-analyzer does not seem to support multiple files by default. I have checked the rust-analyzer documentation and have found nothing regarding the analyzer not working with tabs and windows or multiple files.

I have been able to get the rust-analyzer to work with tabs and windows although it is a rather tedious method: [https://github.com/fannheyward/coc-rust-analyzer/issues/1099](url) so I guess that would indicate at the very least that rust-analyzer is capable of analyzing multiple tabs and windows.

I would hope that it is possible to implement such behavior in the init.lua script.

**Comment by tjdevries** [comment]
Can you try again with latest version of kickstart.nvim? And make sure you on recent nvim version? I have never had this happen to me (and have recently tried editing rust projects in particular with this config).

Thanks.

**Comment by Pxartist** [comment]
Hello, I used the kickstart.nvm and updated to the most recent stable neovim. The issue is no longer present.

Thank you for your suggestion.

**Comment by tjdevries** [comment]
Great! Thanks for reporting back!
