### ISSUE TITLE
Support for `init_options` in mason LSP setup handler

### ISSUE THREAD

**Issue by cprn** [nvim-lua/kickstart.nvim#135]
**Describe the bug**
I'm not entirely sure it's a "bug" per se. I tried to install Intelephense (LSP for PHP) and Mason provides schema for license key:
```
intelephense.licenceKey
```
But it doesn't work. I made a [mason-lspconfig.nvim ticket](https://github.com/williamboman/mason-lspconfig.nvim/issues/129) and it seems it doesn't work because it has to be passed as initialization option so I guess something like this might be needed for more LSP servers:

```lua
local servers = {
    -- [...]
    intelephense = {
        settings = {     -- settings according to schema
            intelephense = { foo = bar },
        }, 
        init_options = { -- sever specific init flags
            licenceKey = 'key goes here',
        },
    },
}

-- [...]

mason_lspconfig.setup_handlers {
    function(server_name)
        require('lspconfig')[server_name].setup {
            capabilities = capabilities,
            on_attach = on_attach,
            settings = servers[server_name][settings],
            init_options = servers[server_name][init_options],
        }
    end,
}
```

**To Reproduce**
1. install kickstart.nvim's `init.lua`
1. setup Intelephense with license key:
    ```lua
    local servers = {
        -- [...]
        intelephense = {
            intelephense = { licenceKey = 'key goes here' },
        }, 
    }
    ```
1. save, quit NeoVim, open PHP project and see there's no message about Intelephense premium features getting activated

My hope is that whoever at Mason LSP Config project is responsible for Intelephense integration, has a license key to test and confirm it, if needed.

**Desktop (please complete the following information):**
- OS: Manjaro Linux 22.0.0
- Terminal: urxvt v9.30

**Neovim Version**
 - Output of running `:version` from inside of neovim:

```
NVIM v0.8.1                                                                                                                                                                           
Build type: Release                                                                                                                                                                   
LuaJIT 2.1.0-beta3
```

**Comment by williamboman** [comment]
Hey! I'm not sure there's anything actionable here (especially not in this repo). I described some background in my comment [here](https://github.com/williamboman/mason-lspconfig.nvim/issues/129#issuecomment-1421349802).

**Comment by tjdevries** [comment]
If you want to pass additional arguments, you can override the setup_handlers method with a `intelephense` key to pass more arguments.
