### ISSUE TITLE
Question - Two Loading Workspace

### ISSUE THREAD

**Issue by flamendless** [nvim-lua/kickstart.nvim#139]
Hi, every time I open or save a lua file, I get this.

I only have LSP sumneko-lua and Mason lua-language-server

![image](https://user-images.githubusercontent.com/17418737/213342836-fb44bf43-a4ac-4d36-95a6-fb9305a0598e.png)

Is this normal?

**Comment by tjdevries** [comment]
Yeah, i've had this too (but just for Lua). I'm actually not sure what can be done and/or whether it's a lua-lsp problem or a neovim problem. But I don't thin we can do anything about it in kickstart.nvim.

I'm going to close for now unless there's something people think I can do to fix here.
