### ISSUE TITLE
Unable to use Ctrl+Backspace to delete word

### ISSUE THREAD

**Issue by ianyepan** [nvim-lua/kickstart.nvim#140]
I'd like to use Ctrl+Backspace to delete a word. So far I've tried:

```
vim.keymap.set('i', '<C-h>', '<C-w>')
vim.keymap.set('i', '<C-bs>', '<C-w>')
vim.cmd [[inoremap <C-h> <C-w>]]
vim.cmd [[inoremap <C-bs> <C-w>]]
```
But none of them seem to work.

Any ideas what I am doing wrong? Thanks!

**Comment by diogotito** [comment]
It could be your terminal emulator. Your Lua is alright. Where are you running Neovim? <kbd>Ctrl</kbd> and Backspace are fiddly to handle in terminal emulators.

Binding <kbd>&lt;C-bs&gt;</kbd> works in `nvim-qt` and Neovide (two GUI apps) but didn't work in any of the terminal emulators I tried.
Binding <kbd>&lt;C-h&gt;</kbd> worked in Windows Terminal and mintty (Git Bash) but didn't work in Alacritty for me.

I was more successful binding Alt+Backspace (<kbd>&lt;M-bs&gt;</kbd>) for that. It works consistently across GUIs and terminal emulators, and has the additional benefit of being the default keybinding used to delete words in many shells, REPLs, etc. so I suggest you to try it out

```lua
vim.keymap.set('i', '<M-BS>', '<C-w>')
```

**Comment by ianyepan** [comment]
Thanks for the reply. I ended up configuring it at the terminal settings level. I am using Windows Terminal, so I just had to put these lines in the `settings.json` file:

```json
{
  "keys": "ctrl+backspace",
  "command": 
  {
    "action": "sendInput",
    "input": "\u0017"
  }
}
```
