### ISSUE TITLE
nmap and vim.keymap.set usage there should be only one.

### ISSUE THREAD

**Issue by ibeex** [nvim-lua/kickstart.nvim#141]
Kickstart is using in config both `nmap` and `vim.keymap.set` for better readability one should be used. 

read init.lua

Edit: nmap

**Comment by cprn** [comment]
It's not using `map`, it's using `nmap` - a helper function defined inside of `init.lua`. This project assumes you have some programming knowledge and that you're used to reading code. Also if you're using NeoVim with this project's `init.lua` to read its `init.lua` then you can press `<leader>ds` and find `nmap` definition from any position in document and when your cursor is on `nmap` reference you can press `K` to see the hover documentation including function declaration.

Honestly, if you want readability in a sense of human-readable config, I'd opt for VimScript instead (as in `.vimrc` file).
