### ISSUE TITLE
Dockerfile (and other Alpine): [mason-lspconfig.nvim] failed to install sumneko_lua.

### ISSUE THREAD

**Issue by liamswenson** [nvim-lua/kickstart.nvim#142]
**Describe the bug**
Trying to use the provided `init.vim` on Alpine hosts (like is used in the provided Dockerfile) will prompt the user with the following error when opening Neovim:
```
[mason-lspconfig.nvim] failed to install sumneko_lua. Installation logs are available in :Mason and :MasonLog
Press ENTER or type command to continue
```
mason.log contains:
```
[INFO  Sat Jan 21 01:19:57 2023] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:120: Executing installer for Package(name=lua-language-server)
[ERROR Sat Jan 21 01:19:58 2023] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=lua-language-server) error="Could not find which release file to download.\nMost likely the current operating system or architecture is not supported (Linux_x64)."
```
This issue seems to stem from [sumneko/lua-language-server](https://github.com/sumneko/lua-language-server)'s lack of provided musl binaries. This is addressed in their issues [948](https://github.com/sumneko/lua-language-server/issues/948) and [661](https://github.com/sumneko/lua-language-server/issues/661), but the solution has been to manually compile instead.

**To Reproduce**
1. `$ git clone https://github.com/nvim-lua/kickstart.nvim`
2. `$ cd kickstart.nvim`
3. `$ podman build -t kickstart .`
4. `$ podman run --rm -it localhost/kickstart:latest`
5. `$ build/bin/nvim`
6. restart neovim

**Desktop**
`Alpine Linux` (Podman/WSL2)
`Gnome terminal/Windows terminal`

**Neovim Version**
`v0.9.0-dev-762+g1c16d0994`

**Comment by liamswenson** [comment]
I opened a discussion at https://github.com/sumneko/lua-language-server/discussions/1843 to see if they would be willing to reconsider providing musl binaries as a potential (and in my opinion preferred) solution.

**Comment by scresante** [comment]
I have a very similar problem running on a raspberry pi. 

`[ERROR Sat 11 Feb 2023 08:25:40 PM UTC] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=lua-language-server) error="Could not find which release file to download.\nMost likely the current operating system or architecture is not supported (Linux_armv7l)."`

**Comment by tjdevries** [comment]
I've actually removed the dockerfile cause there are better ways now to run an isolated nvim test setup locally (see `:help NVIM_APPNAME` for more info)
