### ISSUE TITLE
attempt to call field 'nvim_create_augroup' (a nil value)

### ISSUE THREAD

**Issue by spencerchubb** [nvim-lua/kickstart.nvim#149]
**Describe the bug**
Error detected while processing /home/ubuntu/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/ubuntu/.config/nvim/init.lua:88: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        /home/ubuntu/.config/nvim/init.lua:88: in main chunk

**To Reproduce**
1. sudo apt install neovim
2. Copy the init.lua to .config/nvim/init.lua
3. Open any file with nvim (e.g. nvim foo.txt)

**Desktop (please complete the following information):**
- OS: Windows
- Terminal: Using powershell to connect to Ubuntu through SSH

** Neovim Version **
 - Output of running `:version` from inside of neovim:
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```
```

**Comment by fbaltor** [comment]
Having the same problem.

**Comment by CharlesHawkins** [comment]
Nvim 0.6.1 from Ubuntu 22.04's repos is [too old](https://github.com/nvim-lua/kickstart.nvim/issues/157) for kickstart to work. It gave me the same error. You'll want to uninstall the version you have and install the latest stable Nvim from https://github.com/neovim/neovim/releases/tag/stable (at the moment that's 0.8.2, and kickstart works for me on that version)

**Comment by fbaltor** [comment]
Worked here! Thank you, @CharlesHawkins.

**Comment by tjdevries** [comment]
Yup, that's too old to use. Thanks for answering questions
