### ISSUE TITLE
No C compiler found!

### ISSUE THREAD

**Issue by maslias** [nvim-lua/kickstart.nvim#150]
**Describe the bug**
After the plugin installations via init.lua, reopen nvim and i get following error message:

Error detected while processing /home/marciii/.config/nvim/init.lua:
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.
[mason-lspconfig.nvim] installing sumneko_lua

**To Reproduce**
1. nvm ~.config/nvim/init.lua
2. copy paste the raw from init.lua and saved it
3. open nvim: plugin installed
4. reopen nvim, get the errors

- OS: 5.10.16.3-microsoft-standard-WSL2 / Ubuntu 20.04.5 LTS
- Terminal: windows terminal / zsh

** Neovim Version **
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

**Comment by trev-dev** [comment]
Some tree-sitter grammars/syntax related stuffs do require that you have gcc or some other C compiler on path to use.  This doesn't stop Neovim from working, but it can be obnoxious.  Look up how to get a C compiler on your OS/distro of choice

**Comment by maslias** [comment]
thanks @trev-dev, thats the one.
