### ISSUE TITLE
Installation failed: unzip is not executable

### ISSUE THREAD

**Issue by andreuservera** [nvim-lua/kickstart.nvim#151]
**Installation failed: unzip is not executable**
After setting up init.lua and executing nvim for the first time, an installation error pops up. If you :MasonLog, this is the error output: 
```
[ERROR [...]] ...acker/start/mason.nvim/lua/mason-cora/installer/init.lua:159:Installation failed for Package(name=lua-language-server) error=spawn: unzip failed with exit code - and signal - . unzip is not executable`
```
If you enter :Mason and try to install any package, none of the .zip files neede will be extracted.

**To Reproduce**
1. Paste init.lua in ~/.config/nvim/
2. Restar nvim

**Desktop:**
- OS: Windows with WSL2 (Ubuntu 20.04 or 22.04)
- Terminal: zsh

** Neovim Version 0.7.2 **
 - Output of running `:version` from inside of neovim:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

    system vimrc file: "$VIM/sysinit.vim"
    fall-back for $VIM: "/usr/share/nvim"
```

**Comment by Forthoney** [comment]
Encountering the same issue with neovim 0.8.2

**Comment by Forthoney** [comment]
> If you do a `which unzip` what's the output? If it's missing, maybe `sudo apt install unzip`. This is a common executable on most distros but sometimes its not there.

This worked for me. Thanks!

**Comment by andreuservera** [comment]
I was not expecting unzip not being installed by default. Thanks!

**Comment by joekrall** [comment]
Fellow Ubuntu 22.04 on WSL user here. @trev-dev's hint worked for me, thanks!
