### ISSUE TITLE
**QUESTION: Set indent to tab character and enable relative lines?

### ISSUE THREAD

**Issue by itsrxmmy** [nvim-lua/kickstart.nvim#154]
I know this is for bugs but I didnt know where else to ask this, but how do I set my indentation to a tab character in the init.lua?

**Comment by itsrxmmy** [comment]
Also: how do i enable relative lines?

**Comment by ners10100100** [comment]
For relative line numbers just add this line:

`vim.o.relativenumber = true`

**Comment by feoh** [comment]
You might also consider putting options settings and custom keymaps like this in $XDG_CONFIG_HOME/after/plugin/defaults.lua so you can leave your init.lua file intact.

**Comment by tjdevries** [comment]
Yup, those are both good options.
