### ISSUE TITLE
Init.lua broke my NVIM

### ISSUE THREAD

**Issue by liel-almog** [nvim-lua/kickstart.nvim#157]
**Describe the bug**
I have copied and pasted the init.lua and the telescope plugin did not install due to an error 
In addition whenever I started NVIM an error occurred "Error in packer_compiled:"  

**To Reproduce**
1. Copy and Paste the init.lua as described in [video](https://youtu.be/stqUbv-5u2s?t=226)

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04.1 LTS
- Terminal: bash

** Neovim Version **
NVIM v0.6.1

```
Error in packer_compiled: /home/liel-almog/.config/nvim/plugin/packer_compiled.lua:206: Vim(packadd):E5113: Error
 while calling lua chunk: .../packer/start/nvim-treesitter/plugin/nvim-treesitter.lua:14: attempt to call field '
nvim_create_augroup' (a nil value)^@stack traceback:^@^I.../packer/start/nvim-treesitter/plugin/nvim-treesitter.l
ua:14: in main chunk^@^I[C]: in function 'cmd'^@^I/home/liel-almog/.config/nvim/plugin/packer_compiled.lua:206: i
n function </home/liel-almog/.config/nvim/plugin/packer_compiled.lua:10>^@^I[C]: in function 'pcall'^@^I/home/lie
l-almog/.config/nvim/plugin/packer_compiled.lua:10: in main chunk
Please check your config for correctness

```

**Comment by lsc** [comment]
This project only targets latest stable and nightly. Current stable neovim is 0.8, you're two versions behind...

**Comment by liel-almog** [comment]
I just downloaded it from `sudo apt install neovim`

**Comment by Bikesh78** [comment]
@liel-almog I think the neovim package in apt repository is outdated. You can download version 0.8 of neovim from [here](https://github.com/neovim/neovim/releases/tag/v0.8.2)

**Comment by liel-almog** [comment]
Thank you, I will sure try.
