### ISSUE TITLE
Unknows error

### ISSUE THREAD

**Issue by dontrusthiscode** [nvim-lua/kickstart.nvim#159]
Ok i know that my files could've caused this but still, i just copy pasted and this is what i get? Please help out here.
Error detected while processing /home/script/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/script/.config/nvim/init.lua:88: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        /home/script/.config/nvim/init.lua:88: in main chunk
Error detected while processing /home/script/.local/share/nvim/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:
E5113: Error while calling lua chunk: ...m/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:1: attempt to index field 'keymap' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:1: in main chunk
[nvim-cmp] Your nvim does not has `nvim_create_autocmd` function. Please update to latest nvim.
Error detected while processing /home/script/.local/share/nvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:
E5113: Error while calling lua chunk: ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:15: attempt to call field 'notify_once' (a nil value)
stack traceback:
        ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:15: in main chunk
Error detected while processing /home/script/.local/share/nvim/site/pack/packer/start/nvim-treesitter/plugin/nvim-treesitter.lua:
E5113: Error while calling lua chunk: .../packer/start/nvim-treesitter/plugin/nvim-treesitter.lua:14: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        .../packer/start/nvim-treesitter/plugin/nvim-treesitter.lua:14: in main chunk
Error detected while processing /home/script/.local/share/nvim/site/pack/packer/start/telescope.nvim/plugin/telescope.lua:
Telescope.nvim requires at least nvim-0.7.0. See `:h telescope.changelog-1851`
Error detected while processing /home/script/.local/share/nvim/site/pack/packer/start/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua:
E5113: Error while calling lua chunk: ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:11: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:11: in function 'setup'
        .../packer/start/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua:1: in main chunk
Error detected while processing /home/script/.local/share/nvim/site/pack/packer/start/cmp_luasnip/after/plugin/cmp_luasnip.lua:
E5113: Error while calling lua chunk: .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:14: attempt to call field 'nvim_create_autocmd' (a nil value)
stack traceback:
        .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:14: in main chunk
        [C]: in function 'require'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:6: in main chunk
        [C]: in function 'require'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:1: in main chunk
        [C]: in function 'require'
        ...ck/packer/start/cmp_luasnip/after/plugin/cmp_luasnip.lua:1: in main chunk
![Neovim Starter Config error](https://user-images.githubusercontent.com/123390927/216072728-af33ee18-dd81-4f03-b8d9-8fd9eea0323d.png)

**Comment by tjdevries** [comment]
Please make sure to follow the issue template. Thanks!
