### ISSUE TITLE
Mapping for TS incremental selection doesn't work

### ISSUE THREAD

**Issue by hahuang65** [nvim-lua/kickstart.nvim#167]
**Describe the bug**

It doesn't seem like the default keybinds in `init.lua` works for `scope_incremental` and `node_decremental`

```
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = '<c-space>',
      node_incremental = '<c-space>',
      scope_incremental = '<c-s>',
      node_decremental = '<c-backspace>',
    },
  },
```

**To Reproduce**
Just install... `node_incremental` works great, but `scope_incremental` does nothing, and `node_decremental` just acts like `<BS>`.

**Desktop (please complete the following information):**
- OS: macOS
- Terminal: wezterm

** Neovim Version **
 - Output of running `:version` from inside of neovim:

```
NVIM v0.8.2
```

**Comment by ykhan21** [comment]
It doesn't work for me either.

I'm on a Windows, and I've tried the mapping on Powershell + Wezterm and on cmd.exe.

`:checkhealth` gives me this output:

```
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.17.4 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
...
```

Mapping it to a different key works however.

**Comment by tjdevries** [comment]
This is a terminal problem -- I actually changed it to Alt-Backspace anyway now though. So that should work for people (but you can also just change if your terminal doesn't support it)
