### ISSUE TITLE
sumneko_lua is deprecated, use lua_ls instead

### ISSUE THREAD

**Issue by jschuur** [nvim-lua/kickstart.nvim#171]
After updating plugins today (`PackerSync`) I get the following error when I launch neovim:

```
sumneko_lua is deprecated, use lua_ls instead. See :h deprecated
This function will be removed in lspconfig version 0.2.0
stack traceback:
        .../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:41: in function '__index'
```

However, a simple renaming of `sumneko_lua` to `lua_ls` in my `init.lua` did not do the trick

```
lua_ls = {
  Lua = {
    workspace = { checkThirdParty = false },
    telemetry = { enable = false },
  },
},
```

This now results in 

```
[mason-lspconfig.nvim] Server "lua_ls" is not a valid entry in ensure_installed. Make sure to only provide lspconfig server names.
```

Mason lists `lua-language-server` as installed. 

This would seem to be related to [this renaming](https://github.com/neovim/nvim-lspconfig/pull/2439). 

The renamed repo links [here](https://github.com/LuaLS/lua-language-server/wiki/Getting-Started#command-line) for install instructions, but I'm not sure why I'm supposed to do a full brew install here, since I didn't use brew to set up the LSP under the old name.

Is this an issue with things being slightly out of sync, since this rename just popped up in the nightlies?

At this point, I've uninstalled lua-language-server in Mason and commented out the above block in `init.lua` to make the error go away.

I'm on macOS, NVIM v0.8.3.

**Comment by jschuur** [comment]
Maybe I need to wait for [this mason-lspconfig PR](https://github.com/williamboman/mason-lspconfig.nvim/pull/148)?

**Comment by jinzhongjia** [comment]
> I think I just need to wait for [this mason-lspconfig PR](https://github.com/williamboman/mason-lspconfig.nvim/pull/148)?

Yes, now we just need to wait it

**Comment by tomsiwik** [comment]
My biggest pet peeve with nvim configs currently is that I don't know how to pin versions (upgrade/rollback command) and avoid these deprecation warnings (ignore command). Is there a way to manage this comfortably or are you stopping your day to day work to fix these warnings yourself, as a vim user? This would be a deal-breaker for me if I constantly get disturbed by randomly appearing warnings/deprecations and I have to fiddle around my config.

**Comment by jinzhongjia** [comment]
> My biggest pet peeve with nvim configs currently is that I don't know how to pin versions (upgrade/rollback command) and avoid these deprecation warnings (ignore command). I've tried to remove this warning now for an hour straight without success. Is there a way to manage this comfortably or are you stopping your day to day work to fix these warnings yourself, as a vim user? This would be a deal-breaker for me if I constantly get disturbed by randomly appearing warnings/deprecations and I have to fiddle around my config.   

pin version, this feature should be provided by your packag manager

**Comment by jschuur** [comment]
If it helps, in my case, I ran into this issue due to `PackerSync` updating to at least one nightly. Not sure where it defaults to nightlies (I'm running pretty much the default `init.lua` from this repo still) and this might be an edge case where this kind of aggressive nightlies would not have otherwise triggered an out of sync update so quickly.

I had gotten some kind of 'plugin table is nil' error when running `PackerStatus` and stumbled across  `PackerSync` which did fix the nil error.

**Comment by jschuur** [comment]
> I've tried to remove this warning now for an hour straight without success. Is there a way to manage this comfortably or are you stopping your day to day work to fix these warnings yourself, as a vim user? 

If you're referring to this specific `sumneko_lua is deprecated` warning, I commented out the `sumneko_lua` block. under `local servers = {` in `init.lua` and then also ran `:Mason` in vim and under the LSP list, went to the line with `lua-language-server` and hit X to uninstall it for now.

This gets rid of the warning on startup.

Just need to re-add it later when the PR is merged (if you care about Lua LSP support).

**Comment by tomsiwik** [comment]
> > I've tried to remove this warning now for an hour straight without success. Is there a way to manage this comfortably or are you stopping your day to day work to fix these warnings yourself, as a vim user?
> 
> If you're referring to this specific `sumneko_lua is deprecated` warning, I commented out the `sumneko_lua` block under `local servers = {` in `init.lua` and then also ran `:Mason` in vim and under the LSP list, went to the line with `lua-language-server` and hit X to uninstall it for now.
> 
> This gets rid of the warning on startup.
> 
> Just need to re-add it later when the PR is merged (if you care about Lua LSP support).

Thanks. This worked.

> pin version, this feature should be provided by your packag manager

I don't know which package caused this ([nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) wasn't it) - I'm actually curious what the workflow is once something pops up as a warning: fix it continuously, pin all versions so nothing complains, use some package I don't know of that fixes it.

**Comment by kiyoon** [comment]
@tomsiwik I use lazy.nvim and just restore with `R` key and it will restore to the stable commits. You should also add the lock file to be tracked by git. Then you can make a stable tags for your dotfiles and when something goes wrong you need to either revert a few commits in your dotfiles or revert to the stable tag in your dotfile.

**Comment by nyngwang** [comment]
FYI: [PR from williamboman/mason-lspconfig.nvim](https://github.com/williamboman/mason-lspconfig.nvim/pull/148) has been merged.

**Comment by jschuur** [comment]
> FYI: [PR from `williamboman/mason-lspconfig.nvim`](https://github.com/williamboman/mason-lspconfig.nvim/pull/148) has been merged.

I can confirm that updating plugins (`:PackerUpdate`) and reactivating the `lua-language-server` LSP in Mason with `init.lua` now containing this made the deprecation notice go away:

```lua
lua_ls = {
  Lua = {
    workspace = { checkThirdParty = false },
    telemetry = { enable = false },
  },
},
```
