### ISSUE TITLE
nvim tree strongly recommends disabling netrw?

### ISSUE THREAD

**Issue by Masber** [nvim-lua/kickstart.nvim#172]
**Describe the bug**
https://github.com/nvim-tree/nvim-tree.lua#setup

nvim tree strongly recommends disabling netrw. 

can we add the following lines to the top of ini.lua file?

```
-- disable netrw at the very start of your init.lua (strongly advised)
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
```

**Comment by albertocerrone** [comment]
Hey @Masber. kickstart doesn't use nvim-tree. No need for this change 🤗

**Comment by tjdevries** [comment]
Thanks for the issue, but yeah, that's only if you're also using nvim-tree, which we are not.
