### ISSUE TITLE
No plugins from custom.plugins is loaded

### ISSUE THREAD

**Issue by jby** [nvim-lua/kickstart.nvim#176]
I have the same problem as described in #34.
I've commented in that issue quite a bit.
**To Reproduce**
1. Add plugins to `~/.config/nvim/lua/custom/plugins.lua`
2. Re-start vim or run `PackerSync`
3. No plugins from custom.plugins is installed

**Desktop (please complete the following information):**
- OS: macOS 13.2
- Terminal: iTerm2

** Neovim Version **
 - Output of running `:version` from inside of neovim:

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"
```
My current `~/.config/nvim/lua/custom/plugins.lua`: https://github.com/jby/nvim/blob/nvks/lua/custom/plugins.lua
```lua
return function(use)
  -- Configure nvim-tree
  use({
    {'nvim-tree/nvim-tree.lua', requires = 'nvim-tree/nvim-web-devicons'},
    config = function()
      require("nvim-tree").setup()
      'nvim-tree/nvim-web-devicons'
    end
  })
  -- Add friendly snippets
  use({
    'rafamadriz/friendly-snippets',
    config = function ()
      require('luasnip.loader.from_vscode').lazy_load()
    end
  })
end
```

**Comment by BKDevelop** [comment]
ok I believe the problem is that you are using invalid Packer syntax (see [packer readme](https://github.com/wbthomason/packer.nvim#quickstart) for reference)

This should work

```
return function(use)
  -- Configure nvim-tree
  use {
    'nvim-tree/nvim-tree.lua', requires = 'nvim-tree/nvim-web-devicons',
    config = function()
      require("nvim-tree").setup()
      'nvim-tree/nvim-web-devicons'
    end
  }
  -- Add friendly snippets
  use {
    'rafamadriz/friendly-snippets',
    config = function ()
      require('luasnip.loader.from_vscode').lazy_load()
    end
  }

end
```

@tjdevries  I guess the readme should be updated? I won't submit a PR because I migrated to my own config a while ago and just got curios because @jby  resurrected my old thread. 

@jby maybe you wan't to contribute here?

Have a nice day all around!

**Comment by jby** [comment]
Cheers!
I'll be away from my computer for 2 days - I'll try this when I'm back.

**Comment by feoh** [comment]
I struggled a bit to get friendly snippets working myself.

I ended up with this:
```
  -- friendly-snippets
  use {'rafamadriz/friendly-snippets'}
  require("luasnip.loaders.from_vscode").lazy_load()
```

But maybe your snippet is better because it includes the lazy load call within the context of the use.

Trying to wrap my head around the more functional aspects of the way we do plugin configuration in Lua has been one of the steeper cliffs I've encountered in reaching Neovim enlightenment :)

**Comment by BKDevelop** [comment]
Again I neither use kickstart.nvim nor friendly-snippets (not even packer atm) :) I just noticed the example in this repos readme not matching the specification in packers readme. 

so I can’t really answer this question. Sorry ^^‘

**Comment by jby** [comment]
I've tried it now and the changes in my custom.plugins suggested by @BKDevelop does solve the original question in this issue. However neither suggestion on how to configure `friendly-snippets` seem to work, not the initial suggestion from @BKDevelop, and not the modified version from @feoh...

**Comment by jby** [comment]
Hmm, might not resolve this after all...
It (Packer) does install nvim-tree/nvim-tree.lua, but complains about it's config instead:
```lua
packer.nvim: Error running config for nvim-tree.lua: [string "..."]:0: attempt to call a nil value
```

**Comment by jby** [comment]
Hmm, the above error only shows on 1 of 3 Macs where I've used this setup... 😕

**Comment by jby** [comment]
Hmm, maybe not...

**Comment by jby** [comment]
Hmm, found this https://vi.stackexchange.com/questions/38137/packer-nvim-error-running-config-for-package-attempt-to-call-a-nil-value
And if I change the config code to:

```lua
  use {
    'nvim-tree/nvim-tree.lua', requires = 'nvim-tree/nvim-web-devicons',
    config = function()
      require("nvim-tree").setup({})
      'nvim-tree/nvim-web-devicons'
    end
  }
```
I don't get the startup error any more...

**Comment by tjdevries** [comment]
I'm going to make it way easier to add plugins in #178. Give me a day or two and it should be much more obvious how to extend this easily.

**Comment by jby** [comment]
Yeah, well - with your re-build I found https://www.lazyvim.org and will try that for a while instead.
Thanks for your work though.
I'll look back here when your #178 is merged and see what comes of it.
