### ISSUE TITLE
add neo-tree

### ISSUE THREAD

**Issue by adsick** [nvim-lua/kickstart.nvim#180]
I was surprised that this 'init.nvim' is not shipped with [neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim) in it :eyes:

**Comment by tjdevries** [comment]
I don't think we need it -- personally I don't think file trees are a required experience. You can add one yourself very easily once I'm done with #178

**Comment by tjdevries** [comment]
This is how easy it would be: https://github.com/nvim-lua/kickstart.nvim/pull/178/commits/ba5786cde43eaff6151295c8d6db2721c0e99f3d
