### ISSUE TITLE
telescope-fzf-native Not Found on github

### ISSUE THREAD

**Issue by Fahad-ishfaq** [nvim-lua/kickstart.nvim#181]
**Describe the bug**
 ✗ Failed to install nvim-telescope/telescope-fzf-native.nvim  
  URL: https://github.com/nvim-telescope/telescope-fzf-native.nvi
  Commits:                                                       
    580b6c4 feat: include environment CFLAGS for make (#97) (12 d│~

**To Reproduce**
1. Issue is caused in initial installation of plugins
2. https://github.com/nvim-telescope/telescope-fzf-native.nvi git repo does not exists

**Desktop (please complete the following information):**
- OS: wsl 2 ubuntu
- Terminal: zsh

** Neovim Version **
 - Output of running `:version` from inside of neovim: 0.6

```
```

**Comment by LudoPinelli** [comment]
- You will have a lot of things not working with neovim 0.6, you should update to the latest release (0.8.3)
- Do you have what's needed on wsl 2 Ubuntu to compile fzf? (`sudo apt install build-essential`)

**Comment by Fahad-ishfaq** [comment]
Sorry I got it wrong.
I clicked link from terminal and that didn't opened correctly.
Thank you
