### ISSUE TITLE
Error detected while processing init.lua : No specs found for module custom.plugins

### ISSUE THREAD

**Issue by Zelmoghazy** [nvim-lua/kickstart.nvim#188]
I get this screen everytime I open neovim on windows 11 , neovim 0.8.0 , I used the default init.lua I didnt change anything
![image](https://user-images.githubusercontent.com/99360533/220115590-31b63f76-1a03-4d41-91c1-cc6b7bc5f18d.png)

**Comment by gmnz** [comment]
Look here: :-)

https://github.com/nvim-lua/kickstart.nvim/blob/72364ad9acb35bb44d7e0af64f977f2a4b3c59db/init.lua#L187-L189

**Comment by Zelmoghazy** [comment]
> Look here: :-)
> 
> https://github.com/nvim-lua/kickstart.nvim/blob/72364ad9acb35bb44d7e0af64f977f2a4b3c59db/init.lua#L187-L189

Thank you I am going to read all of it right now :)
