### ISSUE TITLE
ensure installed is not working anymore

### ISSUE THREAD

**Issue by Naf256** [nvim-lua/kickstart.nvim#195]
**Describe the bug**
All language servers do not seem to be valid entry in mason-lspconfig's ensure_installed
**To Reproduce**
1. open the terminal and open nvim

**Desktop (please complete the following information):**
- OS: Popos
- Terminal: gnome terminal

** Neovim Version **
 - Output of running `:version` from inside of neovim:

```
NVIM v0.9.0-dev-525+ga7332ba9b
Build type: RelWithDebInfo
```

**Comment by Naf256** [comment]
Bug was fixed. I actually had the earlier version of this project which caused some issues. If any of you face the same issue, just update your init.lua file from here and you should be good to go

**Comment by FMGordillo** [comment]
Just out of curiosity, how did you configure `mason` in your `kickstart.vim`?
I created a `lua/custom/plugins/mason.lua` and added the following:
```
return {
  'williamboman/mason.nvim'
}
```

But I am stuck trying to create the `ensure_installed` here (it does not work [like this example](https://www.lazyvim.org/plugins/extras/formatting.prettier#masonnvim))
