### ISSUE TITLE
[mason-lspconfig.nvim] Server "lua_ls" is not a valid entry in ensure_installed. (Solved)

### ISSUE THREAD

**Issue by ZoeLogiiK** [nvim-lua/kickstart.nvim#196]
**Describe the bug**

Fresh install of Kickstart.nvim comes with a Mason lsp.nvim error on NeoVim Start up.
**To Reproduce**
1. ... I copy the init.lua file from this Repo and pasted to my .config/nvim

**Desktop (please complete the following information):**
- OS:  WSL2 (Ubuntu)
- Terminal:  Windows Terminal

** Neovim Version **
 - Output of running `:version` from inside of neovim:

:version
NVIM v0.9.0-dev-614+ge35b9020b
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by zoelogiik@Sombra

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

```
```

**Comment by ZoeLogiiK** [comment]
Edit: Problem Solved

Update Plugins with ":Lazy, U"
to update date all the plugins.

Problem fixed.

**Comment by ihgann** [comment]
I'm curious - isn't it generally a good practice to pin commits? What is kickstart.nvim's stance on this?

**Comment by adilJamshad** [comment]
> Edit: Problem Solved
> 
> Update Plugins with ":Lazy, U" to update date all the plugins.
> 
> Problem fixed.

Will you kindly share the steps you took to resolve this persistent error?

**Comment by adilJamshad** [comment]
> I get this same issue and updating through :Lazy does not resolve for me.
> 
> ![image](https://user-images.githubusercontent.com/88270060/227928008-f086270e-320e-4d79-98a5-b24777a8759e.png)
> 
> If anybody could advise how to resolve this then that would be amazing!
> 
> Phil.

Hey Phil,

I just opened nvim and executed :MasonUpdate. This has resolved this warning.

**Comment by Phil-T1** [comment]
Thanks!

That raised the error that it couldn't unzip the package - oops! Unzip was not installed in my Docker env. Sudo apt install unzip and then running nvim again fixed immediately 👍
