### ISSUE TITLE
How to turn off the prompt when nvim starts

### ISSUE THREAD

**Issue by 52funny** [nvim-lua/kickstart.nvim#208]
Every time I open nvim I get this prompt.

![](https://i.328888.xyz/2023/03/03/FPf4A.png)

Does anyone know how to turn off this prompt?

**Comment by Alexis12119** [comment]
maybe there's something in your config that run this command `:TSUpdate`

**Comment by feoh** [comment]
FWIW I'm seeing this too, but I rather like it :) It's not actually a 'prompt' it's just a notification saying you're up to date.

**Comment by Alexis12119** [comment]
https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L171

I think you should remove this line if you don't want that every startup

**Comment by 52funny** [comment]
@Alexis12119 Thank you for your help. according to the tips I have ended the problem.
