### ISSUE TITLE
mason-nvim-dap not working and returning error

### ISSUE THREAD

**Issue by iStagnant** [nvim-lua/kickstart.nvim#213]
**Describe the bug**
The plugin mason-nvim-dap doesn't work and on startup always returns this error:
```
Error detected while processing /home/user/.config/nvim/init.lua:
...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "bash-debug-adapter".
```
This is because mason-nvim-dap is getting required and setup before mason is, and could be solved by simply adding:
`require('mason').setup()` as the first line in the config function, but idk if there's a better solution

**To Reproduce**
1. Let lazy.nvim download all of the plugins
2. Open nvim

**Desktop (please complete the following information):**
- OS: Artix linux
- Terminal: st

** Neovim Version **
 - Output of running `:version` from inside of neovim:
 ```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"
```

**Comment by cramsted** [comment]
Seeing the same thing on WSL2. The only difference is that the error does not show up unless I have a DAP server installed.

**Comment by KudoLayton** [comment]
I made the PR https://github.com/nvim-lua/kickstart.nvim/pull/210 to resolve this problem

**Comment by feoh** [comment]
PR was merges. Please re-open if this problem persists.
