### ISSUE TITLE
Restructure the configuration

### ISSUE THREAD

**Issue by marwanm-dev** [nvim-lua/kickstart.nvim#218]
A 500 line init.lua is not the best especially as plugins and remaps grow.

In need to restructure this repo's 500 line init.lua configuration to be something close to this:
init.lua
remap.lua
set.lua
lazy.nvim.lua
after/plugins
                    /lspconfig.lua
                   /treesitterconfig.lua
inspired by [ThePrimeagen init.lua](https://github.com/ThePrimeagen/init.lua) neovim setup

I understand the concept of a kickstart init.lua but a **pull request** by anyone experienced will be enough and shouldn't take much time as I am not an expert in lua.
Thanks.

**Comment by mateusabelli** [comment]
Hello, for me personally the selling point to kickstart.nvim has always been the single file setup. I feel like it really emphasize the concept that setting up a basic neovim config should not be hard.

**Comment by mjlbach** [comment]
I talked about this with TJ a bit. I renamed the original kickstart repo [starter.nvim](https://github.com/mjlbach/starter.nvim) and will be maintaining it as the most minimal possible single file setup, so this repo is free to expand/focus on whatever TJ's vision :)

**Comment by marwanm-dev** [comment]
As I said, I know the point of a one file configuration but when the file gets bigger it'll be harder to maintain, so if someone should split up the default one file "kickstart.nvim" into the specified folder structure so anyone could use it and expand on that since I am not an expert.

I tried to move plugins into after/plugins and it kept crashing.

**Comment by marwanm-dev** [comment]
As I said, I know the point of a one file configuration but when the file gets bigger it'll be harder to maintain, so if someone should split up the default one file "kickstart.nvim" into the specified folder structure so anyone could use it and expand on that since I am not an expert.

I tried to move plugins into after/plugins and it kept crashing.

With that said, can some experts join us as contributors at [starter.nvim](https://github.com/mjlbach/starter.nvim) by @mjlbach .

Thanks for your time and effort.

**Comment by feoh** [comment]
@mjlbach Thanks so much for creating [starter.nvim](https://github.com/mjlbach/starter.nvim).

I personally eel like there's a ton of value in having a very minimal starting point like that, but also in having a 'batteries included' solution like kickstart.nvim - especially the version that came out of @tjdevries lazy.nvim rewrite.

Seems like all's well that ends well here. Gonna close this issue.
