### ISSUE TITLE
Installing Init.lua only produces a persistant error

### ISSUE THREAD

**Issue by nikfp** [nvim-lua/kickstart.nvim#223]
**Describe the bug**
Installing only the init.lua file produces a persistent error, stemming from line 189. The comments on lines 187-188 say this error is expected, however the better UX would be to comment it out and explain how to comment it back in when the time is right and the user has some config files to add. 

For a new user, just the init.lua is already a lot to grok. If it can be error free, people will feel a lot more empowered getting it working and starting to tweak it. 

**NOTE** I'm happy to submit a PR to address this, just comment on the issue saying so and I'll jump on it. 

Also thank you for putting this together in the first place, it's a great resource. I use it in a blog post I wrote instructing how to smoothly get started on windows. 

**To Reproduce**
1. Install the init.lua file on it's own and load Neovim

**Desktop (please complete the following information):**
- OS: Windows
- Terminal: Windows terminal

** Neovim Version **
 - Output of running `:version` from inside of neovim:
 NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az171-224

```
```

**Comment by nicobld** [comment]
@dimensi It seems there are trailing characters in your file. They must've been added while copy pasting the file. Just download init.lua normaly and move it to your directory.

**Comment by dimensi** [comment]
I found the problem, I had git autocrlf true and it kept breaking plugin installation.
