### ISSUE TITLE
undefined global `vim`

### ISSUE THREAD

**Issue by godalming123** [nvim-lua/kickstart.nvim#228]
**Describe the bug**
When I open my `init.lua` I get errors saying undefined global `vim` this is quite annoying.

Also I would like to have documentation for the vim commands (such as `vim.api.nvim_echo`) for developing plugins in my editor if that is possible instead of just removing the warning.

**To Reproduce**

Use the default config and open `init.lua` then run `MasonInstall lua-language-server`

**Desktop (please complete the following information):**
- OS: Arch linux
- Terminal: Alacritty

** Neovim Version **
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by girishji** [comment]
You can configure the lsp to recognize 'vim' as a global var. Something like this:
```lua
local servers = {
  lua_ls = {
    Lua = {
      diagnostics = {
        globals = { "vim", "describe", "it", "before_each", "after_each", "packer_plugins", "MiniTest" },
      },
    },
  },
}
```

**Comment by godalming123** [comment]
Would that add it my documentation when I press `K`

**Comment by feoh** [comment]
Are you folks still seeing this problem with the latest kickstart.nvim ?

**Comment by godalming123** [comment]
I don't see any changes in the upstream that would effect this issue but I will check

**Comment by feoh** [comment]
Hi there! Would you please consider upgrading to Neovim 0.9.0 ? I can't reproduce with a stock kickstart.nvim and an updated Neovim.

**Comment by godalming123** [comment]
Wired I have neovim 0.9.x and this is still a problem do you have the lua language server installed with mason

**Comment by godalming123** [comment]
It is called `lua-language-server` in Mason, and I have updated the steps to reproduce which is wierd because in the default config on line ~407 I thought it specified to install this by default

**Comment by feoh** [comment]
Ah, no, you're right. My bad. Running :Mason shows me the list of installed lsps and lua_language_server is in fact installed.

I wonder what's different about our respective configurations? You're using the latest files from kickstart.nvim right?

**Comment by godalming123** [comment]
Yep using latest `kickstart.nvim`

**Comment by feoh** [comment]
No response for a week. I'm closing this for now.
