### ISSUE TITLE
Reuse nmap in defaults.lua to use a different key for LSP signature help

### ISSUE THREAD

**Issue by nivalderramas** [nvim-lua/kickstart.nvim#230]
I would like to remap the `nmap('<C-k>', vim.lsp.buf.signature_help, 'Signature Documentation')` command in `defaults.lua` to use a different key for LSP signature help. Specifically, I want to use` <C-k>` to move between splits, and assign a different key for signature help.

I believe I can achieve this by using nmap (somehow obtained from init.lua) but I am not sure of the correct way to do that

Could someone please provide guidance on how to accomplish this?

Thank you in advance for your help!

**Comment by zachwn** [comment]
the default is `<C-w> k` 
You could add something like to 
`vim.keymap.set('n', '<C-k>', '<cmd>wincmd k<CR>', {noremap=true})` 
to you config and then adapt it for hjl if you wish.

**Comment by nivalderramas** [comment]
You're right, but as that mapping was issued using the function `nmap` defined in `init.lua` it uses an additional parameter, buffer. I'd like to know how would that affect the mapping

**Comment by zachwn** [comment]
nmap is just a local helper function specifically for adding language server protocol commands. 
```
  -- In this case, we create a function that lets us more easily define mappings specific
  -- for LSP related items. It sets the mode, buffer and description for us each time.
local nmap = function(keys, func, desc)
    if desc then
      desc = 'LSP: ' .. desc
    end

    vim.keymap.set('n', keys, func, { buffer = bufnr, desc = desc })
  end
```

The buffer is specifically for the lsp, the variable bufr is set when an lsp attaches to a buffer
```
-- LSP settings.
--  This function gets run when an LSP connects to a particular buffer.
local on_attach = function(_, bufnr)
``` 

 I'm just confused. I really don't understand why you  don't just change the <C-k> in
`nmap('<C-k>', vim.lsp.buf.signature_help, 'Signature Documentation')`
and add a addition map for C-k  to the window command?

**Comment by nivalderramas** [comment]
> I'm just confused. I really don't understand why you don't just change the in
nmap('<C-k>', vim.lsp.buf.signature_help, 'Signature Documentation')
and add a addition map for C-k to the window command?
I also thought about that, but I had the believe that then It could work different as the original keymap has a buffer attached, and second does not. I just believe as I'm pretty newbie in nvim. 
Thanks again for your patience

**Comment by zachwn** [comment]
no worries man, no need to apologize, you're all good. I not a maintainer, so i can't close the issue, you will have to.

**Comment by zachwn** [comment]
I would **highly** recommend keeping the default which is ctrl-w followed by a k. 
Ctrl-w handles all the window management stuff and when you press it in kickstart.nvim it will show you all of the available options.

but if you really really want to.
add
`vim.keymap.set('n', '<C-k>', '<cmd>wincmd k<CR>', {})`
then edit the signature doc to what ever you choose ie
`nmap('<C-m>', vim.lsp.buf.signature_help, 'Signature Documentation')`
in your init.lua

**Comment by nivalderramas** [comment]
Thanks!
