### ISSUE TITLE
Confused about modeline

### ISSUE THREAD

**Issue by dbalatero** [nvim-lua/kickstart.nvim#231]
I'm confused about the intent of the modeline included in the kickstart init.lua file:

https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L496-L497

I read through `:h modeline`, but I'm having trouble figuring out whether I actually _need_ this modeline or not, given that I set most of the same options in that modeline globally in my `init.lua` via `vim.o`.

For context, I've used Vim for 15 years but never really used modelines, so I don't have a great sense of whether this is some advanced feature that I never learned, or if it's just some extra bulletproofing being added to the bottom of the init.lua file to avoid something?

I'd like to explore in this issue:
1. Is there an opportunity to update the comment in the `init.lua` file for better clarity or to at least give some context on why we might want this here? (reading `:h modeline` is a little broad and I'm not clear on this repo's motivations in particular)
2. Can I remove this line safely?

**Comment by mjlbach** [comment]
The original context for this was lost when I made the OG kickstart.nvim repo private and TJ pushed a new fork to this repo. Here's the original commit explaining the reasoning:

https://github.com/mjlbach/starter.nvim/issues/43

**Comment by twe4ked** [comment]
Is this still true? Removing the modeline doesn't seem to break the indent guides for me. Might be missing something though, I didn't fiddle with it for long.

**Comment by feoh** [comment]
@dbalatero Sounds like the meat of this is resolved. Please feel free to re-open if there is an actionable issue for us here that needs more work, and thanks for the report!
