### ISSUE TITLE
Requires a neovim version not available from PPA?

### ISSUE THREAD

**Issue by SturmB** [nvim-lua/kickstart.nvim#241]
**Describe the bug**
Error immediately upon launching nvim after cloning this repo.

**To Reproduce**
1. Install neovim on Ubuntu 22.04 using `sudo apt install neovim` (will install v0.6.x)
or
1. Add the PPA first, then install neovim (will install v0.7.2)
2. Follow the kickstart instructions by cloning the repo into `$HOME/.config/nvim`
3. Run `nvim`

**Desktop (please complete the following information):**
- OS: Windows 11 22000.1696 and WSL with Ubuntu 22.04
- Terminal: Windows Terminal 1.16.10262.0

** Neovim Version **
 - Output of running `:version` from inside of neovim:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org
```

The first error to appear when running `nvim` after cloning the repo into the correct location states that it needs neovim 0.8.0 or higher.

```
Error detected while processing /home/sturm/.config/nvim/init.lua:
lazy.nvim requires Neovim >= 0.8.0
E5113: Error while calling lua chunk: /home/sturm/.config/nvim/init.lua:256: module 'telescope' not found:
        no field package.preload['telescope']
        no file './telescope.lua'
        no file '/usr/share/luajit-2.1.0-beta3/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope/init.lua'
        no file '/usr/share/lua/5.1/telescope.lua'
        no file '/usr/share/lua/5.1/telescope/init.lua'
        no file './telescope.so'
        no file '/usr/local/lib/lua/5.1/telescope.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/telescope.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/sturm/.config/nvim/init.lua:256: in main chunk
Press ENTER or type command to continue
```

I've got the latest one available from the PPA, which seems to be 0.7.2 as of this writing. What am I doing wrong?

**Comment by feoh** [comment]
Neovim builds and runs great on WSL.

Don't install the apt package. Follow the 'build from source' instructions on the neovim repo.

**Comment by SturmB** [comment]
Oh, boy. I've always avoided building from source because it seems too daunting. But maybe I'm ready for it now. Thanks!
