### ISSUE TITLE
cannot re-source from inside `nvim` with a keybinding

### ISSUE THREAD

**Issue by amtoine** [nvim-lua/kickstart.nvim#243]
## Describe the bug
i've this keybinding
```lua
vim.keymap.set('n', '<leader>so', ':source ~/.config/nvim/init.lua<CR>', { silent = true })
```
to reload the config when pressing `<leader>so`.

but i get the following error in the footer of `vim`:
```
Re-sourcing your config is not supported with lazy.nvim
```

:question: i'm wondering if this is normal and if there is anything to do to reload a config from inside `nvim` :yum: 

## To Reproduce
1. add `vim.keymap.set('n', '<leader>so', ':source ~/.config/nvim/init.lua<CR>', { silent = true })` to `init.lua`
2. restart `nvim`
3. press `<leader>so`
4. see the error at the bottom

## Desktop
- OS: arch on linux
- Terminal: alacritty

## Neovim Version
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by craigmac** [comment]
This is a limitation of the way lazy.nvim is designed. If you move your bootstrapping code and plugin setup to a multi-file approach, as the docs on lazy.nvim site describe, you'll be able to then do a plain `:so $MYVIMRC` without this error.

**Comment by amtoine** [comment]
> This is a limitation of the way lazy.nvim is designed.
>
oooh i see :thinking: 
thanks :yum: 

> If you move your bootstrapping code and plugin setup to a multi-file approach, as the docs on lazy.nvim site describe, you'll be able to then do a plain `:so $MYVIMRC` without this error.
>
i kinda like the way `kickstart.nvim` does things and i do not want to introduce too many changes :relieved: 

i like configuring `nvim` but having a solid base is what i'm looking for here :+1:

**Comment by amtoine** [comment]
i'm not sure what you mean by 

> If you move your bootstrapping code and plugin setup to a multi-file approach, as the docs on lazy.nvim site describe

do you have a link or an example?

that would be amazing for future people stumbling upon this very issue :star_struck: 
if you have time of course :wink:

**Comment by craigmac** [comment]
Link will probably break for future readers but right now it's here: https://github.com/folke/lazy.nvim#-structuring-your-plugins
in the lazy.nvim README.md file

**Comment by amtoine** [comment]
thanks for the pointer @craigmac :star_struck:
