### ISSUE TITLE
LSP specific settings defined in servers variable do not seem to be respected.

### ISSUE THREAD

**Issue by KaFski** [nvim-lua/kickstart.nvim#254]
**Describe the bug**
I wanted to configure some setting for few of LSP servers that I'm currently using. First I wanted to experiment with gopls, but even tho I've used their [settings documentation](https://github.com/golang/tools/blob/master/gopls/doc/settings.md) I couldn't change the default settings. I'm quite new to Vim/Neovim & LSP land so not really sure how I can debug it properly. 

I tried to look up the `mason_lspconfig.setup_handlers{}` function as this seemed as something there might be misconfigured. I opened and read the help and there is an example how to overwrite specific LSP server configuration, which I used to check if this may help and seems like it did the trick.

**To Reproduce**
So basically having following servers configuration

``` lua
local servers = {
  gopls = {
    analyses = {
      unusedparams = true,
      shadow = true,
      loopclousure = false,
    },
    staticcheck = true,
  },
...
}
``` 

I don't get shadow and ususedparams analyses.

![Screenshot from 2023-04-08 18-26-47](https://user-images.githubusercontent.com/12432243/230732220-49e5f67c-a01c-4035-90c9-eb7287c4ba86.png)

But if I put targeted override like following:
``` lua
mason_lspconfig.setup_handlers {
  function(server_name)
    require('lspconfig')[server_name].setup {
      capabilities = capabilities,
      on_attach = on_attach,
      settings = servers[server_name],
    }
  end,
  ["gopls"] = function()
    require('lspconfig').gopls.setup {
      settings = {
        gopls = {
          analyses = {
            unusedparams = true,
            shadow = true,
            loopclousure = false,
          },
          staticcheck = true,
        },
      }
    }
  end,
}
```

All seems to work perfectly fine and I get additional diagnostic warnings for unused params and shadowed variables.

![Screenshot from 2023-04-08 18-05-43](https://user-images.githubusercontent.com/12432243/230732164-3f0f7a7b-a1b0-48fa-a762-62d938e7f64a.png)

**Desktop (please complete the following information):**
- OS: Linux 5.11.22-2-MANJARO
- Terminal: zsh

**Neovim Version**
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

**Comment by tjdevries** [comment]
Hmm, I'll have to take a look at that -- not sure why it'd be happening.

**Comment by KaFski** [comment]
Ok, I've managed to debug it with injecting print statements inside the default handler function of setup_handers, like following: 
``` lua
    print(server_name)
    print("settings:", vim.inspect(servers[server_name]))
```

It happens that gopls is the name of the LSP server and settings it expects is also gopls struct/table...
So basically the correct configuration is to put gopls inside gopls - which made sense once I displayed what I was trying to provide as settings...
``` lua
  gopls = {
    gopls = {
      analyses = {
        unusedparams = true,
        shadow = true,
        loopclousure = false,
      },
      staticcheck = true,
    },
  },
```

Either way, all works fine, sorry for opening the issue so early. It may be closed now.

**Comment by feoh** [comment]
Glad you figured it out and thanks for leaving as crumb trail for the next person to have this problem!

Closing.
