### ISSUE TITLE
600ms startup time when loading dart file

### ISSUE THREAD

**Issue by trevg22** [nvim-lua/kickstart.nvim#256]
Using the master branch no modifications, when I open an empty .dart file get 600ms startup time, when open .cpp file I get 250ms load time. In both instances the LazyDone + LazyStart times are very reasonable less than 100ms combined. But the UIEnter time is very slow. I am using running sway, foot,and neovim 0.9.0 from package manager. Sorry if dumb question but dont know where to start on this one.

**Comment by tjdevries** [comment]
you can run with `--startuptime` flag, and then see what the output says. Do it happen every time you open a dart file? it's possible that the dart LSP or something is blocking on startup

**Comment by trevg22** [comment]
Thanks for the response! Yes it is only when opening dart files and happens every time. I did what you said and here is biggest time delay. I have done a TSInstall for dart.

091.739  001.216  000.047: require('luasnip.loaders.from_snipmate')
091.927  000.123  000.123: require('luasnip.util.jsonc')
091.932  000.180  000.057: require('luasnip.loaders.from_vscode')
587.558  000.093  000.093: require('vim.treesitter.highlighter')
587.925  000.048  000.048: require('vim.uri')
599.697  000.082  000.082: require('editorconfig')
601.156  512.024: opening buffers
602.523  001.367: BufEnter autocommands
602.528  000.005: editing files in windows
