### ISSUE TITLE
Setting CWD to be the github base folder when opening a file that belongs to it

### ISSUE THREAD

**Issue by bechampion** [nvim-lua/kickstart.nvim#267]
This is more likely to be a configuration change/ feature request but i remember this one of the main things i struggled with vim when i initially moved to emacs.

It would be nice that when you do `<leader>sf` and open a file let's say in `~/Projects/myrepo` ,  the next time you `<leader>sf` your CWD changed to the basepath of your github repo . That would make `Telescope git_status` to work etc etc.

I hope what I'm asking makes sense , i think this is the default behaviour in lunarvim etc etc.

**Comment by bechampion** [comment]
Something like this:
```Dada = function ()
  local opts ={}
  opts.cwd ="~/Projects/yourCompany"
  require("telescope.builtin").find_files(opts)
end
vim.api.nvim_set_keymap("n", "<Leader>x", "<cmd>lua Dada()<CR>", {})
```

**Comment by feoh** [comment]
Remember, kickstart is only a starting point, so you're absolutely encouraged to create such customizations for yourself!

However it's not at all clear to me that all users would consider this behavior desirable, so I'm closing this for now.

Please feel free to re-open if you disagree.
