### ISSUE TITLE
Error detected while processing /home/user/.config/nvim/init.lua:

### ISSUE THREAD

**Issue by zohaibakber** [nvim-lua/kickstart.nvim#269]
No specs found for module custom.plugins
Press Enter or type command to continue

OS: Arch

After clicking any key it goes to normal mode but every time I start nvim it dispalys this error.

**Comment by feoh** [comment]
Hi ! Please follow all the instructions for installation specified in the [README](https://github.com/nvim-lua/kickstart.nvim/blob/master/README.md).

That should clear this up right away!

Please feel free to re-open if you disagree.

**Comment by nPHYN1T3** [comment]
Had this error, read the README, cleared up nothing. I was following the video "Effective Neovim: Instant IDE."
