### ISSUE TITLE
Error - fallen at the first hurdle. - E5112: Error while creating lua chunk:  nvim/init.lua:39: '=' expected near 'vim' `

### ISSUE THREAD

**Issue by capnahab** [nvim-lua/kickstart.nvim#270]
On launching nvim init.lua 

 `E5112: Error while creating lua chunk: /Users/.../.config/nvim/init.lua:39: '=' expected near 'vim' `

I am not sure how to troubleshoot.

**Comment by Drakx** [comment]
line 39 in the init says `-- See `:help mapleader`` have you removed the comments?

**Comment by feoh** [comment]
What @Drakx said :) If you're still having trouble we'd need a bit more info to proceed.

Can you please tell us:
- The platform and OS version you're using
- The Neovim version you're using

Can you please show us:
- The diff between your init.lua and the one currently in the kickstart.nvim HEAD?

**Comment by mech-a** [comment]
@capnahab Do you happen to be still facing this error? If you've solved it, would you be able to tell us what you changed so that we can update our installation instructions if need be?

**Comment by feoh** [comment]
It's been over a month. If we don't hear back by next week let's close this one.
