### ISSUE TITLE
All lua variables turn red once workspace is loaded

### ISSUE THREAD

**Issue by KaFski** [nvim-lua/kickstart.nvim#276]
## Describe the bug
So it started happening to me few days (at most 2 weeks) ago. I open any lua project - including this kickstart.nvim - when neovim finishes to load workspace, for some unknown reason all lua variables including function call params turns red.    

During workspace loading:
![pre-workspace-loaded](https://user-images.githubusercontent.com/12432243/233795782-7d5a2e37-cebd-4468-b30b-0f1c6469e300.png)

After workspace loaded:
![post-workspace-loaded](https://user-images.githubusercontent.com/12432243/233795786-b8376d6c-abb4-4cc8-b434-011b4e3f7581.png)

I know it might not be kickstart.nvim issue after all, but no idea where to look for solution so will be grateful for any tips and directions.

## To Reproduce
Open kickstart.nvim/init.lua file and wait until it finished loading workspace

## Desktop

    OS: Linux 5.11.22-2-MANJARO
    Terminal: zsh

## Neovim Version
    NVIM v0.9.0
    Build type: Release
    LuaJIT 2.1.0-beta3

**Comment by feoh** [comment]
Hi I see this too! But why is it a bug? :)

Seems like the language server syntax highlighting is working as designed.

**Comment by KaFski** [comment]
Hey, 
I've disabled LSP with `LspStop` command and it actually reverted the syntax highlighting to the one like shown in first picture attached, so you are right about LSP doing syntax highlighting.

But why is LSP doing this weird syntax highlighting? I thought it's Treesitter job to do syntax highlighting... 

Is there some way do disable it for lua? I just find it irritating to have all variables in red, would much prefer color set as on the first picture.

Thanks for your answer.

**Comment by WindSoilder** [comment]
I get similar issue in rust code too...It's good to have a chance to disable it

**Comment by WindSoilder** [comment]
I found a way to do this: https://www.reddit.com/r/neovim/comments/109vgtl/comment/j40jzjd/?utm_source=share&utm_medium=web2x&context=3

<img width="1103" alt="图片" src="https://user-images.githubusercontent.com/22256154/233843427-9f29eea0-344e-4b91-8da9-150eebefbbd8.png">

**Comment by KaFski** [comment]
Yes, that works perfectly fine. Thank you!
