### ISSUE TITLE
Not working on Raspberry Pi (4B)

### ISSUE THREAD

**Issue by Meniny** [nvim-lua/kickstart.nvim#286]
So, I installed neovim on my Raspberry Pi, and then cloned this repo to `~/.config/nvim`.

But when I launched `nvim`, nothing happened. It worked on my MacBook and Surface.

What should I do?

OS: `Raspbian GNU/Linux 10 (buster)`
shell: `zsh`

```
$ tree .config/nvim
.config/nvim
├── doc
│   ├── kickstart.txt
│   └── tags
├── init.lua
├── lazy-lock.json
├── LICENSE.md
├── lua
│   ├── custom
│   │   └── plugins
│   │       ├── filetree.lua
│   │       └── init.lua
│   └── kickstart
│       └── plugins
│           ├── autoformat.lua
│           └── debug.lua
└─── README.md
```

**Comment by feoh** [comment]
What happens if you type `nvim --clean` on your raspberry pi? 

Wondering if Neovim itself is busted.

**Comment by feoh** [comment]
What happens when you run `nvim --version`

**Comment by Meniny** [comment]
Thanks.
the version is 0.3.4 on my Raspberry Pi, and 0.9.0 on my MacBook. Maybe I should try to install a newer version.

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
```

`:checkhealth` shows:

```
health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/pi/.config/nvim/init.vim
    - ADVICE:
      - :help init.vim
  - ERROR: 'paste' is enabled. This option is only for pasting text.
    It should not be set in your config.
    - ADVICE:
      - Remove `set paste` from your init.vim, if applicable.
      - Check `:verbose set paste?` to see if a plugin or script set the opti      on.

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/0'
```

**Comment by feoh** [comment]
Sorry but there's your problem. We require at least 0.8 to work properly. You may need to compile from source. Resolving for now. Thanks for the report.

**Comment by Meniny** [comment]
> Sorry but there's your problem. We require at least 0.8 to work properly. You may need to compile from source. Resolving for now. Thanks for the report.

OK. Thanks a lot.
