### ISSUE TITLE
Editing the init.lua file causes nvim to crash

### ISSUE THREAD

**Issue by AresAndy** [nvim-lua/kickstart.nvim#29]
When editing the init.lua file, nvim seems to crash back to the shell it was started from.
It also completely messes up the STDIN, forcing me to close the shell altogether.
See img:

![image](https://user-images.githubusercontent.com/9638528/200781202-83c75222-805e-4be1-94a8-4d7c323b2633.png)

OS: Win10
Nvim version: v0.8.0
Shell: Nushell, running under Windows Terminal

**Comment by AresAndy** [comment]
EDIT: actually even doing  `nvim test.py` (file that does not even exist) will cause `nvim` to crash
Configs are unusable 👎

**Comment by CharlesChiuGit** [comment]
nvim in windows is basically useless, try wsl.

**Comment by AresAndy** [comment]
@CharlesChiuGit 
That is not an option, nor a proper answer.

While I am a Linux guy myself, not always you get the green light to enable HyperV, and then install WSL2,
especially on devices given by a company. Or worse, having admin privileges

Plus you're not even addressing the real issue 🤦

**Comment by CharlesChiuGit** [comment]
Run `:checkhealth` to see if anything needs to be addressed.

**Comment by AresAndy** [comment]
That crashes `nvim` as well

**Comment by tjdevries** [comment]
Can you send the output of ":version"? This seems pretty unusual.

**Comment by AresAndy** [comment]
Yes, that still works:
```
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603

Features: -acl +iconv +tui
```

**Comment by tjdevries** [comment]
You should either be using the released nvim 0.8.1 version or latest nightly. See if that fixes the problem

**Comment by AresAndy** [comment]
Ok, that probably should be stated in the README.md file, that at the very least `0.8.1` is required.
Some distribution system might not supply that version as soon as others

And no, that didn't fix anything, both editing of files and `:checkhealth` are broken.
I have a hunch that the issue lies with `nvim-tree-sitter`, but who knows...

**Comment by tjdevries** [comment]
It is in the readme:

> Kickstart.nvim targets only the Neovim releases tagged ['stable'](https://github.com/neovim/neovim/releases/tag/stable) and ['nightly'](https://github.com/neovim/neovim/releases/tag/nightly).

**Comment by AresAndy** [comment]
> It is in the readme:

No, it isn't. Like you say, it states _..only releases tagged 'stable' and 'nightly'.._
and the version I had previous to the update was flagged as stable.

Which is why I mentioned release cycles of distribution systems.
Since you highlighted a more strict version requirement (`>= 0.8.1`), that should be stated instead.

Nonetheless, I commented out `nvim-treesitter`, which I know gives a lot of issues, but `nvim` still crashes.
Can someone _seriously please_ take a stab at this? Thanks

**Comment by CharlesChiuGit** [comment]
maybe u would want to check [nvim-treesitter requirements](https://github.com/nvim-treesitter/nvim-treesitter#requirements).

**Comment by szaffarano** [comment]
Try running nvim with`-V[N][file]`, e.g. `nvim -Vdebug.log ....`, and please attach the file.

Regarding treesitter, did you run `:packer Sync` after you commented out the configuration related to it?

**Comment by AresAndy** [comment]
Yes I did.... But apparently it was not enough 😅 

I had to do a bunch of Packer clear, compile and sync until `nvim-treesitter` was finally eradicated.
Now  `nvim` no longer crashes, as my 6th sense expected.

That plugin is a total nightmare to get it going, and while it should be a good one, I don't recommend having it enabled by default on these configs. I'll close the issue for now

**Comment by qgates** [comment]
@AresAndy FYI running nvim in Win10, any plugins that compile sources - treesitter and fzf-native being two examples - will have problems if you don't have the correct compiler setup on your system. I had similar issues to you with telescope crashing when I tried installing fzf, and also opening any file types enabled for treesitter.

Turned out the problem was I'd used make/gcc from cygwin64 for building sources of nvim plugins, which creates executables and dll's that aren't Windows binaries. You need to install the mingw64 versions of these tools, and either rename them, symlink them or modify the make files to refer to them directly - eg. `x86_64-w64-mingw32-gcc`.

Bit late for you but hopefully this helps anyone else with nvim plugin issues in Windows 🙂
