### ISSUE TITLE
Incompatibility of the starter for new NVIM versions

### ISSUE THREAD

**Issue by buldi** [nvim-lua/kickstart.nvim#290]
## Describe the bug
**This is my example of nvim problems ...**

Error detected while processing /home/xxxxxxxxxxxx/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/loader.lua:0: ENOENT: no such file or directory: ~/nvim/luac/%home%xxxxxxxxxxxx%.local%share%nvim%lazy%lazy.nvim%lua%lazy%stats.luac
stack traceback:
        [C]: in function 'assert'
        vim/loader.lua: in function 'write'
        vim/loader.lua: in function 'loadfile'
        vim/loader.lua: in function <vim/loader.lua:0>
        [C]: in function 'require'
        ...xxxxxx/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:54: in function 'setup'
        /home/xxxxxxxxxxxx/.config/nvim/init.lua:66: in main chunk
Error detected while processing /usr/share/nvim/runtime/filetype.lua:
E5111: Error calling lua: vim/loader.lua:0: ENOENT: no such file or directory: ~/nvim/luac/%usr%share%nvim%runtime%filetype.luac
stack traceback:
        [C]: in function 'assert'
        vim/loader.lua: in function 'write'
        vim/loader.lua: in function <vim/loader.lua:0>
E5111: Error calling lua: vim/loader.lua:0: ENOENT: no such file or directory: ~/nvim/luac/%usr%share%nvim%runtime%filetype.luac
stack traceback:
        [C]: in function 'assert'
        vim/loader.lua: in function 'write'
        vim/loader.lua: in function <vim/loader.lua:0>
Error detected while processing /usr/share/nvim/runtime/syntax/syntax.vim:
line   42:
E121: Undefined variable: s:did_ft
Error detected while processing /usr/share/nvim/runtime/plugin/editorconfig.lua:
E5111: Error calling lua: vim/loader.lua:0: ENOENT: no such file or directory: ~/nvim/luac/%usr%share%nvim%runtime%plugin%editorconfig.luac
stack traceback:
        [C]: in function 'assert'
        vim/loader.lua: in function 'write'
        vim/loader.lua: in function <vim/loader.lua:0>
Error detected while processing /usr/share/nvim/runtime/plugin/man.lua:
E5111: Error calling lua: vim/loader.lua:0: ENOENT: no such file or directory: ~/nvim/luac/%usr%share%nvim%runtime%plugin%man.luac
stack traceback:
        [C]: in function 'assert'
        vim/loader.lua: in function 'write'
        vim/loader.lua: in function <vim/loader.lua:0>
Error detected while processing /usr/share/nvim/runtime/plugin/nvim.lua:
E5111: Error calling lua: vim/loader.lua:0: ENOENT: no such file or directory: ~/nvim/luac/%usr%share%nvim%runtime%plugin%nvim.luac
stack traceback:
        [C]: in function 'assert'
        vim/loader.lua: in function 'write'
        vim/loader.lua: in function <vim/loader.lua:0>

## To Reproduce
1. copy file init.lua from git to ~/.config/nvim/init.lua
2. run nvim 

## Desktop
XFCE4
- OS: 'Linux 5.19.0-41-generic 42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64' GNU/Linux
- Terminal: GNOME Terminal: Version 3.44.0 for GNOME 42

## Neovim Version
NVIM v0.10.0-dev from https://neovim.io

**Comment by feoh** [comment]
I'm at a loss with this one.

What happens if you run: `nvim --clean`

And then once it's running type: `:lua print("hi")`

You should see 'hi' on the bottom of your screen. If you get an error please paste it here.

**Comment by buldi** [comment]
:( Delivery what I entered and nothing can be seen on the screen. So I conclude that I don't have a Lua plugin ?!

**Comment by feoh** [comment]
Maybe. What happens when you run `:checkhealth` from within Neovim?

**Comment by feoh** [comment]
Whoa. I'm sorry, but there is something VERY broken about your Neovim build. Did you build it yourself from source? 

Check the [pre-requisites](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites) and ensure you have everything you need.

Also, I'm sorry to say, getting a good neovim build may be beyond the scope of tis project :) Please consider consulting one of the other excellent community support options like IRC, Discourse, etc mentioned [here](https://neovim.io/).

I'm going to close this for now. Good luck and sorry you're having trouble!

**Comment by buldi** [comment]
thx
