### ISSUE TITLE
tsserver errors go out of screen boundaries

### ISSUE THREAD

**Issue by alessandrocapra** [nvim-lua/kickstart.nvim#295]
## To Reproduce
1. clone the kickstart.nvim repo
2. open nvim within a project with TS files containing an error
3. the long error message goes out of the screen boundaries

See attachment --> <img width="1680" alt="image" src="https://user-images.githubusercontent.com/3504592/235612601-7e977070-27e4-425c-b045-be6c0c5cdc4c.png">

## Desktop
- OS: MacBook Pro M1 Ventura 13.1
- Terminal: zsh

## Neovim Version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

```
```

**Comment by feoh** [comment]
Hi. This is a design choice as seen [here](https://github.com/neovim/neovim/issues/14568). If you want to see your diagnostics in a different form, Neovim is very flexible and will accommodate with a bit of Lua code.

For now, you can display the diagnostics as a "float" using [this](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L356) keybind already in your init.lua.

**Comment by alessandrocapra** [comment]
Thanks for the explanation! I'm a super noob, still wrapping my head around it 😁 but I am using the leader + e key binding to open the float messeg, which reveals the whole text (it can be quite long, especially in TS).

Thanks and keep up with the good work!
