### ISSUE TITLE
No specs found for module custom.plugins

### ISSUE THREAD

**Issue by evgi88** [nvim-lua/kickstart.nvim#309]
## Describe the bug

I copy-pasted `init.lua` into my newly created `~/.config/nvim/init.lua` file.
Every time I enter `nvim` I get this error: 

Error detected while processing /Users/.../.config/nvim/init.lua:
No specs found for module custom.plugins

## To Reproduce
Basically already described above

## Desktop
- OS: macOS Ventura 13.3.1 (22E261)
- Terminal: ZSH

## Neovim Version

```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"
```

**Comment by feoh** [comment]
You can't just cut and paste into an init.lua and have it work. Please follow the [complete install instructions](https://github.com/nvim-lua/kickstart.nvim/blob/master/README.md).

**Comment by feoh** [comment]
at that time? It did! However, videos become out of date as this one has.
