### ISSUE TITLE
Add auto-update for treesitter?

### ISSUE THREAD

**Issue by Serif-7** [nvim-lua/kickstart.nvim#31]
I'm wondering if the config shouldn't come with auto-update for treesitter parsers. nvim-treesitter 'strongly recommends' this in their repo and I think it's a pretty obvious win towards making a plug-and-play config. It's not strictly necessary, but I can't think of a single reason anyone wouldn't enable this immediately, and it would have made things a little smoother for me as a new user if it was enabled by default.

Here is my proposed change: 

```lua
  use 'nvim-treesitter/nvim-treesitter'  -- Highlight, edit, and navigate code
```

becomes:

```lua
    use {

        'nvim-treesitter/nvim-treesitter',
        run = function()
            local ts_update = require('nvim-treesitter.install').update({ with_sync = true })
            ts_update()
        end,
    } -- Highlight, edit, and navigate code
 ```

I call the function directly because according to https://github.com/nvim-treesitter/nvim-treesitter/wiki/Installation, it would otherwise fail on first install.

**Comment by tjdevries** [comment]
I should have fixed this in the last commit! Does it look good to you now?

**Comment by Serif-7** [comment]
Yeah, looks good. I saw a missing parens on line 34 though, added a comment on the line.

**Comment by tjdevries** [comment]
cool, replied in the comment -- it actually is valid lua on the line. thanks :)

**Comment by Serif-7** [comment]
My bad then. Thanks for pushing the fix!
