### ISSUE TITLE
The current platform is unsupported.

### ISSUE THREAD

**Issue by badlandz** [nvim-lua/kickstart.nvim#312]
## Describe the bug

Lua install failed? May not be kickstart issue, probably need to look at why lua isn't going?

mason.log last line gives:
[ERROR Wed May 17 22:13:36 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:200: Installation failed for Package(name=lua-language-server) error="The current platform is unsupported."
## To Reproduce

1. ...
Install neovim from ports on clean install of 13.2-RELEASE FreeBSD, clone the init with git.
## Desktop

- OS: Freebsd
- Terminal: stm

## Neovim Version

NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@touchy

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
```

**Comment by badlandz** [comment]
I guess it's a known BSD issue. n/m. don't know enough about it to help so...

**Comment by badlandz** [comment]
Still researching if anyone interested, think there may be a fix... 

https://gist.github.com/VonHeikemen/8fc2aa6da030757a5612393d0ae060bd

**Comment by jimkoen** [comment]
https://github.com/LuaLS/lua-language-server/issues/128#issuecomment-587996540

The lua-language-server maintainers have clearly stated that FreeBSD (and with that I suppose all the *BSD's) are not supported as a platform. The error message can be mitigated by removing the following section that enables the Lua language server from init.lua (L596-L603):

https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L596

inb4 why not just compile lua-lsp for FreeBSD: Apparently lua-lsp is dependent on some linux-specific headers (notably inotify). There is an inotify port available for FreeBSD, but I don't think you could incorporate that into lua-lsp without substantial work.
