### ISSUE TITLE
Windows path in README wrong?

### ISSUE THREAD

**Issue by ckaag** [nvim-lua/kickstart.nvim#314]
## Describe the bug
`%userprofile%\AppData\Local\nvim-data\` does not seem to be the correct path for neovim configs under windows (it's used for data as the name implies). The path should be `%userprofile%\AppData\Local\nvim\` (corresponding to ~/.config/nvim on Unix).

It would also probably help to add in a line that a C compiler is required for the plugins to run (e.g. `scoop install gcc`). But that's pretty self-explainable by error messages alone.

## To Reproduce
1. install neovim on Windows (I was using scoop)
2. use the `nvim-data` path 
3. nvim will not load the init.lua

## Desktop
- OS:  Windows 10

## Neovim Version
v0.9.0

**Comment by feoh** [comment]
Please feel free to submit a pull request. You can even do this from the Github web UI without using the command line as well :)

**Comment by feoh** [comment]
I don't currently have a working Windows install to test on. I should revert my laptop to Windws I guess but it's running Manjaro KDE and I've been pretty happy with it :)
