### ISSUE TITLE
some treesitter errors, directly after installation

### ISSUE THREAD

**Issue by Guelakais** [nvim-lua/kickstart.nvim#317]
## Describe the bug

Directly after I've copied the init.lua into my .config/init.lua, my treesitter commented while compilation, that he can't find several files.
## To Reproduce

1. ...
open nvim
2.
`nvim-treesitter[lua]: Error during compilation`  
`
/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/cc1: error while loading shared libraries: libisl.so.23: cannot open shared object file: No such file or directory
/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/cc1: error while loading shared libraries: libisl.so.23: cannot open shared object file: No such file or directory
`
## Desktop

- OS: Steam OS
- Terminal: kde terminal

## Neovim Version

`NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser                                                                                                                                     
                                       
Features: +acl +iconv +tui                      
See ":help feature-compile"                     
                                                
   system vimrc file: "$VIM/sysinit.vim"        
  fall-back for $VIM: "/usr/share/nvim"       
                                                                                                                                                          
Run :checkhealth for more info    `
```
```

**Comment by feoh** [comment]
What happens when you run :checkhealth ?

**Comment by feoh** [comment]
Also, I have no sense of SteamOS, are you sure you installed the package that provides libisl.so to your system?

Either way, this isn't a problem with kickstart.nvim so I'm closing this for now.
