### ISSUE TITLE
High CPU usage after fresh install on MacOS

### ISSUE THREAD

**Issue by timTonelli** [nvim-lua/kickstart.nvim#320]
## Describe the bug
After a fresh install (removing existing `.config/nvim`, `.local/state/nvim`,  `.local/share/nvim`, and `.cache/nvim` first), when I open a `.lua` file in the editor, I get a couple messages saying that it's loading the workspace, and then fairly quickly the entire right side of the terminal is filled with messages saying it's searching files, and both nvim and lua-language-server jump up to about 99% cpu usage as shown in the MacOS monitoring tool.

During this time, normal mode appears to work, but insert mode brings things to a halt. If I wait about 3 minutes, everything seems to finish up, but this happens every time I open nvim. I have uninstalled/reinstalled a few times to try different things, but this happens every time. If I restore my backup of NvChad config, this doesn't happen at all.

<img width="1464" alt="Screen Shot 2023-05-24 at 7 42 41 AM" src="https://github.com/nvim-lua/kickstart.nvim/assets/102175985/7a2efd1d-9c20-478e-ae81-272c26726675">
<img width="1072" alt="Screen Shot 2023-05-24 at 7 48 25 AM" src="https://github.com/nvim-lua/kickstart.nvim/assets/102175985/99acddeb-758f-42d5-86ac-8d06b7d69326">

## To Reproduce

1. Fresh install via git clone of this project
2. Open nvim, and allow kickstart to do the auto-installs it does
3. Open `init.lua`, and the above behavior happens

## Desktop

- OS: MacOS 12.5.1
- Terminal: Alacritty

## Neovim Version

```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"
```

**Comment by mech-a** [comment]
I'm working on recreating your issue. In the mean time, a few things to try out:

- Could you send the output of `:checkhealth'?
- If you comment out the loading of `j-hui/fidget.nvim`, retrigger lazy to uninstall it, does the issue persist?
- Can you change the `lua_ls` server set up to this:
```lua
  lua_ls = {
    Lua = {
      workspace = { checkThirdParty = false, maxPreload=5 },
      telemetry = { enable = false },
    },
  },
```

**Comment by timTonelli** [comment]
Hi @mech-a, after I filed the issue I wound up uninstalling and reverting to my backup config to unblock myself. I decided to give it one more go after work, and I didn't come across the issue for some reason? I did have a different issue with lua-language-server where it wouldn't start, but I uninstalled and reinstalled with mason, and things seem to be working fine since.

Before opening the issue I had tried to uninstall/clean reinstall this repo like 5 times with the same result each time. I genuinely don't know what made the difference this time.

**Comment by mech-a** [comment]
Yeah, it seems that the language servers, when automatically installed, can lead to some odd issues. I've heard of similar bugs before that aren't related to kickstart. I'm glad you're not facing that issue anymore -- in case you run into anything else, reinstalling the treesitter parser & language server may help out.

**Comment by feoh** [comment]
Glad you were able to get this resolved! Closing this for now.
