### ISSUE TITLE
Inspect LSP/Treesitter autoinstallations with Mason

### ISSUE THREAD

**Issue by mech-a** [nvim-lua/kickstart.nvim#321]
Issues like #320 and #236 seem to be related to the first installation of many of the tools. It may be worth inspecting these issues further and trying to reproduce them to see if there is any relationship.

**Comment by feoh** [comment]
I don't think so. #236 is about treesitter pulling in the wrong C/C++ compiler on Windows.

**Comment by mech-a** [comment]
I wrote this ticket wrong -- didn't mean to say that those two issues are related. I'll split this ticket into 2 and clarify them further.

**Comment by feoh** [comment]
@mech-a Is this issue still relevant? Thanks for writing it!

**Comment by mech-a** [comment]
I don't think so, unless we see some more substantial reports. Closing this.
