### ISSUE TITLE
Hi Errors when running init lua file several clone fails ???

### ISSUE THREAD

**Issue by thorrrr** [nvim-lua/kickstart.nvim#332]
Failed (12)
    ○ Comment.nvim 
        Cloning into '/home/dale/.local/share/nvim/lazy/Comment.nvim'...
        fatal: unable to access 'https://github.com/numToStr/Comment.nvim.git/': Could not resolve host: github.com
    ○ fidget.nvim   nvim-lspconfig
        Cloning into '/home/dale/.local/share/nvim/lazy/fidget.nvim'...
        remote: Enumerating objects: 369, done.        
        remote: Counting objects: 100% (82/82), done.        
        remote: Compressing objects: 100% (33/33), done.        
        remote: Total 369 (delta 61), reused 53 (delta 49), pack-reused 287        
        Receiving objects: 100% (369/369), 49.66 KiB | 360.00 KiB/s, done.
        Resolving deltas: 100% (103/103), done.
        fatal: unable to access 'https://github.com/j-hui/fidget.nvim.git/': Could not resolve host: github.com
        fatal: could not fetch d0bef139047d1e7091c19ac8af4898992690f318 from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
    ○ friendly-snippets   nvim-cmp
        Cloning into '/home/dale/.local/share/nvim/lazy/friendly-snippets'...
        remote: Enumerating objects: 1515, done.        
        remote: Counting objects: 100% (233/233), done.        
        remote: Compressing objects: 100% (69/69), done.        
        remote: Total 1515 (delta 189), reused 174 (delta 164), pack-reused 1282        
        Receiving objects: 100% (1515/1515), 311.58 KiB | 1.19 MiB/s, done.
        Resolving deltas: 100% (803/803), done.
        fatal: unable to access 'https://github.com/rafamadriz/friendly-snippets.git/': Could not resolve host: github.com
        fatal: could not fetch d53a50278cd21020c7f175fd2c16e08205e13663 from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
    ○ gitsigns.nvim 
        Cloning into '/home/dale/.local/share/nvim/lazy/gitsigns.nvim'...
        remote: Enumerating objects: 4104, done.        
        remote: Counting objects: 100% (349/349), done.        
        remote: Compressing objects: 100% (157/157), done.        
        remote: Total 4104 (delta 191), reused 279 (delta 171), pack-reused 3755        
        Receiving objects: 100% (4104/4104), 498.73 KiB | 2.13 MiB/s, done.
        Resolving deltas: 100% (2032/2032), done.
        fatal: unable to access 'https://github.com/lewis6991/gitsigns.nvim.git/': Could not resolve host: github.com
        fatal: could not fetch 7235de1c6da47d1730f26807553fee4e4e327c92 from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
    ○ indent-blankline.nvim 
        Cloning into '/home/dale/.local/share/nvim/lazy/indent-blankline.nvim'...
        fatal: unable to access 'https://github.com/lukas-reineke/indent-blankline.nvim.git/': Could not resolve host: github.com
    ○ lualine.nvim 
        Cloning into '/home/dale/.local/share/nvim/lazy/lualine.nvim'...
        fatal: unable to access 'https://github.com/nvim-lualine/lualine.nvim.git/': Could not resolve host: github.com
    ○ mason-lspconfig.nvim   nvim-lspconfig
        Cloning into '/home/dale/.local/share/nvim/lazy/mason-lspconfig.nvim'...
        remote: Enumerating objects: 828, done.        
        remote: Counting objects: 100% (77/77), done.        
        remote: Compressing objects: 100% (46/46), done.        
        remote: Total 828 (delta 35), reused 48 (delta 17), pack-reused 751        
        Receiving objects: 100% (828/828), 133.30 KiB | 1.36 MiB/s, done.
        Resolving deltas: 100% (326/326), done.
        fatal: unable to access 'https://github.com/williamboman/mason-lspconfig.nvim.git/': Could not resolve host: github.com
        fatal: could not fetch 7e9f6a7ddf8ce44a97c41f23c91b5102aee94a41 from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
    ○ nvim-cmp 
        Cloning into '/home/dale/.local/share/nvim/lazy/nvim-cmp'...
        remote: Enumerating objects: 3352, done.        
        remote: Counting objects: 100% (157/157), done.        
        remote: Compressing objects: 100% (74/74), done.        
        remote: Total 3352 (delta 76), reused 110 (delta 48), pack-reused 3195        
        Receiving objects: 100% (3352/3352), 395.32 KiB | 2.03 MiB/s, done.
        Resolving deltas: 100% (1718/1718), done.
        fatal: unable to access 'https://github.com/hrsh7th/nvim-cmp.git/': Could not resolve host: github.com
        fatal: could not fetch 1d0c8d5d8ea93bbe2f0136cf78dbc869cbd0973b from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
    ○ nvim-treesitter-textobjects   nvim-treesitter
        Cloning into '/home/dale/.local/share/nvim/lazy/nvim-treesitter-textobjects'...
        remote: Enumerating objects: 1857, done.        
        remote: Counting objects: 100% (51/51), done.        
        remote: Compressing objects: 100% (27/27), done.        
        remote: Total 1857 (delta 21), reused 40 (delta 16), pack-reused 1806        
        Receiving objects: 100% (1857/1857), 236.82 KiB | 1.03 MiB/s, done.
        Resolving deltas: 100% (845/845), done.
        fatal: unable to access 'https://github.com/nvim-treesitter/nvim-treesitter-textobjects.git/': Could not resolve host: github.com
        fatal: could not fetch bb6a1423efc0537578e723900dadb14b36e554c6 from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
    ○ onedark.nvim 
        Cloning into '/home/dale/.local/share/nvim/lazy/onedark.nvim'...
        remote: Enumerating objects: 650, done.        
        remote: Counting objects: 100% (124/124), done.        
        remote: Compressing objects: 100% (70/70), done.        
        remote: Total 650 (delta 58), reused 100 (delta 48), pack-reused 526        
        Receiving objects: 100% (650/650), 127.70 KiB | 1.05 MiB/s, done.
        Resolving deltas: 100% (162/162), done.
        fatal: unable to access 'https://github.com/navarasu/onedark.nvim.git/': Could not resolve host: github.com
        fatal: could not fetch 08471c380de5157ce837219db75b4c0b7d4bbed3 from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
    ○ telescope-fzf-native.nvim 
        Cloning into '/home/dale/.local/share/nvim/lazy/telescope-fzf-native.nvim'...
        remote: Enumerating objects: 299, done.        
        remote: Counting objects: 100% (63/63), done.        
        remote: Compressing objects: 100% (26/26), done.        
        remote: Total 299 (delta 47), reused 41 (delta 35), pack-reused 236        
        Receiving objects: 100% (299/299), 69.76 KiB | 952.00 KiB/s, done.
        Resolving deltas: 100% (72/72), done.
        fatal: unable to access 'https://github.com/nvim-telescope/telescope-fzf-native.nvim.git/': Could not resolve host: github.com
        fatal: could not fetch 32799e7d5735e571ede09a775329ff4ff3ccad8c from promisor remote
        warning: Clone succeeded, but checkout failed.
        You can inspect what was checked out with 'git status'
        and retry with 'git restore --source=HEAD :/'
    ○ which-key.nvim 
        Cloning into '/home/dale/.local/share/nvim/lazy/which-key.nvim'...
        fatal: unable to access 'https://github.com/folke/which-key.nvim.git/': Could not resolve host: github.com

  Installed (12)
    ○ LuaSnip   nvim-cmp
    ● cmp-nvim-lsp 0.89ms   init.lua
    ○ cmp_luasnip   nvim-cmp
    ● mason.nvim 2.4ms   nvim-lspconfig
    ● neodev.nvim 0.04ms   nvim-lspconfig
    ● nvim-lspconfig 11.29ms  start
    ● nvim-treesitter 4.53ms ✔  build
    ● plenary.nvim 0.16ms   telescope.nvim
    ● telescope.nvim 0.69ms  start
    ● vim-fugitive 1.01ms  start
    ● vim-rhubarb 0.18ms  start
    ● vim-sleuth 0.48ms  start

  Loaded (1)
    ● lazy.nvim 17352.99ms   init.lua

**Comment by thorrrr** [comment]
Also i get 
Error detected while processing /home/dale/.config/nvim/init.lua
No specs found for module custom.plugins?

**Comment by feoh** [comment]
Hi.

1) kickstart.nvim requires a working internet connection to be able to install its plugins.

if `nslookup github.com` doesn't return something reasonable you're out of luck and need to fix your network.

2) You can't just copy the init.lua file despite what the video you may have seen on youtube says. Please fully follow the instructions in https://github.com/nvim-lua/kickstart.nvim#readme 

Closing this for now. Let us know if you're having trouble once you've followed these instructions.
