### ISSUE TITLE
How to prevent it from choosing the first snippet instead of opening a new line when I press `Enter`?

### ISSUE THREAD

**Issue by amalgame21** [nvim-lua/kickstart.nvim#335]
I know this is not a bug of kickstart.nvim, but there are a lot of snippet components used in it ( e.g. cmp_luasnip, friendly-snippets, etc), and I did not know which one is causing the problem.

I would like to make the `Enter` key always open a new line, not choosing the first matching snippet, and if I want to use the first snippet, I can just use `Tab` and `Enter` for that.
It is very annoying when I want to open a newline, and it just choose the first snippet.
I somehow discovered I can press `Ctrl+e` to close the snippet window, but I do not want to check if there is a snippet window pop up every time before pressing `Enter`.
How can I do it? Thanks!

**Comment by mech-a** [comment]
That's all controlled by `nvim-cmp`, which is the actual thing you interact with to work with LSP, LuaSnip, etc. For more information, look at the nvim-cmp repository and `:help cmp`.

Near the end of the config, you should find that inside the object passed to `cmp.setup`, there is a `mapping` property. The line that says ['<CR>'] is defining the behavior for when you hit `Enter`. Feel free to replace that and adjust as what works for you.

**Comment by amalgame21** [comment]
Thanks! Changed `<CR>` to other keybinding and it is all good now!
