### ISSUE TITLE
Defined plugins in 'custom.plugins' are not synced

### ISSUE THREAD

**Issue by BKDevelop** [nvim-lua/kickstart.nvim#34]
The latest change introduced the option to use a seperate file for defining plugins ootb. At least on my machine, this does not seem to work as expected.

**How to reproduce**

1. check out kickstart.nvim in `~/.config/nvim`
2. add file `lua/costum/plugins.lua`
3. copy relevant snippet from Readme
4. save and reopen neovim
5. run `:PackerSync`
6. no new plugins are added :(

Can anybody reproduce this, or is there something wrong with my setup?  Thx

**Comment by tjdevries** [comment]
can you show your exact `custom/plugins` file? And to be clear, you put it in `custom/plugins` not `costom/plugins` right?

**Comment by BKDevelop** [comment]
Sorry for the late reply. Had the chance to try this on a different machine today... It works just fine!

I assume PEBKAC on my last attempt - sorry for the inconvinience!

**Comment by BKDevelop** [comment]
Sorry for the late reply. Had the chance to try this on a different machine today... It works just fine!

I assume PEBKAC on my last attempt - sorry for the inconvinience!

**Comment by tjdevries** [comment]
No problem at all :)  have a good day

**Comment by jby** [comment]
I'm seeing the exact same behaviour here.
My $HOME/.config/nvim/custom/plugins.lua:
```
return function(use)
  use({
	'nvim-tree/nvim-tree.lua'
	config = function()
		require("nvim-tree").setup()
	'nvim-tree/nvim-web-devicons'
	end
	})
```

**Comment by BKDevelop** [comment]
I think the file needs to be located at

$HOME/.config/nvim/**lua**/custom/plugins.lua

**Comment by jby** [comment]
Yes, sorry - my mistake... :(

**Comment by jby** [comment]
However, it would seem that the custom/plugins.lua is only read for _config_ of the plugin. Packer doesn't seem to see any plugins included in it...
I now have 3 plugins configured in it:
```
return function(use)
-- Configure nvim-tree
  use({
	'nvim-tree/nvim-tree.lua'
	config = function()
		require("nvim-tree").setup()
	'nvim-tree/nvim-web-devicons'
	end
-- Add friendly snippets
  use({
	'rafamadriz/friendly-snippets'
	config = function ()
		require("friendly-snippets").setup()
	end
	})
end
```
and it never installs 'friendly-snippets', and if I run PackerSync manually it _always_ asks if it can remove the unused nvim-tree plugins... (which were installed when I had them in init.lua, which was when I had the wrong path to my custom/plugins.lua)
What am I doing wrong?

**Comment by jby** [comment]
I'd guess it's these (rather than ~/.config/cache/nvim) that I should remove?
<img width="750" alt="image" src="https://user-images.githubusercontent.com/1584888/218439755-bba21f27-e336-4940-85d8-29b6ecfce5fc.png">
However a :PackerInstall does nothing...

**Comment by jby** [comment]
I'm pretty sure though, that if I were to remove the above I would no longer have the nvim-tree plugin installed...

**Comment by LudoPinelli** [comment]
You can remove `~/.local/share/nvim`, it will reset your config and reinstall everything (you may have to restart neovim a couple of time for everything to be set up).

I don't knwow if the `custom/plugins.lua` you showed is only a snippet or the entire file. If it is the entire file, a `})` is missing, also `nvim-web-devicons` should be required. Here is the file with the corrections :
```
return function(use)
-- Configure nvim-tree
  use({
	{'nvim-tree/nvim-tree.lua', requires = 'nvim-tree/nvim-web-devicons'},
	config = function()
		require("nvim-tree").setup()
	'nvim-tree/nvim-web-devicons'
	end
	})
-- Add friendly snippets
  use({
	'rafamadriz/friendly-snippets'
	config = function ()
		require("luasnip.loaders.from_vscode").lazy_load()
	end
	})
end
```

**Comment by jby** [comment]
Ok, thanks - but still - no install of the plugins in the custom file.
I did remove ~/.local/share/nvim and when I restarted it re-installed everything again - but not the plugins in the custom file:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/1584888/218456222-ce1bc508-1919-4a70-8eef-0deb2b586681.png">

**Comment by jby** [comment]
Albeit it _does_ look for it since I've configured it...
```
Error detected while processing /Users/jonasb/src/jby/nvim/after/plugin/defaults.lua:
E5113: Error while calling lua chunk: /Users/jonasb/src/jby/nvim/after/plugin/defaults.lua:4: module 'nvim-tree' not found:
        no field package.preload['nvim-tree']
        no file './nvim-tree.lua'
        no file '/usr/local/share/luajit-2.1.0-beta3/nvim-tree.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree/init.lua'
        no file '/Users/jonasb/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvim-tree.lua'
        no file '/Users/jonasb/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvim-tree/init.lua'
        no file '/Users/jonasb/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvim-tree.lua'
        no file '/Users/jonasb/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvim-tree/init.lua'
        no file './nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/Users/jonasb/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvim-tree.so'
stack traceback:
        [C]: in function 'require'
        /Users/jonasb/src/jby/nvim/after/plugin/defaults.lua:4: in main chunk
```

**Comment by jby** [comment]
Hmm, my `~/.config/nvim/lua/custom/plugins.lua` doesn't even seem to be read even if I ignore the logic that's supposed to look for it and manually specify it in `init.lua` like this:
```
(require 'custom.plugins')
```

My `~/.config/nvim/lua/custom/plugins.lua` now:
```lua
return function(use)
  -- Configure nvim-tree
  use({
    {'nvim-tree/nvim-tree.lua', requires = 'nvim-tree/nvim-web-devicons'},
    config = function()
      require("nvim-tree").setup()
      'nvim-tree/nvim-web-devicons'
    end
  })
  -- Add friendly snippets
  use({
    'rafamadriz/friendly-snippets',
    config = function ()
      require('luasnip.loader.from_vscode').lazy_load()
    end
  })
  -- // Comment.nvim
  use {
    'numToStr/Comment.nvim',
    config = function()
      require('Comment').setup()
    end
  }
end
```

**Comment by jby** [comment]
The _only_ way, so far I get the plugins I want to add to actually be installed and used is to add them to `init.lua`...
Doesn't that kind of make the `custom.plugins` rather useless?

**Comment by LudoPinelli** [comment]
> Doesn't that kind of make the `custom.plugins` rather useless?

Sure but it seems that you are the only one with this problem, I'm sorry, I'm running out of ideas.

**Comment by jby** [comment]
I kind of feel like I've hi-jacked someone else's, already closed, issue here. Maybe I should create my own instead?

**Comment by jby** [comment]
Created #176 instead
