### ISSUE TITLE
No specs found for module custom.plugins

### ISSUE THREAD

**Issue by aarishshahmohsin** [nvim-lua/kickstart.nvim#343]
## Describe the bug
When opening a file with neovim, I am greeted with an error. 
The error message:
 Error detected while processing /home/aarish/.config/nvim/init.lua:
No specs found for module custom.plugins

## To Reproduce

1. Copy the contents of init.lua to ~/.config/nvim/init.lua
2. Run nvim and let packer install all plugins
3. open any file using nvim

## Desktop

- OS: Arch Linux
- Terminal: xfce4-terminal 1.0.4

## Neovim Version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```
```
![image](https://github.com/nvim-lua/kickstart.nvim/assets/49566965/2568e909-e795-4dc3-90e0-23d118eedf8b)

**Comment by mikepoullas** [comment]
I'm having the same issue. If you're coming from the TJ DeVries Youtube video, it looks like many are having the same issue and reported weeks ago. And when I do bypass the error and restart NeoVim, its a terrible experience.

**Comment by mikepoullas** [comment]
Solved. You need to download and extract the entire ZIP file for the project into your /nvim folder. Mine now works!

**Comment by AidenLeee** [comment]
thanks, problem solved
