### ISSUE TITLE
initialized ok, but with a little bug

### ISSUE THREAD

**Issue by AidenLeee** [nvim-lua/kickstart.nvim#345]
## Describe the bug

After init the init.lua file, each time i open nvim, it will show the thing like this:
```
Error detected while processing /home/aiden/.config/nvim/init.lua:
No specs found for module custom.plugins
Press ENTER or type command to continue
```
## To Reproduce

1. type `nvim`
2. show the error

## Desktop

- OS: Ubuntu18.04
- Terminal: bash

## Neovim Version

v0.9.1
```
```

**Comment by mech-a** [comment]
It's likely that you did not follow the installation instructions properly. See #343
