### ISSUE TITLE
incorrect syntax highlight in a popup

### ISSUE THREAD

**Issue by azdanov** [nvim-lua/kickstart.nvim#353]
## Describe the bug

When opening popup the syntax is not properly highlighted. I tested with LazyVim, and there is works properly.

![Screenshot 2023-06-25 183043](https://github.com/nvim-lua/kickstart.nvim/assets/6123841/f5e2f87d-a1b6-45f0-9230-eb7e09f8dc2d)
vs
![image](https://github.com/nvim-lua/kickstart.nvim/assets/6123841/87bdc506-279d-4d3d-9384-0bef4fce55e4)

## To Reproduce

1. Clone repo
2. Type `vim.api.nvim_create_augroup`
3. Open popup

## Desktop

- OS: Windows 11 Pro / WSL Debian
- Terminal: Windows Terminal 1.17

## Neovim Version

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by feoh** [comment]
I really don't understand this.

What commands are you *exactly* using to create the popup?

I guarantee you if I type ` vim.api.nvim_create_augroup`  a popup isn't what I get :)

Also what language server are you using?

**Comment by azdanov** [comment]
You get a popup with documentation when you select an autocomplete with `C-n` or `C-p`.

And my question was how to fix missing syntax highlight in Vimdoc documentation.  I assume it's some plugin not working correctly. Because on clean LazyVim setup it works.

I can't debug on my own, since it's quite complicated for me still. A bit of context, I only started with neovim a week ago, so I don't know pretty much anything 🙂.
