### ISSUE TITLE
Formatting automatically clear virtual text diagnostics

### ISSUE THREAD

**Issue by Wizermil** [nvim-lua/kickstart.nvim#356]
## Describe the bug
Formatting automatically clear virtual text diagnostics.
When disabled (`ESC:KickstartFormatToggle`) the diagnostics (virtual text) are not removed and stay visible it's the behavior I'm looking for.
Do you know by any chances a way to keep the diagnostics always visible with formatting enabled?

## To Reproduce
1. enable virtual text diagnostics
```lua
vim.diagnostic.config({
	virtual_text = {
		source = "if_many",
		prefix = '●'
	},
	severity_sort = true,
	float = {
		border = 'rounded',
		source = "if_many",
	},
})
```
2. create any warnings in `init.lua` just add a warning for example:
```lua
'lukas-reineke/indent-blankline.nvim',
opts = {
	char = '┊',
	char = true,
	show_trailing_blankline_indent = false,
},
```
3. save the file (`ESC:w`)
4. virtual text diagnostics disappear
<img width="446" alt="Screenshot 2023-07-01 at 12 27 44" src="https://github.com/nvim-lua/kickstart.nvim/assets/700192/5ee67271-c502-41f6-a90f-b3d48776a5fe">

## Desktop
- OS: macOS 13.4.1
- Terminal: kitty 0.28.1

## Neovim Version
```
NVIM v0.9.1                                                                                                                                                                                              
Build type: Release                                                                                                                                                                                      
LuaJIT 2.1.0-beta3
```

**Comment by feoh** [comment]
Hi.

I'm not seeing this. I get plenty of diagnostics before during and after pop-ups :)

**Comment by feoh** [comment]
Ah OK.

I don't actually have virtual text diagnostics enabled, and we don't do that by default with kickstart.nvim.

I would file an issue with the main Neovim project, or consult other community resources for help with this issue.
