### ISSUE TITLE
can't format jsx file

### ISSUE THREAD

**Issue by ryannewcomer** [nvim-lua/kickstart.nvim#360]
## Describe the bug

i want to use the autoformat, so i enable the autoformat flie. then i install stylua, it work on lua file, then i want to try it on jsx file (javascriptreact) but it said no maching language server
## To Reproduce

1. uncomment the ' require kickstart.plguins.autoformat'
2. restart neovim
3. install stylua in mason
4. format a lua file by :w
5. work!
6. install lsp in mason for jsx
7. format a jsx file
8. error

## Desktop

- OS: endeavouros linux on windows
- Terminal: window terminal

## Neovim Version

![image](https://github.com/nvim-lua/kickstart.nvim/assets/88273136/d098e2a6-6d19-414a-976c-bcd68a0b381a)

p.s.:the error

https://streamable.com/xckvd9

**Comment by mech-a** [comment]
StyLua styles Lua files, not JSX files. You need to configure a `jsx` language server.

**Comment by ryannewcomer** [comment]
I install prettiered in mason, but it still don't work

**Comment by feoh** [comment]
Hi there.

Sorry you're having trouble, but understanding how to configure language server protocol plugins doesn't constitute a bug in kickstart.nvim

Please consult the Github project for the language server plugin you're having trouble with, and they can offer you better ad more complete help than we can here.

Closing this for now and thanks for the report.
