### ISSUE TITLE
No Syntax highlighting after installing from mason

### ISSUE THREAD

**Issue by kazimir-malevich** [nvim-lua/kickstart.nvim#363]
## Describe the bug
I have installed the Kotlin language server through mason however I not receiving the treesitter syntax highling. The custom plugins is blank in the init.lua

## To Reproduce
Compiled neovim from source and added the Kickstart config file  Used mason to install anything with Kotlin in the string. 

## Desktop

- OS: WSL2 Ubuntu 
- Terminal: Microsoft terminal 

## Neovim Version
Cloned today and checked out stable 

```
```

**Comment by feoh** [comment]
Hi.

Not being able to get Kotlin syntax highlighting to function doesn't represent a bug in kickstart.nvim

I suggest reading the documentation of and filing issues with the Github repository of the language servers you installed. They can help you better and more completely than we can here.

Thanks for the report, but I'm closing this for now.
