### ISSUE TITLE
fidget.nvim will soon be rewritten

### ISSUE THREAD

**Issue by recallmenot** [nvim-lua/kickstart.nvim#365]
## Describe the bug
Launching nvim, I get the error `fidget.nvim will soon be rewritten. Please checkout the 'legacy' tag to avoid breaking changes` every time.

## To Reproduce
1. launch nvim

## Desktop
- OS: Manjaro
- Terminal: xfce4-terminal, bash

## Neovim Version
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/share/nvim"

```

**Comment by mech-a** [comment]
This is updated on master. Are you on a recent change of master?

**Comment by recallmenot** [comment]
I've now figured out that I had to update fidget through :Lazy
sorry for the inconvenience

**Comment by ljkenny** [comment]
![](https://i.imgur.com/wBmPZPI.png)

Still seeing this despite being on the legacy tag:

![](https://i.imgur.com/DLLXOyK.png)

![](https://i.imgur.com/5HARuBq.png)
