### ISSUE TITLE
init.lua:L467 "See `:help cmp`" is probably not correct

### ISSUE THREAD

**Issue by AloisMahdal** [nvim-lua/kickstart.nvim#368]
## Describe the bug

[The `:help` comment][hc] is misleading 

  [hc]: https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L467

```
-- [[ Configure nvim-cmp ]]
-- See `:help cmp`
local cmp = require 'cmp'
```

You probably want to point to nvim-cmp documentation, I don't know how to do that, though.

## To Reproduce

1. go to line 467 in init.lua
2. follow instructions
3. be confused

## Desktop

- OS: Debian
- Terminal: URxvt

## Neovim Version
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

**Comment by feoh** [comment]
I don't really understand cmp very well so I don't think I can help here.

I'd love to, and maybe someday I will have a weekend to dedicate to plumbing its depths :)

**Comment by mech-a** [comment]
Both aliases work. Try it :)
<img width="406" alt="image" src="https://github.com/nvim-lua/kickstart.nvim/assets/11798509/6adfed77-45ca-40d7-9928-48ab4d5af3f8">
I don't think we need to change it.

**Comment by feoh** [comment]
@mech-a Works for me! Thank you for as always being so helpful.

**Comment by feoh** [comment]
Closing this. :help cmp works like a charm. And I have some reading to do :)
