### ISSUE TITLE
init.lua complaining of missing imports

### ISSUE THREAD

**Issue by smiggiddy** [nvim-lua/kickstart.nvim#374]
## Describe the bug

text is highlighted stating missing fields import
## To Reproduce

1. cloned this repo and open up init.lua after the install

## Desktop

- OS: endeavouros
- Terminal: gnome-terminal

## Neovim Version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```
```
![image](https://github.com/nvim-lua/kickstart.nvim/assets/89040888/c18dad31-01f9-4f57-b8a5-70f9cf6108be)

**Comment by smiggiddy** [comment]
looks like the update to lua_ls is causing this. I'm trying to figure out how to fix it

**Comment by feoh** [comment]
Thanks very much for digging into this!

**Comment by feoh** [comment]
@smiggiddy Are you still seeing this issue if you pull down the latest code? I'm not seeing this at all on Mac.

I can try to repro on my Arch (Manjaro) desktop later.

**Comment by smiggiddy** [comment]
Looks like only a few lines contain the missing fields error now. 

![image](https://github.com/nvim-lua/kickstart.nvim/assets/89040888/af5c8a62-6f31-4cab-8aaa-d5354d322f98)

**Comment by feoh** [comment]
I'm not seeing any of that either.

Do you have some sort of extra hyperactive linting option turned on? :)

In any case, I think I'm going to close this issue. Whatever you're seeing clearly isn't functionality impairing and at a certain point running down linter warnings in dynamic languages like Lua or Python can get to be like chasing ghosts :)

Please feel free to re-open if you hard disagree and have a plan to get to resolution.

**Comment by giovannifiori** [comment]
@smiggiddy I don't know if you're still facing this issue but just to let you know: I was getting this same warning, then I checked Mason and my `lua-language-server` was outdated. I updated it and now (to 3.6.25) everything is fine here, the warning is gone
