### ISSUE TITLE
Telescope not found

### ISSUE THREAD

**Issue by akarev0** [nvim-lua/kickstart.nvim#377]
## Describe the bug

Tried to do my setup via `git clone` flow, but without any visual succes. 
```
Error detected while processing /home/rev0/.config/nvim/init.lua:
lazy.nvim requires Neovim >= 0.8.0
E5113: Error while calling lua chunk: /home/rev0/.config/nvim/init.lua:273: module 'telescope' not found:
        no field package.preload['telescope']
        no file './telescope.lua'
        no file '/usr/share/luajit-2.1.0-beta3/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope/init.lua'
        no file '/usr/share/lua/5.1/telescope.lua'
        no file '/usr/share/lua/5.1/telescope/init.lua'
        no file './telescope.so'
        no file '/usr/local/lib/lua/5.1/telescope.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/telescope.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/rev0/.config/nvim/init.lua:273: in main chunk
Press ENTER or type command to continue
```
The guide says:
```Run Neovim (from terminal or shortcut) and allow lazy.nvim to download files and set up the basics.```
but this second part actually never happens 

## To Reproduce

1. Follow throught ```Git Clone Installation``` flow

## Desktop

- OS: Ubuntu 22.04
- Terminal: zsh

## Neovim Version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org
```
```

**Comment by feoh** [comment]
Please type:

:Lazy install

and see if that resolves your problem.

Also if that works please put in a PR to improve the README so that would have been obvious to you immediately.

**Comment by akarev0** [comment]
@feoh sorry, I am don't have much experience, tried to type it after semi column but faced another issue
```Press ENTER or type command to continue```
pressed:
```Shift + :```
than typed:
```Lazy install```
received:
```E492: Not an editor command: Lazy install```

**Comment by feoh** [comment]
OK. Something is very wrong with your installation if it can't find the lazy.nvim plugin

Did you check the repository out in $HOME/.config on a UNIX-like system, or $HOME\AppData\Local on a Windows system?

**Comment by mech-a** [comment]
Please upgrade your Neovim version; you have 0.7.2 installed but lazy.nvim needs >=0.8.0, as stated in the error output.

**Comment by feoh** [comment]
Good catch I totally missed that detail! Thank you

**Comment by akarev0** [comment]
@feoh @mech-a 
No matter what I do, I cannot update, for ubuntu I can use only 0.7.2 version

```
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install neovim
```
doesn't update anything

**Comment by feoh** [comment]
Or build from source which is my preferred on Ubuntu, but I understand not everyone has `./configure && make && sudo make install` baked into their brain stem :)

**Comment by shihsyun** [comment]
@akarev0 
Try  [snap](https://snapcraft.io/install/nvim/ubuntu), and don't forget to remove the old nvim before.
