### ISSUE TITLE
whitespace after `set list` and `set listchars` commands displaying inconsistently

### ISSUE THREAD

**Issue by k98kurz** [nvim-lua/kickstart.nvim#378]
## Describe the bug

Sometimes the utf-8 char I specified for spaces appears as "·", other times as "\xb7". Note that this does not happen in normal vim with the same config, nor did it happen with neovim with this config prior to installing this repository.

![image](https://github.com/nvim-lua/kickstart.nvim/assets/4357561/b7668c08-3811-4f4d-951e-720216b6b020)

## To Reproduce

1. Install nvim v0.9.1 from the appimage.
2. Install this config from source using the `git clone` method.
3. Add `let &listchars = 'tab:-> ,space:\xb7'` and `set list` to a file somewhere, e.g. `~/.vimrc`.
4. Add `vim.cmd('source ~/.vimrc')` or whatever the file path was to `~/.config/nvim/init.lua`. (I have experimented with which line to put it on, and the behavior does not change.)
5. Open `~/.config/nvim/init.lua` with nvim and scroll down.

## Desktop

- OS: Ubuntu 22.04
- Terminal: GNOME Terminal version 3.44.0 for GNOME 42

## Neovim Version

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by k98kurz** [comment]
Addendum: manually typing in the commands `let &listchars = 'trail:\xa3,tab:-> ,space:\xb7'` and `set list` in neovim as configured by this repo also produces this inconsistent behavior.

**Comment by antoineco** [comment]
Can confirm:

![image](https://github.com/nvim-lua/kickstart.nvim/assets/3299086/81f00e17-e21d-4135-8eff-a2a036cf8b7f)

Here is the culprit: https://github.com/nvim-lua/kickstart.nvim/blob/3dc1c1c4c2ee3d6c5841ea1b3c13a7c123592086/init.lua#L156-L164

Please open an issue at https://github.com/lukas-reineke/indent-blankline.nvim

**Comment by antoineco** [comment]
It must have something to do with the way the escape is being interpreted. Everything works fine if I set the option as follows, with the literal character to use:

```lua
vim.opt.listchars:append("space:·")
```

![image](https://github.com/nvim-lua/kickstart.nvim/assets/3299086/dec3f0b4-0849-4400-8553-af95dcd0fb32)

**Comment by k98kurz** [comment]
The whole experience of trying to get any part of neovim working is just so frustrating. Whether it's plugins that don't play well together or conflicting configuration files (e.g. plugin managers that say to use `init.vim` when everything else requires using `init.lua`, and using `init.lua` causes `init.vim` to be ignored or to break the whole installation) or just incorrect documentation everywhere or a lack of proper documentation for necessary setup steps, this whole experience has been absolute shit. It makes no sense to have to become an expert in the internals of a code editor just to get a plugin or keymap or custom formatting character working.

**Comment by feoh** [comment]
@k98kurz I can appreciate that you are frustrated but please be constructive. Open source is a gift freely given by the authors so please be respectful.

**Comment by antoineco** [comment]
@k98kurz I can see how parts of what you're saying is true but, as somebody who did that Vim to Neovim journey after many years of Vimming:

- I remember very clearly having a fair share of frustrations with Vim too, trying to get plugins working together. This is universal. And I'm not even mentioning all the things which everyone uses but haven't been maintained for 5+ years.
- Sure you must decide between `init.vim` and `init.lua`, but once you grasp that your `init.lua` can contain vim commands (even full scripts if needed) via `vim.cmd [[ ... ]]`, it all becomes very smooth in my opinion. Vimscript and Lua are two different languages, and that's mostly for the better, but that come with a few quirks like the one you just ran into (and for which I shared a working and idiomatic solution).

**Comment by k98kurz** [comment]
@feoh Not trying to be a dick; just unsure why someone would publish something with incorrect documentation or functionality. In my experience, both writing good documentation and ensuring that code works properly are rewarding activities that are intrinsically motivated, so I find it difficult to empathize when both are lacking. Perhaps it is the inevitable result of the complexity of the system or overly fast development cycle or fragmentation in the community or something.

Is there a Q&A type place where noobs like me can get troubleshooting advice rather than opening issues in github repos? Or perhaps some sort of reliable place to find documentation? Part of the frustration has been a lack of reliable information -- I have found and tried many wrong things that were published by various people with complete confidence, and it gets old really fast. If effective communication is something that is just lacking in general in the neovim community, perhaps that could be remedied. (I could set up a simple site without too much effort if it is necessary.)

Also, I opened an issue with the other repo and got the following response from lukas-reineke:


> The plugin currently does not support hex values. But you can just use the unicode character as the value directly and it should work.
> [...]
> This has nothing to do with the config parser. indent-blankline just reads the values of `listchars` and uses them as is. Internally, when Neovim uses the values it converts hex to utf-8, but that function is not exposed, so I can't just use it. I would have to re implement it in lua. Which of course is possible, but I don't know if I will. There is an easy workaround by just using the utf-8 char directly, and you are the first person to ask for this.
> 
> I'd be happy to except a PR

So I guess I'm going to learn Lua and make a PR to fix it. :shrug:

**Comment by feoh** [comment]
Places to ask questions:
- Check out the [Neovim Discourse](https://neovim.discourse.group/)
- There's also the rather active [Matrix Room](https://app.element.io/#/room/#neovim:matrix.org)

As for accurate documentation - I'm with you. Breaking in can be very challenging. So use the resources above, get answers to your questions, and then channel that frustration into making improvements to the documentation so the next person won't have to suffer.

Also, is learning Lua such a bad thing? :) It's an amazing language and I love it.

**Comment by feoh** [comment]
In any case, sorry you're having such trouble, but I think we've taken this as far as we can here. Closing this issue for now. Please feel free to re-open if you have issues that pertain directly to kickstart.nvim
