### ISSUE TITLE
Missing vim.o.background 

### ISSUE THREAD

**Issue by gregh3269** [nvim-lua/kickstart.nvim#391]
I am just starting nvim, so sorry if this is not an issue.

Starting nvim/appimage the screen is white with no welcome message.  I use a white terminal background gnome.

If I look at ~/.local/share/nvim/lazy/onedark.nvim/lua/onedark/init.lua it uses vim.o.background to set its colours:

if vim.o.background == 'light' then
        M.set_options('style', 'light')
    elseif vim.g.onedark_config.style == 'light' then
        M.set_options('style', 'dark')
    end

The ~/.config/nvim/init.lua needs a 'dark' or 'light' setting

vim.o.background = 'dark'

to set a dark terminal as a default.  The welcome message then shows and its dark.

## To Reproduce

1. Start nvim

## Desktop

- OS: Debian 12
- Terminal: Gnome Version 3.46.8 for GNOME 43

## Neovim Version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

Cheers Greg

**Comment by craigmac** [comment]
The default setting for `:help 'background'` was changed by Neovim to 'dark' by default, it shouldn't be changed here in kickstart configuration for everyone, and leave the user to set that should they wish.

**Comment by gregh3269** [comment]
Thanks, I tried adding

set background=dark 

in my ~.vimrc, does not do anything in either nvim or vim (VIM - Vi IMproved   version 9.0.1499.)

:set background=dark in the terminal works, but does not save on exiting.

......Guess I will leave this and it will sort itself out as I get better with the config.  At lease vim.o.background = 'dark' works for now.

Cheers Greg

**Comment by antoineco** [comment]
`~/.virmrc` is not read my Neovim.
It was replaced with `init.lua`.

**Comment by gregh3269** [comment]
OK thanks.  Maybe have it in the init.lua but commented out? It took me a while to work out how to change the background to dark.  Having it commented would have saved some time.

**Comment by antoineco** [comment]
Following this logic, wouldn't we have to include **all** possible Vim options inside kickstart?
I would argue that a large majority of Neovim users does _not_ change the default background value ("dark"), because people using "light" are rather the exception.

**Comment by gregh3269** [comment]
For me the default for nvim was light.  This was on a new install of the os.
When I watched the getting started videos it seemed to be dark.  Maybe there is something different on gnome?

**Comment by gregh3269** [comment]
Testing this is on gnome terminal, if you have "colours from the system theme" and they are white, and want a dark nvim you need  vim.o.background = 'dark' in init.lua.  If you are using a built-in scheme/custom then you don't need it, as nvim will switch to dark.

I could swith to "green on black" built-in, reminds me of the 20 years I spent on as AS400 SEU.  Hmm.

**Comment by gregh3269** [comment]
checking, vim.o.termguicolors = true.

Using colours from system theme

![image](https://github.com/nvim-lua/kickstart.nvim/assets/3933367/3cecac43-5f05-4c81-a7f4-1539087247bc)

Using green on black built-in

![image](https://github.com/nvim-lua/kickstart.nvim/assets/3933367/39540c04-b667-497c-807a-ca8a2e844ad7)

3.46.8 for GNOME 43 maybe there have been some changes?  Guess this is one of those things.

Thanks

**Comment by antoineco** [comment]
I see you're setting this option at line 256, which is very far into the file. My guess is that you're setting it _after_ the color scheme has been applied. It should instead be set _before_. Try moving it before the plugins section.

**Comment by gregh3269** [comment]
This is the standard init.lua?  I will try to move it.

There have been changes in the 43 setting as there is only now default or dark

![image](https://github.com/nvim-lua/kickstart.nvim/assets/3933367/52d4b39b-1b3a-4daf-b67d-58ace41c52d9)

and the dark does not change the terminal.  I had a look in tweeks but could not see anything.

**Comment by gregh3269** [comment]
Moved it line #44, same white.

![image](https://github.com/nvim-lua/kickstart.nvim/assets/3933367/5ae0ca42-5fb2-46a2-a654-b491712613a6)

**Comment by antoineco** [comment]
Again, if you have `termguicolors` enabled and your terminal emulator supports it (recent versions of GNOME Terminal do) the light/dark switch in your OS should have no influence.

If you are seeing a light theme, it either means that

- Neovim was installed from an operating system package which ships with its own overrides (like a callback that automatically sets `vim.o.background`)
- You configured your colorscheme to use light mode

**Comment by gregh3269** [comment]
I am using the appimage from the kickstart gh.

What do you mean by "You configured your colorscheme to use light mode".

There is now only "style" Default/Dark see image above.    I can see thunderbird changes to dark, whilst the terminal ignores it and displays white.

43 maybe there are breaking changes, in the terminal ie ignoring the Setting | Appearance | Style.  Possibly you have to use profiles now? :

![image](https://github.com/nvim-lua/kickstart.nvim/assets/3933367/323773d8-bc7c-415a-bf17-1411c24e1080)

At least I have learnt something on the config of nvim, they say its a painful journey. :-)

**Comment by antoineco** [comment]
I'm talking about the Neovim colorscheme, not your terminal's colorscheme.

With `termguicolors` enabled, your Neovim colorscheme doesn't depend on your terminal's colorscheme. If it does, something external is messing with your Neovim configuration.

**Comment by gregh3269** [comment]
I am using the default kickstart init.lua (as I have no idea on how to get started).  Would prefer to run this rather than my own until I get better undersatnding.

Maybe it is the shell?  Although the gh page does not recommend one to use.

**Comment by antoineco** [comment]
The only explanation I can think of is that you're actually using the *Vim* program installed on your system, not Neovim.

The screenshots you shared do not look like the One Dark colorscheme to me, so I can only imagine that you're not running what you think you're running.

Could you please share the output of the following commands?

```vim
:version
```
```vim
:echo $VIMRUNTIME
```

**Comment by gregh3269** [comment]
Possibly this is more an issue upstream with the onedark and 43 changes, maybe a bug in the shell where it does not honour the system colour scheme.  Nvim seems to work great.  

#####

It is definately nvim

:version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

:echo $VIMRUNTIME
![image](https://github.com/nvim-lua/kickstart.nvim/assets/3933367/c63cfb37-0550-4800-a685-cf6977de2ec7)

head ~/.config/nvim/init.lua

--[[

=====================================================================
==================== READ THIS BEFORE CONTINUING ====================
=====================================================================

Kickstart.nvim is *not* a distribution.

Kickstart.nvim is a template for your own configuration.
  The goal is that you can read every line of code, top-to-bottom, understand

Thanks for your help!
