### ISSUE TITLE
Update readme with a list of what's included

### ISSUE THREAD

**Issue by AmrSaber** [nvim-lua/kickstart.nvim#393]
Can you update the readme with a list of the included extensions and features and maybe links to those extensions?

I know that a lot is backed up with this simple simple setup of yours, but there are a lot of useful features and mappings that I don't even know about unless I go through the configuration and try to figure everything out. Can you help make this simpler?

**Comment by feoh** [comment]
Hi there!

I can appreciate where you're coming from with this, but the *entire point* of the kickstart.nvim project is to provide you a launch pad from which to start your Neovim learning journey.

I have two serious concerns about this request:

- Reading the code and understanding it so you can modify it yourself and continue the journey on your own is the entire point.
- The README would need to be kept up to date with each new plugin added, that's work that either we the maintainers need to do directly, or we win the un-enviable task of having to gently flail every single contributor into doing it.

I know it's a lot. I can appreciate that it feels overwhelming. You don't need to read every single line. In fact, you can start learning what kickstart.nvim brings to the table by typing :Telescope keymaps from within Nvim. That will give you a nicely self documented list of potential keystrokes.

Please don't hesitate to ask for specific help, and thanks for the report, but I'm closing this for the above cited reasons.
