### ISSUE TITLE
populating matches to quickfix menus

### ISSUE THREAD

**Issue by gregorywaynepower** [nvim-lua/kickstart.nvim#394]
Hello Y'all,

I am trying to see if this is a feature of LSPs or not: being able to add matches found in a buffer via the / key can be added to the quickfix menu?

I'm expecting the following workflow:

1. `/{string}` to search for match `<CR>`
2. `:copen` to open the quickfix list

I've done some research and I've seen [`vim-qf`](https://github.com/romainl/vim-qf#readme) and [`vim-grepper`](https://github.com/mhinz/vim-grepper#readme).

**Comment by feoh** [comment]
Hi. Please file an issue against whichever LSP you want or against Neovim itself. This repo is ONLY for the kickstart.nvim project and we can't be a support hub for the entire Neovim ecosystem.

Thanks for the report. Closing for now.
