### ISSUE TITLE
Error detected while creating processing init.lua

### ISSUE THREAD

**Issue by neeswebservices** [nvim-lua/kickstart.nvim#403]
E5112: Error while creating lua chunk: /home/nees/.config/nvim/init.lua:127: ')' expected near 'prev_hunk'

**Comment by feoh** [comment]
Please follow the instructions in https://github.com/nvim-lua/kickstart.nvim#readme to the letter.

Take special note of the fact that you can't just copy init.lua in, you need to clone the entire repository.

Also please include your Neovim version and platform when submitting bug reports as per the bug report template.
