### ISSUE TITLE
Pattern to Add Configuration To Kickstart Plugin

### ISSUE THREAD

**Issue by jrock2004** [nvim-lua/kickstart.nvim#407]
This is not a bug but would love to get an understanding of best way to add configuration to plugins that kickstarter sets up for. For example, I want to add support in telescope when finding files to look at hidden ones. So I know how to do that but would I `init.lua` where the telescope section is or would add a `telescope.lua` file under `Lua/custom/plugins/telescope.lua` and copy what `init.lua` has? Or would I just go into `init.lua` and add additional config there?

**Comment by jrock2004** [comment]
I guess the idea is I would never pull from this again so I am just going to do what I think is best and just close this

**Comment by bbaldino** [comment]
I actually just ran into this same problem: I wanted to tweak the configuration of some telescope settings that are set in `init.lua`, but I'm trying my best to not touch init.lua so I can continue to update easily.  Is there any recommended way to do this?

**Comment by bbaldino** [comment]
Ah, I just saw [this comment](https://github.com/nvim-lua/kickstart.nvim/issues/300#issuecomment-1556395314) and it sounds like this is intentionally "by design", so guess I'll just need to suck it up and deal with conflicts in init.lua when upgrading.

**Comment by feoh** [comment]
@bbaldino Hiya! I feel your pain. Here's how I made it go MUCH easier.

1) Create a fork on Github. Make your changes in that fork.
2) Use `git merge` from upstream. I know everyone says use rebase, and you SHOULD for cases where you'll want to push changes back up, but for maintaining a private fork like this git merge is just fine and then you ONLY need to resolve conflicts where something *actually* conflicts with your changes.

**Comment by bbaldino** [comment]
Hey @feoh, thanks for the reply!  I've read about that technique, but I already have a "dotfiles" repo which contains my nvim configs as well as some other config which is why I haven't done the fork before.  I thought about using a git submodule for the kickstart.nvim fork within that, but haven't gotten around to actually trying it out.

**Comment by feoh** [comment]
Hey I had this problem too! :)

Use submodules. That way you can keep your Neovim dotfiles in their own forked repo.

Check out https://github.com/feoh/git_dotfiles and take note of the .gitmodules at the root and the .config/nvim submodule directory.

The 'git submodule' command is a smidge tricky to get your head around in terms of setup, but once you have it up and running the only thing you need to remember is treat the submodule as read-only and make changes in a separate checked out copy of your fork.

Then just run `git submodule update --remote` and Bob's your uncle :)

**Comment by bbaldino** [comment]
Ah, beautiful...an example of the same use case is probably enough to combat my laziness :) Thanks!

**Comment by jrock2004** [comment]
For anyone coming to look at this, because kickstarter is using lazy, in the custom folder when you add your plugin, you can just add what you want to change and it will merge whats in kickstarter init to your custom code. Example

```lua
local actions = require 'telescope.actions'

return {
  'nvim-telescope/telescope.nvim',
  dependencies = {
    { 'nvim-tree/nvim-web-devicons' }
  },
  config = function()
    require('telescope').setup {
      pickers = {
        live_grep = {
          theme = 'dropdown',
        },

        grep_string = {
          theme = 'dropdown',
        },

        find_files = {
          theme = 'dropdown',
          file_ignore_patterns = { "node_modules", ".git" },
          hidden = true,
          previewer = false,
        },

        buffers = {
          theme = 'dropdown',
          previewer = false,
          initial_mode = 'normal',
          mappings = {
            i = {
              ['<C-d>'] = actions.delete_buffer,
            },
            n = {
              ['dd'] = actions.delete_buffer,
            },
          },
        },

        planets = {
          show_pluto = true,
          show_moon = true,
        },

        colorscheme = {
          enable_preview = true,
        },

        lsp_references = {
          theme = 'dropdown',
          initial_mode = 'normal',
        },

        lsp_definitions = {
          theme = 'dropdown',
          initial_mode = 'normal',
        },

        lsp_declarations = {
          theme = 'dropdown',
          initial_mode = 'normal',
        },

        lsp_implementations = {
          theme = 'dropdown',
          initial_mode = 'normal',
        },
      },
      extensions = {
        ['ui-select'] = {
          require('telescope.themes').get_dropdown(),
        },
      },
    }

    -- Enable telescope extensions, if they are installed
    pcall(require('telescope').load_extension, 'fzf')
    pcall(require('telescope').load_extension, 'ui-select')

    -- See `:help telescope.builtin`
    local builtin = require 'telescope.builtin'
    vim.keymap.set('n', '<leader>sh', builtin.help_tags, { desc = '[S]earch [H]elp' })
    vim.keymap.set('n', '<leader>sk', builtin.keymaps, { desc = '[S]earch [K]eymaps' })
    vim.keymap.set('n', '<leader>sf', builtin.find_files, { desc = '[S]earch [F]iles' })
    vim.keymap.set('n', '<leader>ss', builtin.builtin, { desc = '[S]earch [S]elect Telescope' })
    vim.keymap.set('n', '<leader>sw', builtin.grep_string, { desc = '[S]earch current [W]ord' })
    vim.keymap.set('n', '<leader>sg', builtin.live_grep, { desc = '[S]earch by [G]rep' })
    vim.keymap.set('n', '<leader>sd', builtin.diagnostics, { desc = '[S]earch [D]iagnostics' })
    vim.keymap.set('n', '<leader>sr', builtin.resume, { desc = '[S]earch [R]esume' })
    vim.keymap.set('n', '<leader>s.', builtin.oldfiles, { desc = '[S]earch Recent Files ("." for repeat)' })
    vim.keymap.set('n', '<leader><leader>', builtin.buffers, { desc = '[ ] Find existing buffers' })

    -- Slightly advanced example of overriding default behavior and theme
    vim.keymap.set('n', '<leader>/', function()
      -- You can pass additional configuration to telescope to change theme, layout, etc.
      builtin.current_buffer_fuzzy_find(require('telescope.themes').get_dropdown {
        winblend = 10,
        previewer = false,
      })
    end, { desc = '[/] Fuzzily search in current buffer' })

    -- Also possible to pass additional configuration options.
    --  See `:help telescope.builtin.live_grep()` for information about particular keys
    vim.keymap.set('n', '<leader>s/', function()
      builtin.live_grep {
        grep_open_files = true,
        prompt_title = 'Live Grep in Open Files',
      }
    end, { desc = '[S]earch [/] in Open Files' })

    -- Shortcut for searching your neovim configuration files
    vim.keymap.set('n', '<leader>sn', function()
      builtin.find_files { cwd = vim.fn.stdpath 'config' }
    end, { desc = '[S]earch [N]eovim files' })
  end,
}
```
