### ISSUE TITLE
Cannot change onedark style

### ISSUE THREAD

**Issue by kamransoomro84** [nvim-lua/kickstart.nvim#408]
## Describe the bug
I am trying to change the style of the onedark theme being used. For example, to "light" instead of "dark".

## To Reproduce
In the `lazy` setup, add the following line under line 139:
```lua
     vim.g.onedark_config = { style = 'light' }
```
      
## Desktop

- OS: Mac OS 12.6.8
- Terminal:  iTerm2 3.4.20

## Neovim Version

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by feoh** [comment]
hi, please consider reporting this on the project repository. Your issue is with the theme itself not kickstart.

https://github.com/navarasu/onedark.nvim

**Comment by feoh** [comment]
thank you for the clarification, but I understood the question. The problem is that I was unable to do this myself as I tried to figure it out and by referring you to the actual repo of the project that you're trying to change I'm hoping you'll be able to have better luck.

**Comment by kamransoomro84** [comment]
For completion, just wanted to say that I figured out the problem. If you set the style before loading the colorscheme it works. My guess is that nvim reads the configuration only once the colorscheme is loaded.
