### ISSUE TITLE
Which plugin does this?

### ISSUE THREAD

**Issue by kamransoomro84** [nvim-lua/kickstart.nvim#409]
There is thie very cool feature where if nvim is expecting a motion input, it shows you a popup with the possible options:

<img width="1247" alt="CleanShot 2023-08-27 at 03 11 30@2x" src="https://github.com/nvim-lua/kickstart.nvim/assets/4132530/2542e14f-cd29-4f6f-abab-3cfa85d74d87">

I wanted to know which plugin does this? I couldn't figure it out from the config.

**Comment by antoineco** [comment]
This one

https://github.com/nvim-lua/kickstart.nvim/blob/01a1ebed38c5ef28cfe1409f8589bce60b7b727b/init.lua#L112-L113

**Comment by feoh** [comment]
thanks for the pointer  @antoineco !

Closing.

**Comment by kamransoomro84** [comment]
> This one
> 
> 
> 
> https://github.com/nvim-lua/kickstart.nvim/blob/01a1ebed38c5ef28cfe1409f8589bce60b7b727b/init.lua#L112-L113

Thank you!
