### ISSUE TITLE
I get white and cyan text on a blue background!

### ISSUE THREAD

**Issue by pauljvallance** [nvim-lua/kickstart.nvim#412]
Yikes!... My Neovim was installed using Homebrew on MacOS 12 (Monterey). The  init.lua files says 'onedark' theme. Am  a noob to this but even I can tell the Onedark theme isn't working. Am sure everything else is fine but can't actually read the text in any docs!

**Comment by Numkil** [comment]
Have you made sure your terminal supports 
vim.o.termguicolors?

I would recommend using iTerm2 on macos

**Comment by feoh** [comment]
Hi!

What happens when you type :version inside Neovim?

Also, did you clone the entire kickstart.nvim Github repository and not just copy over init.lua?

**Comment by feoh** [comment]
No response in  1 week. This is not a widely experienced issue and cannot reproduce so closing for now.

**Comment by hjw** [comment]
I had the same experience. 
I was using the standard mac terminal, not iterm2. Things were unreadable.
It would be sensible to add the requirement for iterm2 or info about gui colors.

**Comment by feoh** [comment]
Please bear in mind that we cannot boil the ocean.

We cannot as a part of this project provide detailed documentation on every aspect of Neovim. That is for the Neovim project itself to do.

I don't mean to come off as un-empathetic. I know how frustrating getting going can be, but this is not the right place for this question as I mentioned many many comments back :) Please consult the main Neovim website or the website for the onedark theme.
