### ISSUE TITLE
missing dependencies to telescope work fine

### ISSUE THREAD

**Issue by itelo** [nvim-lua/kickstart.nvim#416]
## Describe the bug
It's my first week on nvim world, and I lost a lot of time trying to understand why the telescope didn't work immediately. The issue was simple: the telescope was not respecting my `.gitignore` file, and I found a solution in this Reddit's [post](https://www.reddit.com/r/neovim/comments/uxwwbw/telescope_does_not_respect_gitignore/). My problem was that I'm so new to nvim that I assumed it was working as expected in a terrible way. New users of nvim could benefit from some upfront instructions on how to use Telescope effectively, so they don't have to go through the same frustrating experience as I did!
Something like: Make sure your telescope installation is correct by running `:checkhealth telescope`

## To Reproduce
Follow the installation guide on a fresh MacBook

## Desktop
- OS: mac
- Terminal: iterm2

## Neovim Version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by feoh** [comment]
Hi. Please file this issue against the telescope repository if you're still having trouble as I'm pretty sure this is carefully covered in their documentation.

Closing this for now.
