### ISSUE TITLE
syntax highlighting doesn't work for .phtml

### ISSUE THREAD

**Issue by rpolasek-sde** [nvim-lua/kickstart.nvim#421]
## Describe the bug
when i open a .phtml file some part of the content is not syntax highlighted (please see enclosed screeshots).

work-around: when i set the file type manually using command `:set ft=phtml` the syntax highlighting is immediately fixed.

## Desktop

- OS: Ubuntu 22.04.3 LTS
- Terminal: GNOME Terminal Version 3.44.0 for GNOME 42

## Neovim Version
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
```
![Screenshot from 2023-09-07 17-23-31](https://github.com/nvim-lua/kickstart.nvim/assets/43035173/bf1db6ec-d9d5-412c-99d6-7846fa641c44)
![Screenshot from 2023-09-07 17-23-43](https://github.com/nvim-lua/kickstart.nvim/assets/43035173/31f9e377-86cf-4aab-b4b6-a45416416c45)

**Comment by feoh** [comment]
Hi

Thanks for the report, but this project cannot support the entirety of the Neovim ecosystem.

Please file a bug with the repository for your language server or syntax highlighting plugin.

Alternatively, seek more general help using the resources outlined in [The Neovim Community page](https://neovim.io/community/)

Closing this.
