### ISSUE TITLE
How to use Unicode symbols without Meslo or Nerd Font

### ISSUE THREAD

**Issue by ekungurov** [nvim-lua/kickstart.nvim#426]
## Describe the bug
The Lazy.nvim has the following statement in docs: "If you don't want to use a Nerd Font, you can replace the icons with Unicode symbols" (code snippet):
https://github.com/folke/lazy.nvim
I can't figure out how to adopt it and use it inside kickstart init.lua. Could you help me, please

## To Reproduce
1. Paste ui.icons code snippet into init.lua file
2. Restart nvim and open Lazy ui

## Desktop
- OS: MacOS
- Terminal: iTerm2 with Monaco font selected

## Neovim Version
NVIM v0.9.2
Built type: Release
LuaJIT 2.1.0-beta3

**Comment by feoh** [comment]
I have no experiece with this use case, and since you're reporting an issue with Lazy.nvim please report this bug in their repo.

Thanks!
