### ISSUE TITLE
Add the diagnostic popup tool (similar to LazyVim) as optional in comments

### ISSUE THREAD

**Issue by sparrowsl** [nvim-lua/kickstart.nvim#432]
I have tested the LazyVim distro and I want to return back to customizing my own, I miss the diagnostic popup.
PS: extremely new to neovim.

**Comment by feoh** [comment]
I'm sorry but I don't understand what this means. I don't use LazyVim.

You'll need to at least do a bit of research to describe what you want more fully, or perhaps some screenshots?

**Comment by sparrowsl** [comment]
![Screenshot from 2023-09-28 07-04-41](https://github.com/nvim-lua/kickstart.nvim/assets/61359802/a9c967b3-2161-44be-8d36-44af5efc7131)

Top right corner of the image.

**Comment by feoh** [comment]
OK thanks. I have no idea how to accomplish this. Community? Help? Please? :)

**Comment by Danielkonge** [comment]
That is noice: https://github.com/folke/noice.nvim

My setup for noice is here:
https://github.com/Danielkonge/dotfiles/blob/84ea540fab0b3462787982f00613e95ecf02033c/nvim/lua/daniel/init.lua#L320C1-L334C5
and
https://github.com/Danielkonge/dotfiles/blob/main/nvim/after/plugin/noice.lua

But some of the stuff from the second file should probably be moved into the init.lua for kickstart. 

You can also use noice in lualine:
https://github.com/Danielkonge/dotfiles/blob/84ea540fab0b3462787982f00613e95ecf02033c/nvim/after/plugin/lualine.lua#L32C2-L53C11

But some of this should probably be removed for kickstart and just add a simple setup. (Note that noice is still listed as experimental, but it has been mostly stable for me for a long time now. Though it has failed weirdly when other stuff in my config fails, though as soon as fixed the other stuff I never had a problem with it.)

**Comment by feoh** [comment]
Hi.

Thanks so much @Danielkonge for posting this.

If you feel strongly that some aspect of this should be added, please generate a PR and we'll evaluate that in its own right. For now hopefully @sparrowsl has what they need.

Closing this for now but feel free to re-open of you have more to add, or better, generate a PR like I said and we can continue the discussion there :)

Thanks everyone!
