### ISSUE TITLE
lazy-lock.json is gitignored

### ISSUE THREAD

**Issue by Anthony-Fiddes** [nvim-lua/kickstart.nvim#433]
## Describe the bug

Hi all! 

I was wondering why the `lazy-lock.json` file is gitignore'd? I think it makes sense in the context of developing this template repo for it to be ignored, but maybe we could add some explanation for the decision somewhere (could be in the intro text in init.lua, .gitignore, the vim docs or the README?) that encourages folks to learn more and decide whether they want to remove that gitignore line or not.

Could be something like:

> lazy.nvim uses a lockfile called `lazy-lock.json` that records the version of every plugin installed. You can use this lockfile to ensure that all of your plugins use the versions that you expect when using your neovim configuration on a different computer. To use this feature, just remove the line `lazy-lock.json` from `.gitignore`. We just add that line to make our development of kickstart.nvim easier, since there's no need for us to check in plugin versions when the repo is meant to be forked and customized.

lazy.nvim documentation saying it should be checked into VCS for reference: https://github.com/folke/lazy.nvim#-lockfile-lazy-lockjson

Please let me know what you think.

## To Reproduce
N/A

## Desktop
- OS: pop_os!
- Terminal: Kitty

## Neovim Version

```
:version                                                                                                                                           
NVIM v0.9.1                                                                                                                                        
Build type: Release                                                                                                                                
LuaJIT 2.1.0-beta3 
```

**Comment by feoh** [comment]
Looks like @tjdevries made [this change](https://github.com/nvim-lua/kickstart.nvim/commit/3526fbeec9299dad5f7b14894765c34c83cf8324) as part of the migration to lazy.nvim

I don't really understand what this file does so I can't know the motivation behind adding it, or whether adding documentation around it makes sense.

Maybe other folks know more?

**Comment by feoh** [comment]
OK. I did a bit of digging. I agree this lock file shouldn't be in gitignore. Please file a pull request to remove it and I'll merge it post haste. :)

**Comment by Anthony-Fiddes** [comment]
Thanks feoh! :D

**Comment by feoh** [comment]
Pleasure!

**Comment by pnmcosta** [comment]
Hi! 

Recent nvim user using this kickstart, I now have this file always untracked on my fork's clone. Should I commit this file with to my fork repo?

I expect to be only me using it, but I may use it on other machines.

Many thanks for any feedback.

**Comment by Anthony-Fiddes** [comment]
You should commit it! If you use neovim on another machine, it just means that all the versions of your plugins will determined by the lock file (so they'll be the ones you were using when you last committed the file).

**Comment by pnmcosta** [comment]
Brilliant, thank you for confirming.
