### ISSUE TITLE
Exhaustive list of <leader key> shortcuts

### ISSUE THREAD

**Issue by ntn888** [nvim-lua/kickstart.nvim#434]
I've seen many lists of leader key shortcuts around the web. But none seem to correlate to the default bindings used in kickstart.nvim. Is there a list of these shortcuts?

**Comment by feoh** [comment]
Hi.  Please use Neovim's built in self documenting help facilities to get a list of keymaps.

This request is FAR beyond the intended scope of this project. 

Closing for now.
