### ISSUE TITLE
require('nvim-treesitter.configs').setup adds 185ms to startup time when loading C++ file

### ISSUE THREAD

**Issue by AshrafMichail23** [nvim-lua/kickstart.nvim#435]
## Describe the bug
Wrapping the require('nvim-treesitter.configs').setup block in a vim.defer_fn(function()...end, 0) saves 185ms of startup time when I load a C++ file through the command-line with: nvim test.cc.

**Default init.lua:**
302.407  000.007: --- NVIM STARTED ---

**Adding vim.defer_fn around require('nvim-treesitter.configs').setup block:**
115.798  000.005: --- NVIM STARTED ---

The 185ms startup delay does not occur when loading a simple .txt file or .lua file.

## To Reproduce

1. Run nvim test.cc --startuptime default.log
2. Wrap the require('nvim-treesitter.configs').setup block in a vim.defer_fn(function()...end, 0)
3. Run nvim test.cc --startuptime defer_treesitter_setup.log

Notice the time delta to NVIM STARTED in logs.

## Desktop

- VM OS: Ubuntu 22.04.3 LTS
- Terminal:  Windows Terminal

## Neovim Version

v0.9.2

**Comment by feoh** [comment]
Can you please validate that this change would not affect other people using other LSPs?

I'm all for faster startup, but we have many users here with many MANY different use cases.

**Comment by feoh** [comment]
Also, if the answer to the above is an emphatic no, it won't break anyone else, please feel free to file a pull request. I don't understand enough about treesitter config to feel confident writing that code.

**Comment by arnold-lei** [comment]
I can take a stab at it, I think we can just add the default values to the setup 
https://github.com/nvim-treesitter/nvim-treesitter/blob/b5873bacb4ce44e0aac313abb28bb72e67fc9a53/lua/nvim-treesitter/configs.lua#L22C3-L26C28

I am still digging into the cmp issue

**Comment by AshrafMichail23** [comment]
I'll test a few LSP's and if all goes well, submit a PR this weekend.  

I think this change is quite safe, but more LSP testing never hurts.

**Comment by AshrafMichail23** [comment]
@feoh, I submitted a draft PR with this change for others to try:
https://github.com/nvim-lua/kickstart.nvim/pull/448

Note that this PR does change the visual experience:
Before: slower startup + treesitter colors available first frame
After: faster startup + treesitter colors come in after first frame

Personally, I believe the experience with the change is quite a lot better.  But others can try the PR and see what they like the best.

**Comment by feoh** [comment]
I don't honestly know that I'll be able to tell the difference. I'm partially blind so Neovim just POPS in my experience, I dunno whether a microsecond level change will even be something I can see!

I'll lean on others to test and express opinions on this one. Thank you @AshrafMichail23 !

**Comment by AshrafMichail23** [comment]
@feoh, you could measure the difference with --startuptime.  Would love to hear feedback from everyone.

For me, the 200ms difference is the difference between feels fast and feels slow.
