### ISSUE TITLE
E5112: Error while creating lua chunk

### ISSUE THREAD

**Issue by Carlosktdev** [nvim-lua/kickstart.nvim#437]
## Describe the bug
Hey thanks for the hard work!! i'm trying nvim for the first time, i copied init.lua content as your team explained in the youtube video, and after restarting nvim this is the message:
Error detected while processing /home/carlos/.config/nvim/init.lua:
E5112: Error while creating lua chunk: /home/carlos/.config/nvim/init.lua:127: ')' expected near 'preview_hunk'
Press ENTER or type command to continue

I'm sorry if is something dumb, i'm pretty new to all this.

## To Reproduce

1. Just starting nvim after copying init.lua from this repo to my .config/nvim/init.lua

## Desktop

- OS: linux mint 21.2 cinnamon
- Terminal:  the one that comes with the os.

## Neovim Version

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

```
```

**Comment by AshrafMichail23** [comment]
It looks like your nvim version is old which happens if you installed with a package manager.

Documentation says kickstart only supports stable and nightly builds.

I suggest following the neovim build from source install instructions and doing a ‘git checkout stable’ before you build.

**Comment by feoh** [comment]
Closing for now. Old Neovim version. We should really add 256 color terminal and version checks to init.lua, I'll work on that.

**Comment by feoh** [comment]
Closing for now. Old Neovim version. We should really add 256 color terminal and version checks to init.lua, I'll work on that.
