### ISSUE TITLE
packer.nvim installer hangs at installing nvim-telescope\telescope-fzf-native.nvim

### ISSUE THREAD

**Issue by kodecraft** [nvim-lua/kickstart.nvim#44]
Strange, I always get stuck at installing nvim-telescope\telescope-fzf-native.nvim. The rest are installed by packer.nvim though. I am using windows and using nvim v0.8.1 btw if anyone has any ideas how to resolve? tks!

I later installed the latest nightly NVIM v0.9.0-dev-519+g2d8bbe468 and still seeing the issue.

**Comment by kazenix** [comment]
I was running into a similar issue the other day, ultimately the problem was that I didn't have the required build tools for telescope-fzf-native. Check that you've got CMake, and the Microsoft C++ Build Tools installed.

**Comment by tjdevries** [comment]
Oh, that's good to know. Is there an easy way to check if that's installed on windows @kazenix ? I will add a check to not try and install it if it's missing

**Comment by kodecraft** [comment]
tks Kazenix, TJ. I have installed Microsoft C++ Build Tools (that includes CMake) but still not helping me. Wondering if there is some log that can tell me what's missing so I can try fixing? I checked the nvim log and found the following:

```
ERR 2022-12-18T10:55:11.679 nvim.22744.0 terminfo_start:361: uv_tty_set_mode failed: invalid argument
```

not sure if it is then related to https://github.com/neovim/neovim/issues/21445 ?

configuring max_jobs >= 10 also did nothing for me too.

**Comment by kazenix** [comment]
@tjdevries Specifically when I ran into that, it was on my macbook (wasn't installing via kickstart as i hadn't seen the video yet, just followed the docs for telescope-fzf-native.). I'll do some research and see if I can find some checks for that in windows though. I've got my gaming desktop, and would love to have it set up for minor dev stuff too. 

It looks like there's a slightly different run command for windows/cmake. @kodecraft have you tried switching out that run command? from the telescope-fzf-native docs `use {'nvim-telescope/telescope-fzf-native.nvim', run = 'cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build' }`

**Comment by kodecraft** [comment]
Tks for the pointer - that worked! Changing the "run command" to using either the cmake or make windows variant worked for me.

**Comment by kazenix** [comment]
@tjdevries In doing some poking around this morning, it looks like using `vim.fn.executable("cmake")` does work for testing if cmake is present on the system, at least in powershell and neovide. I'm having lua issues with WSL that are preventing my config from working there, so I haven't been able to test that (likely down to it being nvim v0.7.2, but not sure yet).

Seeing as the goal here seems to be adding a simple boostrap anyone can pick apart and understand, adding OS type checks as well as executable checks seems a bit overkill. Perhaps just some documentation of the edge case for Windows would suffice?

**Comment by tjdevries** [comment]
Yeah, that would be useful to include @kazenix if you have some more information that can be easily added (or maybe a windows section in the readme) that's fine w/ me. I can work with you on a PR if you submit one
