### ISSUE TITLE
Missing required fields for Treesitter and CMP

### ISSUE THREAD

**Issue by arnold-lei** [nvim-lua/kickstart.nvim#441]
## Describe the bug

I am getting configuration errors with my init.lua file, it may be a breaking change related to treesitter and nvim-cmp? 

<img width="1298" alt="Screenshot 2023-09-26 at 3 09 22 PM" src="https://github.com/nvim-lua/kickstart.nvim/assets/4966358/f313ca3c-4747-41cc-aa62-b005d4edb3fc">
<img width="1303" alt="Screenshot 2023-09-26 at 3 09 04 PM" src="https://github.com/nvim-lua/kickstart.nvim/assets/4966358/43655876-d6e9-4127-b980-a6b22d1944bd">

## To Reproduce

1. Do a fresh install of kickstart nvim 
2. Open the init.lua file
3. See there are errors on treesitter.config and cmp.setup

## Desktop

- OS:  MacOs Ventura 13.5.2
- Terminal: iTerm2

## Neovim Version

```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.2/share/nvim"
```

**Comment by feoh** [comment]
Hi. What functional problem is this actually causing?

Have you checked the TreeSitter repository?

Do you understand what these advisory 'errors' are telling us?

What do you want to have happen? if your answer is "No errors" then please submit a pull request to fix them, or help us understand them enough for us to fix them?

**Comment by arnold-lei** [comment]
I can take a stab at it, I think we can just add the default values to the setup 
https://github.com/nvim-treesitter/nvim-treesitter/blob/b5873bacb4ce44e0aac313abb28bb72e67fc9a53/lua/nvim-treesitter/configs.lua#L22C3-L26C28

I am still digging into the cmp issue

**Comment by feoh** [comment]
OK. Since this needs to be fixed in the treesitter repo I'm closing this issue here.

**Comment by haloboy777** [comment]
@arnold-lei  Any update on this? I'm also facing this issue and new to the whole vim/neovim land.

**Comment by feoh** [comment]
@haloboy777 Please use the treesitter repo where this was addressed rather than asking here. Thanks!
