### ISSUE TITLE
You are trying to call the setup function of Indent-blankline version 2 but you have version 3 installed

### ISSUE THREAD

**Issue by AaryanTrivedi** [nvim-lua/kickstart.nvim#444]
## Describe the bug
The message "You are trying to call the setup function of Indent-blankline version 2 but you have version 3 installed" appears after adding the init file.

## To Reproduce

1. Install Nvim
2. Add init file in nvim folder
3. open Nvim

## Desktop

- OS: Ubuntu(WSL)
- Terminal: 

## Neovim Version

v0.9.2
```
```
![Screenshot 2023-09-28 180257](https://github.com/nvim-lua/kickstart.nvim/assets/34876037/30f1a0dc-3476-4246-a3ab-e029c79df129)

**Comment by benjaminbauer** [comment]
see also https://github.com/nvim-lua/kickstart.nvim/pull/443

Probably better to make it work with V3 than to pin in to V2
