### ISSUE TITLE
I think this path is incorrect 

### ISSUE THREAD

**Issue by danielo515** [nvim-lua/kickstart.nvim#46]
https://github.com/nvim-lua/kickstart.nvim/blob/760823f1e3cda01d9b8a7c52c7a7e2db63285d5b/init.lua#L60

Shouldn't it start with ".config/"?

**Comment by tjdevries** [comment]
ah, yes, you're right. Thanks

**Comment by danielo515** [comment]
> ah, yes, you're right. Thanks

Thanks to you!
