### ISSUE TITLE
Re-sourcing config file in running neovim session with lazy.nvim causes error

### ISSUE THREAD

**Issue by pengguanya** [nvim-lua/kickstart.nvim#464]
## Describe the bug
Got error `Re-sourcing your config is not supported with lazy.nvim`, when trying to source the config file in a running session of neovim. Re-source-in-session is a useful feature, since we sometimes need to update the config and see the effect without existing neovim. This error prevents this useful feature.

The reason I think is that at __line 67__ of the `init.lua` (latest version of `kickstart.nvim`), `require('lazy').setup` is called explicitly. Thus when we start neovim, it is called once and when we resource the config, it is called once again and lazy.nvim does not allow this according to: [https://github.com/folke/lazy.nvim/issues/140#issuecomment-1364314901](https://github.com/folke/lazy.nvim/issues/140#issuecomment-1364314901)

Maybe consider the utility function as following (not tested). It might not be a good solution, since the function modifies a global variable inside its scope, but it might work for this issue.
```
function lazy.setup(plugins)
  if vim.g.plugins_ready then
    return
  end

  lazy.install(lazy.path)

  vim.opt.rtp:prepend(lazy.path)

  require('lazy').setup(plugins, lazy.opts)
  vim.g.plugins_ready = true
end
```

## To Reproduce

1. Open nvim with latest version of `kickstart.nvim`
2. In command mode, type `:source $MYVIMRC` or `:source <path of init.lua>`
3. Error message `Re-sourcing your config is not supported with lazy.nvim` appears and fail to resource.

## Desktop

- OS: Ubuntu 22.04
- Terminal: gnome-terminal

## Neovim Version

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by jtams** [comment]
Not being able to re-source with lazy.vim is something they added folke/lazy.nvim@7b945eec588e499f0ea36974df90836549a3e734. The issue you linked was an error in the person's config. When a plugin is loaded it can alter neovim's state by adding new commands, setting key binds, and variables etc. After changing the plugins, neovim should be fully restarted to clear any unwanted states. You can separate your custom key binds and settings to another file and then source those separately.

**Comment by mech-a** [comment]
Thanks for the idea, but I don't think that this is good for beginning users. There is definitely a chance of unwanted states and unwanted behavior happening for this since we are a single file configuration as @jtams mentioned. This is something that can be easily implemented by any user with `kickstart.nvim`, and we encourage that, but I don't think it should be in the main repo as it could lead to odd bugs that dissuade people from continuing to use nvim.

**Comment by feoh** [comment]
Hi. Please file this issue at the lazy.nvim repository - we can't control every decision upstream plugins make.

https://github.com/folke/lazy.nvim
