### ISSUE TITLE
speed at the level

### ISSUE THREAD

**Issue by brxxlstxrs** [nvim-lua/kickstart.nvim#47]
why is there no plugin "impatient.nvim", I don't understand something, or does it no longer speed up the startup and work time in new versions of neovim

**Comment by MichaelVessia** [comment]
From the Readme: 


```
Some things that will not be included:
...
Lazy-loading. Kickstart.nvim should start within 40 ms on modern hardware. Please profile and contribute to upstream plugins to optimize startup time instead.
```

**Comment by tjdevries** [comment]
Yeah, basically I didn't think it was worth including out of the box -- It's very easy to add a new plugin, and you should if you want to experience the speedup from impatient.nvim (the point is not to have everything installed out of the box, but instaed have a good starting place for users).

I'll close this for now, but thank you for the question & suggestion!
