### ISSUE TITLE
<c-space> not working for treesitter init_selection and node_incremental

### ISSUE THREAD

**Issue by djschilling** [nvim-lua/kickstart.nvim#470]
I just used kickstart.nvim as my nvim config and the two commands `init_selection` and `node_incremental` are not working. they are mapped to `'<c-space>'`.
If i understand that correctly that stands for Control + Space.
I am using a mac with iTerm.

When i use the default mapping in the treesitter documentation `gnn` it works.

Does anyone know what could make the keymap not working?

**Comment by feoh** [comment]
I don't understand enough about what this feature is trying to do, but could you use the built in help functions to query the key mapping for what you want?

**Comment by feoh** [comment]
Hi.  The problem here is that MacOS is stealing this key chord for itself :)

See this [blog article](https://jay.gooby.org/2022/11/22/re-enabling-ctrl-space-shortcut-for-iterm-and-other-apps-under-macos-ventura) for details.

**Comment by djschilling** [comment]
Thanks that fixed it for me.
