### ISSUE TITLE
What about spporting toggle inlay hint

### ISSUE THREAD

**Issue by WindSoilder** [nvim-lua/kickstart.nvim#474]
Since latest neovim supports virtual text and can make use of inlay hint feature.
I think it'd be awesome to have a way to toggle inlay hint.
Here is what comes up in mind: `<leader>IH` --> `<leader>Toggle [I]nlay [H]int`
What do you think?

**Comment by feoh** [comment]
I have no problem with that but I have no idea how to make it happen :) Maybe some of the more accomplished Neovimmers here can suggest a path to implementing this?

**Comment by feoh** [comment]
Actually wouldn't that be up to like, cmp and the language servers to implement? I don't think this is the right place for this issue.

Please feel free to re-open if you disagree.

**Comment by WindSoilder** [comment]
> Actually wouldn't that be up to like, cmp and the language servers to implement

Yeah, but you can enable it only if relative language server have such feature.
I have the following setup in my config:
```lua
  if client.server_capabilities.inlayHintProvider then
    vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#938aad" })
    nmap('<leader>ih', function() vim.lsp.inlay_hint(0, nil) end, "Toggle [I]nlay [H]int")
  end
```
