### ISSUE TITLE
netrw dash not opening explorer

### ISSUE THREAD

**Issue by TimoKramer** [nvim-lua/kickstart.nvim#475]
## Describe the bug

I was used to open netrw explorer when hitting dash. I just switched to kickstart and love it but I don't know why it does not open the netrw explorer anymore when hitting dash.

## To Reproduce

1. Open nvim
2. Hit `-` (dash)

## Desktop

- OS: WSL2 with [EndeavourOS](https://github.com/sileshn/EndeavourOSWSL2)
- Terminal: Wezterm

## Neovim Version

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1696795921

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by Danielkonge** [comment]
I have something like this in my own setup:
```lua 
-- :Ex short cut
vim.keymap.set("n", "-", vim.cmd.Ex)
```
If I understand what you want correctly, this should do it. I am not sure if this is a good idea to add to kickstart though. Keys like `,`, `.`, `-` etc. are very easy to use for shortcuts, but people probably have a lot of different personal keybindings for these.

**Comment by TimoKramer** [comment]
Thanks! I didn't think one has to add it as a mapping. I thought unless netrw is disabled it should be there by default. But I am fine with adding a mapping, just wanted to know why it's not there.

**Comment by feoh** [comment]
Thank you @TimoKramer ! Indeed this probably doesn't belong in kickstart.

Closing.
