### ISSUE TITLE
Treesitter crashes on [[ ]] lua syntax in init.lua

### ISSUE THREAD

**Issue by kalleh** [nvim-lua/kickstart.nvim#48]
It seems that whenever the [[ xxx ]] pattern is encountered in init.lua is encountered, TS crashes with the following back trace:

ERR 2022-12-17T09:36:32.033 nvim.63645.0 decor_provider_invoke:38: error in provider treesitter/highlighter:line: Error executing lua: ...im/0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
stack traceback:
	[C]: in function '_ts_parse_query'
	...im/0.8.0/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
	....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:36: in function 'new'
	....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:160: in function 'get_query'
	....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:182: in function 'fn'
	...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:210: in function 'for_each_tree'
	...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:214: in function 'for_each_tree'
	....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:168: in function 'on_line_impl'
	....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:231: in function <....0/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:225>

Happend both on nvim 0.8.0 and 0.8.1 - I have not had this issue with my previous config which happily parsed any lua file.

**Comment by MichaelVessia** [comment]
I have this issue as well.  It's because you're in a `.lua` file but there's also `.vim` syntax present.  If I remember correctly, I would `:TSUpdate vim` and it would resolve it.

**Comment by agentHoover** [comment]
Thank you @MichaelVessia this solved it for me.

**Comment by MitchRivet** [comment]
I noticed this too on a fresh install today, but `:TSUpdate vim` has fixed it for me

**Comment by kalleh** [comment]
:TSUpdate vim seems to have resolved it for me as well, but keeping the issue open as it seems common enough that it should probably be worked around in the bootstrap code.

**Comment by tjdevries** [comment]
So just to make sure we're clear, after running `:TSUpdate vim` the problem was resolved?

**Comment by kalleh** [comment]
> 

Correct.

**Comment by agentHoover** [comment]
It did **not** fix it for me. But this predates my starting over with configuration using this repo.  
here is the current output from checkhealth

`nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.0.6-76060006-generic",
  sysname = "Linux",
  version = "#202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N"
}

## Parser/Features H L F I J
  - regex          ✓ . . . .
  - go             ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            x ✓ ✓ . ✓
  - comment        ✓ . . . .
  - lua            ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - gitattributes  ✓ . . . ✓
  - git_rebase     ✓ . . . ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - gitcommit      ✓ . . . ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . ✓
  - mermaid        ✓ . . . .
  - yaml           ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - markdown       ✓ . ✓ . ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: vim(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:171: query: invalid node type at position 4647 for language vim
    vim(highlights) is concatenated from the following files:
    |    [OK]:"/home/moose/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/highlights.scm"
    | [ERROR]:"/usr/local/share/nvim/runtime/queries/vim/highlights.scm", failed to load: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:171: query: invalid node type at position 581 for language vim`



I was able to work around it using this syntax.
`vim.cmd{ cmd='packadd packer.nvim'}`

**Comment by MichaelVessia** [comment]
@agentHoover I have this in my notes, if it's helpful:

```
-- If seeing errors parsing, check that you do not have two parsers installed.  Why this happens I do not know.
-- :echo nvim_get_runtime_file('*/python.so', v:true)
-- rm -rf /usr/local/lib/nvim/parser
```

I'm still learning about treesitter so I don't know why this happens, but it seems like two highlights.scm files sometimes exist, as it seems to be in your case, and then it doesn't know which to use.

**Comment by agentHoover** [comment]
@MichaelVessia yep. That fixed it.  I tried to uninstall the vim parser with `TSUninstall vim` and it told me that vim was still installed and exactly which file to remove manually to uninstall it. Removed the file, reinstalled, and all is well.  The file I removed was located here: ` /usr/local/lib/nvim/parser/vim.so` for what its worth. 

Thanks for your help.

**Comment by fox1t** [comment]
I had the same issue and fixed adding `'vim'` to `ensure_installed.`. Maybe we should add 'vim' to that array by default. Are there drawbacks to adding it?

**Comment by tjdevries** [comment]
:sweat: just that I thought I already had `vim` in the list haha

If someone wants a free PR, they can open. Otherwise I'll do probably tomorrow or soon

**Comment by mlabrkic** [comment]
I have investigated these two situations...

### Situation 1
After installing vim parser no more treesiter (2) errors.
init.lua:
  vim.cmd [[packadd packer.nvim]]
  vim.cmd [[colorscheme onedark]]


### Situation 2

Example 01 (commands-GOOD.lua):  
```
vim.cmd( [[

" ------------------------ COMMANDS --------------------------

" ----------------------------------------------------------
" Comm_ 01:
" Edit init.vim and cd to folder:
command! QeditVIMRC :e $MYVIMRC | tcd %:h

" ----------------------------------------------------------
" Comm_ 02:
" Toggle line relativenumber on or off.
command! QnumberRelativ set relativenumber!

" ----------------------------------------------------------

]] )
```

Example 02 (commands-BAD.lua):  
```
vim.cmd [[

" ------------------------ COMMANDS --------------------------

" ----------------------------------------------------------
" Comm_ 01:
" Edit init.vim and cd to folder:
command! QeditVIMRC :e $MYVIMRC | tcd %:h

" ----------------------------------------------------------
" Comm_ 02:
" Toggle line relativenumber on or off.
command! QnumberRelativ set relativenumber!

" ----------------------------------------------------------

]]
```

**Comment by tjdevries** [comment]
Should have all the required grammars now, so I can't reproduce crash anymore. Thanks!
