### ISSUE TITLE
kickstart.nvim bundle freezes neovim with specific file in linux kernel

### ISSUE THREAD

**Issue by jbwyatt4** [nvim-lua/kickstart.nvim#481]
## Describe the bug

This requires no specific knowledge of the kernel. Just the ability to go to a specific file.

I am not sure what plugin is causing this so I am reporting this here.

## To Reproduce

1. clone the latest torvalds repo
git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git torvalds
cd torvalds

2. Visit file that causes the issue
nvim include/uapi/linux/bpf.h

3. nvim will now freeze

Note: neovim without kickstart (vanilla) does not freeze with this file

## Desktop

- OS: Fedora 38 GNOME
- Terminal: Gnome terminal 3.48.1 for GNOME 44 and KDE Konsole: 23.08.1

## Neovim Version

```
:version
NVIM v0.9.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-para
meter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promot
ion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-comm
on -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-pr
otector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/
usr/include/luajit-2.1 -I/usr/include -I/usr/include/luv -I/builddir/build/BUILD
/neovim-0.9.2/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.
9.2/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.9.2/redhat-linux
-build/cmake.config -I/builddir/build/BUILD/neovim-0.9.2/src -I/usr/include -I/u
sr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/in
clude

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

**Comment by dam9000** [comment]
Wow indeed I can reproduce this. What hangs is the [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), so it's probably best if this is reported there. Until this is resolved you can disable treesitter for `C` with this change to kickstart:
```
diff --git a/init.lua b/init.lua
index a7667dd..fbe35cf 100644
--- a/init.lua
+++ b/init.lua
@@ -338,7 +338,13 @@ vim.defer_fn(function()
     -- Autoinstall languages that are not installed. Defaults to false (but you can change for yourself!)
     auto_install = false,
 
-    highlight = { enable = true },
+    --highlight = { enable = true },
+    highlight = {
+      enable = true,
+      -- list of languages that will be disabled
+      disable = { "c", "cpp", },
+    },
+
     indent = { enable = true },
     incremental_selection = {
       enable = true,
```

btw, if you let nvim run long enough it eventually starts to work, it took about 6 minutes on my system.

**Comment by feoh** [comment]
As @dam9000 said please report this at the [Treesitter repository](https://github.com/nvim-treesitter/nvim-treesitter).

**Comment by jbwyatt4** [comment]
I had email notifications disabled in GitHub. My bad. Opened issue.
