### ISSUE TITLE
Item not selected by default in autocomplete menu

### ISSUE THREAD

**Issue by ShashwatAgrawal20** [nvim-lua/kickstart.nvim#487]
Currently the auto-completions menu items are not selected by default, which is a little confusing/annoying.
![image](https://github.com/nvim-lua/kickstart.nvim/assets/72117025/88d41c89-cac6-497a-b50a-995e694de64b)

I propose that we highlight and select the first item in the autocomplete menu by default.

I would love to work on this issue. Just waiting for the conformation.

**Comment by feoh** [comment]
I do think this would be a good idea. I'm also somewhat confused by the current behavior.

**Comment by destroy-data** [comment]
According to :help completeopt, the noselect option in this line is responsible for this behavior:
vim.o.completeopt = 'menuone,noselect'
But for some reason it don't seem to work for me, maybe there is something in the config that effectively overrides this.

I agree that proposed behavior is more intuitive than the current one. IMO if only - when no item is selected - pressing enter would insert new line, that would be even better and as intuitive. Either way, both solutions are better than the current one.

To get the behavior I described, you need to remove "select = true" from one of cmp's mappings. So far I haven't found any side effect, but I haven't tested it for long.

    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Replace,
      select = true, 
    },
