### ISSUE TITLE
multi-version support

### ISSUE THREAD

**Issue by i3d** [nvim-lua/kickstart.nvim#49]
I have a work-related nvim setup that I can not (and don't want to) mess around (since that's highly customized for my work related stuff). But I do hope to have an easy setup to get a workable nvim setup for my open-source (or personal) development. Is it possible to support multi-version nvim out-of-the-box?

**Comment by tjdevries** [comment]
you can just move your existing setup out of ~/.config/nvim -> ~/.config/nvim2 and test it out. Would that work OK for you?

**Comment by i3d** [comment]
I guess if the goal is me spending time and figure things out, yeah I guess I could but 1) I believe I did that before and it went pretty horribly wrong and took me a while to get things back 2) We aren't experts in neovim internals and setup structures (if I remember correctly, there is like .config/nvim, .local/share/?, and .somewhere... and it by default use $XDG_XXX something to figure things out). I knew that lunarvim does that by default, but things like neovim distributions are quite heavy and opinionated, it's often hard to further customize.  Maybe help us to provide some standard steps to create an alternative isolated env would be very helpful... Thanks TJ!

**Comment by tjdevries** [comment]
Well there is a dockerfile that should still work in this repo that you could use to test if you want a completely isolated environment!
