### ISSUE TITLE
Nothing shown in live grep window

### ISSUE THREAD

**Issue by SirMetathyst** [nvim-lua/kickstart.nvim#496]
Hello. I'm having issues with live grep not showing anything at all. I've made a git repo in the directory, reinstalled nvim with a fresh kickstart.nvim config and made multiple files in my golang project but none of those have worked. I'm quite a new vim user so perhaps I'm missing something obvious. It has worked in the past but I can't recall when exactly it stopped working.

**Comment by feoh** [comment]
@slara Would you be willing to speak to this please? I don't understand how this feature works well enough to help, or to validate whether this person is having a problem understanding the equipment or in fact is reporting a bug with your changes.

Thanks in advance!

**Comment by feoh** [comment]
@SirMetathyst Please give the information prompted for in the bug template.

What Neovim version are you running? On what platform/operating system version?

**Comment by SirMetathyst** [comment]
Thank you for your fast response!

here is my vim `:version`

```
NVIM v0.9.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wm
issing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/
usr/include -I/usr/include/luv -I/builddir/build/BUILD/neovim-0.9.2/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.9.2/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.9.2/redhat-linu
x-build/cmake.config -I/builddir/build/BUILD/neovim-0.9.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

OS/Terminal:
```
Linux fedora 6.5.8-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 20 15:53:48 UTC 2023 x86_64 GNU/Linux
alacritty 0.12.3
```

**Comment by dam9000** [comment]
@SirMetathyst which key shortcut did you use for the live grep the `<space>sg` or `<space>sG`?
Also, do you have ripgrep installed?
```
which rg
/usr/bin/rg
```
install with:
```
dnf -y install ripgrep
```

**Comment by dam9000** [comment]
Yep, it's in the README:
https://github.com/nvim-lua/kickstart.nvim#installation

> Requirements:
> Make sure to review the readmes of the plugins if you are experiencing errors. In particular:
> ripgrep is required for multiple telescope pickers.
>

**Comment by SirMetathyst** [comment]
I'm really sorry for this. I've have to read things more carefully from now on.
