### ISSUE TITLE
Unable to get it to install on a clean Arch following your Docs

### ISSUE THREAD

**Issue by thorrrr** [nvim-lua/kickstart.nvim#499]
Not sure if its a bug or me but i followed the docs had a clean Arch system.
Did a Git clone as mentioned i already had ripgrep installed 
Clone created folder in .conf  but if i try to run nvim says not installed ?

![image](https://github.com/nvim-lua/kickstart.nvim/assets/8170673/a13b4edf-3259-4d8c-be96-92d368d82981)
![image](https://github.com/nvim-lua/kickstart.nvim/assets/8170673/7dc7398e-4c07-4836-a32f-f114b4c4ec6b)

**Comment by juangiordana** [comment]
`pacman -S neovim`

**Comment by thorrrr** [comment]
> `pacman -S neovim`

![image](https://github.com/nvim-lua/kickstart.nvim/assets/8170673/5948fda0-8f7d-419e-b84a-8e84683138bb)

https://logs.notifiarr.com/?a3b345474b63794c#JDtzMWjVbVH8w28br3U3ZE8GbnXpPkRpesn4BL2UVM8i

**Comment by thorrrr** [comment]
OK 
I have run it a few times 
![image](https://github.com/nvim-lua/kickstart.nvim/assets/8170673/91bdaaaa-c95a-4f4f-bc77-135acbd24132)

**Comment by thorrrr** [comment]
> `pacman -S neovim`

Hi Juan 
Cheers for help i think its working now :)
