### ISSUE TITLE
Spawning language server with cmd: `lua-language-server` failed. The language server is either not installed, missing from PATH, or not executable.

### ISSUE THREAD

**Issue by TheYahya** [nvim-lua/kickstart.nvim#50]
Hey @tjdevries, Thank for the Video: https://www.youtube.com/watch?v=stqUbv-5u2s

I get this error after removing my current `~/.config/nvim` and replacing with the one in this repo!

![Screenshot 2022-12-18 at 01 07 36](https://user-images.githubusercontent.com/15307244/208267678-8d8515dc-e7f1-4bc4-a2b9-0e1a61e130d9.png)

**Comment by tjdevries** [comment]
You don't have any other configuration?

**Comment by martyphee** [comment]
I'm also getting lua errors. I've tried deleting all the directories and starting over. Also upgraded all packages with `brew`

```
   90 ## The following errors have been detected:
   91   - ERROR: vim(highlights): ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
   92     vim(highlights) is concatenated from the following files:
   93     | [ERROR]:"/Users/martinphee/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/vim/highlights.scm", failed to load: ...im/0.8.1/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at               position 2765 for language vim
```

**Comment by TheYahya** [comment]
No I moved the whole `/nvim` dir to somewhere else before starting this. @tjdevries 
This issue was happening in `v8.1.0` and `v8.0.0`, I fixed it by installing `v0.9.0-dev`.

**Comment by tjdevries** [comment]
Hm, 0.9 fixed it for you?

**Comment by TheYahya** [comment]
yes

**Comment by tjdevries** [comment]
Can you try with latest version of how we're initializing and running the servers? should be better now.

**Comment by TheYahya** [comment]
Yes, thanks @tjdevries, the language server is fixed. But I still get this error in `0.8.1` version:

![Screenshot 2022-12-25 at 12 03 00](https://user-images.githubusercontent.com/15307244/209462412-bff15469-30bf-43d8-933a-87a682283fb7.png)

**Comment by tjdevries** [comment]
Have you run ":TSUpdate" in the old version?

**Comment by TheYahya** [comment]
I think "yes". I can't be sure thought, hard to remember as I tried everything!

**Comment by tjdevries** [comment]
Will close now cause I think all of this should be handled by Mason now.

**Comment by arindampal-0** [comment]
The neovim is not finding the LSP in the neovim PATH because it has not yet been added to the neovim PATH. This task is handled by `Mason`. But if `nvim-lspconfig` tries to access the LSP server before the appropriate PATH gets added by `Mason` then we encounter the error:
```text
Spawning language server with cmd: `lua-language-server` failed. The language server is either not installed, missing from PATH, or not executable.
```

The solution is given here:
https://github.com/williamboman/nvim-lsp-installer/discussions/509#discussioncomment-3337756

So you need to make sure that `Mason` gets loaded before `nvim-lspconfig` does, i.e. `require("mason").setup()` runs before `require("nvim-lspconfig").setup()`

If you are using `Lazy.nvim` then this solves the problem, adding `mason` as a dependency of `nvim-lspconfig`.
```lua
{
    "neovim/nvim-lspconfig",
    dependencies = {
        "williamboman/mason.nvim",
    },
}
```
