### ISSUE TITLE
Disable "missing-fields" warning in Lua LSP by default

### ISSUE THREAD

**Issue by ashrasmun** [nvim-lua/kickstart.nvim#503]
Hello,

I think it would be a great idea to extend `lua_ls` settings to ignore noisy warnings that are irrelevant for a beginner.

From:
```
    lua_ls = {
        Lua = {
            workspace = { checkThirdParty = false },
            telemetry = { enable = false },
        },
    },
```

To:
```
    lua_ls = {
        Lua = {
            workspace = { checkThirdParty = false },
            telemetry = { enable = false },
            diagnostics = {
                disable = { "missing-fields" },
            },
        },
    },
```

Reference: https://github.com/LuaLS/lua-language-server/wiki/Settings#diagnosticsdisable
I cannot see any template for suggestions, so I hope I won't be automatically dismissed 😊

Kind Regards

**Comment by feoh** [comment]
I'm confused by this. The missing fields indicators are one of the basic features of every LSP. I see this in Python as well as Lua.

From where I sit it's a desirable feature.

Why do you want to turn them off?

Unless people in the community feel very strongly about this I'd prefer we not make this change.

**Comment by ashrasmun** [comment]
As a beginner, I was more confused about the fact that a major part of config was underlined because of these warnings and I thought I am expected to fix the warnings in order to repair this config. However I understand your point - I just shared my initial user's experience with this configuration.

**Comment by feoh** [comment]
Thanks very much for the idea. I just think it's throwing the baby out with the bathwater :) Closing this for now.

**Comment by wommy** [comment]
i agree, i thought my config was broken,
but i vote for

``` lua
    lua_ls = {
        Lua = {
            workspace = { checkThirdParty = false },
            telemetry = { enable = false },
            -- NOTE: Toggle below if Lua LSP Warnings are too much
            -- :help Link
            -- diagnostics = { disable = "missing-fields" },
        },
    },
```

**Comment by dam9000** [comment]
@wommy what is the `:help Link` for? Not sure it's related to the issue?

**Comment by feoh** [comment]
@wommy Please generate a PR for this and, obviously minus the :help link, I'll merge it. I like how this signposts the way for people who want this disabled but doesn't short circuit the lsp defaults.

**Comment by StraightOuttaCrompton** [comment]
Just some related items I've spotted whilst looking for a solution to this.

A [pull request in nvim-cpm](https://github.com/hrsh7th/nvim-cmp/pull/1723) to fix this is open  🎉 

An [issue in treesitter](https://github.com/nvim-treesitter/nvim-treesitter/issues/5297), but looks like it isn't a priority 

And finally there is an example of how to [supress the warnings](https://github.com/andreaswachowski/dotfiles/commit/853fbc1e06595ecd18490cdfad64823be8bb9971) using a mix of `---@diagnostic disable: missing-fields`, `---@diagnostic enable: missing-fields`, and `---@diagnostic disable-next-line: missing-fields`.

**Comment by wommy** [comment]
i was trying to echo how TJ has the `:help`'s peppered throughout, 
but i had another appointment so i just typed up something quick and i thought thatd be clear

as im just trying to make the transition from the vimscript to lua myself, im totally unfamiliar,
is there a way to point to [lua-language-server/settings#diagnosticsDisable](https://github.com/LuaLS/lua-language-server/wiki/Settings#diagnosticsdisable)
what should be pointed to? is there something equivalent / better?

**Comment by wommy** [comment]
https://github.com/nvim-lua/kickstart.nvim/pull/511

**Comment by dam9000** [comment]
@wommy I don't think there is a help entry for that, at least I could not found one. Using the http link should work just as fine, or leaving the comment as is is probably also good enough.

**Comment by wommy** [comment]
https://github.com/nvim-lua/kickstart.nvim/pull/511 got merged
