### ISSUE TITLE
How does one formally comply with the MIT license with this template format?

### ISSUE THREAD

**Issue by lquenti** [nvim-lua/kickstart.nvim#506]
From the license:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

I have [put some comment](https://github.com/lquenti/dotfiles/blob/master/nvim/init.lua#L1) at the top of my `init.lua`, but this I think is formally not enough. Putting some LICENSE file of another persons code seems like something nobody does, but would probably the most compliant version? One could think about embedding the license at the bottom of the `init.lua`, but this defeats the whole appeal of "cool base config with very few LOC".

So, what would be the best way to comply?

**Comment by feoh** [comment]
I do not personally see licensed compliance as this project's highest priority but if other members in the community feel strongly about this, we can certainly work on it.

**Comment by feoh** [comment]
I'm closing this for now. Thank you for your contribution, and if you or anyone else feels motivated enough to actually action this, please feel free to re-open and file a PR against it.
