### ISSUE TITLE
Where does the Windows fix line go?

### ISSUE THREAD

**Issue by lobneroO** [nvim-lua/kickstart.nvim#508]
Installation on Windows not working despite cmake and build tools installed

## Describe the bug
I copied the init.lua file to the specified path and started neovim. The error message appears:
> Error executing vim.schedule lua callback: Failed to load parser for language 'lua': uv_dlopen: C:\Users\user\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so is not a valid Win32 application.

>stack traceback:
        [C]: in function '_ts_add_language'
        ...eovim/share/nvim/runtime/lua/vim/treesitter/language.lua:99: in function 'add'
        ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:98: in function 'new'
        ...m Files/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
        ...m Files/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
        ...m Files/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:459: in function 'start'
        ...a/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
        ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
        ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:118: in function 'enable_module'
        ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:155: in function 'enable_all'
        ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:438: in function 'accumulator'
        ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:246: in function 'recurse_modules'
        ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:435: in function 'setup'
        C:\Users\user\AppData\Local\nvim\init.lua:380: in function 'fn'
        vim/_editor.lua:477: in function 'cb'
        vim/_editor.lua:263: in function <vim/_editor.lua:262>

The readme mentions a fix for windows problems, but it just lists a line of code and I do not know, where to put it. I tried the init.lua file at the very top, but that did not work.
This is my first contact with neovim, so the syntax doesn't help me, where to put it.

## To Reproduce
Windows 11, install VS 2022 professional and CMake.
Install neovim via winget, copy the init.lua file to the appropriate folder.
Start neovim, error appears after some installation routines have run.

## Desktop
- OS: Windows 11
- Terminal: git bash in Windows Terminal

## Neovim Version
v0.9.2

**Comment by feoh** [comment]
Despite what the Youtube video says, please follow the [README](https://github.com/nvim-lua/kickstart.nvim/blob/master/README.md) and run a git clone to download the entire repo rather than just copying over init.lua

Also note that on Windows you'll need the C compiler in your path for some of the TreeSitter stuff. I do this by using the "VS Powershell" prompt shortcut to run commands from.

**Comment by dam9000** [comment]
@GitMurf this should probably help you:
nvim-treesitter Windows support
https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support
