### ISSUE TITLE
Treesitter default keybindings for incremental selection do not seem to work on windows.

### ISSUE THREAD

**Issue by grab-a-byte** [nvim-lua/kickstart.nvim#513]
## Describe the bug

Using Ctrl+Space does not start a treesitter selection although the keymap in init.lua seems to specify otherwise

## To Reproduce

1. Fresh install of nvim and kickstart on windows 11 machine
2. Open init.lua file from kickstart folder
3. Type `Ctrl+Space` to try and init a treesitter selection
4. No action is performed within nvim

## Desktop

- OS: Windows 11
- Terminal: Windows Temrinal Powershell

## Neovim Version

0.9.4
```
```

**Comment by feoh** [comment]
please file this issue against the appropriate upstream repository:

https://github.com/nvim-treesitter

**Comment by lemusthelroy** [comment]
Weirdly this feature just stopped working for me too and I just followed this suggestion which seemed to resolve:

https://github.com/nvim-treesitter/nvim-treesitter/issues/5719#issuecomment-1890976016
