### ISSUE TITLE
LSP configuration does not pass the correct settings object potentially?

### ISSUE THREAD

**Issue by Strik3ria** [nvim-lua/kickstart.nvim#517]
## Describe the bug
While I was working to learn how nvim configuration in Lua works I ran into an issue working with yamlls to add schemas and customTags to the LSP settings. Adding the fields seemed to have no effect. I updated my init.lua to set the settings for the lsp [here](https://github.com/nvim-lua/kickstart.nvim/blob/ee9790b381416781063d0de6653b303f10ed89b0/init.lua#L550) so that it passes the settings object specifically. I think currently it passes it at the level just before you actually get to the settings area. It would be easy to overlook as we don't actually use the settings in the base kickstart but when you start adding settings, it may be problematic.

## To Reproduce
1. Add settings to any of the LSP server configurations, the settings won't be seen. Passing the inner object called settings [here](https://github.com/nvim-lua/kickstart.nvim/blob/ee9790b381416781063d0de6653b303f10ed89b0/init.lua#L550) resolves it.
`settings = servers[server_name]['settings']`

## Desktop
- OS:  Windows 11
- Terminal: Windows Terminal with Ubuntu w/ WSL2 over Docker

## Neovim Version
NVIM v0.10.0-dev-1672+g8b428ca8b
Build type: Release
LuaJIT 2.1.1700008891

Can I submit a PR for this? I don't want to step on anyone's toes by any means.

**Comment by Strik3ria** [comment]
The more I think about it, maybe I should have just passed my settings one level higher? Maybe it is more me than it?

**Comment by Strik3ria** [comment]
Learning achieved, carry on =P

**Comment by derMihai** [comment]
Yeah I was wondering about this too. Alas in my case, neither going one lever higher with the settings, nor using you suggestion seems to fix rust-analyzer ignoring any settings.

neither this:
```lua
  rust_analyzer = {
    settings = {
      ["rust-analyzer"] = {
        cargo = {
          buildScripts = {
            overrideCommand = "cargo check --quiet --workspace --message-format=json --all-targets --bins",
            invocationLocation = "root",
            invocationStrategy = "once",
          },
        },
      },
    },
  },

-- snip 
      settings = servers[server_name]['settings'],
```

nor this

```lua 
  rust_analyzer = {
    ["rust-analyzer"] = {
      cargo = {
        buildScripts = {
          overrideCommand = "cargo check --quiet --workspace --message-format=json --all-targets --bins",
          invocationLocation = "root",
          invocationStrategy = "once",
        },
      },
    },
    settings = {
    },
  },

-- snip
 settings = servers[server_name],
```
has any effect on rust-analyzer. I am also relatively new to both lua and nvim, and the way lspconfig builds tables and parses the user config is quite arcane for me :/
