### ISSUE TITLE
Just getting started on Vim installed LazyVim run a Checkhealth

### ISSUE THREAD

**Issue by thorrrr** [nvim-lua/kickstart.nvim#519]
Please can somebody tell me if this Checkhealth report looks ok!
See [here](https://xbackbone.osopolar.cloud/VIDE3/nOVuZUKA52.)
Or is there some things need fixing?

**Comment by feoh** [comment]
Hi. Kickstart.nvim is not LazyVim. Please file a bug against [their repository](https://www.lazyvim.org/)

**Comment by thorrrr** [comment]
> Hi. Kickstart.nvim is not LazyVim. Please file a bug against [their repository](https://www.lazyvim.org/)

Hi i used kickstart to install ??
https://i.imgur.com/sQ2hIoq.png
https://i.imgur.com/0Qos54d.png

**Comment by dam9000** [comment]
@thorrrr , feoh probably got confused by the header which mentions lazy.nvim:
```
lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
...
```
which is actually used as a plugin manager by the kickstart.

anyway, I think you might have just 2 problems:
```
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
```
I have this:
```
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
```
from:
```
rpm -qf /usr/bin/tree-sitter
tree-sitter-cli-0.20.8-1.fc39.x86_64
```
but since you're on arch check how to install it, although not sure if you need it?

The other issue you have is:
```
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities
```
I have:
```
- OK fd: found fd 8.7.1
```
from:
```
rpm -qf /usr/bin/fd
fd-find-8.7.1-1.fc39.x86_64
```

everything else i think looks fine.

**Comment by feoh** [comment]
My mistake. Thanks @dam9000 for the eagle eye and the assist!

**Comment by dam9000** [comment]
Oh it says LazyVim in the topic, that's probably what caused the confusion. In any case this does not appear an issue with kickstart itself, it's just question of a local install issue at most, so I guess the issue can be closed.

**Comment by feoh** [comment]
@thorrrr Are you good? Do you require additional help? I'm closing this for now but if you need more assistance please feel free to re-open. It looks to me like @dam9000 suggested fixes for your issues.
