### ISSUE TITLE
Startup time is over 300ms on Windows

### ISSUE THREAD

**Issue by GaurangTandon** [nvim-lua/kickstart.nvim#53]
I'm new to NeoVim configurations, and thanks to your latest video, I'm trying out kickstart.nvim

I did what is in the README. I also ran PackerSync just in case there's some upstream updates that I missed. But the startup time is consistently over 300ms on Windows. The output of `nvim --startuptime vim.log` is: [vim.log](https://github.com/nvim-lua/kickstart.nvim/files/10253282/vim.log). I am using:

1. PowerShell 7 in Windows Terminal
3. NeoVim 0.8.1
2. decent specs: 5900HX/SSD/16GB RAM

I understand the goal of kickstart.nvim is to be under 40ms. I also cloned the repo, built the Dockerfile, and that takes around 80ms for startup, which I'm okay with. Is there some known limitation of any upstream plugin on Windows? Or maybe I have made a mistake in the setup?

**Comment by seantwie03** [comment]
I am able to replicate this issue with Neovim 0.8.1 and an i7-8550U. I found that the startup time on Windows take about twice as long as the startup time in WSL2 on the same machine.

Using the same init.lua from master (12/18/2022)

Windows 11 - PowerShell 7 - Installed via Scoop
Startup Time: ~380ms

WSL2 - Bash 5.1.16 - Installed via snap
Startup Time: ~150ms

**Comment by tjdevries** [comment]
Hmm, ok -- I might just remove the 40ms target anyway for windows. It looks like a lot of the startup time is from mason nvim, which is probably doing a lot of system checking (which may not be optimized on windows).

I'll think about this a bit. Thanks for raising the issue

**Comment by tjdevries** [comment]
I think with the latest version things should be much faster on startup since we're using lazy.nvim. Closing for now, you can open a new issue if it's slow on Windows and I'll explore some more.
