### ISSUE TITLE
Path Completion Feature?

### ISSUE THREAD

**Issue by ShashwatAgrawal20** [nvim-lua/kickstart.nvim#535]
It's not necessary, but it would be nice to have some path completion too in the auto-completion menu.

something like-> 
![image](https://github.com/nvim-lua/kickstart.nvim/assets/72117025/9163bdec-01e4-43b2-998f-a48616486c82)

I can work on this, if it's okay!

**Comment by feoh** [comment]
Hi!

Speaking for myself I have no problem with this and it sounds cool, but I would ask that you:

* test extensively and be sure to test on Windows / UNIX.
* Use code comments if there is complicated logic

Thanks!

**Comment by feoh** [comment]
I tested it on windows 11 last night and it works great. Thank you for your contribution!

**Comment by ShashwatAgrawal20** [comment]
> I tested it on windows 11 last night and it works great. Thank you for your contribution!

My Pleasure.
