### ISSUE TITLE
Error detected while processing init.lua (error loading module 'luasnip')

### ISSUE THREAD

**Issue by dusanbrankov** [nvim-lua/kickstart.nvim#537]
## Describe the bug

1. I added the kickstart configuration in an empty `~/.config/nvim` directory, as described in the README:

```sh
git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
```

2. Without editing the `init.lua` file, I opened Neovim with `nvim`.

3. Neovim opens with the following messages:

![Screenshot from 2023-12-08 12-05-35](https://github.com/nvim-lua/kickstart.nvim/assets/132616606/7caf5de6-f49c-47ab-b932-62cff18cd9fb)

![Screenshot from 2023-12-08 12-07-02](https://github.com/nvim-lua/kickstart.nvim/assets/132616606/4f7d1220-97ab-4b53-becf-2971f9116fa2)

## To Reproduce

1. Add the kickstart [`init.lua`](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua) as is to `~/.config/nvim` 
2. Try starting Neovim, the error as shown above should appear.

## Desktop

- OS: Linux Mint 21.2
- Terminal: alacritty 0.13.0-dev (b9c88687)

## Neovim Version

```
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by sitko-j** [comment]
I too updated luasnip and get the same error, no idea how to fix this, watching this thread closely

**Comment by sitko-j** [comment]
@dam9000 suggestion worked a treat, thank you!

**Comment by devpaps** [comment]
I can also confirm that your solution worked @dam9000 👍🏻  Thanks!

**Comment by ozdemir08** [comment]
Thanks @dam9000. I just had the same problem and thanks to you solved it pretty quickly!

**Comment by dam9000** [comment]
@rp1231 the second method should work the same, as for the first, I'm not using windows so I'll need to guess, according to:
https://neovim.io/doc/user/starting.html#standard-path
The equivalent of `~/.local/share/nvim/` on windows is `~/AppData/Local/nvim-data` (or `%userprofile%\AppData\Local\nvim-data`)
So try deleting that.

**Comment by cybercrypt13** [comment]
And if neither work?  I removed the .local/nvim folder but still get lazy error.  If I open nvim and type :Lazy it says not an editor command.

**Comment by piyushdanej** [comment]
In my case I had misspelled "dependencies" to "depencies" for "nvim-cmp" where "LuaSnip" was defined as a dependency.

Come to think of it, a better error message / red underline would have been nice since I misspelled a key-of-object of a well defined standard for neovim plugin configuration. Although I might not have setup any specific plugin for that.
