### ISSUE TITLE
error in nvim-treesitter.configs 

### ISSUE THREAD

**Issue by conXDlation** [nvim-lua/kickstart.nvim#543]
## Describe the bug

on line 428 of init.lua an error with missing fields 
this is the error message that nvim itself caught 
.config/nvim/init.lua|428-490 col 44-4 warning| Missing required fields in type `TSConfig`: `modules`, `sync_install`, `ignore_install`

## To Reproduce
just install the config as it is 
## Desktop

- OS: fedora workstation 38linux 
- Terminal: alacritty with tmux

## Neovim Version

v0.9.4
```
```

**Comment by dam9000** [comment]
This is harmless, and was already reported:
https://github.com/nvim-lua/kickstart.nvim/issues/441

If it bothers you, you can uncomment a line in the config:
```
      -- NOTE: toggle below to ignore Lua_LS's noisy `missing-fields` warnings
      -- diagnostics = { disable = { 'missing-fields' } },
```
link to code:
https://github.com/nvim-lua/kickstart.nvim/blob/76c5b1ec57f40d17ac787feb018817a802e24bb6/init.lua#L578

**Comment by feoh** [comment]
Thanks @dam9000. Closing.
