### ISSUE TITLE
Failed to run `config` for indent-blankline.nvim

### ISSUE THREAD

**Issue by tonton-sol** [nvim-lua/kickstart.nvim#545]
## Describe the bug

On a fresh install this error immediately pops up.
```
Failed to run `config` for indent-blankline.nvim

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:361: module 'ibl' not found:
^Ino field package.preload['ibl']
cache_loader: module ibl not found
cache_loader_lib: module ibl not found
^Ino file './ibl.lua'
^Ino file '/opt/homebrew/share/luajit-2.1/ibl.lua'
^Ino file '/usr/local/share/lua/5.1/ibl.lua'
^Ino file '/usr/local/share/lua/5.1/ibl/init.lua'
^Ino file '/opt/homebrew/share/lua/5.1/ibl.lua'
^Ino file '/opt/homebrew/share/lua/5.1/ibl/init.lua'
^Ino file './ibl.so'
^Ino file '/usr/local/lib/lua/5.1/ibl.so'
^Ino file '/opt/homebrew/lib/lua/5.1/ibl.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - .config/nvim/init.lua:69
```

## To Reproduce

1. Clone the repository 
2. Open nvim

## Desktop

- OS:  Mac OS 14.1.2
- Terminal: WezTerm

## Neovim Version

v0.9.4
```
```

**Comment by dam9000** [comment]
To me this does not seem to be a config issue,

Recommended is:
https://github.com/lukas-reineke/indent-blankline.nvim?tab=readme-ov-file#install
```
{ "lukas-reineke/indent-blankline.nvim", main = "ibl", opts = {} }
```

In kickstart.nvim it is:
https://github.com/nvim-lua/kickstart.nvim/blob/76c5b1ec57f40d17ac787feb018817a802e24bb6/init.lua#L215-L222

Which is the same, but with added comments and minor reformatting.
And `opts = {}` will implicitly call the `require("ibl").setup()` automatically by `lazy.nvim`

Perhaps try syncing the plugins by running the `:Lazy` command and pressing `S` there. Then optionally try uninstalling and reinstalling the ibl plugin by pressing x and i on it.

**Comment by tonton-sol** [comment]
@dam9000 You are correct this is not a config issue. Synching fixes this. The issue was caused by a previous install of a neovim distribution and its plugins. I can reproduce it by installing the distribution, synching, and then installing kickstart.
