### ISSUE TITLE
Troubles installing it on Windows (E5113 & E919)

### ISSUE THREAD

**Issue by sac11221** [nvim-lua/kickstart.nvim#55]
I get this error while trying to install it on windows, what is the issue?

_E5113: Error while calling lua chunk: C:\Users\MIO PC\AppData\Local\nvim\init.lua:7: Vim(packadd):E919: Directory not fo                                                              und in 'packpath': "pack/*/opt/packer.nvim"
stack traceback:
        [C]: in function 'cmd'
        C:\Users\MIO PC\AppData\Local\nvim\init.lua:7: in main chunk_

**Comment by seantwie03** [comment]
Can you please provide some more details?

What version of Windows are you running? What shell were you using? What version of Neovim do you have? etc.

**Comment by debashisbiswas** [comment]
I had this issue, and just fixed it locally. It's because you have a space in your path (`C:\Users\MIO PC`), so the `git clone` which initially installs packer fails. Submitting a fix in a bit

**Comment by sac11221** [comment]
@debashisbiswas Alrighty thank you very much! ^_^
