### ISSUE TITLE
Should the README mention system dependencies?

### ISSUE THREAD

**Issue by seantwie03** [nvim-lua/kickstart.nvim#56]
I think that in order to use this repository a user's system must have several things already installed. One example is a C compiler to compile treesitter parsers.

What level of documentation would be appropriate for the README regarding these system dependencies? On one end of the spectrum we could provide instruction for how to install the system dependencies on a bunch of different OSes. On the other end of the spectrum, we could just link to the docker file and say 'make sure your system has the things this dockerfile installs'. As with most things, the best answer is probably somewhere in the middle.

**Comment by CharlesChiuGit** [comment]
i think it's a gd idea to document system dependencies. We can start from ubuntu, arch, macos, windows. Then accepts PRs from the community to add other distros.

**Comment by kodecraft** [comment]
Agree! I had quite some issues getting "kickstart" to work on windows.

It might be helpful to at least make it clear upfront (tl;dr for the impatient) that certain things below are required, like:

- C compiler tools are required, for eg, cmake, msvc build tools (or make, mingw)
- other things that are somewhat required in the child package dependencies like ripgrep, fd
- esp pwsh... this last one took me by surprise as I thought powershell was OK when in fact it wasn't, something I found out later through the following links:
  - https://github.com/williamboman/mason.nvim/pull/706
  - https://github.com/williamboman/mason.nvim/issues/764

**Comment by tjdevries** [comment]
I don't necessarily want to document every possible package that is required, but particularly a list for windows is probably good. I'll accept PRs that add some information in the README that document some of the required items.

**Comment by michaelrommel** [comment]
Hi there,

is there a minimum version of neovim required? I have a Debian Buster version 0.3.4. Could not find any reference to what might be required. But I guess I have to install it and just try that out...

Thanks for the video, it was quite the teaser to explore some new packages.

  Michael

**Comment by craigmac** [comment]
Latest stable tagged Neovim at a minimum is the only guarantee, says so in the second paragraph in the readme: "Kickstart.nvim targets only the latest ['stable'](https://github.com/neovim/neovim/releases/tag/stable) and latest ['nightly'](https://github.com/neovim/neovim/releases/tag/nightly) of Neovim. If you are experiencing issues, please make sure you have the latest versions."

**Comment by michaelrommel** [comment]
Oh god, I am sorry, don't know how I missed that. Thanks for the pointer, I'll have to do some upgrading then, to try it out…

**Comment by seantwie03** [comment]
I started making a list of the System dependencies for Windows, (without listing every package, per TJ's guidance) and it basically boils down to a C Compiler and golang (if gopls is specified). I'm not sure how helpful having a list with these two items somewhere in the README would be. So, I'm going to close this issue.
