### ISSUE TITLE
Remap default tab keymaps

### ISSUE THREAD

**Issue by acurrieclark** [nvim-lua/kickstart.nvim#562]
## Describe the bug
I have been running through my setup and noticed that the lsp goto Type Definition shortcut is <leader>D. I felt that, for me, a more natural fit would be for it to match the other `goto` maps; perhaps `gt`.

I checked the current `gt` map using whichkey (and :help index) and found that it corresponds to `next tab`, which is a default (neo?)vim mapping.

The problem is that I can't find a way to override it. I have tried deleting the map, setting the map to `<Nop>`, setting it to another action as well as setting it in an autocommand and deferring.

There doesn't seem to be a use for next or previous tab in the default setup, so I was wondering if there was a way to either remove or override it?

## To Reproduce
Default kickstarter.nvim then add in a remap to override the default `gt` map.

## Desktop
- OS: OS X
- Terminal: kitty

## Neovim Version
0.9.4

**Comment by feoh** [comment]
I don't know of one.

**Comment by acurrieclark** [comment]
To be fair, this is highly unlikely to be a kickstart issue. Grateful for you taking a look. Thanks very much.
