### ISSUE TITLE
Follow UP

### ISSUE THREAD

**Issue by Bubba-Bubba** [nvim-lua/kickstart.nvim#575]
It would be great if there was a part 2 to the video, with some simple enhancement steps: I would like to change theme & also modify my lualine.

Also, is there a way you can view  neovim themes - scroll through them like on Helix?

**Comment by SiddharthPant** [comment]
The readme gives an explanation [here](https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#configuration-and-extension) on how to add custom plugin.
I have added my theme rosepine to custom plugin folder and commented out the theme config in init.lua. Also edited lualine.
Here's a quick screenshot:
![CleanShot 2024-01-05 at 16 02 24@2x](https://github.com/nvim-lua/kickstart.nvim/assets/10671794/d2746bfe-d011-4995-a43e-7d0c06ae4a0a)

**Comment by dam9000** [comment]
To scroll through themes, you can use the telescope colorscheme picker.
Type: `<space>ss` then type or select the `colorscheme` picker.
You will get a list of colorschemes, selecting one will change it.
To get back to the previous telescope search type `<space>sr` you will get again the same list with the current one selected.

**Comment by Bubba-Bubba** [comment]
Oh cool, thanks guys. I know it's a bit lame, but kickstarter is so good,
I just don't want to tamper unless I am doing it right. This is great.

At present I have the Dracula Lualine working on onedark, but I will venture out now, and try and get it more refined.
