### ISSUE TITLE
[mason-lspconfig.nvim] installing gopls

### ISSUE THREAD

**Issue by scorbin** [nvim-lua/kickstart.nvim#58]
[mason-lspconfig.nvim] installing gopls is stuck.  restarted nvim and waited 5 min still show the message 
LspInfo show that gopls is installed but message will not go away

**Comment by seantwie03** [comment]
I had a similar issue until I installed go on my system. Do you have go installed? If yes, what version?

**Comment by tjdevries** [comment]
Yeah, you can just remove the go one if you're not going to write Go.
