### ISSUE TITLE
Add tree-sitter-context?

### ISSUE THREAD

**Issue by pimvh** [nvim-lua/kickstart.nvim#59]
Thank you for this basic configuration. Now I have something as inspiration ánd to share with friends. Time to spread neovim love! 

Do you consider [treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context) part of a minimal configuration? 

I think it has also found it's way as a default into VSCode iirc, so in that line of thought it would not be additional bloat to me.

Let me know and I can create a PR.

**Comment by tjdevries** [comment]
I don't think I'll add it as a base plugin, I appreciate the suggestion though. It's a great plugin though :)
