### ISSUE TITLE
Typescript LSP stops working regularly

### ISSUE THREAD

**Issue by joaobibiano** [nvim-lua/kickstart.nvim#595]
## Describe the bug

Hello, I have been noticing that the Typescript LSP is crashing often with my setup

I didn't notice the pattern yet, but seems like that happens when pasting code (when copying from other files within the project)

For example, after pasting it shows:
<img width="1336" alt="Screenshot 2024-01-24 at 15 28 07" src="https://github.com/nvim-lua/kickstart.nvim/assets/29175815/3795dfa1-3300-4421-9610-f5087f9739a9">

It just gets solved after `:LspRestart`

I currently have the [GitHub copilot](https://github.com/github/copilot.vim) installed. I also had the `eslint` installed with Mason but uninstalled (it seems like it improved a little bit the frequency in which it happens)

I work mostly on React/Typescript files and just noticed that in those files. 

Here is my [lsp.log](https://gist.github.com/joaobibiano/370f9136ec519a65b082d2f4d693aed1) 
Here is my [custom configs](https://github.com/joaobibiano/kickstart.nvim/tree/master)
_ps: I'm new into neovim so appreciate your patience and guiding_

## To Reproduce

1. Copy some code in a tab
2. Paste it into a JSX/Typescript File
3. See typescript LSP stopping working

## Desktop

- OS: MacOS
- Terminal: Tmux/Allacrity

## Neovim Version

```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

```

**Comment by feoh** [comment]
Hi please file this issue against the eslint language server repository.  [here](https://github.com/MunifTanjim/eslint.nvim) maybe?

In any case, closing.

**Comment by magnusriga** [comment]
@joaobibiano I have a similar issue. `typescript-tools` + `eslint` + `tmux` seems to cause `eslint` to crash and typescript to become slow.

It works outside of `tmux`. Not sure what `tmux` changes that causes `eslint` and/or `typescript-tools` to misbehave.

Did you figure out what your problem was?
