### ISSUE TITLE
nvim hangs raspberry pi 3A+ system when running with init.lua in ~/.config/nvim

### ISSUE THREAD

**Issue by thumdugger** [nvim-lua/kickstart.nvim#603]
## Describe the bug

When running `nvim` with `init.lua` script in `~/.config/nvim/` the `nvim` editor downloads all the plugins but then hangs on step 0 or step 1 of 12 when trying to compile `nvm-treesitter`.

If I run the `top` command in one terminal and then run `nvim` in another I can see a large number of `cc` process kicked off before everything stops working. This behavior appears identical to a "make -j" fork bomb but I haven't yet figured out how to force the plugins compilation step to only compile things in serial.

The pi 3A+ is a heavily constrained device. I am not sure if the compilation steps are just sucking up every CPU cycle such that absolutely nothing works anymore or if that many `cc` processes are consuming all available memory (only 512MB) and before the system basically suffers a swapping death.

This is part of an astrophotography project I've started and these are the devices slated for use with it. The only issues we have run into with them is when compilation steps insist on doing some variation of force parallelism. The arm7a CPU does have four cores but it also only has 512MB of memory. 

Neovim, itself, had to be carefully compiled to force the make system to only compile serially; once that was accomplished everything worked fine.

## To Reproduce

1. Place a copy of kickstart.nvim `init.lua` into ~/.config/nvim
2. run `nvim` from console

## Desktop

- OS: debian 11.8 in console mode only; no desktop environment.
- Terminal: bash

## Neovim Version

```
NVIM v0.10.0-dev-2221+g47cd532bf                                                                                                       
Build type: Release                                                                                                                    
LuaJIT 2.1.1706185428
```

**Comment by feoh** [comment]
OK. So you're saying neovim launches cleanly with no hangs if you move kickstart.nvim away?

Please note there's more to installing than just copy/pasting init.lua into place. See the README.

Also, it's very likely that the problem you have is with one of our bundled plugins, although I know I've run Neovim on pi before with no issue, and others have as well.

Even if we can isolate the problem, you should file an issue with whichever plugin is malfunctioning.

**Comment by thumdugger** [comment]
Yes.

By renaming `init.lua` to `init.lua.moved`, so that it will be ignored on startup, `nvim` loads and runs without issue.

In fact, even without renaming the file `nvim` runs fine. But once it starts trying to compile the plugins init.lua is trying to install it hangs with many, many `cc` processes being executed.

**Comment by feoh** [comment]
OK.

Honestly, I'm not sure what we can do about this. You're trying to run a very large, complex, multi-layered program on a system that you yourself have said is very constrained.

Have you considered sticking with Vim?

The only alternative is debugging each plugin, turning them off one by one until you find the culprit.

In any case, I'm sorry but this is outside the purview of this project. Good luck and thanks for checking in!

**Comment by thumdugger** [comment]
Well, through many reboots and forcing process limits via `ulimit -u N` where `N` was some random and varying number between 10 and 30 I eventually got everything to install.

The only plugin causing an issue turned out to be `nvm-treesitter`. 

I'm too new to lua and neovim plugin installations but from what I can tell the installer was firing off tons of processes for each and every parser nvm-treesitter was trying to install for.

If I understood this installation procedure better I'm guessing the less sledgehammer way through this would be somehow limiting the parser installations to one parser at a time until each of the desired parsers were installed. I'm sure it's an easy thing to do but I just don't know enough on how to do that just yet.

Thanks for the moral support.

**Comment by dam9000** [comment]
@thumdugger I would suggest that the right place for this issue is the nvim-treesitter project itself:

https://github.com/nvim-treesitter/nvim-treesitter
