### ISSUE TITLE
How to disable LSP notifications (e.g loading workspace in lua)

### ISSUE THREAD

**Issue by TiLopes** [nvim-lua/kickstart.nvim#605]
I have looked around and found that `j-hui/fidget.nvim` does this type of notifications, however even after disabling it nothing has changed.

So I would like to know if it is possible to remove these notifications:
![image](https://github.com/nvim-lua/kickstart.nvim/assets/106965010/f2c2e4c8-ff4e-4b88-8598-a443de5abe18)

I currently have `mini.notify` and have no need to have the same notification twice.

**Comment by feoh** [comment]
Hi. Please file this issue against the [lua language server](https://github.com/LuaLS/lua-language-server) repository. Thanks! Closing.
