### ISSUE TITLE
How to quickfix/how to learn about features

### ISSUE THREAD

**Issue by asnewman** [nvim-lua/kickstart.nvim#607]
Two part noob question I have:
1. I working in javascript files, and vscode often is able to suggest fixes to bad code. For example, on a function that doesn't exist, I can do command+. to pull up a menu to auto-import the function from another file. How can I do that with kickstart/nvim
2. Second, if I wanted to understand what are capabilities of my current setup vs what I should go out and look for, how can I do that? Basically want to become more self-sufficient answering questions like the one above.

Thanks :)

**Comment by stastur** [comment]
Hey @asnewman, I'm not a neovim expert, but I think I can give you some answers

> I working in javascript files, and vscode often is able to suggest fixes to bad code. For example, on a function that doesn't exist, I can do command+. to pull up a menu to auto-import the function from another file. How can I do that with kickstart/nvim

You can open code actions with `<leader>ca` ([config reference](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L517)) combination.

> Second, if I wanted to understand what are capabilities of my current setup vs what I should go out and look for, how can I do that? Basically want to become more self-sufficient answering questions like the one above.

Probably not the full answer, but I found `:Telescope keymaps` command quite useful in exploring what keymaps are available.

**Comment by feoh** [comment]
Yeah, we get this question a lot. And I do sympathize, Neovim is a very deep well and we're asking you to dive in, the water's fine!

Maybe we should add a few lines to the README around how folks can explore kickstart's features.

I could do it but I think someone new who's not suffering from the "curse of knowledge" would be much better suited!

(Hint hint: @asnewman this means you :) Happy to help you put together a PR if you're willing.)

**Comment by asnewman** [comment]
@stastur thank you! exactly what I was looking for :) 

@feoh That makes a lot of sense! I saw you added something, but I'll see if there's anything else I can add

**Comment by feoh** [comment]
I think we're good but obviously if you feel you can add even more value, go for it!

**Comment by pablosanderman** [comment]
Leader key is now space.
