### ISSUE TITLE
Add a keymap for moving lines up and down in visual mode

### ISSUE THREAD

**Issue by stygian91** [nvim-lua/kickstart.nvim#608]
I'm not sure if you're taking addition suggestions but I think a keymap along these lines would be nice, especially for vsc*** people coming to neovim:

```lua
vim.keymap.set('v', '<C-j>', ":m '>+1<CR>gv=gv", { desc = "Move selection down" })
vim.keymap.set('v', '<C-k>', ":m '<-2<CR>gv=gv", { desc = "Move selection up" })
```

**Comment by feoh** [comment]
Ooh I really like this idea!

A danger in merging this:

Someone will pop up from the audience and shout "Hey, I mapped c-j and c-k in Visual mode back in 1991 when Vim was released!" :)

But I'm willing to take that risk. If I don't hear violent opposition in a day or so I'll merge this.

**Comment by dam9000** [comment]
Maybe it's worth pointing out that there are plugins that do this and a bit more - move in all directions and also handle block visual selection:

https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-move.md
https://github.com/matze/vim-move
https://github.com/booperlv/nvim-gomove

**Comment by feoh** [comment]
DING DING DING! WE HAVE A WINNAH!

Please install this plugin. If you like, contribute an additional "For Users coming from VSCode" section at the end of the README with pointers to this. Closing this bug.
