### ISSUE TITLE
Error while calling lua chunk (Telescope)

### ISSUE THREAD

**Issue by Harish-Shankar** [nvim-lua/kickstart.nvim#620]
## Description
I was trying to set up kickstart on my schools ssh terminal and upon creating the init.lua file I get the following error

### Error Message
Error detected while processing /nfs/elsrv4/users2/grad/hshankar/.config/nvim/init.lua:
lazy.nvim requires Neovim >= 0.8.0
E5113: Error while calling lua chunk: /nfs/elsrv4/users2/grad/name/.config/nvim/init.lua:358: module '
telescope' not found:
        no field package.preload['telescope']
        no file './telescope.lua'
        no file '/usr/share/luajit-2.1.0-beta3/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope/init.lua'
        no file '/usr/share/lua/5.1/telescope.lua'
        no file '/usr/share/lua/5.1/telescope/init.lua'
        no file './telescope.so'
        no file '/usr/local/lib/lua/5.1/telescope.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/telescope.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /nfs/elsrv4/users2/grad/name/.config/nvim/init.lua:358: in main chunk

## To Reproduce
I just copied and pasted the init.lua

## Desktop
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy

## Neovim Version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```
```

**Comment by feoh** [comment]
hi there, please follow the instructions in the README file in this repository. Please do not just copy and paste that one file or you will wind up with an improperly installed kickstart as you have found out :-)

**Comment by Harish-Shankar** [comment]
I tried that initially and tried it again, and I still face the same issue.

**Comment by dam9000** [comment]
The neovim version is too old, as stated in your error log:
```
lazy.nvim requires Neovim >= 0.8.0
```
Your version is: NVIM v0.7.2

[README](https://github.com/nvim-lua/kickstart.nvim#introduction) states:
> Kickstart.nvim targets only the latest ['stable'](https://github.com/neovim/neovim/releases/tag/stable) and latest ['nightly'](https://github.com/neovim/neovim/releases/tag/nightly) of Neovim. If you are experiencing issues, please make sure you have the latest versions.

Please upgrade your Neovim to a newer version, the latest is 0.9.5 but I think any 0.9.x would work fine.

**Comment by Harish-Shankar** [comment]
I follow the linux instructions on the NVIM wiki, but I keep running into the same issue

**Comment by dam9000** [comment]
which wiki?
I would suggest trying this:
https://github.com/neovim/neovim/blob/master/INSTALL.md#ubuntu
but skip the first two steps and jump to the PPA section.

**Comment by Harish-Shankar** [comment]
I meant the wiki found in the rep, which is the `Install.md`. I can't use the ubuntu specific one as it requires `sudo` which I do not have permission for in my school's server, so I though I would build from `.appimage`.

**Comment by feoh** [comment]
You can always [install from source](https://github.com/neovim/neovim/blob/master/INSTALL.md#install-from-source). This doesn't require root and is surprisingly easy.

If you're in school, you should probably become familiar with using UNIX build tools in any case. It's a good exercise! :)

I'm closing this issue for now. This isn't a kickstart.nvim bug.
