### ISSUE TITLE
Is there any way to restrict so much spammed pr?

### ISSUE THREAD

**Issue by WindSoilder** [nvim-lua/kickstart.nvim#631]
Sorry it's not a bug report.

I'm watching this repo in order to catch up some exciting updates, but all I can see is so much spammed pr :-(  it's really annoying.

**Comment by feoh** [comment]
We haven't been able to find one yet.

Suggestions as to how we can actually accomplish this are *very* welcome.

If you think it's annoying as a follower, imagine how annoying it is as a co-maintainer? :)

**Comment by dam9000** [comment]
I think the only way would be to lock the master branch and create a contrib branch that would not be the default branch. As I mentioned here: https://github.com/nvim-lua/kickstart.nvim/issues/515#issuecomment-1848415136

**Comment by feoh** [comment]
Yes, and none of us have that power.

Also I think I got a bit frustrated at @WindSoilder 's attitude.

This is a problem we're all dealing with and most of us are content to either filter or ignore it. As I see it it's the price you pay for creating a welcoming environment to those new to Neovim and possibly Github.
