### ISSUE TITLE
<C-k> has conflicting keymaps

### ISSUE THREAD

**Issue by DrewBradfordXYZ** [nvim-lua/kickstart.nvim#639]
Move focus to the upper window behavior isn't working. Commenting out line 500 fixes it.

https://github.com/nvim-lua/kickstart.nvim/blob/51842d80648e13a00d0b898a8db5ebc9d4f779cf/init.lua#L183

https://github.com/nvim-lua/kickstart.nvim/blob/51842d80648e13a00d0b898a8db5ebc9d4f779cf/init.lua#L500

**Comment by DrewBradfordXYZ** [comment]
This was fixed on stream, thank you!

**Comment by tjdevries** [comment]
Good callout, totally forgot we added both!!
