### ISSUE TITLE
Suggestion: Comments about Plugin Spec and Configuration (lazy.nvim)

### ISSUE THREAD

**Issue by brxxlstxrs** [nvim-lua/kickstart.nvim#651]
Add comments on `require("lazy").setup()` function arguments -- Plugin Spec and **lazy.nvim** Configuration (tables),
or/also
if don't fill the second one - omit this empty table as it is optional

**Comment by feoh** [comment]
Feel free to submit a PR. This all sounds reasonable although I don't know about the empty table.

**Comment by brxxlstxrs** [comment]
> although I don't know about the empty table.

it means that `{}` is not necessary here
https://github.com/nvim-lua/kickstart.nvim/blob/af4fd2355f211d4d19ec08ea6d57cbea483e2ee7/init.lua#L811

**Comment by feoh** [comment]
Sounds good! Please submit a pull request!
