### ISSUE TITLE
LSP error when working on an unsaved file (Python)

### ISSUE THREAD

**Issue by dupdrop** [nvim-lua/kickstart.nvim#663]
## Describe the bug

When editing an unsaved buffer with `:set ft=python`, the LSP won't work and will constantly give this error:

```
LSP[ruff_lsp] Ruff: Lint failed (error: a value is required for '--stdin-filename <STDIN_FILENAME>' but none was supplied

For more information, try '--help'.
)
Press ENTER or type command to continue
```

## To Reproduce

1. `:enew`
2. `:set ft=python`
3. `o` (or any command that triggers autocomplete or linting or whatever triggers the LSP)

## Desktop

- OS: Debian unstable on WSL2 on Adware OS for Gamers 10
- Terminal: Adware OS for Gamers Terminal

## Neovim Version

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794
```

**Comment by tjdevries** [comment]
Ruff isn't enabled by default - how did you turn it on?

**Comment by dupdrop** [comment]
I didn't turn it on. I stashed my few changes (only simple vim.opt.* changes), and it still happens. Does it not reproduce for you?

**Comment by feoh** [comment]
Did you perhaps install it via Mason?

What happens when you type `:Mason` ? Do you see it in the list of installed lsps?

**Comment by dupdrop** [comment]
I did have it marked as installed in Mason... probably because I did so a long time ago from lazyvim config which I have in another folder.

I guess this is not an issue with kickstart so you may close. When uninstalled there is no such error.

Both configs share using `~/.local/{share,state}/nvim`, which I didn't take into consideration.
