### ISSUE TITLE
Custom plugins not loading by default using lazy package manager

### ISSUE THREAD

**Issue by xask00** [nvim-lua/kickstart.nvim#665]
## Describe the bug
As a first time user of this kickstarter I want to add custom plugins.
I should be able to easily add them by following the README instructions.
I could not do that.
After adding custom plugin configuration file under ~/.config/nvim/lua/custom/plugins/some_plugin.lua
I restarted nvim and it was NOT picked up, frustrated I tried lot of things in vain and almost gave up 

## To Reproduce
1.  Add custom plugin configuration file under ~/.config/nvim/lua/custom/plugins/some_plugin.lua
2. Restart nvim
3. No new plugin is picked up

## Desktop
- OS: Linux
- Terminal: xterm-256color 

## Neovim Version
0.9.4

**Comment by pina771** [comment]
See instructions on [lines 815-817](https://github.com/nvim-lua/kickstart.nvim/blob/38828dcaf7c140902fedeaa75b017bf968400bb0/init.lua#L815).

**Comment by tjdevries** [comment]
Ya, pretty sure that's the issue - let me know if I'm incorrect

**Comment by xask00** [comment]
Guys the bug is about the README file instructions,
Imagine as a nvim newbie I come to this project, the first this I do is follow the README.md which is visible on your github page.
If I follow those instructions I DO NOT acheive my goal.
Also if i go to the `lua/custom/plugins/init.lua`, it says
`You can add your own plugins here or in other files in this directory!`

You see as a new user it adds unnecessary friction 

As a nvim newbie I may not (most probably will not)  dig so deep into the lua code to find things.

So to help future newbie make their lives easier I suggest we do either of these 2 things
Thing 1
- Change the README.md plugins section to say uncomment this line
- Update  `lua/custom/plugins/init.lua` to say uncomment that line 

Things 2
- Uncomment the line by default and allow loading custom plugins (this is expected behaviour by users btw)

**Comment by dam9000** [comment]
I agree un-commenting the `custom.plugins` would be a bit more noob friendly

**Comment by feoh** [comment]
I think the reason they're left commented as they are is to support the use case where folks are just copying init.lua and not cloning the repository.

I don't think @tjdevries realize it had drifted that way, making his video inaccurate and winning us 900000 support tockets :)

I think I'd need explicit feedback from him before I changed this.

**Comment by feoh** [comment]
The low hanging fruit here is to fix the README.

Generate a PR that does that folks and I'll merge it post haste :)
