### ISSUE TITLE
The return key does not accept the selected completion

### ISSUE THREAD

**Issue by sylvester-roos** [nvim-lua/kickstart.nvim#668]
## Describe the bug

On a fresh clone of the kickstart repo any selected autocompletion does not get accepted when pressing the return key (a.k.a. enter). Instead of accepting the completion, it will behave as if there was no completion and insert a new line.

## To Reproduce

1. `git clone git@github.com:nvim-lua/kickstart.nvim.git ~/.config/nvim-kickstart`
2. `$ NVIM_APPNAME="nvim-kickstart" nvim`
3. Try to accept a completion, for example `vim.opt.numb` and then pressing the return key

## Desktop

- OS: NixOS 23.11
- Terminal: GNOME Console 45.0

## Neovim Version

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/5rmbnq5rwpbq28281as1qxx3pyflzwxg-neovim-unwrapped-0.9.4/share/nvim"
```

**Comment by taliraj** [comment]
I had the same issue. Reading the init.lua file I found that pressing `Ctrl+y` works. 

https://github.com/nvim-lua/kickstart.nvim/blob/94a93643ab76f92435de2db21a41f6476894f8b3/init.lua#L684

**Comment by sylvester-roos** [comment]
Yup, looks like that changed with the newest kickstart!
