### ISSUE TITLE
Set the `termguicolors` option

### ISSUE THREAD

**Issue by brxxlstxrs** [nvim-lua/kickstart.nvim#675]
There is still a rather strange set of affected options,
but i think its good to set `termguicolors` option to true, don't we?

**Comment by SamuelBorn** [comment]
`termguicolors` is set by (almost) all major themes. We don't need to set it ourselves.

**Comment by brxxlstxrs** [comment]
> `termguicolors` is set by (almost) all major themes. We don't need to set it ourselves.

haha, yeah i'm sure, but not in every,
but its not worth adding here tho,
leave it as it is - good
