### ISSUE TITLE
If we delete the whole line and do an undo the X mark is going down 

### ISSUE THREAD

**Issue by YaswanthDasamandam** [nvim-lua/kickstart.nvim#681]
## Describe the bug
If you delete any X marked lines in nvim tutor the X mark goes down even if you do undo 
![image](https://github.com/nvim-lua/kickstart.nvim/assets/48354881/1f1d1021-2ead-4ee7-ab0c-a8c334133456)

## To Reproduce

1.Open nvim kickstart tutorial tutor and try to delete any line with X mark in it 
it will got down now undo with u 

## Desktop

- OS: WSL
- Terminal: bash

## Neovim Version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```
```

**Comment by tjdevries** [comment]
I think should be an issue for the neovim repo, kickstart didn't create `:Tutor`.

**Comment by tjdevries** [comment]
(Closing since this seems like a nvim issue, not a kickstart issue -- unless i find out otherwise later)
