### ISSUE TITLE
Suggestion: remaps for more intuitive navigation

### ISSUE THREAD

**Issue by belyakov-am** [nvim-lua/kickstart.nvim#683]
Hey there!

What do you think about adding these remaps to `Basic Keymaps` section? I found them quite handy and natural in terms of use and I think it might be useful to add them as comments at least

```lua
vim.keymap.set('n', 'H', '^')
vim.keymap.set('n', 'L', '$')
```

**Comment by dam9000** [comment]
my 2 cents: these two keys already have builtin functions - to top and bottom of window, I think we should be careful when overriding builtin functionality. What keymaps will be replacing the go to top/bottom of window then? Besides, the begin and end of line are already covered by `<home>` and `<end>`.

**Comment by feoh** [comment]
thank you for your contribution, but I'm afraid these changes aren't appropriate for this project at this time. Closing.
