### ISSUE TITLE
(Windows Terminal upstream) Text overlays line numbers after new line is inserted

### ISSUE THREAD

**Issue by ghry5** [nvim-lua/kickstart.nvim#69]
I constantly have some wierd behaviour where when I create new lines the rendering gets buggy. Here is an example all i do is hit `o` to make a new line
![image](https://user-images.githubusercontent.com/32223782/208508379-43928f6d-527f-4aa3-bf8b-ad9cc705940c.png)
![image](https://user-images.githubusercontent.com/32223782/208508583-3bdd2633-eb4b-421a-806e-612bcc4c16c4.png)

**Comment by tjdevries** [comment]
What neovim version do you have?

**Comment by ghry5** [comment]
Version: `NVIM v0.9.0-dev-525+ga7332ba9b-dirty`.

Had some more time today.
Turns out that it is caused by Windows Terminal. I tried wezterm and didn't have any issues there so I will be using that. 
Might still be something to look into though. If you need any further information I'd be happy to help. Otherwise feel free to close the issue.

**Comment by tjdevries** [comment]
I'll close and pin, thanks
