### ISSUE TITLE
How does `rtp:prepend` work if it's undefined?

### ISSUE THREAD

**Issue by calebdw** [nvim-lua/kickstart.nvim#693]
Hello!

Lua diagnostics is reporting that `vim.opt.rtp:prepend` is undefined---but it obviously works so why can it not recognize that it's defined?

https://github.com/nvim-lua/kickstart.nvim/blob/b83b2b061c1fab0e1a3a28c185345be7957e74cd/init.lua#L207-L208

Thanks!

**Comment by tjdevries** [comment]
It uses some complicated metaprogramming to make it work, and lua_ls doesn't guess correctly the type
