### ISSUE TITLE
Include linter example

### ISSUE THREAD

**Issue by ChillerDragon** [nvim-lua/kickstart.nvim#698]
What is the recommended way of running a linter? Is the lsp supposed to replace that? Should it be intergrated with the lsp? Is it separate? Having some examples or even one linter turned on by default would be helpful.

I have some key mappings for running shellcheck, luacheck, pylint, ruff, rubocop, ts-standard, yamllint, php -l clang-tidy in my vimrc that just run against the currently opend file. But I was wondering what the neovim/kickstart recommended way of doing it is.

**Comment by fredrikaverpil** [comment]
I just added a PR to fix this in #699, have a look!
Would appreciate any feedback, especially on how to improve the Mason installation.
