### ISSUE TITLE
Strange glyph icons appear.

### ISSUE THREAD

**Issue by joram56** [nvim-lua/kickstart.nvim#700]
## Describe the bug
Following the guide of cloning the repository and opening up neovim, the setup completes, but I see strange glyphs everywhere instead of the intended icons. 
![image](https://github.com/nvim-lua/kickstart.nvim/assets/25789485/b0efc6f0-5aad-4e38-adf4-9c2d79d5494a)

## To Reproduce
I assume this has to do with the fonts on a system, so not sure how to reproduce.

## Desktop

- OS: Ubuntu:20.04 LTS
- Terminal: zsh

## Neovim Version
0.9.1

**Comment by dam9000** [comment]
@joram56 you need to install one of the `Nerd fonts`: https://www.nerdfonts.com/
There's a huge selection, pick one, install it and then configure your terminal to use it.

**Comment by joram56** [comment]
Since this is a requirement, can it be added to the "Install External Dependencies" section of the readme?

**Comment by dam9000** [comment]
@joram56 You are right, I opened a PR: https://github.com/nvim-lua/kickstart.nvim/pull/703

**Comment by dam9000** [comment]
Here is a new PR for this issue: https://github.com/nvim-lua/kickstart.nvim/pull/716
Which makes the Nerd Font an optional requirement that can be toggled via a global flag.
