### ISSUE TITLE
Could not setup properly when opening up neovim for the first time

### ISSUE THREAD

**Issue by OU-ZAA** [nvim-lua/kickstart.nvim#704]
## Describe the bug
I'm following the installation guide, and right after i open up neovim. I get a bunch of errors 

![Screenshot from 2024-03-05 14-14-32](https://github.com/nvim-lua/kickstart.nvim/assets/95318367/0c91d6c7-6a74-416c-9595-05cc5a537608)

## To Reproduce
1. clone the repository
2. type nvim and click enter

## Desktop
- OS: Pop!_OS 22.04 LTS
- Terminal: zsh

## Neovim Version
0.10.0

**Comment by dam9000** [comment]
Did you have some other nvim config before?
Perhaps try removing all old config with:
```
rm -r ~/.config/nvim ~/.local/share/nvim ~/.local/state/nvim ~/.cache/nvim
```
and retry

**Comment by OU-ZAA** [comment]
No, I don't have any previous config. In fact, i just installed pop_os on my computer.

**Comment by dam9000** [comment]
What method did you use to install neovim 0.10?
I see the default on PopOS is 0.6.1

**Comment by dam9000** [comment]
I suspect you don't have the 0.10 version installed.
If I try with the nvim version 0.6.1 that is provided by popos by default I get this error:

```
Error detected while processing /home/pop/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/pop/.config/nvim/init.lua:156: attempt to index field 'k
eymap' (a nil value)
stack traceback:
        /home/pop/.config/nvim/init.lua:156: in main chunk
Press ENTER or type command to continue
```

If I install the latest nvim 0.10 it works perfectly.
I used these steps to install 0.10:

```
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt update
sudo apt install neovim make gcc ripgrep unzip
git clone https://github.com/nvim-lua/kickstart.nvim.git ~/.config/nvim
nvim
```

**Comment by OU-ZAA** [comment]
I build it from source
 
![Screenshot from 2024-03-05 14-56-57](https://github.com/nvim-lua/kickstart.nvim/assets/95318367/b1894a3b-ea19-49e5-b521-402435f078dc)

**Comment by dam9000** [comment]
Perhaps try uninstalling your build and give the `ppa:neovim-ppa/unstable` a try.

**Comment by OU-ZAA** [comment]
Now, it working just fine. Thank you so much for your helping
