### ISSUE TITLE
Consider adding vs code nvim support

### ISSUE THREAD

**Issue by zwhitchcox** [nvim-lua/kickstart.nvim#705]
## Describe the bug
When using the [neovim vs code plugin](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim), it actually runs a neovim instance inside your vs code editor. This could be a great stepping stone for people familiar with VSCode, but want to get into NeoVim (which I assume is at least partially the target audience of this repo).

However, this repo will currently mess a lot of stuff up out of the box. Most notably, syntax highlighting. This can easily fixed by commenting out the colorscheme plugin:

```lua
  -- { -- You can easily change to a different colorscheme.
  --   -- Change the name of the colorscheme plugin below, and then
  --   -- change the command in the config to whatever the name of that colorscheme is
  --   --
  --   -- If you want to see what colorschemes are already installed, you can use `:Telescope colorscheme`
  --   'folke/tokyonight.nvim',
  --   lazy = false, -- make sure we load this during startup if it is your main colorscheme
  --   priority = 1000, -- make sure to load this before all the other start plugins
  --   config = function()
  --     -- Load the colorscheme here
  --     vim.cmd.colorscheme 'tokyonight-night'
  --
  --     -- You can configure highlights by doing something like
  --     vim.cmd.hi 'Comment gui=none'
  --   end,
  -- },
```

However, this is <ideal, because now your colors are messed up when you want to "raw dog" (forgive me) neovim.

A better solution (IMO) is to make sure we are not in VSCode before loading the plugins that will conflict with VS Code:

```lua
if not vim.g.vscode then
    require('lazy').setup {{ -- You can easily change to a different colorscheme.
        -- Change the name of the colorscheme plugin below, and then
        -- change the command in the config to whatever the name of that colorscheme is
        --
        -- If you want to see what colorschemes are already installed, you can use `:Telescope colorscheme`
        'folke/tokyonight.nvim',
        lazy = false, -- make sure we load this during startup if it is your main colorscheme
        priority = 1000, -- make sure to load this before all the other start plugins
        config = function()
            -- Load the colorscheme here
            vim.cmd.colorscheme 'tokyonight-night'

            -- You can configure highlights by doing something like
            vim.cmd.hi 'Comment gui=none'
        end
    }}
end
```

Or even most all the non-vscode plugins to their own file:

```
if not vim.g.vscode then
  require('nonvscodeplugins')
end
```

I know you can't accommodate every editor plugin though, so maybe it would be better to move this issue to the [vscode-neovim plugin repo](https://github.com/vscode-neovim/vscode-neovim). The only thing is that I don't know there's a realistic way to prevent the loading of plugins through through the plugin. Maybe they need to just prevent the opening of new windows or automatically close them or something I guess.

There are other plugins like telescope that conflict with NeoVim as well, like Telescope (although I could understand the hesitancy to remove this as you wrote it). In the NeoVim plugin, this will lead to a weird error where it moves your cursor to the new window, even though the window is not visible, and it looks like your input has no effect (although really, it's just running on the non-visible window, I assume). If you aren't aware of what is happening, most people will just restart VS Code, and this would be enough of a deterrent from using NeoVim for most people to just give up.

I realize this isn't exactly a "bug" unless you are using VSCode, but it was enough to deter me initially from using it, so I thought you might want to know. Feel free to close this if you are not open to suggestions for improvements.

I could try to maintain a fork of this if you want with support for the vs code plugin.

Anyway, thanks for all your hard work, love how easy it is to get started with NeoVim with this!

## To Reproduce
1. Install VSCode
2. Install [VSCode NeoVim Plugin](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim)
3. Install kickstart.nvim

## Desktop
- OS: Mac OS X (will switch to PopOS, don't worry
- Terminal: N/A

## Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim
```

**Comment by feoh** [comment]
thank you for your contribution, but I really don't think this use case is within the purview of this project. Please consider creating a fork and making your changes there. It could be an excellent resource for people who are in fact, pursuing this!

**Comment by zwhitchcox** [comment]
Created fork [here](https://github.com/zwhitchcox/vscode.kickstart.nvim) please feel free to contribute or take over this, anyone who sees this; I am by no means an expert in NeoVim/lua!
