### ISSUE TITLE
markdown_oxide not found by mason after adding to lsp list

### ISSUE THREAD

**Issue by ddogfoodd** [nvim-lua/kickstart.nvim#707]
## Describe the bug
`:help lspconfig-all` lists a lsp called "markdown_oxide" however Mason doesn't seem to find it when trying to autoinstall it.

## To Reproduce
1. Open nvim config
2. scroll down to lsp section
3. like instructed use the nvim command `:help lspconfig-all`
4. you might stumble upon an entry named markdown_oxide
5. add it to the list of lsps
6. close nvim
7. open nvim and watch the error happen

## Desktop
- OS: NixOS
- Terminal: Alacritty

## Neovim Version
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652
```

**Comment by jalemann** [comment]
seems this was just the first one that did not work and the help command is out of date/sync.

**Comment by SebasF1349** [comment]
From their [github](https://github.com/Feel-ix-343/markdown-oxide?tab=readme-ov-file#installation):

> I'm working on getting this into package distributions. Installation/configuration should be easier soon.

Looks like you have to manually install it like it's exaplained there.

**Comment by feoh** [comment]
Thanks for the scoop @SebasF1349 - in any case this isn't a kickstart issue. Closing.
