### ISSUE TITLE
Mention: Alternatives to the plugin management

### ISSUE THREAD

**Issue by brxxlstxrs** [nvim-lua/kickstart.nvim#714]
Should talk about alternative approaches to plugin management here,
Maybe just mention that there are other ways?
(you can suggest a better way to do it? but think it's definitely worth it)

**Comment by SebasF1349** [comment]
What do you mean? As in organizing plugins in different files? There are instructions and an example at the end of the init.lua file.

**Comment by brxxlstxrs** [comment]
I'm talking about there are other "plugin managers" (plugin management) (paq-nvim, mini.deps, pckr.nvim etc), also package managers in some distros (OS) and also native vim packages

**Comment by WearyExploration** [comment]
Some of us would like no plugin-manager at all! Companies sometimes have restrictions on the development servers accessing the internet, so entry-barrier for kickstart is bottle-necked by Lazy not having a simple manual install path.

**Comment by tjdevries** [comment]
Sorry, but that's out of scope for kickstart - it's goal is to be a very simple, streamlined way for people to start exploring neovim. We can't cover everything here, it will just add confusion for people starting out IMO.

Thanks for the suggestion tho! :)
