### ISSUE TITLE
Lua LSP Gets Sent home dir as workspace

### ISSUE THREAD

**Issue by JamesMConroy** [nvim-lua/kickstart.nvim#73]
Every time I open a lua file nvim shows this message.

```
LSP[sumneko_lua] Your workspace is set to `/home/james`. Lua language server refused to load this directory.
Please check your configuration.
[learn more here](https://github.com/sumneko/lua-language-server/wiki/FAQ#why-is-the-server-scanning-the-wrong-folder)
```

Looks like this is behavior introduced in sumneko/vscode-lua [version 3.2.4](https://github.com/sumneko/vscode-lua/blob/1e9036baf13d362834d20c41b743e80829d43b5e/changelog.md#324)

Is anyone else seeing this and know of a fix or a way to silence the warning?

I'm on nvim v0.9.0

**Comment by tjdevries** [comment]
are you opening lua files in a git directory? or any sort of project? I think it's going to recurse until it finds a git directory.

**Comment by JamesMConroy** [comment]
Nope, and that’s probably the problem. I’ll confirm and close

**Comment by JamesMConroy** [comment]
Yep that was the issue, thank you.

**Comment by tjdevries** [comment]
No prob :) thanks for opening and responding!
