### ISSUE TITLE
No keybinds for luasnip choice selection 

### ISSUE THREAD

**Issue by Horryportier** [nvim-lua/kickstart.nvim#735]
I have some snippets containing choice nodes and I've realized there is no  corresponding  key binds  specified for that action. I would like to know if we could add some key binds for that or at least mention in the config.

**Comment by tjdevries** [comment]
Oh, this is a really good point. :laughing: can't believe i forgot to add this

**Comment by tjdevries** [comment]
I actually tried to write something out for this, but think it's just easier to link and mention choice nodes in the doc. Added in 5ac4b58
