### ISSUE TITLE
LiveGrep is not working on WSL2/Ubuntu

### ISSUE THREAD

**Issue by tomsour1s** [nvim-lua/kickstart.nvim#742]
## Describe the bug
The command `leader sg` is not working out of the box.

## To Reproduce

1. Use Windows WSL2
2. Install Ubuntu
3. Install Kickstart
4. Try `leader sg` (will not show any results)

## Desktop

- OS: Ubuntu 5.15.133.1-microsoft-standard-WSL2

I am not sure if it is just a WSL2/Ubuntu thing or always the same with a fresh Ubuntu installation. 

The solution is to install `ripgrep`.  [See this Issue](https://github.com/nvim-telescope/telescope.nvim/issues/506)
I think we should include a little NOTE in the init.lua that ripgrep needs to be installed. 

@tjdevries if this sounds like a good idea to you, I would be happy to open a Pull-Request.

**Comment by dam9000** [comment]
It's stated in the README.md:
https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#install-external-dependencies

> External Requirements:
> - Basic utils: git, make, unzip, C Compiler (gcc)
> - [ripgrep](https://github.com/BurntSushi/ripgrep#installation)
> - A [Nerd Font](https://www.nerdfonts.com/): optional, provides various icons
>   if you have it set vim.g.have_nerd_font in init.lua to true

**Comment by tomsour1s** [comment]
Oh, my bad. 
I only searched in the `init.lua` for a hint.
