### ISSUE TITLE
mini status line errors out when attempting to edit init.lua on MacOS

### ISSUE THREAD

**Issue by riccardoshrives** [nvim-lua/kickstart.nvim#745]
## Describe the bug
When attempting to edit the init.lua file, statusline throws the following error.
```
E5108: Error executing lua ....local/share/nvim/lazy/mini.nvim/lua/mini/statusline.lua:617: attempt to call field 'count' (a nil value)
stack traceback:
        ....local/share/nvim/lazy/mini.nvim/lua/mini/statusline.lua:617: in function 'diagnostic_get_count'
        ....local/share/nvim/lazy/mini.nvim/lua/mini/statusline.lua:300: in function 'section_diagnostics'
        ....local/share/nvim/lazy/mini.nvim/lua/mini/statusline.lua:555: in function <....local/share/nvim/lazy/mini.nvim/lua/mini/statusline.lua:551>
```

I know this might be an issue for mini.nvim but considering I've ONLY been able to reproduce it when editing THIS project's init.lua file, I figured I'd raise it here in case there are any others who have experienced it.

### Troubleshooting steps taken:
1. Used a fresh clone of kickstart. No modifications made (issue persists) 
2. Ran "rm -rf ~/.local/share/nvim" to force Lazy to reinstall everything (issue persists)
3. Attempted to reproduce on a second machine (running ubuntu) (could not reproduce)
   -- weird, right? 
4. Tested in the following terminals: Kitty, Terminal, iTerm2, Warp (issue persists)

## To Reproduce
0. Use a mac (cringe, I know)
1. Edit init.lua (either via nvim ~/.config/nvim/init.lua, or via netrw, or via the "e" command within nvim i.e. ":e ~/.config/nvim/init.lua")

## Desktop
- OS: macOS 14.3.1 23D60 arm64
- Terminal: Kitty (happens on any terminal)

## Neovim Version

```
NVIM v0.10.0-dev-751+gd086bc1e8
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by rbaumgardner93** [comment]
I ran into this same issue when I first ran kickstart. It looks like it has to do with the version of `neovim` you are on. I found this issue: https://github.com/echasnovski/mini.nvim/issues/699 in the `mini` repo and after getting the latest `nightly` version this issue went away.

**Comment by tjdevries** [comment]
> Use a mac (cringe, I know)

LOL

But seriously, you're on a pretty old version of "nightly", this was "nightly" many many nights ago :laughing: Try updating nvim and see if that fixes it.

**Comment by riccardoshrives** [comment]
You're right, @rbaumgardner93 and @tjdevries! How I didn't realise that before is beyond me. 
Updated neovim, and no more error! 

That's most likely more so the reason why it was working on my other machine. Makes more sense. It's a skill issue, not a mac issue... 

Thanks for the help gentlemen!
