### ISSUE TITLE
Got an error after opening nvim

### ISSUE THREAD

**Issue by Denisgsv** [nvim-lua/kickstart.nvim#757]
## Describe the bug
Cloned the repository, started nvim, it failed

## To Reproduce

basically installed fresh nvim, 

## Desktop
- OS: linus mint cinnamon
- Terminal: bash

## Neovim Version
0.9.5

this was the error :

nvim-treesitter[html]: Error during compilation
In file included from src/tree_sitter/parser.h:9,
                 from src/parser.c:1:
/usr/lib/gcc/x86_64-linux-gnu/11/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
    9 | # include_next <stdint.h>
      |                ^~~~~~~~~~
compilation terminated.

**Comment by feoh** [comment]
Does mint require you to install additional packages to compile C code? Isn't it an Ubuntu derivative? Can you maybe `sudo apt install build-essential` ? or similar?

**Comment by Denisgsv** [comment]
> Does mint require you to install additional packages to compile C code? Isn't it an Ubuntu derivative? Can you maybe `sudo apt install build-essential` ? or similar?

that fixed it ! should i delete or just close this.

p.s : for any random "linux mint users" this fixed my problem : sudo apt update && sudo apt install build-essential
