### ISSUE TITLE
OneDrive已续费，但下载仍然提示“访问令牌过期”

### ISSUE THREAD

**Issue by ACGtutusang** [nvim-lua/kickstart.nvim#76]
@n0099

**Comment by tjdevries** [comment]
Sorry, this issue doesn't follow the issue template. Please re-create an issue following the template.

**Comment by ACGtutusang** [comment]
@n0099

**Comment by ACGtutusang** [comment]
@n0099 OneDrive The charge has been continued, but the download still prompts "The access command board expires pls solve this problem

**Comment by tjdevries** [comment]
If you keep posting, I'll have to assume you're a bot and block you from this repo.

**Comment by ACGtutusang** [comment]
no，sry I just borrowed this post to find someone not very often Sorry again
