### ISSUE TITLE
zsh: command not found: nvim

### ISSUE THREAD

**Issue by elieven** [nvim-lua/kickstart.nvim#765]
## Describe the bug

To the best of my knowledge I'm quite sure I did my best to do exactly what the readme specified, installed all the requirements (in wsl ubuntu) and ran the command. It cloned the repo and after that nothing. Trying to run nvim as specified just fails as it cannot find it. Also I restarted and still same. Am I missing something obvious?

```
[ 11:36PM ]  [ elieven@DESKTOP-I52EQ2M:~/.config ]
 $ git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
zsh: correct 'clone' to 'rclone' [nyae]? n
Cloning into '/home/elieven/.config/nvim'...
remote: Enumerating objects: 884, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 884 (delta 9), reused 8 (delta 3), pack-reused 865
Receiving objects: 100% (884/884), 423.58 KiB | 2.46 MiB/s, done.
Resolving deltas: 100% (442/442), done.
[ 11:36PM ]  [ elieven@DESKTOP-I52EQ2M:~/.config ]
 $ nvim
[ 11:36PM ]  [ elieven@DESKTOP-I52EQ2M:~/.config/nvim(master✔) ]
 $ nvim
zsh: correct 'nvim' to 'vim' [nyae]? n
zsh: command not found: nvim
```

## To Reproduce
- Install dependencies mentioned
- Run the git clone command as specified
- Try to run `nvim`

## Desktop

- OS: Ubuntu (Windows wsl)
- Terminal: Oh my zsh

## Neovim Version

Can't get nvim to run so...

```
```

**Comment by dam9000** [comment]
It appears you have not installed the actual nvim.
Here, this should help:

```
wsl --install
wsl
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt update
sudo apt install neovim make gcc ripgrep unzip
git clone https://github.com/nvim-lua/kickstart.nvim.git "$HOME/.config/nvim"
nvim
```

**Comment by elieven** [comment]
Lovely! It works now. I'm a complete beginner to any kind of terminal editing and vim and such. I suggest perhaps updating the readme. As it mentions now - as well as the video on it - it makes it seem that one git clone command is all you need (well it does list some other dependencies too but seemingly not all). Thanks for the help!

**Comment by prathamesh-0909** [comment]
i am a mac user, i find myself in same situation. Also I am using the same terminal zsh. 
I tried cloning the repo and then after hitting nvim, I get zsh: command not found: nvim
Also I did not try the above given solution because I don't want to have wsl.

Thank you
