### ISSUE TITLE
Question: Is there an example of kickstart separated in multiple files?

### ISSUE THREAD

**Issue by jjuel** [nvim-lua/kickstart.nvim#766]
So this is definitely not an issue. I am just trying to separate Kickstart out into multiple files, and not having some success but some things are still not working. Does anyone have a working example of it split into multiple files? I am going to keep working, but just wanted to see if there were examples so I could see where I am going wrong.

**Comment by feoh** [comment]
Hi there!

This is SUCH a common question, we should really add it to the README or maybe create an FAQ.

If you've reached the point where you want a modular configuration, please consider forking kickstart and modularizing yourself, or alternatively, others have already done this. You can search our issues if you like.

Kickstart is designed for a particular type of Neovim user - the TOTAL newcomer who just wants to get going.  Once you've reached the point of "This is inelegant. Let's refactor!" - then you've reached the stage where the stock configuration may not be for you.

Thanks for the issue. I'm closing it for now.

**Comment by dam9000** [comment]
The answer is already in the README, FAQ section:

https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#faq

> Why is the kickstart init.lua a single file? Wouldn't it make sense to split it into multiple files?
> The main purpose of kickstart is to serve as a teaching tool and a reference configuration that someone  can easily use to git clone as a basis for their own. As you progress in learning Neovim and Lua, you  might consider splitting init.lua into smaller parts. A fork of kickstart that does this while maintaining the same functionality is available here:
> [kickstart-modular.nvim](https://github.com/dam9000/kickstart-modular.nvim)
> Discussions on this topic can be found here: https://github.com/nvim-lua/kickstart.nvim/issues/218 https://github.com/nvim-lua/kickstart.nvim/pull/473

**Comment by jjuel** [comment]
Yeah my bad on this. Failed to read the FAQ and now look like an idiot. I apologize, and thank you for the help.

**Comment by feoh** [comment]
No worries! Happens to all of us :)
