### ISSUE TITLE
Treesitter indent currently broken for Python

### ISSUE THREAD

**Issue by g2boojum** [nvim-lua/kickstart.nvim#78]
**Describe the bug**
Out of the box right now, using Treesitter's indentation w/ Python is broken. I've changed the treesitter config to read:
`indent = { enable = true; disable = { "python" } }`
which is not ideal, but breaking indentation for new users might be worse?

**To Reproduce**
1. Open a python file w/ nvim. Open a line after a "def xxxx" line, and watch nvim _not_ indent properly.

**Desktop (please complete the following information):**
- OS: Linux
- Terminal: kitty

** Neovim Version **
 - Output of running `:version` from inside of neovim:
0.8.1
```
```

**Comment by tjdevries** [comment]
good call, i just disabled it cause it was really bad haha

**Comment by g2boojum** [comment]
Looks like this was finally fixed in March (https://github.com/nvim-treesitter/nvim-treesitter/issues/2947), so python indenting in tree-sitter no longer needs to be disabled.

**Comment by amirmohammaddivani** [comment]
I have it disabled now in 2025. Because it's really bad in writing methods in classes especially when the return keyword is used. It's really difficult when you want to write multiple methods inside a class that return something.
