### ISSUE TITLE
Slow load time during file open.

### ISSUE THREAD

**Issue by mwcarlis** [nvim-lua/kickstart.nvim#785]
Hello.

New to neovim, long time vim user...  I started of with this project & when I use the onedark syntax highlighting I am having extremely long load times during file open...  Its actually causing me to insert bugs into code.

Open file, if I type anything before load finishes or /-search or /-paste something it ends up putting it into the file then jumping to the search result... So I don't even really get to see it inserted.

If I comment out the onedark it seems to work well again... I'm not convinced its only a onedark issue however..  I work on large C file (linux kernel), large C++ files & sometimes large python files... Not sure if file size matters...  Let me know if there is something I can do to provide more info..  I usually work in a large sized VM running ubuntu enterprise (No GUI)

**Comment by dam9000** [comment]
I wonder whether you have the old kickstart which used onedark theme by default, or do you use the latest kickstart which uses tokyonight by default but then switched it to onedark? If you are on the old kickstart perhaps try with the latest version.
Although I think it's more likely an issue with treesitter than the theme, you can try disabling treesitter highlighting. Another thing that might be slowing things down is the LSP, in case you enabled the clangd LSP...

**Comment by mwcarlis** [comment]
I'll rebase off the remote and see if it improves... It looks like I must have an older copy...  I didn't enable any clang support if it wasn't already..  Its interesting b/c some files do seem to open fine and others do not so I wonder if it isn't something about the syntax of the file..

Let me see how it goes after a rebase.

**Comment by mwcarlis** [comment]
Something else worth noting is that "vim.opt.mouse = 'a'" prevents you from highlighting text in an out of focus tmux pane....

**Comment by mwcarlis** [comment]
The new config is also "slow-ish" but at least it doesn't show me the code & let me do things before it's done loading.

**Comment by dam9000** [comment]
You can try disabling treesitter highlight, something like this:
 ```
diff --git a/init.lua b/init.lua
index 013fcc2..9af7463 100644
--- a/init.lua
+++ b/init.lua
@@ -796,6 +796,7 @@ require('lazy').setup({
       auto_install = true,
       highlight = {
         enable = true,
+        disable = { 'c', 'cpp' },
         -- Some languages depend on vim's regex highlighting system (such as Ruby) for indent rules.
         --  If you are experiencing weird indenting issues, add the language to
         --  the list of additional_vim_regex_highlighting and disabled languages for indent.
```

**Comment by feoh** [comment]
Hi there.

The goal of the kickstart.nvim project is to provide a starting point for new users that's easy to read and understand.

Fast startup times are not a core goal, but thank you for the report in any case!
