### ISSUE TITLE
Attempt to index field 'uv' (a nil value)

### ISSUE THREAD

**Issue by alfredosa** [nvim-lua/kickstart.nvim#787]
## Describe the bug

On Windows, after installed all the prerequisites, getting this error:

```bash
Error detected while processing C:\Users\alfrsuar\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: ...AppData\Local\nvim-data\lazy\lazy.nvim/lua/lazy/init.lua:40: attempt to index field 'uv' (a nil value)
stack traceback:
        ...AppData\Local\nvim-data\lazy\lazy.nvim/lua/lazy/init.lua:40: in function 'setup'
        C:\Users\alfrsuar\AppData\Local\nvim\init.lua:227: in main chunk
```

Supporting information

Healtcheck passes everything except lazy.vim.

I believe `uv` is part of neovim itself from Libuv.

Any guidance would be greatly appreciated.

## To Reproduce

1. Install all dependencies via Chocolatey
2. Clone Repo: `git clone https://github.com/nvim-lua/kickstart.nvim.git $env:USERPROFILE\AppData\Local\nvim\`
3. Open Neovim. Lazy won't load.

## Desktop

- OS: Windows
- Terminal: Powershell

## Neovim Version

```txt
:version
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info   
```

**Comment by alfredosa** [comment]
I should probably mention, on Mac and Ubuntu this works perfectly fine, as I've tested them all. Could be a Windows skill issue :)

**Comment by dam9000** [comment]
Hmm I just tried this now on Window 10 (in a virtualbox) and it works fine.
Which Windows version are you using?
Have you tried following these instructions exactly:
https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#windows-installation
> Windows with gcc/make using chocolatey

This works for me, here is a screenshot:

![image](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/3643a8ae-5391-42ce-8fbf-c5dbff1e07d1)

**Comment by daveragos** [comment]
am on ubuntu and am getting this error too, but not on the installation process at first it worked fine and after some point i get the error

**Comment by alfredosa** [comment]
@dam9000 I did follow the Chocolatey way, only difference is I'm using powershell. Maybe I give it ago from scratch again. Thanks for confirming it works for you. I must be missing something.

Tho uv is a fundamental part of Neovim as a whole which is super confusing 😢 

even doing vim.uv.version() returns a uv does not exist
