### ISSUE TITLE
Cannot find color scheme 'onedark'

### ISSUE THREAD

**Issue by nazariyv** [nvim-lua/kickstart.nvim#79]
**Describe the bug**
After pasting the init.lua contents into my init.lua, writing and closing, then executing nvim, I get:

```
Error detected while processing /Users/naz/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/naz/.config/nvim/init.lua:120: Vim(colorscheme):E185: Cannot find color scheme 'onedark'
stack traceback:
        [C]: in function 'cmd'
        /Users/naz/.config/nvim/init.lua:120: in main chunk
```

**To Reproduce**
See the above

**Desktop (please complete the following information):**
- OS: Mac OS 12.5.1
- Terminal: Hyper 3.3.0

**Neovim Version**
 - Output of running `:version` from inside of neovim:

```
NVIM v0.9.0-dev-533+ga6747545b-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by tjdevries** [comment]
Have you run `:PackerSync` ?

**Comment by Eric-Marnadi** [comment]
> Have you run `:PackerSync` ?

How do you run this?

**Comment by Eric-Marnadi** [comment]
That fixed it!

**Comment by tjdevries** [comment]
Cool :sunglasses:

**Comment by Utkaarsh-Siingh** [comment]
@tjdevries Thank you so much for your help. I am a beginner and i am trying to configure neovim with lua integration and your support helped me out of this issue. Thank you once again
