### ISSUE TITLE
[bug & fix] TreeSitter Missing `luadoc` to Provide Correct Highlight for Lua's `@diagnostic` Comment

### ISSUE THREAD

**Issue by Saplyn** [nvim-lua/kickstart.nvim#799]
## Describe the bug

`treesitter/highlighter` will complain about `Error executing lua ...` on `---@diagnostic disable-next-line: duplicate-set-field` and other similar doc comments.

## To Reproduce

1. Find a fresh computer that have never installed neovim, e.g. a ubuntu virtual machine (for best reproduction)
2. Install neovim v0.9.4 via `sudo snap install nvim --classic`
3. Install kickstart.nvim by flowing [the instruction](https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#install-kickstart)
4. Open neovim, wait for plugins to install, and navigate to one of the `@diagnostic` doc comment
5. Observe `treesitter/highlighter` complain about "Error executing lua"

## Desktop

- OS: Ubuntu 22.04 jammy
- Terminal: zsh 5.8.1 (gnome-shell)

## Neovim Version

```
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -W
missing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/nvim/parts/nvim
/build/.deps/usr/include/luajit-2.1 -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include -I/build/nvim/p
arts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/bui
ld/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

## Possible Fix

Add `luadoc` to the `ensure_installed` table (or list maybe?) of `nvim-treesitter`, inspired by this [discourse post](https://neovim.discourse.group/t/problems-with-treesitter-in-lua-files-and-in-general/4405), and worked for me.

Specifically, the following steps helped:

1. Add `'luadoc',` to the `ensure_installed`
2. Restart `nvim`, wait for it to finish install
3. Then restart `nvim` again, navigate to one of the `@diagnostic` doc comment
4. No more complains, yeah

For instance, change [this line of code](https://github.com/nvim-lua/kickstart.nvim/blob/dbba54cfd81506a20832aade85735bf4dc377b95/init.lua#L794):

```lua
-- /init.lua 792~796
    build = ':TSUpdate',
    opts = {
--    ensure_installed = { 'bash', 'c', 'html', 'lua', 'markdown', 'vim', 'vimdoc' },
      ensure_installed = { 'bash', 'c', 'html', 'lua', 'luadoc', 'markdown', 'vim', 'vimdoc' },
      -- Autoinstall languages that are not installed
      auto_install = true,
```

## Misc

Might be a bit irrelevant but, shall this be an issue or a pull request? Sorry but this is my first time actually have a solution to a potential problem of other's project. And if this kind of things should be a pull request, will it be suitable for me to directly open a pull request without opening an issue in the future (if I encounter the same situation again)?

**Comment by feoh** [comment]
Hi! It's an issue but please *do* generate a PR for this! I'll merge it immediately.

**Comment by Saplyn** [comment]
Thanks! I have created #800, and double checked it to make sure that I did it right. (never hurts to triple check and correct me if I did it wrong though). Shall I close this issue then?

**Comment by calebdw** [comment]
@Saplyn, standard practice is to mention in the PR that it "Closes #<issue number>" this issue and then merging the PR will automatically close this issue.

I see that you tried that in the PR but Github isn't picking up the verbiage---try to update the PR description and then you should see a reference on the PR and here that merging the PR will close this issue

**Comment by Saplyn** [comment]
Sorry for the inconvenience, I have edited the pr comment and it should work now? (I noticed that the reference is added to the "Development" part of the pr) I didn't know that ["fixes" works but "fixing" does not](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by calebdw** [comment]
No inconvenience, just raising awareness :) That will work---now merging the PR will auto-close this issue

**Comment by feoh** [comment]
Great issue. Great PR! Thank you to all involved!

**Comment by Saplyn** [comment]
I'm happy to help! Also thank all of you to help me get it on the right track!

\**happy cat noise* 😺✨

**Comment by A-Dagaate** [comment]
FYI The latest kickstart.nvim still spews this error on Windows 10. So far TSInstall reports all parsers are up to snuff. 
Still puzzling it out. TSUpdate vimdoc returns a complaint about 'Access  is denied.^M'
`nvim-treesitter[vimdoc]: Failed to execute the following command:
{
  cmd = "cmd",
  opts = {
      args = { "/C", "move", "/Y", "parser.so", "C:\path_to\\AppData\\Local\\nvim-data\\lazy\\nvim-treesitter\\parser\\\\vimdoc.so" },
  stdio = {
      [2] = <userdata 1>,
      [3] = <userdata 2>
   }
 }
}
Access is denied. ^M`
