### ISSUE TITLE
Suggestion: secure way of loading colorscheme

### ISSUE THREAD

**Issue by voyeg3r** [nvim-lua/kickstart.nvim#8]
If by any change packer fails on installing the colorscheme the starting process will not fail or bother the user more than needed:

```lua
-- in my config I use ayu colorscheme
local colorscheme = "ayu-dark"
local status_ok, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
if not status_ok then
    vim.notify("colorscheme " .. colorscheme .. " not found!")
    return
end
```

**Comment by tjdevries** [comment]
I don't think we will add this -- thanks for the suggestion though. It should be that upon install the colorscheme exists so there shouldn't be any reason for this to happen. Thanks :)
