### ISSUE TITLE
nvim-web-devicons is disabled

### ISSUE THREAD

**Issue by paulobarros** [nvim-lua/kickstart.nvim#801]
## Describe the bug
I can't get the icons to work, I am using a NF, my tmux session shows icons from fonts ok, but can't make it work in neovim. I am using the default config from kickstart, didn't modify nothing in the init.lua file. I am using MesloLGS NF font. 

![image](https://github.com/nvim-lua/kickstart.nvim/assets/697817/d7424928-326f-454a-9569-6af78f09c30a)

```
-- Useful for getting pretty icons, but requires a Nerd Font.
      { 'nvim-tree/nvim-web-devicons', enabled = vim.g.have_nerd_font },
```

![image](https://github.com/nvim-lua/kickstart.nvim/assets/697817/98050b19-edc2-4e03-a804-301d0499bf77)

## Desktop

- OS: pop!_OS 22.04 Kernel: 6.8.0-76060800daily20240311-generic 
- Terminal:  zsh 5.8.1

## Neovim Version

NVIM v0.10.0-dev                                                                                                          
Build type: RelWithDebInfo                                                                                                
LuaJIT 2.1.0-beta3  
```
```

**Comment by feoh** [comment]
Hi. I have no experience with this font and can't find any details on it to know whether or not it would in fact support web devicons.

Could you please try with a more common Nerd font like firacode and see if you have success? If you do, then your problem is the font and not Neovim/Kickstart :)

**Comment by dam9000** [comment]
@paulobarros you need to set `vim.g.have_nerd_font = true`, like this:
```
diff --git a/init.lua b/init.lua
index db55a9e..26f21f0 100644
--- a/init.lua
+++ b/init.lua
@@ -91,7 +91,7 @@ vim.g.mapleader = ' '
 vim.g.maplocalleader = ' '
 
 -- Set to true if you have a Nerd Font installed
-vim.g.have_nerd_font = false
+vim.g.have_nerd_font = true
 
 -- [[ Setting options ]]
 -- See `:help vim.opt`
```

**Comment by paulobarros** [comment]
I feel stupid now, how did I miss that line! Thank you!

**Comment by feoh** [comment]
@paulobarros You're in good company :) I was there when they made this change and totally forgot about it myself :)
