### ISSUE TITLE
Error when using "current buffer fuzzy find" in a file with $ in the name

### ISSUE THREAD

**Issue by ReidCole** [nvim-lua/kickstart.nvim#805]
## Describe the bug

When editing a file with particular symbols in the name (not sure of the exact combination, but my tests indicate having `_` and `$` cause the error), using the "current buffer fuzzy find" doesn't go to the correct position when selecting an option from the list.
- If I select the option that is on line 1 of the file, it will open a new buffer where the file name is the same as before but with the dollar sign part removed (e.g. `_foo.$bar.txt` => `_foo..txt`)
- If I select any other option from the list, it will do the same thing, but also show the following error message:
```
E5108: Error executing lua: ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:521: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:521: in function <...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:515>
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:75: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:252>
```

## To Reproduce

1. install default kickstart config to `~/.config/nvim`
2. create a file named `_$a`. command: `touch _\$a`
3. open the file in neovim. command: `nvim _\$a`
4. write on line 1: `hello`, then on line 2: `world`
5. hit `<leader>/` to open buffer fuzzy find
6. hit `enter` on any option in the list.
7. it will not go to where it should

## Desktop

- OS: Ubuntu 22.04 under WSL 2 on Windows 11 
- Terminal: Windows Terminal [(from microsoft store)](https://www.microsoft.com/store/productId/9N0DX20HK701?ocid=pdpshare)

## Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

For additional context, I encountered this bug when building a web app in [Remix](https://remix.run/docs/en/main/file-conventions/routes), which uses a file naming convention that requires using dollar signs and underscores for certain functionality.

**Comment by dam9000** [comment]
Interesting, I can reproduce this in WSL, but not in Linux proper or in Windows native. It must be some peculiarity of WSL I guess. In any case I think this is not an issue with the Kickstart, but perhaps with Telescope, I would suggest opening the issue there:
https://github.com/nvim-telescope/telescope.nvim

**Comment by ReidCole** [comment]
Thanks for testing in the other environments. I'll open this in telescope's repo.
