### ISSUE TITLE
Undefined global `vim`

### ISSUE THREAD

**Issue by talentix-ch** [nvim-lua/kickstart.nvim#810]
The kickstart configuration (init.lua) warns next to each "vim.opt....." definition "Undefined global `vim`". OK, it is only a warning, but is there a way to satisfy the code checking on this issue?

TJ, Thank you for your work.

Uri

**Comment by dam9000** [comment]
I'm not seeing this. Also pressing `K` on `vim.opt` shows proper definition:
![image](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/02855a3a-27d4-4ebc-9016-c7ac5e9ab881)

Can you make sure you have the latest kickstart and update all the plugins to latest versions run:
- `:Lazy` then press `S`
- `:Mason` then press `U`

Also, does `:checkhealth` report any unusual error/warning?
What is your nvim version, and OS type/version?

**Comment by aski** [comment]
I noticed this too when opening nvim config files outside of the default locations (`~/.config/nvim`, `~/.config/nvim-suffix`).
The neodev readme [describes how to configure custom locations.](https://github.com/folke/neodev.nvim/blob/main/README.md#-setup)

@talentix-ch are your files in a custom location?

**Comment by dam9000** [comment]
@aski I just tried it and you are right, if the files are outside nvim config location the hover doc is not complete but I don't get any diagnostic warnings as the OP reported, do you get warnings too?
Here is how it looks for me outside the nvim config (example /tmp):

![image](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/249c09f8-c988-4331-a964-0bd1ce7383be)

Compared to when the file is in nvim config dir:

![image](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/1f839127-2901-4a52-a97b-a4e5ab1ae09a)

So, hover help is different but I don't get any diagnostic warnings.

**Comment by aski** [comment]
@dam9000 

the edited file must be inside a directory named `lua`:

- `.../lua/file.lua`

or 

- `.../lua/.../file.lua`

or the file must be somewhere inside of `stdpath('config')`, e.g. `/home/username/.config/nvim/`,
or the `override` function must set `library.enabled=true` for the directory in question - see above or see `:help neodev.nvim-neodev.nvim-setup`.

**Comment by feoh** [comment]
Based on @aski's excellent feedback it seems like this is expected behavior for neodev. Please re-open if that's not the case, and thanks everyone for the report!

**Comment by wiraki** [comment]
I am sorry for picking this back up, I am just in the learning phase and I would like to make sure I understand.

Context, I have my kickstart `init.lua` in `~/.config/nvim-kick/init.lua`. To start neovim with this config, I have the following alias:

```
```

**Comment by wiraki** [comment]
I am sorry for picking this back up, I am just in the learning phase and I would like to make sure I understand.

Context, I have my kickstart init.lua in ~/.config/nvim-kick/init.lua. To start neovim with this config, I have the following alias:

```
> which kvim
kvim: aliased to NVIM_APPNAME=nvim-kick nvim
```

(this is to allow me to open neovim with different configs using aliases)

I was also seeing these warnings in the `init.lua`, so I tried to fix it as suggested here, like so: 

```
			{
				"folke/neodev.nvim",

				opts = {
					override = function(root_dir, library)
						if root_dir:find("~/.config/nvim-kick", 1, true) == 1 then
							library.enabled = true
							library.plugins = true
						end
					end,
				},
			},
```

However that did not seem to work. I was still having the warnings. 

Creating an empty `lua/` directory alongside the `init.lua` did work, but I was wondering why the above snippet did not ?

**Comment by dam9000** [comment]
@wiraki probably the `~` does not expand in lua as it expands in shell.
You can try using `vim.env.HOME`, something like this:
```
if root_dir:find(vim.env.HOME .. "/.config/nvim-kick", 1, true) == 1 then
```

**Comment by dam9000** [comment]
You are right, that's not enough, in addition the `lua_ls` has its own root path checks, see:
https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/lua_ls.lua
It's there that the existence of a lua dir is checked, in addition from that file I saw another way to force it to recognize a root dir is to create a `.stylua.toml` in the folder where your init.lua file is located. But if you really want to configure it programmatically, then try adding this:
```
diff --git a/init.lua b/init.lua
index 88658ef..8617fda 100644
--- a/init.lua
+++ b/init.lua
@@ -582,6 +582,17 @@ require('lazy').setup({
           -- cmd = {...},
           -- filetypes = { ...},
           -- capabilities = {},
+          root_dir = function(fname)
+            local root = require('lspconfig').lua_ls.document_config.default_config.root_dir(fname)
+            if root then
+              return root
+            end
+            local mypath = vim.env.HOME .. '/.config/nvim-kick'
+            if fname:find(mypath, 1, true) == 1 then
+              return mypath
+            end
+            return nil
+          end,
           settings = {
             Lua = {
               completion = {
```
Note, the neodev changes that you already made are also required.

**Comment by wiraki** [comment]
Thank you @dam9000 ! This works. It was not really a preference to settle this programmatically, but rather I thought it would be a good exercise in understanding lua neovim config. I can't say I fully grasp what happened though :see_no_evil:
