### ISSUE TITLE
Enable Telescope preview?

### ISSUE THREAD

**Issue by AkashRajpurohit** [nvim-lua/kickstart.nvim#812]
## Describe the bug

Following the kickstart.nvim guide, saw the video from [TJ DeVries](https://www.youtube.com/@teej_dv) as well, noticed that the telescope showed up preview when going through the list of files however that is not the same for me, what am I missing here?

## To Reproduce

1. Cloned kickstart.nvim
2. Let Lazy install all packages, did not see any errors.
3. `<leader>sf` to open telescope to search files but previews are not available
<img width="1510" alt="image" src="https://github.com/nvim-lua/kickstart.nvim/assets/30044630/483b4879-c6cc-47ba-9f97-796f1ed1bdd2">

## Desktop

- OS: Debian
- Terminal: ITerm2 (SSH-ing from Mac to Debian Linux)

## Neovim Version

```
NVIM v0.10.0-dev-2752+g35239e977
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
```

**Comment by dam9000** [comment]
The preview is enabled automatically if the terminal is wide enough, try resizing to at least 120 columns. For more control on this see Telescope config parameters.

**Comment by AkashRajpurohit** [comment]
Makes sense, thanks @dam9000
