### ISSUE TITLE
Telescope gives some duplicated results for goto definition and goto references

### ISSUE THREAD

**Issue by jcoffa** [nvim-lua/kickstart.nvim#815]
## Describe the bug

Using the goto definition or goto references features of Telescope shows multiple results for the same line under some scenarios.

## To Reproduce

1. Clear pre-existing Neovim config if necessary (`rm -rf ~/.local/share/nvim && mv ~/.config/nvim ~/.config/nvim-old`)
2. Install kickstart.nvim as normal so that it becomes the default neovim configuration
3. Open kickstart's `init.lua` file and find the `map` function used for LSP keymaps (`/map =<CR>`)
4. Hover cursor on any of the calls to the `map` function and use the goto definition finder `gd` to find definitions
5. Telescope gives 2 results for the `map` function

Hovering either option gives the exact same results in the "Grep Preview" pane (show below) and pressing Enter on either of them takes you to the same line, so it's not a different identical option off-screen or something like that.

![image](https://github.com/nvim-lua/kickstart.nvim/assets/35551680/a71db3f3-de0b-4071-83ca-bc00373d5116)

This entry also shows up twice when using goto references with `gr`.

## Desktop

- OS: Arch Linux 6.8.2-arch2-1
- Terminal: wezterm 20240203-110809-5046fc22

## Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by feoh** [comment]
Is this not expected given that you can have multiple lsps installed etc?

**Comment by jcoffa** [comment]
Does the default kickstart configuration have multiple Lua LSPs installed or something? I'm not totally sure what you mean by that. My expectation would be that `goto definition` will immediately jump to the target if there is only one place that symbol could be resolved to in the target scope. This is the only definition of the `map` function for example, and yet I get 2 results that both point to the same line of code.

**Comment by jcoffa** [comment]
Just `lua_ls` and `stylua`

![image](https://github.com/nvim-lua/kickstart.nvim/assets/35551680/0c1573d7-02c5-455e-a7c6-c77b65259f17)

Here's the output of `:LspInfo` as well just in case that matters too

![image](https://github.com/nvim-lua/kickstart.nvim/assets/35551680/c9f5edba-2a6d-4340-821e-853048b78ff4)

I also verified that I still get the double results in this neovim session, just to make sure that I didn't unknowingly have multiple LSPs attached in the earlier screenshots when I originally made the issue.

**Comment by dam9000** [comment]
Amazing debugging skill @aski !
This looks like it should be an improvement in telescope itself - to merge matches on the same line to one, so perhaps the issue with all these details should be opened in the telescope project.

**Comment by jcoffa** [comment]
Interesting behaviour that it captures both the function name in `local map =` and the actual function syntax `function()` itself, but looking at it now kind of makes sense it would work that way. Still a bit unfortunate behaviour since `variable = function() ... end` is a very common pattern in Lua and I personally think it would be better if there's some way to control if multiple entries on the same line could be collapsed to an instant jump (which was the behaviour I expected, and why I thought it was a bug in the first place). This feels like a more natural expectation instead of requiring a decision on whether to jump between points only a few characters away that are very similar logical entities anyways (plus an extra keyboard input or two).

Would it be reasonable for me to make an issue in the Telescope repo as a potential enhancement? Or would it make more sense for one of the kickstart contributors to do it? Or are we thinking this isn't something that should be changed at all?

**Comment by dam9000** [comment]
@jcoffa I think it would not make a difference if you raise this issue or anyone else in this community, so go ahead.
