### ISSUE TITLE
Autocomplete keybindings not functioning as before

### ISSUE THREAD

**Issue by masyyy** [nvim-lua/kickstart.nvim#816]
## Describe the bug
Migrated to a new computer and installed nvim kickstart. Expected tab and enter keys to work with autocomplete as with my previous setup (using commit `a005f15cec8072c97201f86e15df62c7e4a4490e`) . Instead they produce a tab and a newline respectively.
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23210320/5bc52454-4bcd-4e43-9d71-182112566205)
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23210320/6373cf22-afbb-4114-82a4-ac592d7cf843)

## To Reproduce
1. Open a code file of your choice and try to use autocomplete
2. Tab key not switching between the autocomplete options, but produces a tab.
3. Enter key not applying autocomplete, but produces a newline.

## Desktop

- OS: MacOS
- Terminal: Alacritty

## Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

**Comment by masyyy** [comment]
I see now what hotkeys are mapped for this behaviour in init.lua. There is a comment explaining that `:help ins-completion` explains the motivation for this, I read it and I do not understand it, but I will close as this seems to be intended behaviour.

**Comment by masyyy** [comment]
I see now what hotkeys are mapped for this behaviour in init.lua. There is a comment explaining that :help ins-completion explains the motivation for this, I read it and I do not understand it, but I will close as this seems to be intended behaviour.

**Comment by henrique-marques-vsoft** [comment]
If anyone else, like me, got lost when trying auto-complete (which we used to use "Enter" or "Tab" keys), you can get the same result by pressing ``Ctrl-y``. It will complete with the selected word in the pop-up.

**Comment by kushagra-xo** [comment]
@henrique-marques-vsoft 

```lua
          -- Select the [n]ext item
          ['<Tab>'] = cmp.mapping.select_next_item(),
          -- Select the [p]revious item
          ['<S-Tab>'] = cmp.mapping.select_prev_item(),
          -- Accept ([y]es) the completion.
          --  This will auto-import if your LSP supports it.
          --  This will expand snippets if the LSP sent a snippet.
          ['<Return>'] = cmp.mapping.confirm { select = true },
```
          this is a excerpt from my configuration
