### ISSUE TITLE
Excessive Error Messages Flooding Neovim Screen

### ISSUE THREAD

**Issue by vishalnagda1** [nvim-lua/kickstart.nvim#820]
## Describe the bug

As a new user to Neovim, I'm encountering a bug where multiple lines of error messages inundate the Neovim terminal screen. Please refer to the attached screenshots.

![Screenshot from 2024-04-02 14-53-09](https://github.com/nvim-lua/kickstart.nvim/assets/11268650/ac1c26bb-fa5f-44ff-9741-6ee133c79ebf)

![Screenshot from 2024-04-02 14-44-21](https://github.com/nvim-lua/kickstart.nvim/assets/11268650/101af579-8fa9-43f2-b36b-8e608f449ad1)

![Screenshot from 2024-04-02 14-41-22](https://github.com/nvim-lua/kickstart.nvim/assets/11268650/76c39e22-fad1-445a-8b96-021891c60222)

![Screenshot from 2024-04-02 11-57-37](https://github.com/nvim-lua/kickstart.nvim/assets/11268650/f6a0b2c2-a5d2-4686-8a70-e0040997fe50)

## To Reproduce

This issue occurs sporadically while working on a Python project. Steps to reproduce are unavailable as the error appears randomly. Below is the LSP configuration in `init.lua`:
```lua
ruff_lsp = {
  filetypes = { 'python' },
  init_options = {
    settings = {
      lint = {
        args = {
          '--select=ARG,F,E,I001',
          '--line-length=120',
        },
      },
    },
  },
},
pyright = {
  settings = {
    python = {
      analysis = {
        autoSearchPaths = true,
        typeCheckingMode = 'off',
        useLibraryCodeForTypes = true,
        diagnosticMode = 'openFilesOnly',
        autoImportCompletions = true,
      },
    },
  },
},
```

## Desktop

- OS: Ubuntu 22.04 LTS
- Terminal: Kitty 0.33.0

## Neovim Version

```shell
NVIM v0.10.0-dev-2657+g9765efb40
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
```

This issue is reported as a bug. As a new user to Neovim, I'm seeking guidance on resolving this issue. Any help or advice would be greatly appreciated. Thank you!

**Comment by dam9000** [comment]
The error messages appear to come from Treesitter. I think that project will be more able to help with this. I would recommend opening an issue there:
https://github.com/nvim-treesitter/nvim-treesitter

**Comment by vishalnagda1** [comment]
@dam9000 Certainly, the error seems to originate from Treesitter. However, I reported the bug here because it's causing a flood of error messages across the entire Neovim window. My main concern is the issue of **Flooding errors on the entire Neovim window**."

**Comment by feoh** [comment]
Hi. Thank you for the report.

We fully understand what your concerns are, but we are saying that this is the incorrect place for this bug report. Please report a bug to the repository @dam9000 suggested. I am closing this issue.

**Comment by henrique-marques-vsoft** [comment]
I'm getting the same error. From what I've been able to investigate so far, the problem really isn't with neovim as @feoh pointed out. First make sure that you are able to use the node normally through that terminal.
`node --version`
This needs to return node's version.
Are you using fish or bashrc? I recently installed fish and had the same problem. I managed to solve it by doing the following:
`mkdir -p ~/.config/fish/fnm.fish`
Inside this created file you need to put the following code to make sure your terminal has access to fnm:
`fnm env --use-on-cd | source`
This way your name will be available for all instances of the fish you create.
If this doesn't help, please give me more information about your system, such as:
- node version
- npm version
- kitty version
- tree-sitter version
- Are you using some tool such as LazyVim or Packer?

This is the version of treesitter that I have installed and it is working well. Make sure your treesitter is working for the files in question.
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23097578/4b9dfd39-3a49-4e8b-89ca-d2725b0e6777)

**Comment by vishalnagda1** [comment]
Thank you for your attention to my issue, @henrique-marques-vsoft. Below are the system configurations you requested:

    Shell: zsh
    Node: v20.11.1
    NPM: 10.5.1
    Zsh: 5.8.1

![Screenshot from 2024-04-08 11-26-39](https://github.com/nvim-lua/kickstart.nvim/assets/11268650/44f812b3-2141-44b2-bd53-31ec84ad87c8)


I'm indeed using LazyVim, as it came bundled with Neovim Kickstart.

Regarding Treesitter, I've attached a screenshot of my Treesitter setup below. However, despite this configuration, I'm still encountering flooding errors in Neovim.

![Screenshot from 2024-04-08 11-10-04](https://github.com/nvim-lua/kickstart.nvim/assets/11268650/c42fe01b-e53b-45b7-8c28-3a215399b661)


Since you suggested checking the Treesitter setup, I'll dive deeper into that. If you have any further advice or insights, I'd greatly appreciate them.
Thank you for your assistance.
