### ISSUE TITLE
Cfilter doesn't works

### ISSUE THREAD

**Issue by componhead** [nvim-lua/kickstart.nvim#826]
From hash [c4363e4](https://github.com/nvim-lua/kickstart.nvim/commit/c4363e4ad8aa3269a581d89b1e11403dd89df291)

https://asciinema.org/a/mANXZHxikVJnYQqgxJ2j3RWvI

**Comment by feoh** [comment]
Nice animation!

Can you please try this:

Run neovim by typing: `nvim --clean`

and then repeating your use case?

I'm wondering if this is actually a neovim issue and not a kickstart issue. Also, could you please check to ensure that Telescope doesn't do what you want? I've never heard of cfilter before so sorry if this is a clueless ask.

**Comment by dam9000** [comment]
Cfilter works fine for me, what are you trying to achieve?
> The :Cfilter command creates a new quickfix list from the entries matching
{pat} in the current quickfix list. 
Your quickfix list did not contain any entry that would match `dap-ui` so Cfilter did not match anything. Try `:Cfilter debug` and it will reduce the quickfix list to just the debug.lua entry.

**Comment by componhead** [comment]
> Cfilter works fine for me, what are you trying to achieve?
> 
> > The :Cfilter command creates a new quickfix list from the entries matching
> > {pat} in the current quickfix list.
> 
> Your quickfix list did not contain any entry that would match `dap-ui` so Cfilter did not match anything. Try `:Cfilter debug` and it will reduce the quickfix list to just the debug.lua entry.

Ok. I misunderstood the operation of the tool. Is there something for "refilter" an already filtered quickfix (by grepping for example?)

**Comment by feoh** [comment]
Seems like this is working as designed :) Closing. Consider asking this question in a general Neovim forum. Look on neovim.org for a zillion options :)
