### ISSUE TITLE
rust-analyzer not working completions, lints etc

### ISSUE THREAD

**Issue by cirqueira-labs** [nvim-lua/kickstart.nvim#829]
I made a fresh install of neovim and kickstart and I tried configure the rust-analyzer LSP
I've tried using Mason Install, manul config (@tjdevries VOD with bashbunni) in init.lua and 'mrcjkb/rustaceanvim'
I have all rust / rustup / cargo bin installed
But, doesnt work completions for Rust
For Lua it's looking great
thanks for help
regards

**Comment by feoh** [comment]
Do you have the rust-analyzer binary installed outside of Neovim?

**Comment by henrique-marques-vsoft** [comment]
Do you at least get errors highlighted on your code?
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23097578/b7d6c156-f362-44eb-b2b7-e8d911b35f4f)

You can also try `:LspInfo`. You should have something similar to this (specifically `rust_analizer`):
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23097578/ac459210-8640-4212-a5f2-f452f882bd08)

If there is no `rust_analyzer` there, make sure to install it with `:LspInstall rust_analyzer`.
Mason should pop-up and show you the installation process. Wait until you statusline says `"rust_analyzer" was successfully installed.`:
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23097578/c97ed5c3-500f-4b0e-b32e-b38924f29960)

Press `q` to quit Mason and see if you get any completions or errors on your code:
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23097578/f6da0519-fc3d-410b-a521-b64d06e52a7f)

If you still don't get any of that, try quitting and entering nvim again. Hope it helps you.

**Comment by cirqueira-labs** [comment]
> Do you have the rust-analyzer binary installed outside of Neovim?

Yes @feoh , I tried starting the rust-analyzer by rustup run command and Mason , I had some errors highlighted but no autocomplete.

**Comment by cirqueira-labs** [comment]
> Do you at least get errors highlighted on your code? ![image](https://private-user-images.githubusercontent.com/23097578/320175373-b7d6c156-f362-44eb-b2b7-e8d911b35f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODE3ODYsIm5iZiI6MTcxMjU4MTQ4NiwicGF0aCI6Ii8yMzA5NzU3OC8zMjAxNzUzNzMtYjdkNmMxNTYtZjM2Mi00NGViLWIyYjctZThkOTExYjM1ZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEzMDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZGRiZmUzZTRjZTM0Zjg1NGYxMDk0ZmY2MzEwMWE2MDNjNmNiYTdiZGI2OTE5OGE0NWViMzNiMjBiZDBkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hBSEGbZmLtI1wra3e8TYZwiRSqrZxuLu4KfplJUMIKo)
> 
> You can also try `:LspInfo`. You should have something similar to this (specifically `rust_analizer`): ![image](https://private-user-images.githubusercontent.com/23097578/320175450-ac459210-8640-4212-a5f2-f452f882bd08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODE3ODYsIm5iZiI6MTcxMjU4MTQ4NiwicGF0aCI6Ii8yMzA5NzU3OC8zMjAxNzU0NTAtYWM0NTkyMTAtODY0MC00MjEyLWE1ZjItZjQ1MmY4ODJiZDA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEzMDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNWIzMGM3MTExZjUyYTBhZGRjYjBlNjcyZTUyMzNmN2I5YWQ4NTA2YzgxM2FlMTJlMzcxYjUwZTMzNWQ2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vb9GvgvBmPprHxfAANSf5sQIeBHWassiKFQU7G_GH_U)
> 
> If there is no `rust_analyzer` there, make sure to install it with `:LspInstall rust_analyzer`. Mason should pop-up and show you the installation process. Wait until you statusline says `"rust_analyzer" was successfully installed.`: ![image](https://private-user-images.githubusercontent.com/23097578/320175491-c97ed5c3-500f-4b0e-b32e-b38924f29960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODE3ODYsIm5iZiI6MTcxMjU4MTQ4NiwicGF0aCI6Ii8yMzA5NzU3OC8zMjAxNzU0OTEtYzk3ZWQ1YzMtNTAwZi00YjBlLWIzMmUtYjM4OTI0ZjI5OTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEzMDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjY4MzE0ZTYwYTdiMjg0NTIxODAzNmI2OGE4YWVjZmQ3Zjc4NThlNDljZTI2YTBjZTU5NGUzOGYzZjk3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cOrtbBysA5PWC2dHxvUPedgwcx8zOJxKjxv-9PYGFe0)
> 
> Press `q` to quit Mason and see if you get any completions or errors on your code: ![image](https://private-user-images.githubusercontent.com/23097578/320175583-f6da0519-fc3d-410b-a521-b64d06e52a7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODE3ODYsIm5iZiI6MTcxMjU4MTQ4NiwicGF0aCI6Ii8yMzA5NzU3OC8zMjAxNzU1ODMtZjZkYTA1MTktZmMzZC00MTBiLWE1MjEtYjY0ZDA2ZTUyYTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEzMDQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZjI0ZWRlMzhjYWNjMDBlN2Y1ZmJiMzgwZjg0NTk3NTE5OWFjZWExMDQ0ZTQ3Y2VjZTVlMGZlMjNmN2QwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KiAZuDWexwAluJykmitm0AR2ikX-JXj0LXCpQtnBpXs)
> 
> If you still don't get any of that, try quitting and entering nvim again. Hope it helps you.

@henrique-marques-vsoft I had some errors highlighted but no autocomplete, i tried using Mason and starting rust-analyzer by rustup run.

**Comment by feoh** [comment]
Hi.

I don't see method/variable auto complete with rust-analyzer either.

Are we sure it offers that? :)

**Comment by feoh** [comment]
@henrique-marques-vsoft I'm a rust newbie but I'm not seeing any of that either. Let me try the diagnostic steps you specified. I know I saw rust-analyzer in lsp-info.

**Comment by henrique-marques-vsoft** [comment]
> 
> @henrique-marques-vsoft I had some errors highlighted but no autocomplete, i tried using Mason and starting rust-analyzer by rustup run.

> I don't see method/variable auto complete with rust-analyzer either.
> Are we sure it offers that? :)

Hmm, that's strange to be honest. I uninstalled neovim and installed again (pacman -S neovim), added the kickstart init lua file and everything is working:
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23097578/6a6ca5f5-f9c3-4bb0-a729-99a4ca854e1e)
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23097578/e22a0792-6751-4f6d-8cd8-df9c934823a6)

**Comment by cirqueira-labs** [comment]
I've tried now, the same steps, removing neovim, update cargo/rustup , installing neovim and kickstart
open a rust project for example rustlings , installing via Mason , and not working autocomplete , nothing showing when C-Space or Tab
But in a Lua project it works well 

![image](https://github.com/nvim-lua/kickstart.nvim/assets/70902061/d2ac26ac-2ce5-43b9-a7e1-088eeae1ae0a)

**Comment by feoh** [comment]
Folks I'm sorry you're having trouble, but I'm quite confident your issues lie not with kickstart.nvim but with your rust_analyzer install.

You might try filing an issue against that repo as that community may be able to help you more readily than we can.

Closing this for now. Thanks for the report.

**Comment by DominicD** [comment]
I had the same problem and found the solution here: https://github.com/nvim-lua/kickstart.nvim/issues/235 maybe it helps you as well @cirqueira-labs

**Comment by ShivamRawat0l** [comment]
I was getting the same error. Turned out i wasn't importing it in the main file and the file was just hanging. 
After importing to the main file it started working.

**Comment by SyedAsadK** [comment]
i was facing this issue... i had the rust package installed (AUR) , uninstalled it and switched to rustup and it fixed this for me
