### ISSUE TITLE
Some of the lsp failed to install.

### ISSUE THREAD

**Issue by shivajee98** [nvim-lua/kickstart.nvim#834]
# Failed to install some lsp
## e.g. groovy_language_server, java_language_server and many more
![Screenshot from 2024-04-09 15-26-16](https://github.com/nvim-lua/kickstart.nvim/assets/130691874/f2dc7233-50a5-4d58-8d69-cc9d292a4836)

**Comment by puttehi** [comment]
Try `groovyls` and `java_language_server`. These are not present in this kickstart configuration so this issue should probably go elsewhere (e.g. Mason if you are using Mason to manage LSP installations).

This is a common problem with LSP management with Nvim, where the "friendly name" and the "real name" are two different things. In `:Mason`, these can be seen easily next to each other.

**Comment by neira-daniel** [comment]
I got a similar message when _uncommenting_ line 543 of init.lua: `pyright: failed to install`.

I'm trying kickstart.nvim in openSUSE-Tumbleweed through WSL2 with nvim v0.9.5.

**Comment by neira-daniel** [comment]
After inspecting the logs of Mason with `:MasonLog` I learned that `npm` is a requirement to install pyright.

Installing npm was enough to solve the problem with pyright.

**Comment by feoh** [comment]
Thanks for your report, but none of this has anything to do with kickstart and is all about your LSP of choice.
