### ISSUE TITLE
Fresh ubuntu/neovim error: Provider "github" "get_latest_release" failed

### ISSUE THREAD

**Issue by mathsten** [nvim-lua/kickstart.nvim#84]
**Describe the bug**
I get the following errors when checking `MasonLog`. This is on a fresh ubuntu 20.04 system and with a fresh neovim stable v.0.8.1 version.

I also double checked in a fresh docker to confirm I got the same errors a second time.

```
...acker/start/mason.nvim/lua/mason-core/installer/init.lua:119: Executing installer for Package(name=lua-language-server)
...acker/start/mason.nvim/lua/mason-core/providers/init.lua:58: Provider "github" "get_latest_release" failed: spawn: wget failed with exit code 4 and signal 0.
...acker/start/mason.nvim/lua/mason-core/providers/init.lua:69: No provider implementation found for github.get_latest_release
...acker/start/mason.nvim/lua/mason-core/installer/init.lua:155: Installation failed for Package(name=lua-language-server) error="...acker/start/mason.nvim/lua/mason-core/installer/init.lua:122: ...start/mason.nvim/l      ua/mason-core/managers/github/init.lua:55: Failed to fetch latest release from GitHub API. Refer to :h mason-provider-errors for more information."

```

**To Reproduce**
1. Install ubuntu 20.04
2. Install git, gcc, g++
3. Install neovim v.0.8.1 via deb release
4. Copy kickstart.nvim into $HOME/.config/nvim/init.lua
5. Run `nvim` and see that all packages except `telescope-fzf-native.nvim` is installed correctly
6. Quit and run `nvim` again, 8/8 treesitter modules is installed correctly
7. Quit and run `nvim` again to see that nvim prints `[mason-lspconfig.nvim] installing sumneko_lua` forever.
8. Run `:MasonLog` and see error.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Terminal: gnome-terminal

**Neovim Version**
 - Output of running `:version` from inside of neovim:

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by mathsten** [comment]
While writing this ticket I realize that this might primarily be a mason.nvim issue?

**Comment by craigmac** [comment]
Make sure you have `cargo` binary available on path to build the lua language server, check `:echo executable('cargo')`

**Comment by mathsten** [comment]
I did not, but I installed it now, and `:echo executable('cargo')` returns `1`, but the same errors persist.

**Comment by craigmac** [comment]
You sure you have `:echo executable('wget')` on $PATH?

**Comment by mathsten** [comment]
Yep, wget returns true as well.

```
  mason: require("mason.health").check()    
  ========================================================================    
  ## mason.nvim report    
    - OK: neovim version >= 0.7.0    
    - WARNING: Go: not available        
    - OK: cargo: `cargo 1.66.0 (d65d197ad 2022-11-15)`        
    - WARNING: luarocks: not available        
    - WARNING: Ruby: not available        
    - WARNING: RubyGem: not available        
    - WARNING: Composer: not available        
    - WARNING: PHP: not available        
    - ERROR: npm: not available        
    - ERROR: node: not available        
    - WARNING: python3: not available        
    - WARNING: pip3: not available        
    - WARNING: javac: not available        
    - WARNING: java: not available        
    - WARNING: julia: not available        
    - OK: wget: `GNU Wget 1.20.3 built on linux-gnu.`        
    - OK: curl: `curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0            libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3`
    - OK: gzip: `gzip 1.10`        
    - OK: tar: `tar (GNU tar) 1.30`        
    - WARNING: pwsh: not available        
    - OK: bash: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`        
    - OK: sh: `Ok`        
    - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Wed Dec 21 22:25:57 2022.    
```

**Comment by craigmac** [comment]
https://github.com/williamboman/mason.nvim/blob/ba8f01835cdcf512d5ab1abb1dcedfaf7c07b99e/doc/mason.txt#L342 try suggestions there

**Comment by mathsten** [comment]
Thank you for your helpful suggestions! I should have read the help section more careful the first time around! The issue was corporate vpn that caused SSL issues.
