### ISSUE TITLE
E5113: Error while calling lua chunk: /home/$USER/.config/nvim/init.lua:227: module 'lazy' not found:

### ISSUE THREAD

**Issue by brayo-pip** [nvim-lua/kickstart.nvim#841]
## Describe the bug

I get the above error after cloning into the config folder as stated in the instructions

## Desktop

- OS: Arch
- Terminal: Gnome terminal

## Neovim Version

0.9.4
```
```

**Comment by feoh** [comment]
Please try clearing out your local cache and restarting neovim:

$HOME/.local/share/nvim
$HOME/.cache/nvim

and restart.

**Comment by brayo-pip** [comment]
Reinstalled in a fresh distro. It works now
