### ISSUE TITLE
Scroll up Ctrl+U not working with clean install.

### ISSUE THREAD

**Issue by ChrisTaylorDeveloper** [nvim-lua/kickstart.nvim#845]
## Describe the bug
Following a clean install of kickstart.nvim, scroll up with `Ctrl+U` is not working.  Scroll down with `Ctrl+D` is working OK.  If I start with `nvim --clean` then `Ctrl+U` is working.

## To Reproduce
Perform a clean install of kickstart.nvim and try `Ctrl+U`.

## Desktop
- OS: Ubuntu 22.04.4 LTS
- Terminal: Gnome terminal

## Neovim Version
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

**Comment by dam9000** [comment]
This works fine for me, what does this say:
```
nmap <c-u>
```
It should say `No mapping found`

**Comment by ChrisTaylorDeveloper** [comment]
When I run `nmap <c-u>` the response is `no mapping found`.

**Comment by ChrisTaylorDeveloper** [comment]
I think the problem might be tmux.
