### ISSUE TITLE
Treesitter: Error during download, please verify your internet connection

### ISSUE THREAD

**Issue by nfgferreira** [nvim-lua/kickstart.nvim#847]
## Describe the bug
The treesitter instalation gave the error above for me.

## To Reproduce
Install Kickstart and run Neovim

## Desktop
- OS: WSL, Ubuntu
- Terminal: Stock terminal

## Neovim Version
0.9.5

## Additional notes

The problem was fixed for me after adding `require("nvim-treesitter.install").prefer_git` = true as described here: [https://github.com/nvim-treesitter/nvim-treesitter/issues/3232]

I suspect that the issue may have happened because I am using a corporate PC with some network access limitations. I think it is worth mentioning in the good description provided by the init.lua file.

**Comment by feoh** [comment]
Hi guys. This could be fixed if we add prefer_git as per [this treesitter issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/3232).

```lua
require("nvim-treesitter.install").prefer_git = true
```

Want me to generate a pull request? I'd fixed it this way locally but didn't know how well the change would be received so I didn't PR.

Also, I seem to have lost the fix in my local fork. I sometimes wonder how much churn and lost code I suffer from just maintaining the silly fork :)

**Comment by dam9000** [comment]
@feoh you opened a similar PR already in the past:
https://github.com/nvim-lua/kickstart.nvim/pull/654

But the comment was wrong because it implied precompiled binaries, so removing the mention of precompiled binaries and opening a new PR sound like a good idea.

**Comment by feoh** [comment]
OK. I'm honestly not entirely sure how to translate that syntax into lazy.nvim

I *THINK* maybe I just add `prefer_git = true` to the opts = section?

**Comment by dam9000** [comment]
@feoh I checked the treesitter code and it appears that the prefer_git is not a global treesitter cofig option but a local to the `nvim-treesitter.install` module, so using lazy `opts` will not work. This should work:
```
diff --git a/init.lua b/init.lua
index 496f45b..a3128a1 100644
--- a/init.lua
+++ b/init.lua
@@ -817,6 +817,7 @@ require('lazy').setup({
     config = function(_, opts)
       -- [[ Configure Treesitter ]] See `:help nvim-treesitter`
 
+      require('nvim-treesitter.install').prefer_git = true
       ---@diagnostic disable-next-line: missing-fields
       require('nvim-treesitter.configs').setup(opts)
```
I tested it with:
```
:lua vim.print(require('nvim-treesitter.install').prefer_git)
```
and it says true.

btw, the prefer_git is already set to true by default on native Windows:
```
nvim-treesitter/install.lua:
M.prefer_git = fn.has "win32" == 1
```
But not for WSL which pretends to be ubuntu, so on WSL prefer_git is false and the issue is reported on WSL.

**Comment by feoh** [comment]
@dam9000 PR submitted. Thank you for the assist. lazy.nvim still throws me sometimes :)

**Comment by Fred-Vatin** [comment]
If you’re still having issue like me, check this other [issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/3232#issuecomment-2695968260).
