### ISSUE TITLE
which-key bug preventing normal key function

### ISSUE THREAD

**Issue by BirdeeHub** [nvim-lua/kickstart.nvim#849]
## Describe the bug

On fresh install of kickstart, pressing ```"``` key causes this error, and cancels operator pending
```
E5107: Error loading lua [string ":lua"]:1: ')' expected near '", {mode = "'
```
This is because of the which-key plugins.registers option

Also on a fresh install, pressing ```<C-w>``` will not work.

Instead, it will show ```<80> ^DW``` in the bottom right key pending display, and then pretends the key you pressed was the number 23

This is because of the which-key plugins.presets.windows option

## To Reproduce

1. go through setup instructions for kickstart.nvim on any linux system (have tried on ubuntu, kali, arch, and nixos)
2. press ```"``` or ```<c-w>```
3. observe above behavior

To "fix"
```lua
      require('which-key').setup {
        -- some features of which key prevent normal functioning of the key
        -- this is a bug, so we will disable the problematic features.
        -- which-key is very useful for those new to vim motions, so it is still included.
        plugins = {
          -- this will currently prevent the " keybind from working in normal mode.
          registers = false, -- shows your registers on " in NORMAL or <C-r> in INSERT mode
          presets = {
            -- this will currently prevent the <C-w> keybinds from working in normal mode.
            windows = false, -- default bindings on <c-w>
          },
        },
      }
```

## Desktop

- OS: ubuntu, kali, arch, nixos on WSL, bare metal, or vm
- Terminal: alacritty (I also have experienced this bug on xfce4-terminal and windows terminal, I have not tried any others for this bug)

## Neovim Version

Keep in mind, this has been a bug since at least 0.9, but here is my current version

```
NVIM v0.10.0-dev
Build type: Release
LuaJIT 2.1.1693350652
Run ":verbose version" for more info
```

**Comment by dam9000** [comment]
This works fine for me (on fedora, nvim 0.9.5). I will try other platforms later.
Are you sure this isn't an issue with your setup?

**Comment by dam9000** [comment]
I made some more tests on various platforms and it seems to work fine for me everywhere.
I think this must be some odd config or install issue on your end.
Here are the tests for the `"` in:

ubuntu 22.04 nvim 0.10 alacritty:
![nvim0100-ubuntu2204-alacritty](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/48f967c1-8c27-408e-ac80-8c771b17a478)

ubuntu 22.04 nvim 0.10 gnome-terminal:
![nvim-0100-ubuntu2204](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/449ce7cb-48dc-4692-8aea-59c2128a315b)

windows 10 nvim 0.9.5 cmd:
![nvim095-win10](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/a1123e27-fdca-4ecb-bafa-89ac9dc4623f)

windows 10 WSL nvim 0.10:
![nvim-0100-win10-wsl](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/3054bf59-7621-4998-b51b-df1a6c6ed1f4)

**Comment by BirdeeHub** [comment]
I have no clue what is causing this, but I tried having only which-key and no other plugins and as you say, it seems to work?!?!

But I had tried with a fresh install of nvim on a vm for kickstart, followed the instructions to install kickstart, and it gave the errors described and I cant figure out what is causing the issue, i tried disabling a bunch of stuff, and nothing was changing until I diabled those... It was a thing when I started with kickstart about 8 months ago, and its still a thing now, on many different linux distros

I have no clue whats going on, but SOMETHING is a problem lol

Im setting up a new vm to test in a little bit here, Im going to download nvim and kickstart on it, and very systematically disable every other thing 1 at a time until ```"``` and ```<c-w>``` starts working again so that I can find the issue.

**Comment by BirdeeHub** [comment]
HMMMM

So, It appears that I did not try it properly since the rework. I could have sworn I did.....

Sorry for wasting your time... what the actual heck is going on though?!

Gonna be searching for this one for a while

It was definitely an existing bug with the previous kickstart version, but I have absolutely no idea what could be causing it anymore.

**Comment by BirdeeHub** [comment]
The reason I filed this was because I watched primeagen help anthonyGG and I saw his ```<c-w>``` was also not working and so I assumed it was still a bug, and it was there last I had tested it so I just submitted the fix without enough testing.

**Comment by BirdeeHub** [comment]
vim.o.cpoptions = 'I'


It is caused by this option.........................

I forgot when I was trying it out I swapped the options for my options.....................

**Comment by BirdeeHub** [comment]
vim.o.cpoptions = (vim.o.cpoptions or '') .. 'I'

This fixes it....
