### ISSUE TITLE
Nerd fonts not loading without additional steps

### ISSUE THREAD

**Issue by yamanmucahit** [nvim-lua/kickstart.nvim#853]
## Describe the bug
Having a nerd font installed and setting ```vim.g.have_nerd_font in init.lua``` to ```true``` is not enough to make neovim use a nerd font. You also need to set the font your terminal emulator is using to a nerd font in order for this to work properly hence the wording is wrong and lacks precision.

## To Reproduce
1. have a nerd font installed
2. set ```vim.g.have_nerd_font in init.lua``` to ```true```
3. open neovim

## Desktop
- OS: Windows
- Terminal: Powershell

## Neovim Version
0.9.5

**Comment by kirankumarmanku** [comment]
Same issue. I am using Mac and iTerm2. I had to install Nerd Font and had to select font version to use in iTerm preferences to see the icons.
