### ISSUE TITLE
Failed to run `config` for which-key.nvim

### ISSUE THREAD

**Issue by ericd33** [nvim-lua/kickstart.nvim#855]
## To Reproduce

1.  Follow kickstart install instructions
2.  Execute nvim

## Desktop

- OS: 
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- Terminal: Windows Ubuntu wsl

## Neovim Version

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

I get the following errors from which-key plugin every time I open nvim, apparently there's some conflicting keys, If I comment the default mapped keys provided it stops. I'd like to not modify the init.lua that was given from the get go. Is this my error? How can I fix it?

```
Failed to run `config` for which-key.nvim
...al/share/nvim/lazy/which-key.nvim/lua/which-key/util.lua:128: {
  internal = { "<", "s", "p", "a", "c", "e", ">", "d", "_" },
  keystr = "<leader>d_",
  notation = { "<", "l", "e", "a", "d", "e", "r", ">", "d", "_" }
}

# stacktrace:
  - /which-key.nvim/lua/which-key/util.lua:128 _in_ **parse_keys**
  - /which-key.nvim/lua/which-key/mappings.lua:183
  - vim/shared.lua:0 _in_ **parse**
  - /which-key.nvim/lua/which-key/keys.lua:208 _in_ **register**
  - /which-key.nvim/lua/which-key/init.lua:73 _in_ **register**
  - init.lua:195 _in_ **config**
```

**Comment by dam9000** [comment]
This seems strange:
```
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```
Are you mixing your native Windows and WSL configs?

This is what I get on WSL:
```
  fall-back for $VIM: "/usr/share/nvim"
```
This is what I get on native Windows:
```
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

nvim with kickstart works for me in both WSL and native Windows.
Have you tried following the install steps mentioned in the README for windows (via choko) or wsl install?

**Comment by ericd33** [comment]
![image](https://github.com/nvim-lua/kickstart.nvim/assets/23160003/6bf662ab-6888-477e-a508-73ce65062166)
This is what I'm using I thought this was wsl, now that I re-check it turns out it is very different? I don't get why it shouldn't be workinf if it's in it's own environment supossedly. I'll try installing wsl the other way and then installing everything on it

**Comment by ericd33** [comment]
Ok so It works now, I think the problem was that I didn't fork and clone, I just copied the init.lua and I assumed it would work. Thanks for the help
