### ISSUE TITLE
no key combination accepts autocomplete suggestion

### ISSUE THREAD

**Issue by alanifotis** [nvim-lua/kickstart.nvim#866]
## Describe the bug

no key combination accepts autocomplete suggestion
I've tried enter & enter + ctrl/shift/alt 
nothing makes it possible to accept the autocomplete 

https://github.com/nvim-lua/kickstart.nvim/assets/44728074/6f849992-8d5b-4765-bb73-7d3743ee3538

PS. sorry if i'm opening this issue in the wrong place 

## To Reproduce

1. Fresh build of neovim and I installed kickstart
2. No matter in what language and lsp(even with the ones included in the init.lua) 
3. Try pressing on the autocomplete suggestion no way to accept it
4. I can freely move to another suggestion 
5. English isn't my first language and maybe I am not using the correct terminology but you can see it better in the video 😅😅

## Desktop

- OS: tried on windows and linux
- Terminal: windows terminal/ gnome terminal, kitty and alacrity

## Neovim Version

:version                                                                                                                NVIM v0.10.0-dev-2947+ge1ca7a7bf                                                                                        Build type: RelWithDebInfo                                                                                              LuaJIT 2.1.1710088188                                                                                                   Run ":verbose version" for more info

```
```

**Comment by dduyanhhoang** [comment]
Meet the same problem in Powershell on Windows 11 and also on WSL (Ubuntu LTS) (both on windows terminal) using the current version of kickstart nvim. I have already check the prerequisites (git, make, unzip, gcc, ripgrep) and language installation.

**Comment by feoh** [comment]
Folks, do you have any language servers installed?

Type :Mason to get started.

**Comment by dduyanhhoang** [comment]
<img width="915" alt="image" src="https://github.com/nvim-lua/kickstart.nvim/assets/137117837/7e822634-9140-46bb-bc03-f89af16e39bd">

Yes. Currently I use nvim for python. Same problem with clangd when I was using kickstart on wsl.

**Comment by dam9000** [comment]
This is a recurring question, duplicates:

https://github.com/nvim-lua/kickstart.nvim/issues/816  Autocomplete keybindings not functioning as before

https://github.com/nvim-lua/kickstart.nvim/issues/851  How to use Autocomplete

And the answer is, the keymap was changed in the recent rewrite from `<enter>` to `<c-y>` so `ctrl-y` to confirm a autocomplete selection. Try if that works.

If you don't like the `c-y` keymap, here is how to restore to the previous "classic" keymaps:

```
diff --git a/init.lua b/init.lua
index 62d2c5c..ce2abb6 100644
--- a/init.lua
+++ b/init.lua
@@ -720,6 +720,11 @@ require('lazy').setup({
           --  This will expand snippets if the LSP sent a snippet.
           ['<C-y>'] = cmp.mapping.confirm { select = true },
 
+          -- Classic completion keymaps
+          ['<CR>'] = cmp.mapping.confirm { select = true },
+          ['<Tab>'] = cmp.mapping.select_next_item(),
+          ['<S-Tab>'] = cmp.mapping.select_prev_item(),
+
           -- Manually trigger a completion from nvim-cmp.
           --  Generally you don't need this, because nvim-cmp will display
           --  completions whenever it has completion options available.
```
For more info:
https://github.com/hrsh7th/nvim-cmp?tab=readme-ov-file#recommended-configuration
https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings

@feoh should we add that as a commented-out example? Should I open such a PR?

**Comment by dduyanhhoang** [comment]
It does do the work. Thanks @dam9000 . I'll try to read the init before positing more question.

**Comment by alanifotis** [comment]
Thank you @dam9000 for your help i will close the issue now

**Comment by jxu** [comment]
Can the default be restored to Enter or Tab? That is much more familiar for most users.

**Comment by TheLustriVA** [comment]
`ctrl-y` doesn't work on my setup, last updated in the last week of May, 2025. 

Blink.cmp has its `opts` `keymap` as `preset = 'default',`

**Comment by dduyanhhoang** [comment]
@TheLustriVA I just got the fresh installation and `CTRL - Y` working just fine (Ubuntu 24.04, NVIM v0.12.0-dev)

>         -- 'default' (recommended) for mappings similar to built-in completions
>         --   <c-y> to accept ([y]es) the completion.
>         --    This will auto-import if your LSP supports it.
>         --    This will expand snippets if the LSP sent a snippet.

From https://github.com/nvim-lua/kickstart.nvim/blob/3338d3920620861f8313a2745fd5d2be39f39534/init.lua#L817-L820

**Comment by heshan-g** [comment]
For anyone wanting to override the default `blink-cmp` keybinding:

```
diff --git a/init.lua b/init.lua
index ff651a0..86dc2e4 100644
--- a/init.lua
+++ b/init.lua
@@ -838,6 +838,8 @@ require('lazy').setup({
         -- See :h blink-cmp-config-keymap for defining your own keymap
         preset = 'default',

+        ['<CR>'] = { 'select_and_accept' },
+
         -- For more advanced Luasnip keymaps (e.g. selecting choice nodes, expansion) see:
         --    https://github.com/L3MON4D3/LuaSnip?tab=readme-ov-file#keymaps
       },
```

**Comment by heshan-g** [comment]
If anybody still needs to change the config back to ENTER using `blink.cmp`:

```
diff --git a/init.lua b/init.lua
index 014f51d..e817b7b 100644
--- a/init.lua
+++ b/init.lua
@@ -840,6 +840,8 @@ require('lazy').setup({
         -- See :h blink-cmp-config-keymap for defining your own keymap
         preset = 'default',

+        ['<Enter>'] = { 'select_and_accept', 'fallback' },
+
         -- For more advanced Luasnip keymaps (e.g. selecting choice nodes, expansion) see:
         --    https://github.com/L3MON4D3/LuaSnip?tab=readme-ov-file#keymaps
       },
```

Using `<Enter>` instead of `<CR>` lets you enter new lines in insert mode when you don't see the autocomplete list, which I find ideal.

**Comment by jxu** [comment]
I like Tab for auto-complete, as it matches bash autocomplete and some other popular text editors.
In my opinion, the classic keybinds make more sense than c-y.
