### ISSUE TITLE
feat: Add spell checker ?

### ISSUE THREAD

**Issue by afifurrohman-id** [nvim-lua/kickstart.nvim#878]
# Probably needed for starting?

```lua
vim.opt.spell = true
vim.opt.spelllang = 'en_us'
```

**Comment by dam9000** [comment]
Well, enabling it by default and setting the language is probably a user customization.
However, I can propose a keymap to toggle the spell checking, here is a PR: https://github.com/nvim-lua/kickstart.nvim/pull/879

**Comment by afifurrohman-id** [comment]
> Well, enabling it by default and setting the language is probably a user customization. However, I can propose a keymap to toggle the spell checking, here is a PR: #879

Hmm alright, but i think add example within commenting may is worth?

**Comment by feoh** [comment]
Hi.

The universe of potential extensions to Neovim is *VAST*.

Kickstart doesn't try to be all things to all people.

Spell checking is a feature with MANY contexts. I personally enable it via filetype plugins for Markdown and Text, and that's all.

The feature is extremely well documented in the standard Neovim docs [here](https://neovim.io/doc/user/spell.html).

All I had to do was do a web search on "Neovim spelling" to find it.

Thanks for your contribution, but I don't think this is a good fit for kickstart at this time.
