### ISSUE TITLE
Kinoite: installation failed - clone failed LuaSnip

### ISSUE THREAD

**Issue by sonlar** [nvim-lua/kickstart.nvim#882]
## Describe the bug

LuaSnip fails during installation of kickstart. At first I was trying to setup neovim and kickstart in toolbox since I use Kinoite. Later on I tried to layer neovim and still ran into the same issue. I followed the advice in ["failed to update LuaSnip via Lazy.nvim"](https://github.com/L3MON4D3/LuaSnip/issues/1071) thinking I had the same issue by editing init.lua in [my fork](https://github.com/sonlar/kickstart.nvim/tree/master).
![VTADTMt](https://github.com/nvim-lua/kickstart.nvim/assets/31799749/9887aea3-c10d-41ad-83be-24fe27969922)

## To Reproduce

1. clone repo
2. start nvim

## Desktop

- OS: Fedora Kinoite
- Terminal: Konsole

## Neovim Version

v0.9.5
![Leu3XgN](https://github.com/nvim-lua/kickstart.nvim/assets/31799749/20d52563-e46d-4034-aa2e-9cbfdbc95910)

```
```

**Comment by feoh** [comment]
Hi.

Sorry you're having trouble but kinoite is a pretty arcane platform to get support for.

Could it be the OOM killer? Or are you seeing some weird artifact of containerization?
