### ISSUE TITLE
Clipboard tool not listed as dependency

### ISSUE THREAD

**Issue by stgpepper** [nvim-lua/kickstart.nvim#884]
## Describe the bug
Installation instructions do not include installation of clipboard tool. Still suing the system clipboard is on by default. This might cause confusion to new users when starting out. On my case I found this out when trying things out in fresh Ubuntu install. On my situation installing xclip solved the issue.

## To Reproduce
1. Use newly installed Ubuntu (mine running on wsl2).
2. Only install dependencies specified in documentation.
3. Install neovim and neovim kickstart as per documentation.
4. Run neovim and try to copy anything from a file to a system clipboard.

## Desktop
- OS: Ubuntu LTS 22.04
- Terminal: ?

## Neovim Version
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

## Also...
There might be also some other application

**Comment by dam9000** [comment]
@stgpepper opened a PR to address this, please review: https://github.com/nvim-lua/kickstart.nvim/pull/886

**Comment by stgpepper** [comment]
> @stgpepper opened a PR to address this, please review: https://github.com/nvim-lua/kickstart.nvim/pull/886
> 

I would review, but sadly I lack foundational knowledge of the scope of this issue. The solution in PR looks like it would work in my case. And if it were included in the docs from the get go it probably would have saved me some debugging time. I simply dont know what other options are available and what limitations migth be present and therefore feel incompetent to say wheter or not it works for the community.

That said, looks good to me and appreciate the PR 👍. Probably better that someone more experienced on the subject would actually aprove it if nessessary.
