### ISSUE TITLE
Refactor lazypath: is it possible

### ISSUE THREAD

**Issue by ayoubelmhamdi** [nvim-lua/kickstart.nvim#885]
i want to ask about using some convention about the usage of `lazypath`, to be more practice when we test many configs.
i want to send the same [PR](https://github.com/NvChad/starter/pull/22)

```lua
local lazypath = vim.env.LAZY or vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not (vim.env.LAZY or (vim.uv or vim.loop).fs_stat(lazypath)) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end

vim.opt.rtp:prepend(lazypath)

if not pcall(require, "lazy") then
  vim.api.nvim_echo({ { ("Unable to load lazy from: %s\n"):format(lazypath), "ErrorMsg" }, { "Press any key to exit...", "MoreMsg" }}, true, {})
  vim.fn.getchar()
  vim.cmd.quit()
end
```
or hardcode the `lazypath`:
```lua
local lazypath = vim.fn.stdpath "data" .. "/lazykickstart/lazy.nvim"
```

but's, maybe i am wrong about simplicity of using many configs.

**Comment by dam9000** [comment]
@ayoubelmhamdi you want to use multiple configs with neovim?
Then the easiest is to use the NVIM_APPNAME as suggested in the README FAQ:
https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#faq


- Can I keep my existing configuration in parallel to kickstart?

Yes! You can use [NVIM_APPNAME](https://neovim.io/doc/user/starting.html#%24NVIM_APPNAME)=nvim-NAME to maintain multiple configurations. For example, you can install the kickstart configuration in ~/.config/nvim-kickstart and create an alias:
```
alias nvim-kickstart='NVIM_APPNAME="nvim-kickstart" nvim'
```
When you run Neovim using nvim-kickstart alias it will use the alternative config directory and the matching local directory ~/.local/share/nvim-kickstart. You can apply this approach to any Neovim distribution that you would like to try out.

**Comment by ayoubelmhamdi** [comment]
> When you run Neovim using nvim-kickstart alias it will use the alternative config directory and the matching local directory ~/.local/share/nvim-kickstart. You can apply this approach to any Neovim distribution that you would like to try out.

is awesome, this is very very intuitive, i don't think it's works easily like that, i think i should handle the location of plugins manually.
