### ISSUE TITLE
Post-installation crash/hang on v0.9.5

### ISSUE THREAD

**Issue by HunterSThomp** [nvim-lua/kickstart.nvim#892]
## Describe the bug
Post installation, any command run (simply opening a file 'nvim ./file.cpp', nvim -> :checkhealth, etc.) will crash and/or hang the nvim instance. All installation processes have been completed prior to exiting nvim and restarting post-installation.

I've included a gif where I go from a fresh install, and display the bugs. The gif appears to hang for a short time after the initial hang on nvim init.lua where I'm trying to close nvim if the instance is running, before running a checkhealth which also crashes, leaving no logs.

https://imgur.com/5hTopgi

## To Reproduce

1. Install kickstart
2. Close and re-open
3. Run any command/open any file.

## Desktop

- OS: Windows 10 Pro
- Terminal: Terminal (Powershell)/CMD

## Neovim Version
```
(Installed with Chocolatey)
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
```

**Comment by dam9000** [comment]
Weird, this works fine for me.
Can you try runing:
```
nvim -V8aaa_log --startuptime bbb.log init.lua
```
and then check and perhaps attach the files `aaa_log` and `bbb.log` if that gives any hint on where it hangs.

**Comment by HunterSThomp** [comment]
Here are the two files you've requested.

[aaa.log](https://github.com/nvim-lua/kickstart.nvim/files/15151572/aaa.log)
[bbb.log](https://github.com/nvim-lua/kickstart.nvim/files/15151573/bbb.log)

**Comment by feoh** [comment]
The aaa log just ... dies literally mid-word.

The b log looks like it may have stopped while doing highlighting?

Can you please delete your nvim dir in AppData and try launching Neovim that way? Does it stay loaded and run properly without Kickstart?

**Comment by HunterSThomp** [comment]
Hello,

So, I deleted both nvim and nvim-data from the Appdata directory, and launched nvim via strictly just 'nvim ./main.cpp' and it's working fine. Additionally, I had NvChad running prior to completely wiping everything similar to what I've just done, and switching to kickstart, and was having no issues w/ NvChad.

I do have nvim installed into C:\Tools (plural), which I believe is the default directory installed into by chocolatey, so unless the source is explicitly looking for 'C:\Tool\neovim\bin\nvim.exe' I too am not sure why it would be failing mid log.

**Comment by dam9000** [comment]
Hmm are you sure choco installed to `C:\Tools` ?
Because mine is in `C:\Program Files\Neovim`
Could it be possible you have two installs on your system?
And they are somehow in conflict?
```
C:\Users\vbox>dir "C:\Program Files\Neovim\bin\nvim.exe"
 Volume in drive C has no label.
 Volume Serial Number is 28F0-A6EF

 Directory of C:\Program Files\Neovim\bin

12/30/2023  02:22 PM         5,214,720 nvim.exe
               1 File(s)      5,214,720 bytes
               0 Dir(s)  23,261,732,864 bytes free

C:\Users\vbox>dir "C:\Tools"
 Volume in drive C has no label.
 Volume Serial Number is 28F0-A6EF

 Directory of C:\Tools

02/29/2024  12:58 PM    <DIR>          .
02/29/2024  12:58 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  23,257,382,912 bytes free
```

**Comment by HunterSThomp** [comment]
Seems for me Chocolatey installs to C:\Tools, not entirely sure why exactly if yours is installing to Program Files. I do not have any other instance of Neovim that I can see in my Install/Uninstall programs and files, nor in Program Files or Program Files (x86).

https://imgur.com/dvqJ7dO

**Comment by dam9000** [comment]
@HunterSThomp disregard my previous message (I deleted it because it was wrong)
I had multiple virtual machines where I tested different install methods and was looking at the wrong one.
Anyway, I just did the all the choco install steps from a clean windows snapshot and it works fine for me, and yes, it does install to `C:\Tools`

**Comment by feoh** [comment]
One thing remains constant though - your log files show a "hard" crash - the last line if your aaa log is:

```
finished sourcing C:\Users\Hunter\AppData\Local\nvim-data\lazy\cmp-nvim-lsp\after/plugin/cmp_nvim_lsp.lua
continuing in nvim_exec2() ca%

```

When you ran choco install did you use the appropriate permissions? It usually whines at me about such things and I just run gsudo choco install. That may not be best practice but it works for me :)

**Comment by HunterSThomp** [comment]
@feoh I always run choco from an elevated (windows) terminal, otherwise it won't install anything. However, I believe this issue not to be 100% the fault of kickstart, because something extremely similar happened with running the starter for Lazy. I suspect something is not playing well with my system, or the way it's setup, but haven't narrowed it down to what.

I will point out that NvChad, for whatever reason, seems to work with no issues. Given that it also relies on Lazy, as does the Lazy starter, as well as Kickstart, I'm really left scratching my head as to what is causing the issue.

Given that I don't believe this issue to be pertinent to this particular repo, I'll be closing this ticket. Thanks for the help.
