### ISSUE TITLE
init.lua not working

### ISSUE THREAD

**Issue by fractalspace** [nvim-lua/kickstart.nvim#90]
Following the instructions in https://www.youtube.com/watch?v=stqUbv-5u2s, the configuration did not work as expected.

**To Reproduce**
1. copy init.lua from this repo to ~/config/nvim/
2. Start nvim

Expected results:
Plugins get loaded, new features such as file search, colors etc are available.
Actual resuts:

no change in nvim before installing init.lua

Error detected while processing /home/admin/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/admin/.config/nvim/init.lua:7: Vim(p
ackadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
stack traceback:
        [C]: in function 'cmd'
        /home/admin/.config/nvim/init.lua:7: in main chunk

**Desktop (please complete the following information):**
- OS:  Linux ubuntu 22.04.01
- Terminal: bash?

** Neovim Version **
 - Output of running `:version` from inside of neovim:
:version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

**Comment by craigmac** [comment]
You need a newer version of Neovim: 

> Kickstart.nvim targets only the latest ['stable'](https://github.com/neovim/neovim/releases/tag/stable) and latest ['nightly'](https://github.com/neovim/neovim/releases/tag/nightly) of Neovim. If you are experiencing issues, please make sure you have the latest versions.

**Comment by tjdevries** [comment]
Thanks @craigmac . That's correct. If you still have the issue on latest nvim, let me know. Closing.
