### ISSUE TITLE
I don't know what this error is

### ISSUE THREAD

**Issue by Zekdes** [nvim-lua/kickstart.nvim#904]
Every time I open a file this happens

![Captura de tela 2024-05-04 110613](https://github.com/nvim-lua/kickstart.nvim/assets/53283981/75d72397-ec70-4d60-9e97-a51df24a341a)

I still can use Neovim normally, I just wandering if I did something wrong
The version of my Neovim is 0.9.5

- OS: Windows 11 
- Terminal: cmd / Powershell

**Comment by dam9000** [comment]
How did you install Neovim?

Which compiler do you have installed? (MS Visual Studio or gcc or ?)

I would suggest:
- uninstall nvim
- delete: `%userprofile%\AppData\Local\nvim`
- delete: `%userprofile%\AppData\Local\nvim-data`
- reinstall following the instructions "Windows with gcc/make using chocolatey" in: https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#windows-installation

**Comment by Sama-004** [comment]
stop using windows bruh

**Comment by feoh** [comment]
No platform shaming please.

**Comment by Zekdes** [comment]
> How did you install Neovim?
> 
> Which compiler do you have installed? (MS Visual Studio or gcc or ?)
> 
> I would suggest:
> 
> * uninstall nvim
> * delete: `%userprofile%\AppData\Local\nvim`
> * delete: `%userprofile%\AppData\Local\nvim-data`
> * reinstall following the instructions "Windows with gcc/make using chocolatey" in: https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#windows-installation

I install nvim on the official web site
and the compliler that I install is GCC

**Comment by Zekdes** [comment]
> How did you install Neovim?
> 
> Which compiler do you have installed? (MS Visual Studio or gcc or ?)
> 
> I would suggest:
> 
> * uninstall nvim
> * delete: `%userprofile%\AppData\Local\nvim`
> * delete: `%userprofile%\AppData\Local\nvim-data`
> * reinstall following the instructions "Windows with gcc/make using chocolatey" in: https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#windows-installation

I did what you recommend to do and the error still persist
howerver, the first time I open a file this show up

![Captura de tela 2024-05-06 123928](https://github.com/nvim-lua/kickstart.nvim/assets/53283981/089ba6ce-6a55-4224-8f2d-164d6d926d34)

I don't know if this helps but here it is

**Comment by feoh** [comment]
Do you have a C compiler installed?

**Comment by Zekdes** [comment]
> Do you have a C compiler installed?

Yes, I install gcc

![Captura de tela 2024-05-06 131712](https://github.com/nvim-lua/kickstart.nvim/assets/53283981/64f8489f-87b7-44d8-9b21-57c2b6307685)

**Comment by feoh** [comment]
What happens if you either:
- install Python (choco install python) 
- OR remove python from the list of treesitter syntaxes?

**Comment by feoh** [comment]
No comment from @Zekdes in a while. Will close due to inactivity in a few days.

**Comment by christophermadsen** [comment]
> > Do you have a C compiler installed?
> 
> Yes, I install gcc
> 
> ![Captura de tela 2024-05-06 131712](https://private-user-images.githubusercontent.com/53283981/328245426-64f8489f-87b7-44d8-9b21-57c2b6307685.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjY2MjYsIm5iZiI6MTcxNTYyNjMyNiwicGF0aCI6Ii81MzI4Mzk4MS8zMjgyNDU0MjYtNjRmODQ4OWYtODdiNy00NGQ4LTliMjEtNTdjMmI2MzA3Njg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE4NTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMmFkYjMxMzJlZTYwYmI1NjYxN2RhNjlkODE2MTc3M2QwYTE1MDE0OTI3YzJiMjllMGM2YWRjZWI5M2IwNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5hnfTjY8HXQ79ymyHiG3yrtSR7agrms4y2Zeok-r3oI)

Still supported versions of GCC are currently 11.4, 12.3, 13.2, 14.1 and 15.0 is in development. I don't know anything about your issue, but maybe update your GCC and then do what @dam9000 suggested again.

**Comment by dam9000** [comment]
@christophermadsen hmm perhaps you are right, the choco installed mingw/gcc version is 13.2.0, so the version that @Zekdes has looks old, perhaps that's the reason for some incompatibility.
Here is what choco says on my win11 for mingw/gcc:

```
C:\Users\vbox>choco info mingw
Chocolatey v2.2.2
mingw 13.2.0
 Title: MinGW-w64 | Published: 10/8/2023
 Package testing status: Passing on Oct 07 2023 19:13:06.
 Number of Downloads: 1113232 | Downloads for this version: 125978
 Package url https://community.chocolatey.org/packages/mingw/13.2.0
 Chocolatey Package Source: https://bitbucket.org/xoviat/chocolatey-packages
 Package Checksum: 'ORgZ1jPrbuQdltDAAO3tzkJuP8WhA9+E4uQLCltrsTbpJ/UV79rtIBtebjLusBcCMG7F1tm0GMljwOeXrtVQvg==' (SHA512)
 Tags: compiler gcc mingw mingw-w64
 Software Site: http://mingw-w64.org/
 Software License: n/a
 Summary: GCC for Windows 64 & 32 bits.
 Description: Mingw-w64 is an advancement of the original mingw.org project, created to support the GCC compiler on Windows systems. It has forked it in 2007 in order to provide support for 64 bits and new APIs. It has since then gained widespread use and distribution.

1 packages found.

C:\Users\vbox>gcc --version
gcc (x86_64-posix-seh-rev0, Built by MinGW-Builds project) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by christophermadsen** [comment]
I would also recommend [scoop](https://scoop.sh/#/) over chocolatey.

Unless you've got a specific setup, why not try and uninstall all the requirements of Kickstart and reinstall with scoop/chocolatey?

```powershell
choco uninstall neovim git ripgrep wget fd unzip gzip mingw make
choco install -y neovim git ripgrep wget fd unzip gzip mingw make
```

or

```powershell
choco uninstall neovim git ripgrep wget fd unzip gzip mingw make
scoop neovim git ripgrep wget fd unzip gzip mingw make
```

**Comment by Zekdes** [comment]
> I would also recommend [scoop](https://scoop.sh/#/) over chocolatey.
> 
> Unless you've got a specific setup, why not try and uninstall all the requirements of Kickstart and reinstall with scoop/chocolatey?
> 
> ```powershell
> choco uninstall neovim git ripgrep wget fd unzip gzip mingw make
> choco install -y neovim git ripgrep wget fd unzip gzip mingw make
> ```
> 
> or
> 
> ```powershell
> choco uninstall neovim git ripgrep wget fd unzip gzip mingw make
> scoop install neovim git ripgrep wget fd unzip gzip mingw make
> ```

ok, so I tried to do  what you said to me
and then use 'gcc -version' to see if works
and this show up

![Captura de tela 2024-05-13 211422](https://github.com/nvim-lua/kickstart.nvim/assets/53283981/6494712e-0b33-4ef2-9938-548abfc4468f)

so now my current theory is that I have two versions of gcc in my computer 
and in case anyone is wondering if I install correctly, here is the proof

![Captura de tela 2024-05-13 212005](https://github.com/nvim-lua/kickstart.nvim/assets/53283981/2cbd4009-499c-4fea-8486-da6c7fb9cb32)

**Comment by dam9000** [comment]
That has to be it,  find the old gcc version and uninstall it. Any idea how you installed it?

**Comment by Zekdes** [comment]
So, I went in to the file explore to see if my theory was correct, and it was
there was two versions of MinGW, one was in the program data with the version 13.x
and one in his own folder with the version 6.x

So just to see what happens I remove the folder with the version 6 and then use the 'gcc --version'
and this show up

![Captura de tela 2024-05-13 221819](https://github.com/nvim-lua/kickstart.nvim/assets/53283981/c27f2fe7-78a4-48a5-b2f2-7df5be4d3117)

now, I open Neovim if the error still there and ...

![Captura de tela 2024-05-13 222042](https://github.com/nvim-lua/kickstart.nvim/assets/53283981/2001ea82-0511-4cfb-a5e4-576d25ae813c)

and remember, I unstall and install everything 
so this is a 'new' neovim with the same error

**Comment by dam9000** [comment]
Did you also delete `AppData/local/nvim-data` ?

**Comment by Zekdes** [comment]
> Did you also delete `AppData/local/nvim-data` ?

I did what you asked, and I can finaly say It was solved

thank you very much for the attention and patience
you guys are awesome

**Comment by dam9000** [comment]
:partying_face: :tada:
