### ISSUE TITLE
Gitsignes errors whenever there is not a git repo in the parent folder.

### ISSUE THREAD

**Issue by a73s** [nvim-lua/kickstart.nvim#905]
## Describe the bug
Gitsignes gives errors when opening neovim whenever it cannot find a git repo in the parent. 
Maybe there is a way to prevent gitsignes from running for folders where there is not git repo.

## To Reproduce

1. open a file with nvim which does not have a git repo in it's parent folder

## Desktop

- OS: Windows
- Terminal: Alacritty

## Neovim Version

```
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJit 2.1.1703942320
```

**Comment by dam9000** [comment]
What errors?
Can you post a screenshot?
How did you install nvim?

This works fine for me I'm not seeing any errors outside git.
Perhaps try following these install instructions:
https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#windows-installation
- Windows with gcc/make using chocolatey

**Comment by a73s** [comment]
Ok wtf now its not doing it. I believe its because I updated my plugins. Sorry...

**Comment by a73s** [comment]
https://github.com/lewis6991/gitsigns.nvim/issues/989 I think this fixed it
