### ISSUE TITLE
Error in loading the kickstarter config in kali WSL package.

### ISSUE THREAD

**Issue by detox366** [nvim-lua/kickstart.nvim#906]
The setup of the kickstarter doesn't work for newly built nvim from the source for kali linux in WSL.

## To Reproduce
Build the nvim from source and then run the kickstarter code ```git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim```

## Desktop
OS: Kali GNU/Linux Rolling on Windows 10 x86_64
Kernel: 5.15.153.1-microsoft-standard-WSL2
Uptime: 1 hour, 26 mins
Packages: 3251 (dpkg)
Shell: zsh 5.9
Theme: Kali-Dark [GTK2], adw-gtk3-dark [GTK3]
Icons: Flat-Remix-Blue-Dark [GTK2/3]
Terminal: Relay(12)
CPU: Intel i5-9400F (6) @ 2.903GHz
GPU: b053:00:00.0 Microsoft Corporation Basic Render Driver
Memory: 356MiB / 7918MiB

## Neovim Version
-- Install configuration: "RelWithDebInfo"

Error inside nvim:
```
Error detected while processing /home/kunix/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: module 'vim.diagnostic' not fo
und:
        no field package.preload['vim.diagnostic']
        no file './vim/diagnostic.lua'
        no file '/home/kunix/neovim/.deps/usr/share/luajit-2.1/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic.lua'
        no file '/usr/local/share/lua/5.1/vim/diagnostic/init.lua'
        no file '/home/kunix/neovim/.deps/usr/share/lua/5.1/vim/diagnostic.lua'
        no file '/home/kunix/neovim/.deps/usr/share/lua/5.1/vim/diagnostic/init.lua'
        no file './vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/vim/diagnostic.so'
        no file '/home/kunix/neovim/.deps/usr/lib/lua/5.1/vim/diagnostic.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/home/kunix/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        /home/kunix/.config/nvim/init.lua:165: in main chunk
E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim
```

**Comment by feoh** [comment]
Hi.

We have no way to test this or help you but happy to try to work through it.

It seems like maybe there's a binary dependency you need to have installed here but didn't?

```
E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim
```

Maybe something like neovim-shared or something? I have no sense of Kali, I'm not an Infosec guy :)

**Comment by feoh** [comment]
Just noticed you built from source.

Does /usr/local/share/nvim/runtime/syntax.vim exist?

Does Neovim work on the WSL command line without kickstart installed?

I run Neovim on Ubuntu and Manjaro WSL all the time with zero issue, but I installed from binary packages for both.

Would you consider just installing from a pre-built binary? Kali is Debian based, you could just install that one.

**Comment by feoh** [comment]
No further activity on this. Will close soon.
