### ISSUE TITLE
How to install this

### ISSUE THREAD

**Issue by derrick1001** [nvim-lua/kickstart.nvim#909]
Having a hard time install neovim and just reading the configuration i have. Why isnt this as easy as just installing the program and reading the /home/$USER/.config/nvim/ directory and just working? Nothing works. All kinds of errors, doesnt install initially, its so bad. I love neovim and got it working about a year ago now but now that ive had to change laptops, you cant get anything to just work with my config. This is probably just my misunderstanding of how all this works, but please help! I love neovim and the configuration abilities of it and would like to get it working agiain without all the errors.
## To Reproduce

1. ...

## Desktop

- OS: 
- Terminal: 

## Neovim Version

```
```

**Comment by feoh** [comment]
respectfully, this isn't a Bug report it's a rant or a wine or something. In any case it's not actionable so I'm closing it.

have you considered using something point and drool like visual studio code? You might be happier.

**Comment by derrick1001** [comment]
Wow is this the support you give to your users? I stated that I've used neovim up to now without any problems and without errors, but when I need to copy this configuration to a new machine I am having issues. Your response is very aggressive and demeaning, not something I would expect from a neovim moderator. Perhaps you should help me with my issue instead of dismissing it to some sub par "point and drool" editor as you so un-professionally stated. Or point me in the direction that I could receive help. Instead of being a condescending prick. I hope your superiors can see these email strings.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by feoh** [comment]
You're right. That response was unprofessional on my part, and for that I'm sorry.

The people who volunteer here are just that, volunteers. If you file a bug saying everything sucks nothing works. How precisely do you expect the human on the other end of the line to feel?

So, let's start over.

Please include all the details cited in https://github.com/nvim-lua/kickstart.nvim/blob/master/.github/ISSUE_TEMPLATE/bug_report.md in your bug report. We can't help you if you don't give us any details to go on.

**Comment by derrick1001** [comment]
I apologize as well, my post was a bit of a rant. And honestly it's prob not a bug and just my lack of knowledge on how it should be installed. I'll do more research and figure it out.

I appreciate your response and your time.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by feoh** [comment]
No worries, it happens to the best of us :) Please feel free to file another bug if you have specific questions and please do include all the details in the template. It'll help us help you better :)
