### ISSUE TITLE
Does not work on macOS Ventura 13.1

### ISSUE THREAD

**Issue by senicko** [nvim-lua/kickstart.nvim#91]
I don't know where to start. Installing plugins by packers seems to work fine but after restarting nvim some lua thing (sumneko_lua) is loading for a long time, and it starts loading again every time I press `:w`.  In addition to that I see some treesitter issues and when I select the code I see different things rendered under selection.

What is going on??? 😂 Please help.

**To Reproduce**

1. Install neovim on macOS Ventura 13.1
2. Create init.lua with kickstart.nvim init.lua contents
3. Just open neovim follow installation instructions and restart

**Desktop**

- OS: macOS Ventura 13.1
- Terminal: zsh (using alacritty but the same happens inside of kitty). I have oh-my-zsh installed

** Neovim Version **

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"

https://user-images.githubusercontent.com/25861704/209447827-3a295e2f-5e28-451a-b78b-4830a6989621.mp4


  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

https://user-images.githubusercontent.com/25861704/209447843-f0a76493-e7d9-4d9b-ae0a-a578f266e056.mp4

**Comment by mischavandenburg** [comment]
I needed to install the vim language for treeitter by running `TSInstall vim`

https://stackoverflow.com/questions/70373650/how-to-solve-treesitter-highlighter-error-executing-lua-problem-in-neovim-confi

**Comment by senicko** [comment]
Thanks, it looks like running `:TSInstall vim` solves the issue with treesitter.
