### ISSUE TITLE
Align color scheme with kitty

### ISSUE THREAD

**Issue by kevaldonga** [nvim-lua/kickstart.nvim#914]
Is there way to align neovim color scheme with kitty terminal colors.
I want to set neovim theme whatever kitty theme is, as it is not picking up colors from kitty and it is showing boundry between terminal and neovim.

**Comment by dam9000** [comment]
Not sure which colors you mean, but if you just want to use the same background color in nvim as is defined by the terminal, you can set the `transparent` option like this:
```
diff --git a/init.lua b/init.lua
index 88658ef..02779bc 100644
--- a/init.lua
+++ b/init.lua
@@ -780,6 +780,7 @@ require('lazy').setup({
     -- If you want to see what colorschemes are already installed, you can use `:Telescope colorscheme`.
     'folke/tokyonight.nvim',
     priority = 1000, -- Make sure to load this before all the other start plugins.
+    opts = { transparent = true },
     init = function()
       -- Load the colorscheme here.
       -- Like many other themes, this one has different styles, and you could load
```
For more details see:
https://github.com/folke/tokyonight.nvim

Or you can try to find a different colorscheme that better matches whatever style you prefer.

**Comment by kevaldonga** [comment]
yes I have set up background color to transparent. but what I am saying is I don't want tokyo night or any other theme in neovim I want it to pick up colors from kitty terminal. it that possible ?

**Comment by dam9000** [comment]
You could try using one of the colorschemes that support the terminal defined 16 colors, for example habamax and then force that mode. Try this:
```
:set notermguicolors
:set t_Co=16
:colorscheme habamax
```
This should force the colorscheme to use the cterm instead of the gui defined colors. If you do that with tokyonight it will just go to a black-and-white mode, but habamax and other builtin schemes do support the 16 color modes. To get a list of all builtin colorschemes check: `/usr/share/nvim/runtime/colors`

**Comment by jglueckstein** [comment]
Maybe [this](https://rrethy.github.io/book/colorscheme.html) solution would work for you.

**Comment by feoh** [comment]
In any case, this isn't a kickstart problem. You'd still get a (default) theme from neovim without kickstart, so I'm closing this. Hope folks suggestions have helped.
