### ISSUE TITLE
Cannot install kickstart

### ISSUE THREAD

**Issue by dimensi** [nvim-lua/kickstart.nvim#92]
**Describe the bug**
I've copy kickstart.lua to ~/.config/nvim/init.lua and got a lot of errors from install and restart nvim

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/11390039/209471895-03333a49-a75c-4eda-8943-5f2b7008851c.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/11390039/209471937-f1013775-5598-4a5f-aed4-9b07ad95122b.png">

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/11390039/209471850-ea5cde57-8f50-42dc-96bf-3c0e183b293a.png">

**To Reproduce**
1. Copy install script to config dir

**Desktop (please complete the following information):**
- OS: MacOS 13.1
- Terminal: Terminal.app

** Neovim Version **
 - Output of running `:version` from inside of neovim:

```
:version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

**Comment by AminGholizad** [comment]
I have another problem. it installs everything after first run and after I quit and run `nvim` again I get this error
```
Error detected while processing /home/amin/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/amin/.config/nvim/init.lua:88: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        /home/amin/.config/nvim/init.lua:88: in main chunk
Error in packer_compiled: /home/amin/.config/nvim/plugin/packer_compiled.lua:206: Vim(packadd):E5113: Error while calling lua chunk: .../packer/start/nvim-t
reesitter/plugin/nvim-treesitter.lua:14: attempt to call field 'nvim_create_augroup' (a nil value)^@stack traceback:^@^I.../packer/start/nvim-treesitter/plu
gin/nvim-treesitter.lua:14: in main chunk^@^I[C]: in function 'cmd'^@^I/home/amin/.config/nvim/plugin/packer_compiled.lua:206: in function </home/amin/.conf
ig/nvim/plugin/packer_compiled.lua:10>^@^I[C]: in function 'pcall'^@^I/home/amin/.config/nvim/plugin/packer_compiled.lua:10: in main chunk
Please check your config for correctness
Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:
E5113: Error while calling lua chunk: ...m/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:1: attempt to index field 'keymap' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:1: in main chunk
[nvim-cmp] Your nvim does not has `nvim_create_autocmd` function. Please update to latest nvim.
Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:
E5113: Error while calling lua chunk: ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:15: attempt to call field 'notify_once' (a nil value)
stack traceback:
        ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:15: in main chunk
Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/telescope.nvim/plugin/telescope.lua:
Telescope.nvim requires at least nvim-0.7.0. See `:h telescope.changelog-1851`
Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua:
E5113: Error while calling lua chunk: ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:11: attempt to call field 'nvim_create_augroup' (a nil val
ue)
stack traceback:
        ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:11: in function 'setup'
        .../packer/start/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua:1: in main chunk
Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/cmp_luasnip/after/plugin/cmp_luasnip.lua:
E5113: Error while calling lua chunk: .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:12: attempt to call field 'nvim_create_autocmd' (a nil val
ue)
stack traceback:
        .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:12: in main chunk
        [C]: in function 'require'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:6: in main chunk
        [C]: in function 'require'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:1: in main chunk
        [C]: in function 'require'
        ...ck/packer/start/cmp_luasnip/after/plugin/cmp_luasnip.lua:1: in main chunk
```

**Comment by winthers** [comment]
I got this problem (mac m1 os 13)

        
Error executing lua callback: .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: attempt to call field 'start' (a nil value)
stack traceback:
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:130>

**Comment by mewajda** [comment]
> I have another problem. it installs everything after first run and after I quit and run `nvim` again I get this error
> 
> ```
> Error detected while processing /home/amin/.config/nvim/init.lua:
> E5113: Error while calling lua chunk: /home/amin/.config/nvim/init.lua:88: attempt to call field 'nvim_create_augroup' (a nil value)
> stack traceback:
>         /home/amin/.config/nvim/init.lua:88: in main chunk
> Error in packer_compiled: /home/amin/.config/nvim/plugin/packer_compiled.lua:206: Vim(packadd):E5113: Error while calling lua chunk: .../packer/start/nvim-t
> reesitter/plugin/nvim-treesitter.lua:14: attempt to call field 'nvim_create_augroup' (a nil value)^@stack traceback:^@^I.../packer/start/nvim-treesitter/plu
> gin/nvim-treesitter.lua:14: in main chunk^@^I[C]: in function 'cmd'^@^I/home/amin/.config/nvim/plugin/packer_compiled.lua:206: in function </home/amin/.conf
> ig/nvim/plugin/packer_compiled.lua:10>^@^I[C]: in function 'pcall'^@^I/home/amin/.config/nvim/plugin/packer_compiled.lua:10: in main chunk
> Please check your config for correctness
> Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:
> E5113: Error while calling lua chunk: ...m/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:1: attempt to index field 'keymap' (a nil value)
> stack traceback:
>         ...m/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:1: in main chunk
> [nvim-cmp] Your nvim does not has `nvim_create_autocmd` function. Please update to latest nvim.
> Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:
> E5113: Error while calling lua chunk: ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:15: attempt to call field 'notify_once' (a nil value)
> stack traceback:
>         ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:15: in main chunk
> Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/telescope.nvim/plugin/telescope.lua:
> Telescope.nvim requires at least nvim-0.7.0. See `:h telescope.changelog-1851`
> Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua:
> E5113: Error while calling lua chunk: ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:11: attempt to call field 'nvim_create_augroup' (a nil val
> ue)
> stack traceback:
>         ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:11: in function 'setup'
>         .../packer/start/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua:1: in main chunk
> Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/cmp_luasnip/after/plugin/cmp_luasnip.lua:
> E5113: Error while calling lua chunk: .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:12: attempt to call field 'nvim_create_autocmd' (a nil val
> ue)
> stack traceback:
>         .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:12: in main chunk
>         [C]: in function 'require'
>         ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:6: in main chunk
>         [C]: in function 'require'
>         ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:1: in main chunk
>         [C]: in function 'require'
>         ...ck/packer/start/cmp_luasnip/after/plugin/cmp_luasnip.lua:1: in main chunk
> ```

I am getting the same error using the stable version on popOS installed through ‘apt’.  I am going to try the nightly version so see if that matters.

**Comment by mewajda** [comment]
> > I have another problem. it installs everything after first run and after I quit and run `nvim` again I get this error
> > ```
> > Error detected while processing /home/amin/.config/nvim/init.lua:
> > E5113: Error while calling lua chunk: /home/amin/.config/nvim/init.lua:88: attempt to call field 'nvim_create_augroup' (a nil value)
> > stack traceback:
> >         /home/amin/.config/nvim/init.lua:88: in main chunk
> > Error in packer_compiled: /home/amin/.config/nvim/plugin/packer_compiled.lua:206: Vim(packadd):E5113: Error while calling lua chunk: .../packer/start/nvim-t
> > reesitter/plugin/nvim-treesitter.lua:14: attempt to call field 'nvim_create_augroup' (a nil value)^@stack traceback:^@^I.../packer/start/nvim-treesitter/plu
> > gin/nvim-treesitter.lua:14: in main chunk^@^I[C]: in function 'cmd'^@^I/home/amin/.config/nvim/plugin/packer_compiled.lua:206: in function </home/amin/.conf
> > ig/nvim/plugin/packer_compiled.lua:10>^@^I[C]: in function 'pcall'^@^I/home/amin/.config/nvim/plugin/packer_compiled.lua:10: in main chunk
> > Please check your config for correctness
> > Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:
> > E5113: Error while calling lua chunk: ...m/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:1: attempt to index field 'keymap' (a nil value)
> > stack traceback:
> >         ...m/site/pack/packer/start/Comment.nvim/plugin/Comment.lua:1: in main chunk
> > [nvim-cmp] Your nvim does not has `nvim_create_autocmd` function. Please update to latest nvim.
> > Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:
> > E5113: Error while calling lua chunk: ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:15: attempt to call field 'notify_once' (a nil value)
> > stack traceback:
> >         ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:15: in main chunk
> > Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/telescope.nvim/plugin/telescope.lua:
> > Telescope.nvim requires at least nvim-0.7.0. See `:h telescope.changelog-1851`
> > Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua:
> > E5113: Error while calling lua chunk: ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:11: attempt to call field 'nvim_create_augroup' (a nil val
> > ue)
> > stack traceback:
> >         ...pack/packer/start/cmp-nvim-lsp/lua/cmp_nvim_lsp/init.lua:11: in function 'setup'
> >         .../packer/start/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua:1: in main chunk
> > Error detected while processing /home/amin/.local/share/nvim/site/pack/packer/start/cmp_luasnip/after/plugin/cmp_luasnip.lua:
> > E5113: Error while calling lua chunk: .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:12: attempt to call field 'nvim_create_autocmd' (a nil val
> > ue)
> > stack traceback:
> >         .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/async.lua:12: in main chunk
> >         [C]: in function 'require'
> >         ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:6: in main chunk
> >         [C]: in function 'require'
> >         ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:1: in main chunk
> >         [C]: in function 'require'
> >         ...ck/packer/start/cmp_luasnip/after/plugin/cmp_luasnip.lua:1: in main chunk
> > ```
> 
> I am getting the same error using the stable version on popOS installed through ‘apt’. I am going to try the nightly version so see if that matters.

Turns out of the version of neovim through `apt` was `0.6*`.  I manually downloaded neovim and installed it and everything is working great now

**Comment by BenPearo** [comment]
> I got this problem (mac m1 os 13)
> 
> When i open the init.lua in nvim i get this:
> 
> Error executing lua callback: .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: attempt to call field 'start' (a nil value) stack traceback: .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: in function 'attach' ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module' ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module' ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:130>

I was able to solve this by updating nvim via `brew upgrade nvim`

**Comment by t3kg33k** [comment]
I get this error in Fedora 37 (KDE):
                                                                                                                                                                                                              
```
nvim-treesitter[lua]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
Press ENTER or type command to continue
```


![Screenshot_20221230_075353](https://user-images.githubusercontent.com/4992046/210072250-ea0279b0-eb08-4f5b-852a-53bc14d7fe94.png)

**Comment by Slate245** [comment]
Also having issue as the author above. Fedora 37 Gnome, neovim v.0.8.1

**Comment by Slate245** [comment]
@t3kg33k I've fixed this issue by installing C++ development packages

```sh
sudo dnf install libstdc++-static gcc-c++
```

**Comment by t3kg33k** [comment]
Yep, that worked. Also, git install was also required.

**Comment by trev-dev** [comment]
I had this problem while installing on Windows at one point and it was do to the fact I had git's core.autoclrf set incorrectly.  Try setting it to true with git config --global core.autoclrf true.

You're trying to build the config with invalid line returns.

**Comment by tjdevries** [comment]
Ok -- there's a completely new setup workflow now with lazy.nvim. I'm going to close this issue now, but if you try with the latest version and it doesn't work, please create an issue. Thanks!
