### ISSUE TITLE
How do I add language specific LSP keymaps?

### ISSUE THREAD

**Issue by dotfrag** [nvim-lua/kickstart.nvim#927]
How do I add language specific LSP keymaps? Similarly to how LazyVim does it [here](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/typescript.lua#L13-L58).

Adding the `keys` field the server setup doesn't work. I'm guessing LazyVim does some magic to load them.

How/where can I add this functionality?

**Comment by jglueckstein** [comment]
> Adding the `keys` field the server setup doesn't work. I'm guessing LazyVim does some magic to load them.

Can you show what you tried?

**Comment by dotfrag** [comment]
Yes of course, inside lsp config function:

```lua
local servers = {
  ...
  pyright = {},
  ruff = {
    keys = {
      {
        "<leader>co",
        function()
          vim.lsp.buf.code_action({
            apply = true,
            context = { only = { "source.organizeImports" }, diagnostics = {} },
          })
        end,
        desc = "Organize Imports",
      },
    },
  },
  ...
}
```

When opening a python file, ruff is loaded but the key doesn't register.

**Comment by dam9000** [comment]
That syntax appears to be a LazyVim specific, and is handled by:
`LazyVim/lua/lazyvim/plugins/lsp/keymaps.lua`:
```
    local maps = opts.servers[client.name] and opts.servers[client.name].keys or {}
```

**Comment by dam9000** [comment]
Using kickstart you could try this:
```
diff --git a/init.lua b/init.lua
index 88658ef..6f61c5e 100644
--- a/init.lua
+++ b/init.lua
@@ -513,6 +513,16 @@ require('lazy').setup({
           --
           -- When you move your cursor, the highlights will be cleared (the second autocommand).
           local client = vim.lsp.get_client_by_id(event.data.client_id)
+
+          if client.config.name == 'riff' then
+            map('<leader>co', function()
+              vim.lsp.buf.code_action {
+                apply = true,
+                context = { only = { 'source.organizeImports' }, diagnostics = {} },
+              }
+            end, 'Organize Imports')
+          end
+
           if client and client.server_capabilities.documentHighlightProvider then
             local highlight_augroup = vim.api.nvim_create_augroup('kickstart-lsp-highlight', { clear = false })
             vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {

```

**Comment by dotfrag** [comment]
Thanks @dam9000, that worked perfectly. Also `client.name` works. I don't know if it is any different.

I was hoping to use the `servers.<lang>.keys` table to avoid defining the keys separately to the server config.

I thought that something like `servers[client.config.name].keys` would work, but `vim.print(servers[client.config.name].keys)`  prints `nil`. Do you know if I'm doing something wrong?

**Comment by dam9000** [comment]
:clap:
