### ISSUE TITLE
Language server does not install using termux on android

### ISSUE THREAD

**Issue by hat7004** [nvim-lua/kickstart.nvim#929]
## Describe the bug
Installation occurs and works normally but language server does not work and at startup it produces the following error:

stylua: failed to install
lua-language-server: failed to install

## To Reproduce
Clean install of android for ARM
Install termux app
Install neovim and kickstart dependencies
copy and paste install command
run nvim and wait for the installation to finish
exit nvim and run it again

## Desktop
- OS: Android REL 14 aarch64 on host samsung SM-A536E
- Terminal: Termux

## Neovim Version

```:version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/data/data/com.termux/files/usr/share/nvim"

Run :checkhealth for more info

**Comment by feoh** [comment]
i'm sorry, but I'm afraid installing on android phones is not supported. Good luck and please feel free to write your solutions back here if you should find one.
