### ISSUE TITLE
How to uninstall kickstart.nvim?

### ISSUE THREAD

**Issue by WillNilges** [nvim-lua/kickstart.nvim#93]
**Describe the bug**
I'd like to go back to vanilla neovim and start over. How do I do so?

**To Reproduce**
1. Install kickstart.nvim
2. Read README.md
3. Be confused

**Desktop (please complete the following information):**
- OS: Arch Linux
- Terminal: Alacritty

** Neovim Version **
NVIM v0.8.1

**Comment by GustavoPrietoP** [comment]
just run:
1.  `rm -rf ~/.config/nvim/*`
2. `rm -rf ~/.local/share/nvim/*`

and you should have vanila neovim

**Comment by tjdevries** [comment]
if anyone wants to add to FAQ, it's easy PR ;)
