### ISSUE TITLE
Language servers removed from `servers` table still take affect

### ISSUE THREAD

**Issue by samualtnorman** [nvim-lua/kickstart.nvim#930]
## Describe the bug
I would expect language servers removed from the [`servers`](https://github.com/nvim-lua/kickstart.nvim/blob/5aeddfdd5d0308506ec63b0e4f8de33e2a39355f/init.lua#L567) table to no longer take affect. This is particularly annoying if a language has multiple LSP server options and I change my mind and switch to another.

## To Reproduce

1. Add a language server to the `servers` table
2. Start Neovim and wait for Mason to do its thing
3. Remove it and restart Neovim

## Desktop

- OS: NixOS 23.11.7093.44072e24566c (Tapir) x86_64
- Terminal: tmux 3.3a

## Neovim Version

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/7r7hqkq5gkbh6hxq9s309y6s1li1m99j-neovim-unwrapped-0.9.4/share/nvim"
```

**Comment by dam9000** [comment]
You can run this to remove installed packages that are not listed in ensure_installed:
```
:MasonToolsClean
```
Or add this to init.lua:
```
diff --git a/init.lua b/init.lua
index 88658ef..c125657 100644
--- a/init.lua
+++ b/init.lua
@@ -610,6 +610,9 @@ require('lazy').setup({
       })
       require('mason-tool-installer').setup { ensure_installed = ensure_installed }
 
+      -- remove mason installed packages that are not listed in ensure_installed
+      require('mason-tool-installer').clean()
+
       require('mason-lspconfig').setup {
         handlers = {
           function(server_name)
```

Not sure if this should be the default behaviour or not, perhaps it would be too disruptive and then we would get questions like: "_Why are the packages that I manually install using Mason uninstalled when I restart nvim?_"

**Comment by dam9000** [comment]
@samualtnorman Btw, you seem to be a NixOS user, can you check if you could help with this issue:
https://github.com/nvim-lua/kickstart.nvim/issues/924 "Telescope bindings don't work [on NixOS]"

**Comment by samualtnorman** [comment]
> You can run this to remove installed packages that are not listed in ensure_installed:
> 
> ```
> :MasonToolsClean
> ```
> 
> Or add this to init.lua:
> 
> ```
> diff --git a/init.lua b/init.lua
> index 88658ef..c125657 100644
> --- a/init.lua
> +++ b/init.lua
> @@ -610,6 +610,9 @@ require('lazy').setup({
>        })
>        require('mason-tool-installer').setup { ensure_installed = ensure_installed }
>  
> +      -- remove mason installed packages that are not listed in ensure_installed
> +      require('mason-tool-installer').clean()
> +
>        require('mason-lspconfig').setup {
>          handlers = {
>            function(server_name)
> ```
> 
> Not sure if this should be the default behaviour or not, perhaps it would be too disruptive and then we would get questions like: "_Why are the packages that I manually install using Mason uninstalled when I restart nvim?_"

ty this lua snippet seems to be what I'm looking for
