### ISSUE TITLE
Can we please enable DISCUSSIONS on this repo?

### ISSUE THREAD

**Issue by sumanth-lingappa** [nvim-lua/kickstart.nvim#935]
Other than issues, if we need to discuss some best practices, it will be ideal to converse in the `discussions` tab of the repo. 
Request you to enable the same. 
Thank you.

**Comment by amirmohammaddivani** [comment]
That sounds like a good idea. I hope Teej accepts that.

**Comment by marcthe12** [comment]
Good to have discussions. As kickstarter is a template, discussion can be useful for next steps on how to do customize it

**Comment by alikebrahim** [comment]
That would be very helpful. Would be a platform to help each other figure neovim's powers

**Comment by damccull** [comment]
I would also like to not create new issues which must be closed to just to ask a few questions.

**Comment by feoh** [comment]
None of us have any control over this. Please petition the repo *owners*.

**Comment by sumanth-lingappa** [comment]
How to _petition_ ?
