### ISSUE TITLE
Telescope Current Buffer Fuzzy Find is showing last result

### ISSUE THREAD

**Issue by wiraki** [nvim-lua/kickstart.nvim#939]
## Describe the bug
It is tricky to explain, but basically when I invoke Telescope fuzzy find in the current buffer (with default keymap <Leader>+/) and type in a search string, I am often shown only the last-scoring result. I then need to scroll up or down to see the other results, and importantly the best matches. Here is a screenshot of searching for "leader" inside the kickstart `init.lua`, just after I finish typing the search string:

![image](https://github.com/nvim-lua/kickstart.nvim/assets/11855154/fdc0cdf0-076a-4cc8-8afd-8dd8dba47fd0)

## To Reproduce

1. Install neovim 0.10
2. Get kickstart's `init.lua` as config.
3. Open a file and invoke telescope current buffer fuzzy find with `<Leader>+/`
4. Search for a string.

## Desktop

- OS: Pop!_OS 22.04 LTS x86_64 
- Terminal: kitty 0.34.1

## Neovim Version

```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

**Comment by wiraki** [comment]
Removed the branch field, but then `<leader>/` raises this error:

```
E5108: Error executing lua: ...ck/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:486: attempt to call field 'has_ts_parser' (a nil value)                                                                                                          
stack traceback:                                                                                                                                                                                                                                          
        ...ck/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:486: in function 'v'                                                                                                                                                                  
        ...ck/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:641: in function 'v'                                                                                                                                                                  
        ...-kick/lazy/telescope.nvim/lua/telescope/builtin/init.lua:542: in function 'current_buffer_fuzzy_find'  
```

When Lazy updated the Telescope plugin (after removing the `branch` field), it did print a changelog and mentioning "breaking changes" but I did not pay attention to the details. Maybe one of those changes is affecting now?

**Comment by dam9000** [comment]
I don't know, the change works for me. Try running `:Lazy` and update (`U`) or sync (`S`) all the plugins.

**Comment by wiraki** [comment]
Indeed, I think the Sync did it. Thank you very much :pray:
