### ISSUE TITLE
Initialization problem

### ISSUE THREAD

**Issue by cloyop** [nvim-lua/kickstart.nvim#949]
![Screenshot 2024-05-24 090359](https://github.com/nvim-lua/kickstart.nvim/assets/150424322/0f8f7be6-5180-4266-805c-de16b612b3a5)

**Comment by Gabocota** [comment]
Exact same problem. 
![image](https://github.com/nvim-lua/kickstart.nvim/assets/88735758/d55c4796-c2b0-4d89-bce9-67d80267d979)

**Comment by SahilAli3628** [comment]
The error you're encountering, "attempt to index field 'keymap' (a nil value)," suggests that the vim.keymap module is not available in your version of Neovim. AFAIK This module is specific to Neovim 0.7.0 and later. If you're using an older version of Neovim, it won't recognize the keymap module.

Can you please confirm the version of neovim that you are running is higher than that of 0.7.0 ? If not, can you please try upgrading it

**Comment by cloyop** [comment]
Yes, its was that. thanks!

**Comment by cloyop** [comment]
My version was too old
