### ISSUE TITLE
Very slow with large C++ files in insert mode.

### ISSUE THREAD

**Issue by mwcarlis** [nvim-lua/kickstart.nvim#950]
## Describe the bug:
I'm having issues with neovim being very slow when I am in insert mode while working on large C++ files.  I also noticed that it is using the wrong indentation in these large file.   The file I have here is ~21k lines of C++. 

## To Reproduce

1. Open a large C++ file.  Go into "insert" mode. Subsequent user input will seem very slow/delayed.
2. If I disable treesitter issue seems to go away... 

## Desktop
- OS:  Ubuntu 18
- Terminal: I'm ssh'd via iterm2 into an Ubuntu VM with 40 cores 132 GB of RAM. (Developer VM).  My TERM="screen". 

## Neovim Version
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

**Comment by mwcarlis** [comment]
This might just be a treesitter issues so I'm sorry to start here, but if I need to take it over to them I can do that.

**Comment by dam9000** [comment]
Yes, bring it up to Treesitter, nothing kickstart can do about it.
