### ISSUE TITLE
neodev has been deprecated in favour of lazydev

### ISSUE THREAD

**Issue by jpoliv** [nvim-lua/kickstart.nvim#960]
The neodev plugin is now end-of-life and should be replaced by the new lazydev plugin.

neodev plugin:
https://github.com/folke/neodev.nvim

lazydev plugin:
https://github.com/folke/lazydev.nvim

Caveat:
The lazydev plugin requires Neovim >= 0.10.0

neodev usage:
https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L423-L425

**Comment by maztaim** [comment]
It's deprecated enough that updating is blocked using Lazy.

**Comment by feoh** [comment]
Fixed in a recent merge.
