### ISSUE TITLE
Warning on missing a parameter 

### ISSUE THREAD

**Issue by sergeken** [nvim-lua/kickstart.nvim#965]
## Describe the bug
LuaLS gives a warning on is_enabled

## To Reproduce
if client and client.server_capabilities.inlayHintProvider and vim.lsp.inlay_hint then
  -- Toggle inlay hints
  map('<leader>th', function()
    vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
  end, '[T]oggle Inlay [H]ints')
end

adding {} to inlay_hint.is_enabled() solves the problem inlay_hint.is_enabled({})

## Desktop
- OS: ArchLinux WSL
- Terminal: Windows Terminal

## Neovim Version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```
```

**Comment by tjkuson** [comment]
#947 would fix this

**Comment by VlaDexa** [comment]
This was an upstream [neovim issue](https://github.com/neovim/neovim/issues/29230)
