### ISSUE TITLE
Incorrect comments in init.lua

### ISSUE THREAD

**Issue by proofer** [nvim-lua/kickstart.nvim#968]
init.lua line 539:
```
         -- The following autocommand is used to enable inlay hints in your
         -- code, if the language server you are using supports them

```
The code following the comment creates a keymap to toggle inlay hints, not an autocommand.

**Comment by feoh** [comment]
Pretty sure this is fixed in a recent merge. Please feel free to reopen if this is in error.

**Comment by rmacklin** [comment]
It doesn't look like it was fixed. I've opened a PR to fix it here:
- https://github.com/nvim-lua/kickstart.nvim/pull/1041
