### ISSUE TITLE
Please set `conceallevel` to 0 when the `FileType` is `help`.

### ISSUE THREAD

**Issue by vimkim** [nvim-lua/kickstart.nvim#975]
## Describe the Bug

The current configuration internally sets `conceallevel` to 2, which makes it difficult to view help files. When `conceallevel` is set to a value other than 0, many characters are hidden, making it hard to understand the context of the help documentation. There should be an autocommand in `init.lua` that sets `conceallevel` to 0 when the `FileType` is `help`.

### conceallevel 2

![image](https://github.com/nvim-lua/kickstart.nvim/assets/18080546/d60479a3-7a97-4af4-8a9b-827284814fbc)

### conceallevel 0

![image](https://github.com/nvim-lua/kickstart.nvim/assets/18080546/b34f36f3-caa0-43d0-9c8e-fa66bd619088)

As you can see, conceallevel 2 hides important keywords (such as |map-overview|) from the paragraph, making it almost impossible to understand the context.

For the new comers who just started to learn vim or neovim, this conceallevel feature is a huge barrier and some might think the help manual is broken.

## To Reproduce

1. Open Neovim.
2. Execute `:help map`.
3. Observe that many paragraphs are not viewable due to hidden characters. 

## Expected Behavior

Help files should be fully viewable without hidden characters, making the documentation easy to read and understand.

## Desktop

- **OS**: 
  - Windows 11 & WSL Ubuntu 22.04 (both tested)
  - Amazon EC2 Ubuntu 22.04.03 LTS
- **Terminal**: 
  - Windows Terminal
  - neovide --wsl

## Neovim Version

```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1693350652
Run "nvim -V1 -v" for more info
```

## Proposed Solution

Add an autocommand in `init.lua` to set `conceallevel` to 0 when the `FileType` is `help`:

```lua
-- Set conceallevel to 0 for help files
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'help',
  callback = function()
    vim.wo.conceallevel = 0
  end,
})
```

This will ensure that help files are always readable by displaying all characters.

**Comment by dam9000** [comment]
I tested this and the text appears just fine with the default kickstart, perhaps your issue lies in your own customization, perhaps it's caused by the `colorscheme` that you changed, which one do you use?
Here is how the default kickstart looks for me:
concealllevel=2:
![image](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/cb347ea5-f45d-468c-b9a5-e3220e299846)

and concealllevel=0:
![image](https://github.com/nvim-lua/kickstart.nvim/assets/148590335/04d4bb0f-e706-40a9-a99c-47b36c00d05c)

**Comment by vimkim** [comment]
@dam9000 Interesting. Mine is the default kickstart.nvim as well.
Just in case, I removed the entire ~/.config/nvim and reinstalled the default kickstart nvim, and it reproduced the same bug.

I'm kindly asking you the followings:

- What is your version of neovim?
- Other than `~/.config/nvim`, what else should I have to remove? Are there something like `nvim/share` or cache directories I must remove?

---

I confirmed that, under the same configuration, using neovim v0.9.0 did not produce the bug.

### 0.9.0

![image](https://github.com/nvim-lua/kickstart.nvim/assets/18080546/aca8ab4c-f393-4e04-92ce-85eff6d6dfb4)
![image](https://github.com/nvim-lua/kickstart.nvim/assets/18080546/4cead6ab-0188-43a9-8844-01e00d384250)

### 0.10.0

![image](https://github.com/nvim-lua/kickstart.nvim/assets/18080546/9790dfae-81e8-47a7-81fb-5ce94970e63d)
![image](https://github.com/nvim-lua/kickstart.nvim/assets/18080546/0949e66d-0fb0-4cd3-8168-632a93234e52)

---

### How to reproduce:

1. Install the latest neovim.
2. type `:help map`

### neovim versions

neovim v0.10.0 installed with 
- nix-env
- nvim-linux64.tar.gz
both versions produced the same bug.

neovim v0.9.0 installed with
- app-image
did not produce the above bug.

### How to fix bug

```
nvim --noplugin # v0.10.0
```

didn't come with the bug. But that also results in conceallevel = 0.

---

Additional testing results: setting conceallevel = 2 after `nvim --noplugin` does not produce the bug and the help files are readable.

There is probably some bug with the plugins kickstart.nvim is using and the recent version of neovim.

I wonder what feature of the new neovim (or the compatibility issue of the plugins, maybe UI) causes the conceallevel=2 to behave differently on the most recent version of the neovim.

**Comment by vimkim** [comment]
By the way, my colorscheme is `tokyonight` as well, since I tested with the default kickstart.nvim configuration.

 It means @dam9000 your colorscheme and mine are the same one, but it looks different. Probably some weird terminal color rendering issue...? Anyway, just FYI.

**Comment by dam9000** [comment]
@vimkim my neovim is 0.10, but I also have not noticed such an issue previously with 0.9.5.
From your screenshots it appears to be an issue with your terminal colors.
Perhaps try a different terminal or something
as for the directories that nvim uses these are:
```
~/.config/nvim
~/.cache/nvim
~/.local/share/nvim
~/.local/state/nvim
```

**Comment by vimkim** [comment]
I figured that the colorscheme change was due to my TERM=tmux-256color env var set by .tmux plugin (oh-my-tmux).

Now my color scheme looks exactly the same as yours in the image if I quit TMUX.

and I deleted all the below listed directories as you mentioned.

```
~/.config/nvim
~/.cache/nvim
~/.local/share/nvim
~/.local/state/nvim
```

But still, **the same problem happens**. I guess it is not only me whose experiencing the issue, as inferred from #988.

## I reproduced the same bug when:
- I used alacritty, wsl2 zsh, Uduntu 22.04, neovim v0.10.0 LuaJit 2.1.1713484068 installed from tar binary
- I used Neovide GUI, wsl2 zsh, Uduntu 22.04, neovim v0.10.0 LuaJit 2.1.16 installed from nixpkg
- I used windows terminal, wsl2 zsh, Uduntu 22.04, neovim v0.10.0 LuaJit 2.1.16 installed from nixpkg
- I used windows terminal, wsl2 zsh, Uduntu 22.04, neovim v0.10.0 LuaJit 2.1.1713484068 installed from tar binary
- I used windows terminal, wsl2 bash, Uduntu 22.04, neovim v0.10.0 LuaJit 2.1.1713484068 installed from tar binary

## I did not reproduce the bug when:
- I used windows terminal, powershell, Windows 11, neovim v0.10.0 LuaJit 2.1.1713484068 installed from choco
- I used windows terminal, wsl2, Uduntu 22.04, neovim v0.9 installed from homebrew? apt?

Thus, This bug is presumed to be related to the OS (as it works fine in Windows 11) and the neovim version.

It seems it is not the fault of kickstart.nvim.

For those who want a temporary patch until the issue gets resolved, you can put this at the bottom of your init.lua.

```lua
-- Set conceallevel to 0 for help files
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'help',
  callback = function()
    vim.wo.conceallevel = 0
  end,
})
```


I hope this to be fixed one day.
