### ISSUE TITLE
Path changing to wrong drive when trying to open neovim files

### ISSUE THREAD

**Issue by jkwtw** [nvim-lua/kickstart.nvim#986]
## Describe the bug
When I press leader sn to serch neovim files the telescope list and previews work as intended but when I press enter to open the file it tries to open it under H:\AppData\Local\nvim\lua\kickstart instead of C: where the folder is actually located.
This behaviour seems to change based on what folder I'm in with my terminal. Being on C;/ opens the files as intended, being in my Documents folder tries opening on H:\
The preview in telescope always works correctly.
My username is user.domain. Not sure if the . might cause issues.
The H:\ drive does exist but none of the other folders along the nvim path do.
Navigating to files within my cw works as intended.

## To Reproduce
Press leader sn and enter on any file.
Can provide further system specifics as required.

## Desktop
- OS: windows
- Terminal: wezterm/psh

## Neovim Version
v0.10.0

```
```

**Comment by mlabrkic** [comment]
I solved the problem as follows:

Windows,
Win-s: system var
=> Environment variables

new Windows Env variable:
HOME = %USERPROFILE%

https://github.com/mlabrkic/mykickstart.nvim

**Comment by feoh** [comment]
Workaround provided. Thanks. Closing.

**Comment by jkwtw** [comment]
That worked for me. Thank you very much!
