### ISSUE TITLE
Conform breaking change

### ISSUE THREAD

**Issue by SebasF1349** [nvim-lua/kickstart.nvim#987]
## Describe the bug
Conform.nvim has just introduced a breaking change. This is the commit: https://github.com/stevearc/conform.nvim/commit/9228b2ff4efd58b6e081defec643bf887ebadff6

It seems that the only thing kickstart needs to update is the keymap and change

`require('conform').format { async = true, lsp_fallback = true }`

(https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L635)

with `require('conform').format { async = true, lsp_format = "fallback" }`

## To Reproduce
1. Just update conform.nvim (doesn't seem to crash kickstart, but probably the fallback won't work).

## Desktop

- OS: Ubuntu (WSL)
- Terminal: Wezterm

## Neovim Version
Nightly

**Comment by SebasF1349** [comment]
I can make a pr if you want.

**Comment by rmacklin** [comment]
Per https://github.com/stevearc/conform.nvim/pull/456#issuecomment-2178715893 this should be fixed in the latest version - can you confirm?

**Comment by SebasF1349** [comment]
Will test later on home, but in any case even if the fallback works `lsp_fallback` has been deprecated and shouldn't be in the config. Change should be made, although it can wait for now just to be backwards compatible with people that hasn't updated yet.

**Comment by feoh** [comment]
Fixed in latest conform. Closing.
