### ISSUE TITLE
how do i have auto brackets?

### ISSUE THREAD

**Issue by leyloe** [nvim-lua/kickstart.nvim#989]
like when i type {}, i want an intention to happen automatically, when i go inside and press enter. also how do i setup debugging for rust? if its a few lines, feel free to make a pull request on my fork. thank you 🙏

**Comment by jiaad** [comment]
Uncomment [this](https://github.com/nvim-lua/kickstart.nvim/blob/5aeddfdd5d0308506ec63b0e4f8de33e2a39355f/init.lua#L879) line (around line 879)

`require 'kickstart.plugins.autopairs',`
and restart nvim

**Comment by feoh** [comment]
Hi. Someone already mentioned autopairs. Debugging in rust is something I haven't tried yet and can't suggest details on.

Google "Neovim debug rust" perhaps?
