### ISSUE TITLE
How to configure LSPs  wihout mason-lspconfig

### ISSUE THREAD

**Issue by Pilgrim1379** [nvim-lua/kickstart.nvim#991]
I have all the language servers that I need installed globally on my system since other text editors also rely on them. At the moment if I don't install the language servers via Mason, Neovim isn't able to use the globally avaiable ones. 

I find it a bit of a waste that I should have dual copies of the language servers on my system. Can you show me a way to use the already installed language servers on my system.

**Comment by VlaDexa** [comment]
Here's an example of code that enables use of system's rust_analyzer.
```lua
require('lspconfig').rust_analyzer.setup {}
```



For further information see `:h lspconfig-setup` and [nvim-lspconfig repo](https://github.com/neovim/nvim-lspconfig)
