### ISSUE TITLE
Deprecation of vim.dagnostic.goto_prev and vim.diagnostic.goto_next

### ISSUE THREAD

**Issue by jonl500** [nvim-lua/kickstart.nvim#992]
## Describe the bug
My neovim config was raising an error which I noticed and looked up: 
https://neovim.io/doc/user/deprecated.html
## To Reproduce
I do not know if the error was caught using 'Trouble' or one the the built in tools from kickstart, but it's a quick fix.
Once I used 'Trouble', I got a warning on the deprecated code.
1. 
## Desktop
- OS: Ubuntu
- Terminal: zsh

## Neovim Version
v0.11.0-dev
```
```
![Screenshot from 2024-06-26 13-37-30](https://github.com/nvim-lua/kickstart.nvim/assets/45649952/1baf3ec3-3401-47f1-81a8-cdfd7ca4b9e8)

**Comment by fbernier** [comment]
You're using an unreleased version of neovim which is not yet supported by kickstart.

You may be interested in https://github.com/nvim-lua/kickstart.nvim/pull/936

**Comment by VlaDexa** [comment]
You can safely remove those two maps, because since 0.10 Neovim maps these keys by default to these actions.

**Comment by ParsaNobahari** [comment]
> You're using an unreleased version of neovim which is not yet supported by kickstart.

then why this repository's "install instructions for Neovim and dependencies" is to install Neovim through unstable Neovim ppa for Ubuntu if it's not supported: https://github.com/nvim-lua/kickstart.nvim?tab=readme-ov-file#linux-install
which installs v0.11.0-dev
maybe change it to what Neovim repo recommends: https://github.com/neovim/neovim/wiki/Installing-Neovim/921fe8c40c34dd1f3fb35d5b48c484db1b8ae94b#ubuntu

**Comment by feoh** [comment]
Fixed in #936
