### ISSUE TITLE
Kickstart Plugin Configuration Problem

### ISSUE THREAD

**Issue by sabinadams** [nvim-lua/kickstart.nvim#995]
I am attempting to update the `opts` in the neo-tree configuration (`/lua/kickstart/plugins/neo-tree.lua`). 

I've updated that file to be:

```lua
 return {
  'nvim-neo-tree/neo-tree.nvim',
  version = '*',
  dependencies = {
    'nvim-lua/plenary.nvim',
    'nvim-tree/nvim-web-devicons', -- not strictly required, but recommended
    'MunifTanjim/nui.nvim',
  },
  cmd = 'Neotree',
  keys = {
    { '\\', ':Neotree reveal<CR>', { desc = 'NeoTree reveal' } },
  },
  opts = {
    filesystem = {
      filtered_items = {
        visible = true, -- This is what you want: If you set this to `true`, all "hide" just mean "dimmed out"
        hide_dotfiles = false,
        hide_gitignored = false,
      },
      window = {
        mappings = {
          ['\\'] = 'close_window',
        },
      },
    },
  },
}
```

I've also gone into `init.lua` and uncommented the line that imports that plugin:

```lua
require 'kickstart.plugins.neo-tree',
```

The goal was to have neo-tree show hidden files by default, but after restarting nvim I'm still seeing the files as hidden by default. Did I do something wrong configuring the opts?

Thanks in advance :)

**Comment by VlaDexa** [comment]
Your setup seems to be working fine on my machine... Maybe try writing an issue to the neotree devs?

![neotree_issue](https://github.com/nvim-lua/kickstart.nvim/assets/52157081/e76d531c-f8a6-4d79-831d-eae3120d8fce)

**Comment by sabinadams** [comment]
Huh okay, thanks for checking! I'll raise an issue there 👍
